/** @file     Rte_SAC_SWC.h
  *
  * @brief    Application header file
  *
  * @note     AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
  *
  * @note     Generated by ETAS RTA-RTE
  * @note     Version 7.3.0 
  */

#ifndef RTE_SAC_SWC_H
#define RTE_SAC_SWC_H

#ifndef RTE_CORE
#ifdef RTE_APPLICATION_HEADER_FILE
#error Multiple application header files included.
#endif /* RTE_APPLICATION_HEADER_FILE */
#define RTE_APPLICATION_HEADER_FILE
#endif /* RTE_CORE */

/*******************************************************
 ***
 *** Includes
 ***
 *******************************************************/

#include "Rte.h"
#include "Rte_Intl.h"
#include "Rte_SAC_SWC_Type.h"

#include "Rte_DataHandleType.h"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#if defined(RTE_RUNNABLEAPI_SAC_Controller)
   /* Do nothing for this and all elif clauses below (rte_sws_2751) */
#elif defined(RTE_RUNNABLEAPI_SAC_Init)
#else
   /* None of above defined so define value including all APIs (rte_sws_2751) */
   #define RTE_PRV_ALL_API
#endif

/*******************************************************
 ***
 *** Constants
 ***
 *******************************************************/


/*******************************************************
 ***
 *** Public Types
 ***
 *******************************************************/

/* BEGIN: SWC types (core visible) */
struct Rte_CDS_SAC_SWC {
   /* Data handles */
   P2VAR(Rte_DE_IDT_SAC_Interface_sac_can_strDevMsgTx1_mu32       , AUTOMATIC, RTE_DATA) SAC_Controller_Provided_SAC_sac_can_strDevMsgTx1_mu32;
   P2VAR(Rte_DE_IDT_SAC_Interface_sac_can_strDevMsgTx2_mu32       , AUTOMATIC, RTE_DATA) SAC_Controller_Provided_SAC_sac_can_strDevMsgTx2_mu32;
   P2VAR(Rte_DE_IDT_SAC_Interface_sac_qap_stFas01_mu8             , AUTOMATIC, RTE_DATA) SAC_Controller_Provided_SAC_sac_qap_stFas01_mu8;
   P2VAR(Rte_DE_IDT_SAC_Interface_sac_qap_stFas02_mu8             , AUTOMATIC, RTE_DATA) SAC_Controller_Provided_SAC_sac_qap_stFas02_mu8;
   P2VAR(Rte_DE_IDT_SAC_Interface_sac_qap_stFas03_mu8             , AUTOMATIC, RTE_DATA) SAC_Controller_Provided_SAC_sac_qap_stFas03_mu8;
   P2VAR(Rte_DE_IDT_SAC_Interface_sac_qap_stFas04_mu8             , AUTOMATIC, RTE_DATA) SAC_Controller_Provided_SAC_sac_qap_stFas04_mu8;
   P2VAR(Rte_DE_IDT_SAC_Interface_sac_qap_stFas05_mu8             , AUTOMATIC, RTE_DATA) SAC_Controller_Provided_SAC_sac_qap_stFas05_mu8;
   P2VAR(Rte_DE_IDT_SAC_Interface_sac_qap_stPrioToTnDsaTsc_mu16   , AUTOMATIC, RTE_DATA) SAC_Controller_Provided_SAC_sac_qap_stPrioToTnDsaTsc_mu16;
   P2VAR(Rte_DE_IDT_SAC_Interface_sac_qap_stQFK_mu8               , AUTOMATIC, RTE_DATA) SAC_Controller_Provided_SAC_sac_qap_stQFK_mu8;
   P2VAR(Rte_DE_IDT_SAC_Interface_sac_qap_stSelQfk_mu8            , AUTOMATIC, RTE_DATA) SAC_Controller_Provided_SAC_sac_qap_stSelQfk_mu8;
   P2VAR(Rte_DE_IDT_SAC_Interface_sac_qap_stVMM_mu8               , AUTOMATIC, RTE_DATA) SAC_Controller_Provided_SAC_sac_qap_stVMM_mu8;
   P2VAR(Rte_DE_IDT_SAC_Interface_sac_qap_stVibr_mu8              , AUTOMATIC, RTE_DATA) SAC_Controller_Provided_SAC_sac_qap_stVibr_mu8;
   P2VAR(Rte_DE_IDT_SAC_Interface_sac_qhm_fSollNUel_mi16          , AUTOMATIC, RTE_DATA) SAC_Controller_Provided_SAC_sac_qhm_fSollNUel_mi16;
   P2VAR(Rte_DE_IDT_SAC_Interface_sac_qhm_fSoll_mi16              , AUTOMATIC, RTE_DATA) SAC_Controller_Provided_SAC_sac_qhm_fSoll_mi16;
   P2VAR(Rte_DE_IDT_SAC_Interface_sac_qhm_mskStatus_mu8           , AUTOMATIC, RTE_DATA) SAC_Controller_Provided_SAC_sac_qhm_mskStatus_mu8;
   P2VAR(Rte_DE_IDT_SAC_Interface_sac_qhm_nivIstKraft_mi16        , AUTOMATIC, RTE_DATA) SAC_Controller_Provided_SAC_sac_qhm_nivIstKraft_mi16;
   P2VAR(Rte_DE_IDT_SAC_Interface_sac_qpr_fSollVib_mi16           , AUTOMATIC, RTE_DATA) SAC_Controller_Provided_SAC_sac_qpr_fSollVib_mi16;
   P2VAR(Rte_DE_IDT_SAC_Interface_sac_qua_krIst_mi16              , AUTOMATIC, RTE_DATA) SAC_Controller_Provided_SAC_sac_qua_krIst_mi16;
   P2VAR(Rte_DE_IDT_SAC_Interface_sac_qua_stGierSoll_mu8          , AUTOMATIC, RTE_DATA) SAC_Controller_Provided_SAC_sac_qua_stGierSoll_mu8;
   P2VAR(Rte_DE_IDT_SAC_Interface_sac_qua_trqGierSoll_mi16        , AUTOMATIC, RTE_DATA) SAC_Controller_Provided_SAC_sac_qua_trqGierSoll_mi16;
   P2VAR(Rte_DE_IDT_SAC_Interface_sac_qua_vFzgLvHigh_mu16         , AUTOMATIC, RTE_DATA) SAC_Controller_Provided_SAC_sac_qua_vFzgLvHigh_mu16;
   P2VAR(Rte_DE_IDT_SAC_Interface_sac_stSAC_mu32                  , AUTOMATIC, RTE_DATA) SAC_Controller_Provided_SAC_sac_stSAC_mu32;
   P2VAR(Rte_DE_IDT_SAC_BSW_Interface_asc_fSoll_mi16              , AUTOMATIC, RTE_DATA) SAC_Controller_Required_BSW_asc_fSoll_mi16;
   P2VAR(Rte_DE_IDT_SAC_BSW_Interface_asc_ger_phiL_mi16           , AUTOMATIC, RTE_DATA) SAC_Controller_Required_BSW_asc_ger_phiL_mi16;
   P2VAR(Rte_DE_IDT_SAC_BSW_Interface_asc_stASC_mu32              , AUTOMATIC, RTE_DATA) SAC_Controller_Required_BSW_asc_stASC_mu32;
   P2VAR(Rte_DE_IDT_SAC_BSW_Interface_asc_stDsaTsc2Qfk_mu16       , AUTOMATIC, RTE_DATA) SAC_Controller_Required_BSW_asc_stDsaTsc2Qfk_mu16;
   P2VAR(Rte_DE_IDT_SAC_BSW_Interface_bsw_fSollLimMtl_mi16        , AUTOMATIC, RTE_DATA) SAC_Controller_Required_BSW_bsw_fSollLimMtl_mi16;
   P2VAR(Rte_DE_IDT_SAC_BSW_Interface_bsw_levelAssist_mu8         , AUTOMATIC, RTE_DATA) SAC_Controller_Required_BSW_bsw_levelAssist_mu8;
   P2VAR(Rte_DE_IDT_SAC_BSW_Interface_bsw_mskStatusbits01_mu32    , AUTOMATIC, RTE_DATA) SAC_Controller_Required_BSW_bsw_mskStatusbits01_mu32;
   P2VAR(Rte_DE_IDT_SAC_BSW_Interface_bsw_mskStatusbits02_mu32    , AUTOMATIC, RTE_DATA) SAC_Controller_Required_BSW_bsw_mskStatusbits02_mu32;
   P2VAR(Rte_DE_IDT_SAC_BSW_Interface_bsw_phvRitzel_mi16          , AUTOMATIC, RTE_DATA) SAC_Controller_Required_BSW_bsw_phvRitzel_mi16;
   P2VAR(Rte_DE_IDT_SAC_BSW_Interface_bsw_stFehlerULstg_mu8       , AUTOMATIC, RTE_DATA) SAC_Controller_Required_BSW_bsw_stFehlerULstg_mu8;
   P2VAR(Rte_DE_IDT_BSW_Interface_bsw_stFrgBusFehler_mu8          , AUTOMATIC, RTE_DATA) SAC_Controller_Required_BSW_bsw_stFrgBusFehler_mu8;
   P2VAR(Rte_DE_IDT_SAC_BSW_Interface_bsw_stKl15_mu8              , AUTOMATIC, RTE_DATA) SAC_Controller_Required_BSW_bsw_stKl15_mu8;
   P2VAR(Rte_DE_IDT_SAC_BSW_Interface_bsw_stVzstLimSafetyFader_mu8, AUTOMATIC, RTE_DATA) SAC_Controller_Required_BSW_bsw_stVzstLimSafetyFader_mu8;
   P2VAR(Rte_DE_IDT_SAC_BSW_Interface_bsw_stVzstLimSafety_mu8     , AUTOMATIC, RTE_DATA) SAC_Controller_Required_BSW_bsw_stVzstLimSafety_mu8;
   P2VAR(Rte_DE_IDT_SAC_BSW_Interface_bsw_trqSensorLku_mi16       , AUTOMATIC, RTE_DATA) SAC_Controller_Required_BSW_bsw_trqSensorLku_mi16;
   P2VAR(Rte_DE_IDT_SAC_BSW_Interface_bsw_trqSensor_mi16          , AUTOMATIC, RTE_DATA) SAC_Controller_Required_BSW_bsw_trqSensor_mi16;
   P2VAR(Rte_DE_IDT_SAC_BSW_Interface_bsw_uBatt_mu16              , AUTOMATIC, RTE_DATA) SAC_Controller_Required_BSW_bsw_uBatt_mu16;
   P2VAR(Rte_DE_IDT_SAC_BSW_Interface_bsw_vZstLimMax_mi16         , AUTOMATIC, RTE_DATA) SAC_Controller_Required_BSW_bsw_vZstLimMax_mi16;
   P2VAR(Rte_DE_IDT_SAC_BSW_Interface_bsw_vZstLimMin_mi16         , AUTOMATIC, RTE_DATA) SAC_Controller_Required_BSW_bsw_vZstLimMin_mi16;
   P2VAR(Rte_DE_IDT_SAC_BSW_Interface_bsw_vZst_mi16               , AUTOMATIC, RTE_DATA) SAC_Controller_Required_BSW_bsw_vZst_mi16;
   P2VAR(Rte_DE_IDT_SAC_BSW_Interface_bsw_xZstEASoll_mi16         , AUTOMATIC, RTE_DATA) SAC_Controller_Required_BSW_bsw_xZstEASoll_mi16;
   P2VAR(Rte_DE_IDT_SAC_BSW_Interface_bsw_xZstGerKorr_mi32        , AUTOMATIC, RTE_DATA) SAC_Controller_Required_BSW_bsw_xZstGerKorr_mi32;
   P2VAR(Rte_DE_IDT_SAC_BSW_Interface_bsw_xZst_mi32               , AUTOMATIC, RTE_DATA) SAC_Controller_Required_BSW_bsw_xZst_mi32;
   P2VAR(Rte_DE_IDT_SAC_BSW_Interface_can_beschlQuer_mi16         , AUTOMATIC, RTE_DATA) SAC_Controller_Required_BSW_can_beschlQuer_mi16;
   P2VAR(Rte_DE_IDT_SAC_BSW_Interface_can_cntFas01_mu8            , AUTOMATIC, RTE_DATA) SAC_Controller_Required_BSW_can_cntFas01_mu8;
   P2VAR(Rte_DE_IDT_SAC_BSW_Interface_can_cntFas02_mu8            , AUTOMATIC, RTE_DATA) SAC_Controller_Required_BSW_can_cntFas02_mu8;
   P2VAR(Rte_DE_IDT_SAC_BSW_Interface_can_cntFas03_mu8            , AUTOMATIC, RTE_DATA) SAC_Controller_Required_BSW_can_cntFas03_mu8;
   P2VAR(Rte_DE_IDT_SAC_BSW_Interface_can_cntFas04_mu8            , AUTOMATIC, RTE_DATA) SAC_Controller_Required_BSW_can_cntFas04_mu8;
   P2VAR(Rte_DE_IDT_SAC_BSW_Interface_can_cntFas05_mu8            , AUTOMATIC, RTE_DATA) SAC_Controller_Required_BSW_can_cntFas05_mu8;
   P2VAR(Rte_DE_IDT_SAC_BSW_Interface_can_cntVMM_mu8              , AUTOMATIC, RTE_DATA) SAC_Controller_Required_BSW_can_cntVMM_mu8;
   P2VAR(Rte_DE_IDT_SAC_BSW_Interface_can_facSignal1Fas01_mu16    , AUTOMATIC, RTE_DATA) SAC_Controller_Required_BSW_can_facSignal1Fas01_mu16;
   P2VAR(Rte_DE_IDT_SAC_BSW_Interface_can_facSignal1Fas02_mu16    , AUTOMATIC, RTE_DATA) SAC_Controller_Required_BSW_can_facSignal1Fas02_mu16;
   P2VAR(Rte_DE_IDT_SAC_BSW_Interface_can_facSignal1Fas03_mu16    , AUTOMATIC, RTE_DATA) SAC_Controller_Required_BSW_can_facSignal1Fas03_mu16;
   P2VAR(Rte_DE_IDT_SAC_BSW_Interface_can_facSignal1Fas04_mu16    , AUTOMATIC, RTE_DATA) SAC_Controller_Required_BSW_can_facSignal1Fas04_mu16;
   P2VAR(Rte_DE_IDT_SAC_BSW_Interface_can_facSignal1Fas05_mu16    , AUTOMATIC, RTE_DATA) SAC_Controller_Required_BSW_can_facSignal1Fas05_mu16;
   P2VAR(Rte_DE_IDT_SAC_BSW_Interface_can_facSignal1VMM_mu16      , AUTOMATIC, RTE_DATA) SAC_Controller_Required_BSW_can_facSignal1VMM_mu16;
   P2VAR(Rte_DE_IDT_SAC_BSW_Interface_can_facSignal2Fas01_mu16    , AUTOMATIC, RTE_DATA) SAC_Controller_Required_BSW_can_facSignal2Fas01_mu16;
   P2VAR(Rte_DE_IDT_SAC_BSW_Interface_can_facSignal2Fas02_mu16    , AUTOMATIC, RTE_DATA) SAC_Controller_Required_BSW_can_facSignal2Fas02_mu16;
   P2VAR(Rte_DE_IDT_SAC_BSW_Interface_can_facSignal2Fas03_mu16    , AUTOMATIC, RTE_DATA) SAC_Controller_Required_BSW_can_facSignal2Fas03_mu16;
   P2VAR(Rte_DE_IDT_SAC_BSW_Interface_can_facSignal2Fas04_mu16    , AUTOMATIC, RTE_DATA) SAC_Controller_Required_BSW_can_facSignal2Fas04_mu16;
   P2VAR(Rte_DE_IDT_SAC_BSW_Interface_can_facSignal2Fas05_mu16    , AUTOMATIC, RTE_DATA) SAC_Controller_Required_BSW_can_facSignal2Fas05_mu16;
   P2VAR(Rte_DE_IDT_SAC_BSW_Interface_can_facSignal2VMM_mu16      , AUTOMATIC, RTE_DATA) SAC_Controller_Required_BSW_can_facSignal2VMM_mu16;
   P2VAR(Rte_DE_IDT_SAC_BSW_Interface_can_facSpuerbFas01_mu16     , AUTOMATIC, RTE_DATA) SAC_Controller_Required_BSW_can_facSpuerbFas01_mu16;
   P2VAR(Rte_DE_IDT_SAC_BSW_Interface_can_facSpuerbFas02_mu16     , AUTOMATIC, RTE_DATA) SAC_Controller_Required_BSW_can_facSpuerbFas02_mu16;
   P2VAR(Rte_DE_IDT_SAC_BSW_Interface_can_facSpuerbFas03_mu16     , AUTOMATIC, RTE_DATA) SAC_Controller_Required_BSW_can_facSpuerbFas03_mu16;
   P2VAR(Rte_DE_IDT_SAC_BSW_Interface_can_facSpuerbFas04_mu16     , AUTOMATIC, RTE_DATA) SAC_Controller_Required_BSW_can_facSpuerbFas04_mu16;
   P2VAR(Rte_DE_IDT_SAC_BSW_Interface_can_facSpuerbFas05_mu16     , AUTOMATIC, RTE_DATA) SAC_Controller_Required_BSW_can_facSpuerbFas05_mu16;
   P2VAR(Rte_DE_IDT_SAC_BSW_Interface_can_facSpuerbVMM_mu16       , AUTOMATIC, RTE_DATA) SAC_Controller_Required_BSW_can_facSpuerbVMM_mu16;
   P2VAR(Rte_DE_IDT_SAC_BSW_Interface_can_gierrate_mi16           , AUTOMATIC, RTE_DATA) SAC_Controller_Required_BSW_can_gierrate_mi16;
   P2VAR(Rte_DE_IDT_SAC_BSW_Interface_can_krSollFas01_mi16        , AUTOMATIC, RTE_DATA) SAC_Controller_Required_BSW_can_krSollFas01_mi16;
   P2VAR(Rte_DE_IDT_SAC_BSW_Interface_can_krSollFas02_mi16        , AUTOMATIC, RTE_DATA) SAC_Controller_Required_BSW_can_krSollFas02_mi16;
   P2VAR(Rte_DE_IDT_SAC_BSW_Interface_can_krSollFas03_mi16        , AUTOMATIC, RTE_DATA) SAC_Controller_Required_BSW_can_krSollFas03_mi16;
   P2VAR(Rte_DE_IDT_SAC_BSW_Interface_can_krSollFas04_mi16        , AUTOMATIC, RTE_DATA) SAC_Controller_Required_BSW_can_krSollFas04_mi16;
   P2VAR(Rte_DE_IDT_SAC_BSW_Interface_can_krSollFas05_mi16        , AUTOMATIC, RTE_DATA) SAC_Controller_Required_BSW_can_krSollFas05_mi16;
   P2VAR(Rte_DE_IDT_SAC_BSW_Interface_can_phiEscKinX1_mu16        , AUTOMATIC, RTE_DATA) SAC_Controller_Required_BSW_can_phiESCKinX1_mu16;
   P2VAR(Rte_DE_IDT_SAC_BSW_Interface_can_phiEscKinX2_mu16        , AUTOMATIC, RTE_DATA) SAC_Controller_Required_BSW_can_phiESCKinX2_mu16;
   P2VAR(Rte_DE_IDT_SAC_BSW_Interface_can_phiEscKinX3_mu16        , AUTOMATIC, RTE_DATA) SAC_Controller_Required_BSW_can_phiESCKinX3_mu16;
   P2VAR(Rte_DE_IDT_SAC_BSW_Interface_can_phiEscKinX4_mu16        , AUTOMATIC, RTE_DATA) SAC_Controller_Required_BSW_can_phiESCKinX4_mu16;
   P2VAR(Rte_DE_IDT_SAC_BSW_Interface_can_phiEscKinX5_mu16        , AUTOMATIC, RTE_DATA) SAC_Controller_Required_BSW_can_phiESCKinX5_mu16;
   P2VAR(Rte_DE_IDT_SAC_BSW_Interface_can_phiEscKinY1_mu16        , AUTOMATIC, RTE_DATA) SAC_Controller_Required_BSW_can_phiESCKinY1_mu16;
   P2VAR(Rte_DE_IDT_SAC_BSW_Interface_can_phiEscKinY2_mu16        , AUTOMATIC, RTE_DATA) SAC_Controller_Required_BSW_can_phiESCKinY2_mu16;
   P2VAR(Rte_DE_IDT_SAC_BSW_Interface_can_phiEscKinY3_mu16        , AUTOMATIC, RTE_DATA) SAC_Controller_Required_BSW_can_phiESCKinY3_mu16;
   P2VAR(Rte_DE_IDT_SAC_BSW_Interface_can_phiEscKinY4_mu16        , AUTOMATIC, RTE_DATA) SAC_Controller_Required_BSW_can_phiESCKinY4_mu16;
   P2VAR(Rte_DE_IDT_SAC_BSW_Interface_can_phiEscKinY5_mu16        , AUTOMATIC, RTE_DATA) SAC_Controller_Required_BSW_can_phiESCKinY5_mu16;
   P2VAR(Rte_DE_IDT_SAC_BSW_Interface_can_sESCRadstand_mu16       , AUTOMATIC, RTE_DATA) SAC_Controller_Required_BSW_can_sESCRadstand_mu16;
   P2VAR(Rte_DE_IDT_SAC_BSW_Interface_can_stAnfFas01_mu8          , AUTOMATIC, RTE_DATA) SAC_Controller_Required_BSW_can_stAnfFas01_mu8;
   P2VAR(Rte_DE_IDT_SAC_BSW_Interface_can_stAnfFas02_mu8          , AUTOMATIC, RTE_DATA) SAC_Controller_Required_BSW_can_stAnfFas02_mu8;
   P2VAR(Rte_DE_IDT_SAC_BSW_Interface_can_stAnfFas03_mu8          , AUTOMATIC, RTE_DATA) SAC_Controller_Required_BSW_can_stAnfFas03_mu8;
   P2VAR(Rte_DE_IDT_SAC_BSW_Interface_can_stAnfFas04_mu8          , AUTOMATIC, RTE_DATA) SAC_Controller_Required_BSW_can_stAnfFas04_mu8;
   P2VAR(Rte_DE_IDT_SAC_BSW_Interface_can_stAnfFas05_mu8          , AUTOMATIC, RTE_DATA) SAC_Controller_Required_BSW_can_stAnfFas05_mu8;
   P2VAR(Rte_DE_IDT_SAC_BSW_Interface_can_stArt1Fas01_mu8         , AUTOMATIC, RTE_DATA) SAC_Controller_Required_BSW_can_stArt1Fas01_mu8;
   P2VAR(Rte_DE_IDT_SAC_BSW_Interface_can_stArt1Fas02_mu8         , AUTOMATIC, RTE_DATA) SAC_Controller_Required_BSW_can_stArt1Fas02_mu8;
   P2VAR(Rte_DE_IDT_SAC_BSW_Interface_can_stArt1Fas03_mu8         , AUTOMATIC, RTE_DATA) SAC_Controller_Required_BSW_can_stArt1Fas03_mu8;
   P2VAR(Rte_DE_IDT_SAC_BSW_Interface_can_stArt1Fas04_mu8         , AUTOMATIC, RTE_DATA) SAC_Controller_Required_BSW_can_stArt1Fas04_mu8;
   P2VAR(Rte_DE_IDT_SAC_BSW_Interface_can_stArt1Fas05_mu8         , AUTOMATIC, RTE_DATA) SAC_Controller_Required_BSW_can_stArt1Fas05_mu8;
   P2VAR(Rte_DE_IDT_SAC_BSW_Interface_can_stArt1VMM_mu8           , AUTOMATIC, RTE_DATA) SAC_Controller_Required_BSW_can_stArt1VMM_mu8;
   P2VAR(Rte_DE_IDT_SAC_BSW_Interface_can_stArt2Fas01_mu8         , AUTOMATIC, RTE_DATA) SAC_Controller_Required_BSW_can_stArt2Fas01_mu8;
   P2VAR(Rte_DE_IDT_SAC_BSW_Interface_can_stArt2Fas02_mu8         , AUTOMATIC, RTE_DATA) SAC_Controller_Required_BSW_can_stArt2Fas02_mu8;
   P2VAR(Rte_DE_IDT_SAC_BSW_Interface_can_stArt2Fas03_mu8         , AUTOMATIC, RTE_DATA) SAC_Controller_Required_BSW_can_stArt2Fas03_mu8;
   P2VAR(Rte_DE_IDT_SAC_BSW_Interface_can_stArt2Fas04_mu8         , AUTOMATIC, RTE_DATA) SAC_Controller_Required_BSW_can_stArt2Fas04_mu8;
   P2VAR(Rte_DE_IDT_SAC_BSW_Interface_can_stArt2Fas05_mu8         , AUTOMATIC, RTE_DATA) SAC_Controller_Required_BSW_can_stArt2Fas05_mu8;
   P2VAR(Rte_DE_IDT_SAC_BSW_Interface_can_stArt2VMM_mu8           , AUTOMATIC, RTE_DATA) SAC_Controller_Required_BSW_can_stArt2VMM_mu8;
   P2VAR(Rte_DE_IDT_SAC_BSW_Interface_can_stEingLvVMM_mu8         , AUTOMATIC, RTE_DATA) SAC_Controller_Required_BSW_can_stEingLvVMM_mu8;
   P2VAR(Rte_DE_IDT_SAC_BSW_Interface_can_stEingVMM_mu8           , AUTOMATIC, RTE_DATA) SAC_Controller_Required_BSW_can_stEingVMM_mu8;
   P2VAR(Rte_DE_IDT_SAC_BSW_Interface_can_stLimCtlFReq_mu8        , AUTOMATIC, RTE_DATA) SAC_Controller_Required_BSW_can_stLimCtlFReq_mu8;
   P2VAR(Rte_DE_IDT_SAC_BSW_Interface_can_stSetupStgRackPosnFr_mu8, AUTOMATIC, RTE_DATA) SAC_Controller_Required_BSW_can_stSetupStgRackPosnFr_mu8;
   P2VAR(Rte_DE_IDT_SAC_BSW_Interface_can_stSignale01_mu32        , AUTOMATIC, RTE_DATA) SAC_Controller_Required_BSW_can_stSignale01_mu32;
   P2VAR(Rte_DE_IDT_SAC_BSW_Interface_can_stSignale02_mu32        , AUTOMATIC, RTE_DATA) SAC_Controller_Required_BSW_can_stSignale02_mu32;
   P2VAR(Rte_DE_IDT_SAC_BSW_Interface_can_stStgVibPatReq_mu8      , AUTOMATIC, RTE_DATA) SAC_Controller_Required_BSW_can_stStgVibPatReq_mu8;
   P2VAR(Rte_DE_IDT_SAC_BSW_Interface_can_stTaHfHOD_mu8           , AUTOMATIC, RTE_DATA) SAC_Controller_Required_BSW_can_stTaHfHOD_mu8;
   P2VAR(Rte_DE_IDT_SAC_BSW_Interface_can_stTaHfKBI_mu8           , AUTOMATIC, RTE_DATA) SAC_Controller_Required_BSW_can_stTaHfKBI_mu8;
   P2VAR(Rte_DE_IDT_SAC_BSW_Interface_can_stTaHfODD_mu8           , AUTOMATIC, RTE_DATA) SAC_Controller_Required_BSW_can_stTaHfODD_mu8;
   P2VAR(Rte_DE_IDT_SAC_BSW_Interface_can_stTilIntpPosnCtlFr_mu8  , AUTOMATIC, RTE_DATA) SAC_Controller_Required_BSW_can_stTilIntpPosnCtlFr_mu8;
   P2VAR(Rte_DE_IDT_SAC_BSW_Interface_can_stVSignalQualifier_mu8  , AUTOMATIC, RTE_DATA) SAC_Controller_Required_BSW_can_stVSignalQualifier_mu8;
   P2VAR(Rte_DE_IDT_SAC_BSW_Interface_can_strDevMsgRx1_mu32       , AUTOMATIC, RTE_DATA) SAC_Controller_Required_BSW_can_strDevMsgRx1_mu32;
   P2VAR(Rte_DE_IDT_SAC_BSW_Interface_can_strDevMsgRx2_mu32       , AUTOMATIC, RTE_DATA) SAC_Controller_Required_BSW_can_strDevMsgRx2_mu32;
   P2VAR(Rte_DE_IDT_SAC_BSW_Interface_can_xZstSollVMM_mi16        , AUTOMATIC, RTE_DATA) SAC_Controller_Required_BSW_can_xZstSollVMM_mi16;
   P2VAR(Rte_DE_IDT_SAC_BSW_Interface_dia_mskAnpassung01_mu32     , AUTOMATIC, RTE_DATA) SAC_Controller_Required_BSW_dia_mskAnpassung01_mu32;
   P2VAR(Rte_DE_IDT_SAC_BSW_Interface_dia_mskCodierung01_mu32     , AUTOMATIC, RTE_DATA) SAC_Controller_Required_BSW_dia_mskCodierung01_mu32;
   P2VAR(Rte_DE_IDT_SAC_BSW_Interface_dia_stDiagnose_mu32         , AUTOMATIC, RTE_DATA) SAC_Controller_Required_BSW_dia_stDiagnose_mu32;
   P2VAR(Rte_DE_IDT_SAC_BSW_Interface_eaf_fSoll_mi16              , AUTOMATIC, RTE_DATA) SAC_Controller_Required_BSW_eaf_fSoll_mi16;
   P2VAR(Rte_DE_IDT_SAC_BSW_Interface_eps_nivAssistRampe_mu16     , AUTOMATIC, RTE_DATA) SAC_Controller_Required_BSW_eps_nivAssistRampe_mu16;
   P2VAR(Rte_DE_IDT_SAC_BSW_Interface_fga_mskStVFzg_mu8           , AUTOMATIC, RTE_DATA) SAC_Controller_Required_BSW_fga_mskStVFzg_mu8;
   P2VAR(Rte_DE_IDT_SAC_BSW_Interface_fga_vFzgRohW_mu16           , AUTOMATIC, RTE_DATA) SAC_Controller_Required_BSW_fga_vFzgRohW_mu16;
   P2VAR(Rte_DE_IDT_SAC_BSW_Interface_fga_vFzg_mu16               , AUTOMATIC, RTE_DATA) SAC_Controller_Required_BSW_fga_vFzg_mu16;
   P2VAR(Rte_DE_IDT_SAC_BSW_Interface_fga_vRadHl_mu16             , AUTOMATIC, RTE_DATA) SAC_Controller_Required_BSW_fga_vRadHl_mu16;
   P2VAR(Rte_DE_IDT_SAC_BSW_Interface_fga_vRadHr_mu16             , AUTOMATIC, RTE_DATA) SAC_Controller_Required_BSW_fga_vRadHr_mu16;
   P2VAR(Rte_DE_IDT_SAC_BSW_Interface_fga_vRadVl_mu16             , AUTOMATIC, RTE_DATA) SAC_Controller_Required_BSW_fga_vRadVl_mu16;
   P2VAR(Rte_DE_IDT_SAC_BSW_Interface_fga_vRadVr_mu16             , AUTOMATIC, RTE_DATA) SAC_Controller_Required_BSW_fga_vRadVr_mu16;
   P2VAR(Rte_DE_IDT_SAC_BSW_Interface_lku_fSoll_mi16              , AUTOMATIC, RTE_DATA) SAC_Controller_Required_BSW_lku_fSoll_mi16;
   P2VAR(Rte_DE_IDT_SAC_BSW_Interface_tac_stTAC_mu32              , AUTOMATIC, RTE_DATA) SAC_Controller_Required_BSW_tac_stTAC_mu32;
   P2VAR(Rte_DE_IDT_SAC_BSW_Interface_unt_diag_aktiv_mu8          , AUTOMATIC, RTE_DATA) SAC_Controller_Required_BSW_unt_diag_aktiv_mu8;
};
typedef struct Rte_CDS_SAC_SWC Rte_CDS_SAC_SWC;
/* END: SWC types (core visible) */

/*******************************************************
 ***
 *** Private Types
 ***
 *******************************************************/

/* BEGIN: SWC types (private) */
/* END: SWC types (private) */

/*******************************************************
 ***
 *** Instance Declarations
 ***
 *******************************************************/

#define RTE_START_SEC_CONST_UNSPECIFIED
#include "Std_Types.h"
extern CONST(struct Rte_CDS_SAC_SWC, RTE_CONST) Rte_Inst_SAC_SWC;
#define RTE_STOP_SEC_CONST_UNSPECIFIED
#include "Std_Types.h"


#ifndef RTE_CORE
typedef CONSTP2CONST(struct Rte_CDS_SAC_SWC, AUTOMATIC, RTE_CONST) Rte_Instance;
#endif /* RTE_CORE */

/*******************************************************
 ***
 *** API Mapping macros
 ***
 *******************************************************/

/* API Mapping Macros */
#ifndef RTE_CORE
#define RTE_START_SEC_VAR_IMPLICITSR_TASKOEM2_1MS
#include "Std_Types.h"
extern VAR(Rte_TDB_TaskOem2_1ms, RTE_DATA) Rte_ImplicitBufs_TaskOem2_1ms;
#define RTE_STOP_SEC_VAR_IMPLICITSR_TASKOEM2_1MS
#include "Std_Types.h"
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_SAC_Controller)
/* Inline read optimization; Rte_IRead_SAC_Controller_Required_BSW_asc_fSoll_mi16 to implicit access macro */
#define Rte_IRead_SAC_Controller_Required_BSW_asc_fSoll_mi16()  ( (CONST(IDT_SAC_BSW_Interface_asc_fSoll_mi16, RTE_DATA)) Rte_ImplicitBufs_TaskOem2_1ms.sbuf22.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_SAC_Controller)
/* Inline read optimization; Rte_IRead_SAC_Controller_Required_BSW_asc_ger_phiL_mi16 to implicit access macro */
#define Rte_IRead_SAC_Controller_Required_BSW_asc_ger_phiL_mi16()  ( (CONST(IDT_SAC_BSW_Interface_asc_ger_phiL_mi16, RTE_DATA)) Rte_ImplicitBufs_TaskOem2_1ms.sbuf23.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_SAC_Controller)
/* Inline read optimization; Rte_IRead_SAC_Controller_Required_BSW_asc_stASC_mu32 to implicit access macro */
#define Rte_IRead_SAC_Controller_Required_BSW_asc_stASC_mu32()  ( (CONST(IDT_SAC_BSW_Interface_asc_stASC_mu32, RTE_DATA)) Rte_ImplicitBufs_TaskOem2_1ms.sbuf24.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_SAC_Controller)
/* Inline read optimization; Rte_IRead_SAC_Controller_Required_BSW_asc_stDsaTsc2Qfk_mu16 to implicit access macro */
#define Rte_IRead_SAC_Controller_Required_BSW_asc_stDsaTsc2Qfk_mu16()  ( (CONST(IDT_SAC_BSW_Interface_asc_stDsaTsc2Qfk_mu16, RTE_DATA)) Rte_ImplicitBufs_TaskOem2_1ms.sbuf25.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_SAC_Controller)
/* Inline read optimization; Rte_IRead_SAC_Controller_Required_BSW_bsw_fSollLimMtl_mi16 to implicit access macro */
#define Rte_IRead_SAC_Controller_Required_BSW_bsw_fSollLimMtl_mi16()  ( (CONST(IDT_SAC_BSW_Interface_bsw_fSollLimMtl_mi16, RTE_DATA)) Rte_ImplicitBufs_TaskOem2_1ms.sbuf26.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_SAC_Controller)
/* Inline read optimization; Rte_IRead_SAC_Controller_Required_BSW_bsw_levelAssist_mu8 to implicit access macro */
#define Rte_IRead_SAC_Controller_Required_BSW_bsw_levelAssist_mu8()  ( (CONST(IDT_SAC_BSW_Interface_bsw_levelAssist_mu8, RTE_DATA)) Rte_ImplicitBufs_TaskOem2_1ms.sbuf27.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_SAC_Controller)
/* Inline read optimization; Rte_IRead_SAC_Controller_Required_BSW_bsw_mskStatusbits01_mu32 to implicit access macro */
#define Rte_IRead_SAC_Controller_Required_BSW_bsw_mskStatusbits01_mu32()  ( (CONST(IDT_SAC_BSW_Interface_bsw_mskStatusbits01_mu32, RTE_DATA)) Rte_ImplicitBufs_TaskOem2_1ms.sbuf28.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_SAC_Controller)
/* Inline read optimization; Rte_IRead_SAC_Controller_Required_BSW_bsw_mskStatusbits02_mu32 to implicit access macro */
#define Rte_IRead_SAC_Controller_Required_BSW_bsw_mskStatusbits02_mu32()  ( (CONST(IDT_SAC_BSW_Interface_bsw_mskStatusbits02_mu32, RTE_DATA)) Rte_ImplicitBufs_TaskOem2_1ms.sbuf29.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_SAC_Controller)
/* Inline read optimization; Rte_IRead_SAC_Controller_Required_BSW_bsw_phvRitzel_mi16 to implicit access macro */
#define Rte_IRead_SAC_Controller_Required_BSW_bsw_phvRitzel_mi16()  ( (CONST(IDT_SAC_BSW_Interface_bsw_phvRitzel_mi16, RTE_DATA)) Rte_ImplicitBufs_TaskOem2_1ms.sbuf30.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_SAC_Controller)
/* Inline read optimization; Rte_IRead_SAC_Controller_Required_BSW_bsw_stFehlerULstg_mu8 to implicit access macro */
#define Rte_IRead_SAC_Controller_Required_BSW_bsw_stFehlerULstg_mu8()  ( (CONST(IDT_SAC_BSW_Interface_bsw_stFehlerULstg_mu8, RTE_DATA)) Rte_ImplicitBufs_TaskOem2_1ms.sbuf31.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_SAC_Controller)
/* Inline read optimization; Rte_IRead_SAC_Controller_Required_BSW_bsw_stFrgBusFehler_mu8 to implicit access macro */
#define Rte_IRead_SAC_Controller_Required_BSW_bsw_stFrgBusFehler_mu8()  ( (CONST(IDT_BSW_Interface_bsw_stFrgBusFehler_mu8, RTE_DATA)) Rte_ImplicitBufs_TaskOem2_1ms.sbuf32.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_SAC_Controller)
/* Inline read optimization; Rte_IRead_SAC_Controller_Required_BSW_bsw_stKl15_mu8 to implicit access macro */
#define Rte_IRead_SAC_Controller_Required_BSW_bsw_stKl15_mu8()  ( (CONST(IDT_SAC_BSW_Interface_bsw_stKl15_mu8, RTE_DATA)) Rte_ImplicitBufs_TaskOem2_1ms.sbuf33.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_SAC_Controller)
/* Inline read optimization; Rte_IRead_SAC_Controller_Required_BSW_bsw_stVzstLimSafetyFader_mu8 to implicit access macro */
#define Rte_IRead_SAC_Controller_Required_BSW_bsw_stVzstLimSafetyFader_mu8()  ( (CONST(IDT_SAC_BSW_Interface_bsw_stVzstLimSafetyFader_mu8, RTE_DATA)) Rte_ImplicitBufs_TaskOem2_1ms.sbuf123.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_SAC_Controller)
/* Inline read optimization; Rte_IRead_SAC_Controller_Required_BSW_bsw_stVzstLimSafety_mu8 to implicit access macro */
#define Rte_IRead_SAC_Controller_Required_BSW_bsw_stVzstLimSafety_mu8()  ( (CONST(IDT_SAC_BSW_Interface_bsw_stVzstLimSafety_mu8, RTE_DATA)) Rte_ImplicitBufs_TaskOem2_1ms.sbuf124.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_SAC_Controller)
/* Inline read optimization; Rte_IRead_SAC_Controller_Required_BSW_bsw_trqSensorLku_mi16 to implicit access macro */
#define Rte_IRead_SAC_Controller_Required_BSW_bsw_trqSensorLku_mi16()  ( (CONST(IDT_SAC_BSW_Interface_bsw_trqSensorLku_mi16, RTE_DATA)) Rte_ImplicitBufs_TaskOem2_1ms.sbuf34.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_SAC_Controller)
/* Inline read optimization; Rte_IRead_SAC_Controller_Required_BSW_bsw_trqSensor_mi16 to implicit access macro */
#define Rte_IRead_SAC_Controller_Required_BSW_bsw_trqSensor_mi16()  ( (CONST(IDT_SAC_BSW_Interface_bsw_trqSensor_mi16, RTE_DATA)) Rte_ImplicitBufs_TaskOem2_1ms.sbuf35.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_SAC_Controller)
/* Inline read optimization; Rte_IRead_SAC_Controller_Required_BSW_bsw_uBatt_mu16 to implicit access macro */
#define Rte_IRead_SAC_Controller_Required_BSW_bsw_uBatt_mu16()  ( (CONST(IDT_SAC_BSW_Interface_bsw_uBatt_mu16, RTE_DATA)) Rte_ImplicitBufs_TaskOem2_1ms.sbuf36.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_SAC_Controller)
/* Inline read optimization; Rte_IRead_SAC_Controller_Required_BSW_bsw_vZstLimMax_mi16 to implicit access macro */
#define Rte_IRead_SAC_Controller_Required_BSW_bsw_vZstLimMax_mi16()  ( (CONST(IDT_SAC_BSW_Interface_bsw_vZstLimMax_mi16, RTE_DATA)) Rte_ImplicitBufs_TaskOem2_1ms.sbuf125.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_SAC_Controller)
/* Inline read optimization; Rte_IRead_SAC_Controller_Required_BSW_bsw_vZstLimMin_mi16 to implicit access macro */
#define Rte_IRead_SAC_Controller_Required_BSW_bsw_vZstLimMin_mi16()  ( (CONST(IDT_SAC_BSW_Interface_bsw_vZstLimMin_mi16, RTE_DATA)) Rte_ImplicitBufs_TaskOem2_1ms.sbuf126.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_SAC_Controller)
/* Inline read optimization; Rte_IRead_SAC_Controller_Required_BSW_bsw_vZst_mi16 to implicit access macro */
#define Rte_IRead_SAC_Controller_Required_BSW_bsw_vZst_mi16()  ( (CONST(IDT_SAC_BSW_Interface_bsw_vZst_mi16, RTE_DATA)) Rte_ImplicitBufs_TaskOem2_1ms.sbuf37.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_SAC_Controller)
/* Inline read optimization; Rte_IRead_SAC_Controller_Required_BSW_bsw_xZstEASoll_mi16 to implicit access macro */
#define Rte_IRead_SAC_Controller_Required_BSW_bsw_xZstEASoll_mi16()  ( (CONST(IDT_SAC_BSW_Interface_bsw_xZstEASoll_mi16, RTE_DATA)) Rte_ImplicitBufs_TaskOem2_1ms.sbuf38.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_SAC_Controller)
/* Inline read optimization; Rte_IRead_SAC_Controller_Required_BSW_bsw_xZstGerKorr_mi32 to implicit access macro */
#define Rte_IRead_SAC_Controller_Required_BSW_bsw_xZstGerKorr_mi32()  ( (CONST(IDT_SAC_BSW_Interface_bsw_xZstGerKorr_mi32, RTE_DATA)) Rte_ImplicitBufs_TaskOem2_1ms.sbuf39.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_SAC_Controller)
/* Inline read optimization; Rte_IRead_SAC_Controller_Required_BSW_bsw_xZst_mi32 to implicit access macro */
#define Rte_IRead_SAC_Controller_Required_BSW_bsw_xZst_mi32()  ( (CONST(IDT_SAC_BSW_Interface_bsw_xZst_mi32, RTE_DATA)) Rte_ImplicitBufs_TaskOem2_1ms.sbuf40.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_SAC_Controller)
/* Inline read optimization; Rte_IRead_SAC_Controller_Required_BSW_can_beschlQuer_mi16 to implicit access macro */
#define Rte_IRead_SAC_Controller_Required_BSW_can_beschlQuer_mi16()  ( (CONST(IDT_SAC_BSW_Interface_can_beschlQuer_mi16, RTE_DATA)) Rte_ImplicitBufs_TaskOem2_1ms.sbuf41.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_SAC_Controller)
/* Inline read optimization; Rte_IRead_SAC_Controller_Required_BSW_can_cntFas01_mu8 to implicit access macro */
#define Rte_IRead_SAC_Controller_Required_BSW_can_cntFas01_mu8()  ( (CONST(IDT_SAC_BSW_Interface_can_cntFas01_mu8, RTE_DATA)) Rte_ImplicitBufs_TaskOem2_1ms.sbuf42.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_SAC_Controller)
/* Inline read optimization; Rte_IRead_SAC_Controller_Required_BSW_can_cntFas02_mu8 to implicit access macro */
#define Rte_IRead_SAC_Controller_Required_BSW_can_cntFas02_mu8()  ( (CONST(IDT_SAC_BSW_Interface_can_cntFas02_mu8, RTE_DATA)) Rte_ImplicitBufs_TaskOem2_1ms.sbuf43.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_SAC_Controller)
/* Inline read optimization; Rte_IRead_SAC_Controller_Required_BSW_can_cntFas03_mu8 to implicit access macro */
#define Rte_IRead_SAC_Controller_Required_BSW_can_cntFas03_mu8()  ( (CONST(IDT_SAC_BSW_Interface_can_cntFas03_mu8, RTE_DATA)) Rte_ImplicitBufs_TaskOem2_1ms.sbuf44.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_SAC_Controller)
/* Inline read optimization; Rte_IRead_SAC_Controller_Required_BSW_can_cntFas04_mu8 to implicit access macro */
#define Rte_IRead_SAC_Controller_Required_BSW_can_cntFas04_mu8()  ( (CONST(IDT_SAC_BSW_Interface_can_cntFas04_mu8, RTE_DATA)) Rte_ImplicitBufs_TaskOem2_1ms.sbuf45.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_SAC_Controller)
/* Inline read optimization; Rte_IRead_SAC_Controller_Required_BSW_can_cntFas05_mu8 to implicit access macro */
#define Rte_IRead_SAC_Controller_Required_BSW_can_cntFas05_mu8()  ( (CONST(IDT_SAC_BSW_Interface_can_cntFas05_mu8, RTE_DATA)) Rte_ImplicitBufs_TaskOem2_1ms.sbuf46.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_SAC_Controller)
/* Inline read optimization; Rte_IRead_SAC_Controller_Required_BSW_can_cntVMM_mu8 to implicit access macro */
#define Rte_IRead_SAC_Controller_Required_BSW_can_cntVMM_mu8()  ( (CONST(IDT_SAC_BSW_Interface_can_cntVMM_mu8, RTE_DATA)) Rte_ImplicitBufs_TaskOem2_1ms.sbuf47.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_SAC_Controller)
/* Inline read optimization; Rte_IRead_SAC_Controller_Required_BSW_can_facSignal1Fas01_mu16 to implicit access macro */
#define Rte_IRead_SAC_Controller_Required_BSW_can_facSignal1Fas01_mu16()  ( (CONST(IDT_SAC_BSW_Interface_can_facSignal1Fas01_mu16, RTE_DATA)) Rte_ImplicitBufs_TaskOem2_1ms.sbuf48.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_SAC_Controller)
/* Inline read optimization; Rte_IRead_SAC_Controller_Required_BSW_can_facSignal1Fas02_mu16 to implicit access macro */
#define Rte_IRead_SAC_Controller_Required_BSW_can_facSignal1Fas02_mu16()  ( (CONST(IDT_SAC_BSW_Interface_can_facSignal1Fas02_mu16, RTE_DATA)) Rte_ImplicitBufs_TaskOem2_1ms.sbuf49.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_SAC_Controller)
/* Inline read optimization; Rte_IRead_SAC_Controller_Required_BSW_can_facSignal1Fas03_mu16 to implicit access macro */
#define Rte_IRead_SAC_Controller_Required_BSW_can_facSignal1Fas03_mu16()  ( (CONST(IDT_SAC_BSW_Interface_can_facSignal1Fas03_mu16, RTE_DATA)) Rte_ImplicitBufs_TaskOem2_1ms.sbuf50.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_SAC_Controller)
/* Inline read optimization; Rte_IRead_SAC_Controller_Required_BSW_can_facSignal1Fas04_mu16 to implicit access macro */
#define Rte_IRead_SAC_Controller_Required_BSW_can_facSignal1Fas04_mu16()  ( (CONST(IDT_SAC_BSW_Interface_can_facSignal1Fas04_mu16, RTE_DATA)) Rte_ImplicitBufs_TaskOem2_1ms.sbuf51.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_SAC_Controller)
/* Inline read optimization; Rte_IRead_SAC_Controller_Required_BSW_can_facSignal1Fas05_mu16 to implicit access macro */
#define Rte_IRead_SAC_Controller_Required_BSW_can_facSignal1Fas05_mu16()  ( (CONST(IDT_SAC_BSW_Interface_can_facSignal1Fas05_mu16, RTE_DATA)) Rte_ImplicitBufs_TaskOem2_1ms.sbuf52.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_SAC_Controller)
/* Inline read optimization; Rte_IRead_SAC_Controller_Required_BSW_can_facSignal1VMM_mu16 to implicit access macro */
#define Rte_IRead_SAC_Controller_Required_BSW_can_facSignal1VMM_mu16()  ( (CONST(IDT_SAC_BSW_Interface_can_facSignal1VMM_mu16, RTE_DATA)) Rte_ImplicitBufs_TaskOem2_1ms.sbuf53.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_SAC_Controller)
/* Inline read optimization; Rte_IRead_SAC_Controller_Required_BSW_can_facSignal2Fas01_mu16 to implicit access macro */
#define Rte_IRead_SAC_Controller_Required_BSW_can_facSignal2Fas01_mu16()  ( (CONST(IDT_SAC_BSW_Interface_can_facSignal2Fas01_mu16, RTE_DATA)) Rte_ImplicitBufs_TaskOem2_1ms.sbuf54.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_SAC_Controller)
/* Inline read optimization; Rte_IRead_SAC_Controller_Required_BSW_can_facSignal2Fas02_mu16 to implicit access macro */
#define Rte_IRead_SAC_Controller_Required_BSW_can_facSignal2Fas02_mu16()  ( (CONST(IDT_SAC_BSW_Interface_can_facSignal2Fas02_mu16, RTE_DATA)) Rte_ImplicitBufs_TaskOem2_1ms.sbuf55.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_SAC_Controller)
/* Inline read optimization; Rte_IRead_SAC_Controller_Required_BSW_can_facSignal2Fas03_mu16 to implicit access macro */
#define Rte_IRead_SAC_Controller_Required_BSW_can_facSignal2Fas03_mu16()  ( (CONST(IDT_SAC_BSW_Interface_can_facSignal2Fas03_mu16, RTE_DATA)) Rte_ImplicitBufs_TaskOem2_1ms.sbuf56.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_SAC_Controller)
/* Inline read optimization; Rte_IRead_SAC_Controller_Required_BSW_can_facSignal2Fas04_mu16 to implicit access macro */
#define Rte_IRead_SAC_Controller_Required_BSW_can_facSignal2Fas04_mu16()  ( (CONST(IDT_SAC_BSW_Interface_can_facSignal2Fas04_mu16, RTE_DATA)) Rte_ImplicitBufs_TaskOem2_1ms.sbuf57.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_SAC_Controller)
/* Inline read optimization; Rte_IRead_SAC_Controller_Required_BSW_can_facSignal2Fas05_mu16 to implicit access macro */
#define Rte_IRead_SAC_Controller_Required_BSW_can_facSignal2Fas05_mu16()  ( (CONST(IDT_SAC_BSW_Interface_can_facSignal2Fas05_mu16, RTE_DATA)) Rte_ImplicitBufs_TaskOem2_1ms.sbuf58.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_SAC_Controller)
/* Inline read optimization; Rte_IRead_SAC_Controller_Required_BSW_can_facSignal2VMM_mu16 to implicit access macro */
#define Rte_IRead_SAC_Controller_Required_BSW_can_facSignal2VMM_mu16()  ( (CONST(IDT_SAC_BSW_Interface_can_facSignal2VMM_mu16, RTE_DATA)) Rte_ImplicitBufs_TaskOem2_1ms.sbuf59.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_SAC_Controller)
/* Inline read optimization; Rte_IRead_SAC_Controller_Required_BSW_can_facSpuerbFas01_mu16 to implicit access macro */
#define Rte_IRead_SAC_Controller_Required_BSW_can_facSpuerbFas01_mu16()  ( (CONST(IDT_SAC_BSW_Interface_can_facSpuerbFas01_mu16, RTE_DATA)) Rte_ImplicitBufs_TaskOem2_1ms.sbuf60.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_SAC_Controller)
/* Inline read optimization; Rte_IRead_SAC_Controller_Required_BSW_can_facSpuerbFas02_mu16 to implicit access macro */
#define Rte_IRead_SAC_Controller_Required_BSW_can_facSpuerbFas02_mu16()  ( (CONST(IDT_SAC_BSW_Interface_can_facSpuerbFas02_mu16, RTE_DATA)) Rte_ImplicitBufs_TaskOem2_1ms.sbuf61.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_SAC_Controller)
/* Inline read optimization; Rte_IRead_SAC_Controller_Required_BSW_can_facSpuerbFas03_mu16 to implicit access macro */
#define Rte_IRead_SAC_Controller_Required_BSW_can_facSpuerbFas03_mu16()  ( (CONST(IDT_SAC_BSW_Interface_can_facSpuerbFas03_mu16, RTE_DATA)) Rte_ImplicitBufs_TaskOem2_1ms.sbuf62.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_SAC_Controller)
/* Inline read optimization; Rte_IRead_SAC_Controller_Required_BSW_can_facSpuerbFas04_mu16 to implicit access macro */
#define Rte_IRead_SAC_Controller_Required_BSW_can_facSpuerbFas04_mu16()  ( (CONST(IDT_SAC_BSW_Interface_can_facSpuerbFas04_mu16, RTE_DATA)) Rte_ImplicitBufs_TaskOem2_1ms.sbuf63.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_SAC_Controller)
/* Inline read optimization; Rte_IRead_SAC_Controller_Required_BSW_can_facSpuerbFas05_mu16 to implicit access macro */
#define Rte_IRead_SAC_Controller_Required_BSW_can_facSpuerbFas05_mu16()  ( (CONST(IDT_SAC_BSW_Interface_can_facSpuerbFas05_mu16, RTE_DATA)) Rte_ImplicitBufs_TaskOem2_1ms.sbuf64.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_SAC_Controller)
/* Inline read optimization; Rte_IRead_SAC_Controller_Required_BSW_can_facSpuerbVMM_mu16 to implicit access macro */
#define Rte_IRead_SAC_Controller_Required_BSW_can_facSpuerbVMM_mu16()  ( (CONST(IDT_SAC_BSW_Interface_can_facSpuerbVMM_mu16, RTE_DATA)) Rte_ImplicitBufs_TaskOem2_1ms.sbuf65.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_SAC_Controller)
/* Inline read optimization; Rte_IRead_SAC_Controller_Required_BSW_can_gierrate_mi16 to implicit access macro */
#define Rte_IRead_SAC_Controller_Required_BSW_can_gierrate_mi16()  ( (CONST(IDT_SAC_BSW_Interface_can_gierrate_mi16, RTE_DATA)) Rte_ImplicitBufs_TaskOem2_1ms.sbuf66.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_SAC_Controller)
/* Inline read optimization; Rte_IRead_SAC_Controller_Required_BSW_can_krSollFas01_mi16 to implicit access macro */
#define Rte_IRead_SAC_Controller_Required_BSW_can_krSollFas01_mi16()  ( (CONST(IDT_SAC_BSW_Interface_can_krSollFas01_mi16, RTE_DATA)) Rte_ImplicitBufs_TaskOem2_1ms.sbuf67.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_SAC_Controller)
/* Inline read optimization; Rte_IRead_SAC_Controller_Required_BSW_can_krSollFas02_mi16 to implicit access macro */
#define Rte_IRead_SAC_Controller_Required_BSW_can_krSollFas02_mi16()  ( (CONST(IDT_SAC_BSW_Interface_can_krSollFas02_mi16, RTE_DATA)) Rte_ImplicitBufs_TaskOem2_1ms.sbuf68.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_SAC_Controller)
/* Inline read optimization; Rte_IRead_SAC_Controller_Required_BSW_can_krSollFas03_mi16 to implicit access macro */
#define Rte_IRead_SAC_Controller_Required_BSW_can_krSollFas03_mi16()  ( (CONST(IDT_SAC_BSW_Interface_can_krSollFas03_mi16, RTE_DATA)) Rte_ImplicitBufs_TaskOem2_1ms.sbuf69.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_SAC_Controller)
/* Inline read optimization; Rte_IRead_SAC_Controller_Required_BSW_can_krSollFas04_mi16 to implicit access macro */
#define Rte_IRead_SAC_Controller_Required_BSW_can_krSollFas04_mi16()  ( (CONST(IDT_SAC_BSW_Interface_can_krSollFas04_mi16, RTE_DATA)) Rte_ImplicitBufs_TaskOem2_1ms.sbuf70.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_SAC_Controller)
/* Inline read optimization; Rte_IRead_SAC_Controller_Required_BSW_can_krSollFas05_mi16 to implicit access macro */
#define Rte_IRead_SAC_Controller_Required_BSW_can_krSollFas05_mi16()  ( (CONST(IDT_SAC_BSW_Interface_can_krSollFas05_mi16, RTE_DATA)) Rte_ImplicitBufs_TaskOem2_1ms.sbuf71.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_SAC_Controller)
/* Inline read optimization; Rte_IRead_SAC_Controller_Required_BSW_can_phiESCKinX1_mu16 to implicit access macro */
#define Rte_IRead_SAC_Controller_Required_BSW_can_phiESCKinX1_mu16()  ( (CONST(IDT_SAC_BSW_Interface_can_phiEscKinX1_mu16, RTE_DATA)) Rte_ImplicitBufs_TaskOem2_1ms.sbuf72.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_SAC_Controller)
/* Inline read optimization; Rte_IRead_SAC_Controller_Required_BSW_can_phiESCKinX2_mu16 to implicit access macro */
#define Rte_IRead_SAC_Controller_Required_BSW_can_phiESCKinX2_mu16()  ( (CONST(IDT_SAC_BSW_Interface_can_phiEscKinX2_mu16, RTE_DATA)) Rte_ImplicitBufs_TaskOem2_1ms.sbuf73.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_SAC_Controller)
/* Inline read optimization; Rte_IRead_SAC_Controller_Required_BSW_can_phiESCKinX3_mu16 to implicit access macro */
#define Rte_IRead_SAC_Controller_Required_BSW_can_phiESCKinX3_mu16()  ( (CONST(IDT_SAC_BSW_Interface_can_phiEscKinX3_mu16, RTE_DATA)) Rte_ImplicitBufs_TaskOem2_1ms.sbuf74.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_SAC_Controller)
/* Inline read optimization; Rte_IRead_SAC_Controller_Required_BSW_can_phiESCKinX4_mu16 to implicit access macro */
#define Rte_IRead_SAC_Controller_Required_BSW_can_phiESCKinX4_mu16()  ( (CONST(IDT_SAC_BSW_Interface_can_phiEscKinX4_mu16, RTE_DATA)) Rte_ImplicitBufs_TaskOem2_1ms.sbuf75.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_SAC_Controller)
/* Inline read optimization; Rte_IRead_SAC_Controller_Required_BSW_can_phiESCKinX5_mu16 to implicit access macro */
#define Rte_IRead_SAC_Controller_Required_BSW_can_phiESCKinX5_mu16()  ( (CONST(IDT_SAC_BSW_Interface_can_phiEscKinX5_mu16, RTE_DATA)) Rte_ImplicitBufs_TaskOem2_1ms.sbuf76.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_SAC_Controller)
/* Inline read optimization; Rte_IRead_SAC_Controller_Required_BSW_can_phiESCKinY1_mu16 to implicit access macro */
#define Rte_IRead_SAC_Controller_Required_BSW_can_phiESCKinY1_mu16()  ( (CONST(IDT_SAC_BSW_Interface_can_phiEscKinY1_mu16, RTE_DATA)) Rte_ImplicitBufs_TaskOem2_1ms.sbuf77.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_SAC_Controller)
/* Inline read optimization; Rte_IRead_SAC_Controller_Required_BSW_can_phiESCKinY2_mu16 to implicit access macro */
#define Rte_IRead_SAC_Controller_Required_BSW_can_phiESCKinY2_mu16()  ( (CONST(IDT_SAC_BSW_Interface_can_phiEscKinY2_mu16, RTE_DATA)) Rte_ImplicitBufs_TaskOem2_1ms.sbuf78.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_SAC_Controller)
/* Inline read optimization; Rte_IRead_SAC_Controller_Required_BSW_can_phiESCKinY3_mu16 to implicit access macro */
#define Rte_IRead_SAC_Controller_Required_BSW_can_phiESCKinY3_mu16()  ( (CONST(IDT_SAC_BSW_Interface_can_phiEscKinY3_mu16, RTE_DATA)) Rte_ImplicitBufs_TaskOem2_1ms.sbuf79.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_SAC_Controller)
/* Inline read optimization; Rte_IRead_SAC_Controller_Required_BSW_can_phiESCKinY4_mu16 to implicit access macro */
#define Rte_IRead_SAC_Controller_Required_BSW_can_phiESCKinY4_mu16()  ( (CONST(IDT_SAC_BSW_Interface_can_phiEscKinY4_mu16, RTE_DATA)) Rte_ImplicitBufs_TaskOem2_1ms.sbuf80.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_SAC_Controller)
/* Inline read optimization; Rte_IRead_SAC_Controller_Required_BSW_can_phiESCKinY5_mu16 to implicit access macro */
#define Rte_IRead_SAC_Controller_Required_BSW_can_phiESCKinY5_mu16()  ( (CONST(IDT_SAC_BSW_Interface_can_phiEscKinY5_mu16, RTE_DATA)) Rte_ImplicitBufs_TaskOem2_1ms.sbuf81.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_SAC_Controller)
/* Inline read optimization; Rte_IRead_SAC_Controller_Required_BSW_can_sESCRadstand_mu16 to implicit access macro */
#define Rte_IRead_SAC_Controller_Required_BSW_can_sESCRadstand_mu16()  ( (CONST(IDT_SAC_BSW_Interface_can_sESCRadstand_mu16, RTE_DATA)) Rte_ImplicitBufs_TaskOem2_1ms.sbuf82.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_SAC_Controller)
/* Inline read optimization; Rte_IRead_SAC_Controller_Required_BSW_can_stAnfFas01_mu8 to implicit access macro */
#define Rte_IRead_SAC_Controller_Required_BSW_can_stAnfFas01_mu8()  ( (CONST(IDT_SAC_BSW_Interface_can_stAnfFas01_mu8, RTE_DATA)) Rte_ImplicitBufs_TaskOem2_1ms.sbuf83.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_SAC_Controller)
/* Inline read optimization; Rte_IRead_SAC_Controller_Required_BSW_can_stAnfFas02_mu8 to implicit access macro */
#define Rte_IRead_SAC_Controller_Required_BSW_can_stAnfFas02_mu8()  ( (CONST(IDT_SAC_BSW_Interface_can_stAnfFas02_mu8, RTE_DATA)) Rte_ImplicitBufs_TaskOem2_1ms.sbuf84.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_SAC_Controller)
/* Inline read optimization; Rte_IRead_SAC_Controller_Required_BSW_can_stAnfFas03_mu8 to implicit access macro */
#define Rte_IRead_SAC_Controller_Required_BSW_can_stAnfFas03_mu8()  ( (CONST(IDT_SAC_BSW_Interface_can_stAnfFas03_mu8, RTE_DATA)) Rte_ImplicitBufs_TaskOem2_1ms.sbuf85.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_SAC_Controller)
/* Inline read optimization; Rte_IRead_SAC_Controller_Required_BSW_can_stAnfFas04_mu8 to implicit access macro */
#define Rte_IRead_SAC_Controller_Required_BSW_can_stAnfFas04_mu8()  ( (CONST(IDT_SAC_BSW_Interface_can_stAnfFas04_mu8, RTE_DATA)) Rte_ImplicitBufs_TaskOem2_1ms.sbuf86.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_SAC_Controller)
/* Inline read optimization; Rte_IRead_SAC_Controller_Required_BSW_can_stAnfFas05_mu8 to implicit access macro */
#define Rte_IRead_SAC_Controller_Required_BSW_can_stAnfFas05_mu8()  ( (CONST(IDT_SAC_BSW_Interface_can_stAnfFas05_mu8, RTE_DATA)) Rte_ImplicitBufs_TaskOem2_1ms.sbuf87.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_SAC_Controller)
/* Inline read optimization; Rte_IRead_SAC_Controller_Required_BSW_can_stArt1Fas01_mu8 to implicit access macro */
#define Rte_IRead_SAC_Controller_Required_BSW_can_stArt1Fas01_mu8()  ( (CONST(IDT_SAC_BSW_Interface_can_stArt1Fas01_mu8, RTE_DATA)) Rte_ImplicitBufs_TaskOem2_1ms.sbuf88.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_SAC_Controller)
/* Inline read optimization; Rte_IRead_SAC_Controller_Required_BSW_can_stArt1Fas02_mu8 to implicit access macro */
#define Rte_IRead_SAC_Controller_Required_BSW_can_stArt1Fas02_mu8()  ( (CONST(IDT_SAC_BSW_Interface_can_stArt1Fas02_mu8, RTE_DATA)) Rte_ImplicitBufs_TaskOem2_1ms.sbuf89.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_SAC_Controller)
/* Inline read optimization; Rte_IRead_SAC_Controller_Required_BSW_can_stArt1Fas03_mu8 to implicit access macro */
#define Rte_IRead_SAC_Controller_Required_BSW_can_stArt1Fas03_mu8()  ( (CONST(IDT_SAC_BSW_Interface_can_stArt1Fas03_mu8, RTE_DATA)) Rte_ImplicitBufs_TaskOem2_1ms.sbuf90.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_SAC_Controller)
/* Inline read optimization; Rte_IRead_SAC_Controller_Required_BSW_can_stArt1Fas04_mu8 to implicit access macro */
#define Rte_IRead_SAC_Controller_Required_BSW_can_stArt1Fas04_mu8()  ( (CONST(IDT_SAC_BSW_Interface_can_stArt1Fas04_mu8, RTE_DATA)) Rte_ImplicitBufs_TaskOem2_1ms.sbuf91.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_SAC_Controller)
/* Inline read optimization; Rte_IRead_SAC_Controller_Required_BSW_can_stArt1Fas05_mu8 to implicit access macro */
#define Rte_IRead_SAC_Controller_Required_BSW_can_stArt1Fas05_mu8()  ( (CONST(IDT_SAC_BSW_Interface_can_stArt1Fas05_mu8, RTE_DATA)) Rte_ImplicitBufs_TaskOem2_1ms.sbuf92.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_SAC_Controller)
/* Inline read optimization; Rte_IRead_SAC_Controller_Required_BSW_can_stArt1VMM_mu8 to implicit access macro */
#define Rte_IRead_SAC_Controller_Required_BSW_can_stArt1VMM_mu8()  ( (CONST(IDT_SAC_BSW_Interface_can_stArt1VMM_mu8, RTE_DATA)) Rte_ImplicitBufs_TaskOem2_1ms.sbuf93.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_SAC_Controller)
/* Inline read optimization; Rte_IRead_SAC_Controller_Required_BSW_can_stArt2Fas01_mu8 to implicit access macro */
#define Rte_IRead_SAC_Controller_Required_BSW_can_stArt2Fas01_mu8()  ( (CONST(IDT_SAC_BSW_Interface_can_stArt2Fas01_mu8, RTE_DATA)) Rte_ImplicitBufs_TaskOem2_1ms.sbuf94.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_SAC_Controller)
/* Inline read optimization; Rte_IRead_SAC_Controller_Required_BSW_can_stArt2Fas02_mu8 to implicit access macro */
#define Rte_IRead_SAC_Controller_Required_BSW_can_stArt2Fas02_mu8()  ( (CONST(IDT_SAC_BSW_Interface_can_stArt2Fas02_mu8, RTE_DATA)) Rte_ImplicitBufs_TaskOem2_1ms.sbuf95.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_SAC_Controller)
/* Inline read optimization; Rte_IRead_SAC_Controller_Required_BSW_can_stArt2Fas03_mu8 to implicit access macro */
#define Rte_IRead_SAC_Controller_Required_BSW_can_stArt2Fas03_mu8()  ( (CONST(IDT_SAC_BSW_Interface_can_stArt2Fas03_mu8, RTE_DATA)) Rte_ImplicitBufs_TaskOem2_1ms.sbuf96.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_SAC_Controller)
/* Inline read optimization; Rte_IRead_SAC_Controller_Required_BSW_can_stArt2Fas04_mu8 to implicit access macro */
#define Rte_IRead_SAC_Controller_Required_BSW_can_stArt2Fas04_mu8()  ( (CONST(IDT_SAC_BSW_Interface_can_stArt2Fas04_mu8, RTE_DATA)) Rte_ImplicitBufs_TaskOem2_1ms.sbuf97.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_SAC_Controller)
/* Inline read optimization; Rte_IRead_SAC_Controller_Required_BSW_can_stArt2Fas05_mu8 to implicit access macro */
#define Rte_IRead_SAC_Controller_Required_BSW_can_stArt2Fas05_mu8()  ( (CONST(IDT_SAC_BSW_Interface_can_stArt2Fas05_mu8, RTE_DATA)) Rte_ImplicitBufs_TaskOem2_1ms.sbuf98.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_SAC_Controller)
/* Inline read optimization; Rte_IRead_SAC_Controller_Required_BSW_can_stArt2VMM_mu8 to implicit access macro */
#define Rte_IRead_SAC_Controller_Required_BSW_can_stArt2VMM_mu8()  ( (CONST(IDT_SAC_BSW_Interface_can_stArt2VMM_mu8, RTE_DATA)) Rte_ImplicitBufs_TaskOem2_1ms.sbuf99.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_SAC_Controller)
/* Inline read optimization; Rte_IRead_SAC_Controller_Required_BSW_can_stEingLvVMM_mu8 to implicit access macro */
#define Rte_IRead_SAC_Controller_Required_BSW_can_stEingLvVMM_mu8()  ( (CONST(IDT_SAC_BSW_Interface_can_stEingLvVMM_mu8, RTE_DATA)) Rte_ImplicitBufs_TaskOem2_1ms.sbuf100.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_SAC_Controller)
/* Inline read optimization; Rte_IRead_SAC_Controller_Required_BSW_can_stEingVMM_mu8 to implicit access macro */
#define Rte_IRead_SAC_Controller_Required_BSW_can_stEingVMM_mu8()  ( (CONST(IDT_SAC_BSW_Interface_can_stEingVMM_mu8, RTE_DATA)) Rte_ImplicitBufs_TaskOem2_1ms.sbuf101.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_SAC_Controller)
/* Inline read optimization; Rte_IRead_SAC_Controller_Required_BSW_can_stLimCtlFReq_mu8 to implicit access macro */
#define Rte_IRead_SAC_Controller_Required_BSW_can_stLimCtlFReq_mu8()  ( (CONST(IDT_SAC_BSW_Interface_can_stLimCtlFReq_mu8, RTE_DATA)) Rte_ImplicitBufs_TaskOem2_1ms.sbuf127.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_SAC_Controller)
/* Inline read optimization; Rte_IRead_SAC_Controller_Required_BSW_can_stSetupStgRackPosnFr_mu8 to implicit access macro */
#define Rte_IRead_SAC_Controller_Required_BSW_can_stSetupStgRackPosnFr_mu8()  ( (CONST(IDT_SAC_BSW_Interface_can_stSetupStgRackPosnFr_mu8, RTE_DATA)) Rte_ImplicitBufs_TaskOem2_1ms.sbuf128.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_SAC_Controller)
/* Inline read optimization; Rte_IRead_SAC_Controller_Required_BSW_can_stSignale01_mu32 to implicit access macro */
#define Rte_IRead_SAC_Controller_Required_BSW_can_stSignale01_mu32()  ( (CONST(IDT_SAC_BSW_Interface_can_stSignale01_mu32, RTE_DATA)) Rte_ImplicitBufs_TaskOem2_1ms.sbuf102.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_SAC_Controller)
/* Inline read optimization; Rte_IRead_SAC_Controller_Required_BSW_can_stSignale02_mu32 to implicit access macro */
#define Rte_IRead_SAC_Controller_Required_BSW_can_stSignale02_mu32()  ( (CONST(IDT_SAC_BSW_Interface_can_stSignale02_mu32, RTE_DATA)) Rte_ImplicitBufs_TaskOem2_1ms.sbuf103.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_SAC_Controller)
/* Inline read optimization; Rte_IRead_SAC_Controller_Required_BSW_can_stStgVibPatReq_mu8 to implicit access macro */
#define Rte_IRead_SAC_Controller_Required_BSW_can_stStgVibPatReq_mu8()  ( (CONST(IDT_SAC_BSW_Interface_can_stStgVibPatReq_mu8, RTE_DATA)) Rte_ImplicitBufs_TaskOem2_1ms.sbuf129.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_SAC_Controller)
/* Inline read optimization; Rte_IRead_SAC_Controller_Required_BSW_can_stTaHfHOD_mu8 to implicit access macro */
#define Rte_IRead_SAC_Controller_Required_BSW_can_stTaHfHOD_mu8()  ( (CONST(IDT_SAC_BSW_Interface_can_stTaHfHOD_mu8, RTE_DATA)) Rte_ImplicitBufs_TaskOem2_1ms.sbuf131.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_SAC_Controller)
/* Inline read optimization; Rte_IRead_SAC_Controller_Required_BSW_can_stTaHfKBI_mu8 to implicit access macro */
#define Rte_IRead_SAC_Controller_Required_BSW_can_stTaHfKBI_mu8()  ( (CONST(IDT_SAC_BSW_Interface_can_stTaHfKBI_mu8, RTE_DATA)) Rte_ImplicitBufs_TaskOem2_1ms.sbuf132.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_SAC_Controller)
/* Inline read optimization; Rte_IRead_SAC_Controller_Required_BSW_can_stTaHfODD_mu8 to implicit access macro */
#define Rte_IRead_SAC_Controller_Required_BSW_can_stTaHfODD_mu8()  ( (CONST(IDT_SAC_BSW_Interface_can_stTaHfODD_mu8, RTE_DATA)) Rte_ImplicitBufs_TaskOem2_1ms.sbuf133.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_SAC_Controller)
/* Inline read optimization; Rte_IRead_SAC_Controller_Required_BSW_can_stTilIntpPosnCtlFr_mu8 to implicit access macro */
#define Rte_IRead_SAC_Controller_Required_BSW_can_stTilIntpPosnCtlFr_mu8()  ( (CONST(IDT_SAC_BSW_Interface_can_stTilIntpPosnCtlFr_mu8, RTE_DATA)) Rte_ImplicitBufs_TaskOem2_1ms.sbuf130.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_SAC_Controller)
/* Inline read optimization; Rte_IRead_SAC_Controller_Required_BSW_can_stVSignalQualifier_mu8 to implicit access macro */
#define Rte_IRead_SAC_Controller_Required_BSW_can_stVSignalQualifier_mu8()  ( (CONST(IDT_SAC_BSW_Interface_can_stVSignalQualifier_mu8, RTE_DATA)) Rte_ImplicitBufs_TaskOem2_1ms.sbuf104.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_SAC_Controller)
/* Inline read optimization; Rte_IRead_SAC_Controller_Required_BSW_can_strDevMsgRx1_mu32 to implicit access macro */
#define Rte_IRead_SAC_Controller_Required_BSW_can_strDevMsgRx1_mu32()  ( (CONST(IDT_SAC_BSW_Interface_can_strDevMsgRx1_mu32, RTE_DATA)) Rte_ImplicitBufs_TaskOem2_1ms.sbuf105.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_SAC_Controller)
/* Inline read optimization; Rte_IRead_SAC_Controller_Required_BSW_can_strDevMsgRx2_mu32 to implicit access macro */
#define Rte_IRead_SAC_Controller_Required_BSW_can_strDevMsgRx2_mu32()  ( (CONST(IDT_SAC_BSW_Interface_can_strDevMsgRx2_mu32, RTE_DATA)) Rte_ImplicitBufs_TaskOem2_1ms.sbuf106.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_SAC_Controller)
/* Inline read optimization; Rte_IRead_SAC_Controller_Required_BSW_can_xZstSollVMM_mi16 to implicit access macro */
#define Rte_IRead_SAC_Controller_Required_BSW_can_xZstSollVMM_mi16()  ( (CONST(IDT_SAC_BSW_Interface_can_xZstSollVMM_mi16, RTE_DATA)) Rte_ImplicitBufs_TaskOem2_1ms.sbuf107.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_SAC_Controller)
/* Inline read optimization; Rte_IRead_SAC_Controller_Required_BSW_dia_mskAnpassung01_mu32 to implicit access macro */
#define Rte_IRead_SAC_Controller_Required_BSW_dia_mskAnpassung01_mu32()  ( (CONST(IDT_SAC_BSW_Interface_dia_mskAnpassung01_mu32, RTE_DATA)) Rte_ImplicitBufs_TaskOem2_1ms.sbuf108.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_SAC_Controller)
/* Inline read optimization; Rte_IRead_SAC_Controller_Required_BSW_dia_mskCodierung01_mu32 to implicit access macro */
#define Rte_IRead_SAC_Controller_Required_BSW_dia_mskCodierung01_mu32()  ( (CONST(IDT_SAC_BSW_Interface_dia_mskCodierung01_mu32, RTE_DATA)) Rte_ImplicitBufs_TaskOem2_1ms.sbuf109.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_SAC_Controller)
/* Inline read optimization; Rte_IRead_SAC_Controller_Required_BSW_dia_stDiagnose_mu32 to implicit access macro */
#define Rte_IRead_SAC_Controller_Required_BSW_dia_stDiagnose_mu32()  ( (CONST(IDT_SAC_BSW_Interface_dia_stDiagnose_mu32, RTE_DATA)) Rte_ImplicitBufs_TaskOem2_1ms.sbuf110.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_SAC_Controller)
/* Inline read optimization; Rte_IRead_SAC_Controller_Required_BSW_eaf_fSoll_mi16 to implicit access macro */
#define Rte_IRead_SAC_Controller_Required_BSW_eaf_fSoll_mi16()  ( (CONST(IDT_SAC_BSW_Interface_eaf_fSoll_mi16, RTE_DATA)) Rte_ImplicitBufs_TaskOem2_1ms.sbuf111.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_SAC_Controller)
/* Inline read optimization; Rte_IRead_SAC_Controller_Required_BSW_eps_nivAssistRampe_mu16 to implicit access macro */
#define Rte_IRead_SAC_Controller_Required_BSW_eps_nivAssistRampe_mu16()  ( (CONST(IDT_SAC_BSW_Interface_eps_nivAssistRampe_mu16, RTE_DATA)) Rte_ImplicitBufs_TaskOem2_1ms.sbuf112.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_SAC_Controller)
/* Inline read optimization; Rte_IRead_SAC_Controller_Required_BSW_fga_mskStVFzg_mu8 to implicit access macro */
#define Rte_IRead_SAC_Controller_Required_BSW_fga_mskStVFzg_mu8()  ( (CONST(IDT_SAC_BSW_Interface_fga_mskStVFzg_mu8, RTE_DATA)) Rte_ImplicitBufs_TaskOem2_1ms.sbuf113.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_SAC_Controller)
/* Inline read optimization; Rte_IRead_SAC_Controller_Required_BSW_fga_vFzgRohW_mu16 to implicit access macro */
#define Rte_IRead_SAC_Controller_Required_BSW_fga_vFzgRohW_mu16()  ( (CONST(IDT_SAC_BSW_Interface_fga_vFzgRohW_mu16, RTE_DATA)) Rte_ImplicitBufs_TaskOem2_1ms.sbuf114.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_SAC_Controller)
/* Inline read optimization; Rte_IRead_SAC_Controller_Required_BSW_fga_vFzg_mu16 to implicit access macro */
#define Rte_IRead_SAC_Controller_Required_BSW_fga_vFzg_mu16()  ( (CONST(IDT_SAC_BSW_Interface_fga_vFzg_mu16, RTE_DATA)) Rte_ImplicitBufs_TaskOem2_1ms.sbuf115.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_SAC_Controller)
/* Inline read optimization; Rte_IRead_SAC_Controller_Required_BSW_fga_vRadHl_mu16 to implicit access macro */
#define Rte_IRead_SAC_Controller_Required_BSW_fga_vRadHl_mu16()  ( (CONST(IDT_SAC_BSW_Interface_fga_vRadHl_mu16, RTE_DATA)) Rte_ImplicitBufs_TaskOem2_1ms.sbuf116.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_SAC_Controller)
/* Inline read optimization; Rte_IRead_SAC_Controller_Required_BSW_fga_vRadHr_mu16 to implicit access macro */
#define Rte_IRead_SAC_Controller_Required_BSW_fga_vRadHr_mu16()  ( (CONST(IDT_SAC_BSW_Interface_fga_vRadHr_mu16, RTE_DATA)) Rte_ImplicitBufs_TaskOem2_1ms.sbuf117.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_SAC_Controller)
/* Inline read optimization; Rte_IRead_SAC_Controller_Required_BSW_fga_vRadVl_mu16 to implicit access macro */
#define Rte_IRead_SAC_Controller_Required_BSW_fga_vRadVl_mu16()  ( (CONST(IDT_SAC_BSW_Interface_fga_vRadVl_mu16, RTE_DATA)) Rte_ImplicitBufs_TaskOem2_1ms.sbuf118.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_SAC_Controller)
/* Inline read optimization; Rte_IRead_SAC_Controller_Required_BSW_fga_vRadVr_mu16 to implicit access macro */
#define Rte_IRead_SAC_Controller_Required_BSW_fga_vRadVr_mu16()  ( (CONST(IDT_SAC_BSW_Interface_fga_vRadVr_mu16, RTE_DATA)) Rte_ImplicitBufs_TaskOem2_1ms.sbuf119.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_SAC_Controller)
/* Inline read optimization; Rte_IRead_SAC_Controller_Required_BSW_lku_fSoll_mi16 to implicit access macro */
#define Rte_IRead_SAC_Controller_Required_BSW_lku_fSoll_mi16()  ( (CONST(IDT_SAC_BSW_Interface_lku_fSoll_mi16, RTE_DATA)) Rte_ImplicitBufs_TaskOem2_1ms.sbuf120.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_SAC_Controller)
/* Inline read optimization; Rte_IRead_SAC_Controller_Required_BSW_tac_stTAC_mu32 to implicit access macro */
#define Rte_IRead_SAC_Controller_Required_BSW_tac_stTAC_mu32()  ( (CONST(IDT_SAC_BSW_Interface_tac_stTAC_mu32, RTE_DATA)) Rte_ImplicitBufs_TaskOem2_1ms.sbuf121.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_SAC_Controller)
/* Inline read optimization; Rte_IRead_SAC_Controller_Required_BSW_unt_diag_aktiv_mu8 to implicit access macro */
#define Rte_IRead_SAC_Controller_Required_BSW_unt_diag_aktiv_mu8()  ( (CONST(IDT_SAC_BSW_Interface_unt_diag_aktiv_mu8, RTE_DATA)) Rte_ImplicitBufs_TaskOem2_1ms.sbuf122.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_SAC_Controller)
/* Inline write optimization; Rte_IWriteRef_SAC_Controller_Provided_SAC_sac_can_strDevMsgTx1_mu32 to implicit access macro */
#define Rte_IWriteRef_SAC_Controller_Provided_SAC_sac_can_strDevMsgTx1_mu32()  ( (P2VAR(IDT_SAC_Interface_sac_can_strDevMsgTx1_mu32, AUTOMATIC, RTE_DATA)) &Rte_ImplicitBufs_TaskOem2_1ms.sbuf0.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_SAC_Controller)
/* Inline write optimization; Rte_IWriteRef_SAC_Controller_Provided_SAC_sac_can_strDevMsgTx2_mu32 to implicit access macro */
#define Rte_IWriteRef_SAC_Controller_Provided_SAC_sac_can_strDevMsgTx2_mu32()  ( (P2VAR(IDT_SAC_Interface_sac_can_strDevMsgTx2_mu32, AUTOMATIC, RTE_DATA)) &Rte_ImplicitBufs_TaskOem2_1ms.sbuf1.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_SAC_Controller)
/* Inline write optimization; Rte_IWriteRef_SAC_Controller_Provided_SAC_sac_qap_stFas01_mu8 to implicit access macro */
#define Rte_IWriteRef_SAC_Controller_Provided_SAC_sac_qap_stFas01_mu8()  ( (P2VAR(IDT_SAC_Interface_sac_qap_stFas01_mu8, AUTOMATIC, RTE_DATA)) &Rte_ImplicitBufs_TaskOem2_1ms.sbuf2.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_SAC_Controller)
/* Inline write optimization; Rte_IWriteRef_SAC_Controller_Provided_SAC_sac_qap_stFas02_mu8 to implicit access macro */
#define Rte_IWriteRef_SAC_Controller_Provided_SAC_sac_qap_stFas02_mu8()  ( (P2VAR(IDT_SAC_Interface_sac_qap_stFas02_mu8, AUTOMATIC, RTE_DATA)) &Rte_ImplicitBufs_TaskOem2_1ms.sbuf3.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_SAC_Controller)
/* Inline write optimization; Rte_IWriteRef_SAC_Controller_Provided_SAC_sac_qap_stFas03_mu8 to implicit access macro */
#define Rte_IWriteRef_SAC_Controller_Provided_SAC_sac_qap_stFas03_mu8()  ( (P2VAR(IDT_SAC_Interface_sac_qap_stFas03_mu8, AUTOMATIC, RTE_DATA)) &Rte_ImplicitBufs_TaskOem2_1ms.sbuf4.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_SAC_Controller)
/* Inline write optimization; Rte_IWriteRef_SAC_Controller_Provided_SAC_sac_qap_stFas04_mu8 to implicit access macro */
#define Rte_IWriteRef_SAC_Controller_Provided_SAC_sac_qap_stFas04_mu8()  ( (P2VAR(IDT_SAC_Interface_sac_qap_stFas04_mu8, AUTOMATIC, RTE_DATA)) &Rte_ImplicitBufs_TaskOem2_1ms.sbuf5.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_SAC_Controller)
/* Inline write optimization; Rte_IWriteRef_SAC_Controller_Provided_SAC_sac_qap_stFas05_mu8 to implicit access macro */
#define Rte_IWriteRef_SAC_Controller_Provided_SAC_sac_qap_stFas05_mu8()  ( (P2VAR(IDT_SAC_Interface_sac_qap_stFas05_mu8, AUTOMATIC, RTE_DATA)) &Rte_ImplicitBufs_TaskOem2_1ms.sbuf6.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_SAC_Controller)
/* Inline write optimization; Rte_IWriteRef_SAC_Controller_Provided_SAC_sac_qap_stPrioToTnDsaTsc_mu16 to implicit access macro */
#define Rte_IWriteRef_SAC_Controller_Provided_SAC_sac_qap_stPrioToTnDsaTsc_mu16()  ( (P2VAR(IDT_SAC_Interface_sac_qap_stPrioToTnDsaTsc_mu16, AUTOMATIC, RTE_DATA)) &Rte_ImplicitBufs_TaskOem2_1ms.sbuf7.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_SAC_Controller)
/* Inline write optimization; Rte_IWriteRef_SAC_Controller_Provided_SAC_sac_qap_stQFK_mu8 to implicit access macro */
#define Rte_IWriteRef_SAC_Controller_Provided_SAC_sac_qap_stQFK_mu8()  ( (P2VAR(IDT_SAC_Interface_sac_qap_stQFK_mu8, AUTOMATIC, RTE_DATA)) &Rte_ImplicitBufs_TaskOem2_1ms.sbuf8.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_SAC_Controller)
/* Inline write optimization; Rte_IWriteRef_SAC_Controller_Provided_SAC_sac_qap_stSelQfk_mu8 to implicit access macro */
#define Rte_IWriteRef_SAC_Controller_Provided_SAC_sac_qap_stSelQfk_mu8()  ( (P2VAR(IDT_SAC_Interface_sac_qap_stSelQfk_mu8, AUTOMATIC, RTE_DATA)) &Rte_ImplicitBufs_TaskOem2_1ms.sbuf20.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_SAC_Controller)
/* Inline write optimization; Rte_IWriteRef_SAC_Controller_Provided_SAC_sac_qap_stVMM_mu8 to implicit access macro */
#define Rte_IWriteRef_SAC_Controller_Provided_SAC_sac_qap_stVMM_mu8()  ( (P2VAR(IDT_SAC_Interface_sac_qap_stVMM_mu8, AUTOMATIC, RTE_DATA)) &Rte_ImplicitBufs_TaskOem2_1ms.sbuf9.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_SAC_Controller)
/* Inline write optimization; Rte_IWriteRef_SAC_Controller_Provided_SAC_sac_qap_stVibr_mu8 to implicit access macro */
#define Rte_IWriteRef_SAC_Controller_Provided_SAC_sac_qap_stVibr_mu8()  ( (P2VAR(IDT_SAC_Interface_sac_qap_stVibr_mu8, AUTOMATIC, RTE_DATA)) &Rte_ImplicitBufs_TaskOem2_1ms.sbuf21.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_SAC_Controller)
/* Inline write optimization; Rte_IWriteRef_SAC_Controller_Provided_SAC_sac_qhm_fSollNUel_mi16 to implicit access macro */
#define Rte_IWriteRef_SAC_Controller_Provided_SAC_sac_qhm_fSollNUel_mi16()  ( (P2VAR(IDT_SAC_Interface_sac_qhm_fSollNUel_mi16, AUTOMATIC, RTE_DATA)) &Rte_ImplicitBufs_TaskOem2_1ms.sbuf10.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_SAC_Controller)
/* Inline write optimization; Rte_IWriteRef_SAC_Controller_Provided_SAC_sac_qhm_fSoll_mi16 to implicit access macro */
#define Rte_IWriteRef_SAC_Controller_Provided_SAC_sac_qhm_fSoll_mi16()  ( (P2VAR(IDT_SAC_Interface_sac_qhm_fSoll_mi16, AUTOMATIC, RTE_DATA)) &Rte_ImplicitBufs_TaskOem2_1ms.sbuf11.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_SAC_Controller)
/* Inline write optimization; Rte_IWriteRef_SAC_Controller_Provided_SAC_sac_qhm_mskStatus_mu8 to implicit access macro */
#define Rte_IWriteRef_SAC_Controller_Provided_SAC_sac_qhm_mskStatus_mu8()  ( (P2VAR(IDT_SAC_Interface_sac_qhm_mskStatus_mu8, AUTOMATIC, RTE_DATA)) &Rte_ImplicitBufs_TaskOem2_1ms.sbuf12.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_SAC_Controller)
/* Inline write optimization; Rte_IWriteRef_SAC_Controller_Provided_SAC_sac_qhm_nivIstKraft_mi16 to implicit access macro */
#define Rte_IWriteRef_SAC_Controller_Provided_SAC_sac_qhm_nivIstKraft_mi16()  ( (P2VAR(IDT_SAC_Interface_sac_qhm_nivIstKraft_mi16, AUTOMATIC, RTE_DATA)) &Rte_ImplicitBufs_TaskOem2_1ms.sbuf13.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_SAC_Controller)
/* Inline write optimization; Rte_IWriteRef_SAC_Controller_Provided_SAC_sac_qpr_fSollVib_mi16 to implicit access macro */
#define Rte_IWriteRef_SAC_Controller_Provided_SAC_sac_qpr_fSollVib_mi16()  ( (P2VAR(IDT_SAC_Interface_sac_qpr_fSollVib_mi16, AUTOMATIC, RTE_DATA)) &Rte_ImplicitBufs_TaskOem2_1ms.sbuf14.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_SAC_Controller)
/* Inline write optimization; Rte_IWriteRef_SAC_Controller_Provided_SAC_sac_qua_krIst_mi16 to implicit access macro */
#define Rte_IWriteRef_SAC_Controller_Provided_SAC_sac_qua_krIst_mi16()  ( (P2VAR(IDT_SAC_Interface_sac_qua_krIst_mi16, AUTOMATIC, RTE_DATA)) &Rte_ImplicitBufs_TaskOem2_1ms.sbuf15.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_SAC_Controller)
/* Inline write optimization; Rte_IWriteRef_SAC_Controller_Provided_SAC_sac_qua_stGierSoll_mu8 to implicit access macro */
#define Rte_IWriteRef_SAC_Controller_Provided_SAC_sac_qua_stGierSoll_mu8()  ( (P2VAR(IDT_SAC_Interface_sac_qua_stGierSoll_mu8, AUTOMATIC, RTE_DATA)) &Rte_ImplicitBufs_TaskOem2_1ms.sbuf16.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_SAC_Controller)
/* Inline write optimization; Rte_IWriteRef_SAC_Controller_Provided_SAC_sac_qua_trqGierSoll_mi16 to implicit access macro */
#define Rte_IWriteRef_SAC_Controller_Provided_SAC_sac_qua_trqGierSoll_mi16()  ( (P2VAR(IDT_SAC_Interface_sac_qua_trqGierSoll_mi16, AUTOMATIC, RTE_DATA)) &Rte_ImplicitBufs_TaskOem2_1ms.sbuf17.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_SAC_Controller)
/* Inline write optimization; Rte_IWriteRef_SAC_Controller_Provided_SAC_sac_qua_vFzgLvHigh_mu16 to implicit access macro */
#define Rte_IWriteRef_SAC_Controller_Provided_SAC_sac_qua_vFzgLvHigh_mu16()  ( (P2VAR(IDT_SAC_Interface_sac_qua_vFzgLvHigh_mu16, AUTOMATIC, RTE_DATA)) &Rte_ImplicitBufs_TaskOem2_1ms.sbuf18.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_SAC_Controller)
/* Inline write optimization; Rte_IWriteRef_SAC_Controller_Provided_SAC_sac_stSAC_mu32 to implicit access macro */
#define Rte_IWriteRef_SAC_Controller_Provided_SAC_sac_stSAC_mu32()  ( (P2VAR(IDT_SAC_Interface_sac_stSAC_mu32, AUTOMATIC, RTE_DATA)) &Rte_ImplicitBufs_TaskOem2_1ms.sbuf19.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_SAC_Controller)
/* Inline write optimization; Rte_IWrite_SAC_Controller_Provided_SAC_sac_can_strDevMsgTx1_mu32 to implicit access macro */
#define Rte_IWrite_SAC_Controller_Provided_SAC_sac_can_strDevMsgTx1_mu32( data )  ( Rte_ImplicitBufs_TaskOem2_1ms.sbuf0.value = (data) )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_SAC_Controller)
/* Inline write optimization; Rte_IWrite_SAC_Controller_Provided_SAC_sac_can_strDevMsgTx2_mu32 to implicit access macro */
#define Rte_IWrite_SAC_Controller_Provided_SAC_sac_can_strDevMsgTx2_mu32( data )  ( Rte_ImplicitBufs_TaskOem2_1ms.sbuf1.value = (data) )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_SAC_Controller)
/* Inline write optimization; Rte_IWrite_SAC_Controller_Provided_SAC_sac_qap_stFas01_mu8 to implicit access macro */
#define Rte_IWrite_SAC_Controller_Provided_SAC_sac_qap_stFas01_mu8( data )  ( Rte_ImplicitBufs_TaskOem2_1ms.sbuf2.value = (data) )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_SAC_Controller)
/* Inline write optimization; Rte_IWrite_SAC_Controller_Provided_SAC_sac_qap_stFas02_mu8 to implicit access macro */
#define Rte_IWrite_SAC_Controller_Provided_SAC_sac_qap_stFas02_mu8( data )  ( Rte_ImplicitBufs_TaskOem2_1ms.sbuf3.value = (data) )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_SAC_Controller)
/* Inline write optimization; Rte_IWrite_SAC_Controller_Provided_SAC_sac_qap_stFas03_mu8 to implicit access macro */
#define Rte_IWrite_SAC_Controller_Provided_SAC_sac_qap_stFas03_mu8( data )  ( Rte_ImplicitBufs_TaskOem2_1ms.sbuf4.value = (data) )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_SAC_Controller)
/* Inline write optimization; Rte_IWrite_SAC_Controller_Provided_SAC_sac_qap_stFas04_mu8 to implicit access macro */
#define Rte_IWrite_SAC_Controller_Provided_SAC_sac_qap_stFas04_mu8( data )  ( Rte_ImplicitBufs_TaskOem2_1ms.sbuf5.value = (data) )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_SAC_Controller)
/* Inline write optimization; Rte_IWrite_SAC_Controller_Provided_SAC_sac_qap_stFas05_mu8 to implicit access macro */
#define Rte_IWrite_SAC_Controller_Provided_SAC_sac_qap_stFas05_mu8( data )  ( Rte_ImplicitBufs_TaskOem2_1ms.sbuf6.value = (data) )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_SAC_Controller)
/* Inline write optimization; Rte_IWrite_SAC_Controller_Provided_SAC_sac_qap_stPrioToTnDsaTsc_mu16 to implicit access macro */
#define Rte_IWrite_SAC_Controller_Provided_SAC_sac_qap_stPrioToTnDsaTsc_mu16( data )  ( Rte_ImplicitBufs_TaskOem2_1ms.sbuf7.value = (data) )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_SAC_Controller)
/* Inline write optimization; Rte_IWrite_SAC_Controller_Provided_SAC_sac_qap_stQFK_mu8 to implicit access macro */
#define Rte_IWrite_SAC_Controller_Provided_SAC_sac_qap_stQFK_mu8( data )  ( Rte_ImplicitBufs_TaskOem2_1ms.sbuf8.value = (data) )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_SAC_Controller)
/* Inline write optimization; Rte_IWrite_SAC_Controller_Provided_SAC_sac_qap_stSelQfk_mu8 to implicit access macro */
#define Rte_IWrite_SAC_Controller_Provided_SAC_sac_qap_stSelQfk_mu8( data )  ( Rte_ImplicitBufs_TaskOem2_1ms.sbuf20.value = (data) )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_SAC_Controller)
/* Inline write optimization; Rte_IWrite_SAC_Controller_Provided_SAC_sac_qap_stVMM_mu8 to implicit access macro */
#define Rte_IWrite_SAC_Controller_Provided_SAC_sac_qap_stVMM_mu8( data )  ( Rte_ImplicitBufs_TaskOem2_1ms.sbuf9.value = (data) )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_SAC_Controller)
/* Inline write optimization; Rte_IWrite_SAC_Controller_Provided_SAC_sac_qap_stVibr_mu8 to implicit access macro */
#define Rte_IWrite_SAC_Controller_Provided_SAC_sac_qap_stVibr_mu8( data )  ( Rte_ImplicitBufs_TaskOem2_1ms.sbuf21.value = (data) )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_SAC_Controller)
/* Inline write optimization; Rte_IWrite_SAC_Controller_Provided_SAC_sac_qhm_fSollNUel_mi16 to implicit access macro */
#define Rte_IWrite_SAC_Controller_Provided_SAC_sac_qhm_fSollNUel_mi16( data )  ( Rte_ImplicitBufs_TaskOem2_1ms.sbuf10.value = (data) )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_SAC_Controller)
/* Inline write optimization; Rte_IWrite_SAC_Controller_Provided_SAC_sac_qhm_fSoll_mi16 to implicit access macro */
#define Rte_IWrite_SAC_Controller_Provided_SAC_sac_qhm_fSoll_mi16( data )  ( Rte_ImplicitBufs_TaskOem2_1ms.sbuf11.value = (data) )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_SAC_Controller)
/* Inline write optimization; Rte_IWrite_SAC_Controller_Provided_SAC_sac_qhm_mskStatus_mu8 to implicit access macro */
#define Rte_IWrite_SAC_Controller_Provided_SAC_sac_qhm_mskStatus_mu8( data )  ( Rte_ImplicitBufs_TaskOem2_1ms.sbuf12.value = (data) )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_SAC_Controller)
/* Inline write optimization; Rte_IWrite_SAC_Controller_Provided_SAC_sac_qhm_nivIstKraft_mi16 to implicit access macro */
#define Rte_IWrite_SAC_Controller_Provided_SAC_sac_qhm_nivIstKraft_mi16( data )  ( Rte_ImplicitBufs_TaskOem2_1ms.sbuf13.value = (data) )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_SAC_Controller)
/* Inline write optimization; Rte_IWrite_SAC_Controller_Provided_SAC_sac_qpr_fSollVib_mi16 to implicit access macro */
#define Rte_IWrite_SAC_Controller_Provided_SAC_sac_qpr_fSollVib_mi16( data )  ( Rte_ImplicitBufs_TaskOem2_1ms.sbuf14.value = (data) )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_SAC_Controller)
/* Inline write optimization; Rte_IWrite_SAC_Controller_Provided_SAC_sac_qua_krIst_mi16 to implicit access macro */
#define Rte_IWrite_SAC_Controller_Provided_SAC_sac_qua_krIst_mi16( data )  ( Rte_ImplicitBufs_TaskOem2_1ms.sbuf15.value = (data) )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_SAC_Controller)
/* Inline write optimization; Rte_IWrite_SAC_Controller_Provided_SAC_sac_qua_stGierSoll_mu8 to implicit access macro */
#define Rte_IWrite_SAC_Controller_Provided_SAC_sac_qua_stGierSoll_mu8( data )  ( Rte_ImplicitBufs_TaskOem2_1ms.sbuf16.value = (data) )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_SAC_Controller)
/* Inline write optimization; Rte_IWrite_SAC_Controller_Provided_SAC_sac_qua_trqGierSoll_mi16 to implicit access macro */
#define Rte_IWrite_SAC_Controller_Provided_SAC_sac_qua_trqGierSoll_mi16( data )  ( Rte_ImplicitBufs_TaskOem2_1ms.sbuf17.value = (data) )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_SAC_Controller)
/* Inline write optimization; Rte_IWrite_SAC_Controller_Provided_SAC_sac_qua_vFzgLvHigh_mu16 to implicit access macro */
#define Rte_IWrite_SAC_Controller_Provided_SAC_sac_qua_vFzgLvHigh_mu16( data )  ( Rte_ImplicitBufs_TaskOem2_1ms.sbuf18.value = (data) )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_SAC_Controller)
/* Inline write optimization; Rte_IWrite_SAC_Controller_Provided_SAC_sac_stSAC_mu32 to implicit access macro */
#define Rte_IWrite_SAC_Controller_Provided_SAC_sac_stSAC_mu32( data )  ( Rte_ImplicitBufs_TaskOem2_1ms.sbuf19.value = (data) )
#endif

#endif /* RTE_CORE */

/*******************************************************
 ***
 *** RE Prototypes
 ***
 *******************************************************/

#define SAC_SWC_START_SEC_CODE
#include "Std_Types.h"
FUNC(void, SAC_SWC_CODE) SAC_Controller_runnable(void);
FUNC(void, SAC_SWC_CODE) SAC_Init_runnable(void);
#define SAC_SWC_STOP_SEC_CODE
#include "Std_Types.h"

/* Initial values for data element prototypes */

#ifdef __cplusplus
} /* extern C */
#endif /* __cplusplus */

#endif /* !RTE_SAC_SWC_H */
