/** @file     Rte_DataHandleType.h
  *
  * @brief    RTE DataElement type definitions
  *
  * @note     AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
  *
  * @note     Generated by ETAS RTA-RTE
  * @note     Version 7.3.0 
  */

#ifndef RTE_DATA_HANDLE_TYPE_H
#define RTE_DATA_HANDLE_TYPE_H

#include "Rte_Type.h"
#include "Rte_Cfg.h"

typedef struct {
   IDT_ASC_BSW_Interface_bsw_iBat_mi16 value;
} Rte_DE_IDT_ASC_BSW_Interface_bsw_iBat_mi16;

typedef struct {
   IDT_ASC_BSW_Interface_bsw_levelAssist_mu8 value;
} Rte_DE_IDT_ASC_BSW_Interface_bsw_levelAssist_mu8;

typedef struct {
   IDT_ASC_BSW_Interface_bsw_lku_fSoll_mi16 value;
} Rte_DE_IDT_ASC_BSW_Interface_bsw_lku_fSoll_mi16;

typedef struct {
   IDT_ASC_BSW_Interface_bsw_mskStatusbits01_mu32 value;
} Rte_DE_IDT_ASC_BSW_Interface_bsw_mskStatusbits01_mu32;

typedef struct {
   IDT_ASC_BSW_Interface_bsw_mskStatusbits02_mu32 value;
} Rte_DE_IDT_ASC_BSW_Interface_bsw_mskStatusbits02_mu32;

typedef struct {
   IDT_ASC_BSW_Interface_bsw_phiRitzelMotor_mi16 value;
} Rte_DE_IDT_ASC_BSW_Interface_bsw_phiRitzelMotor_mi16;

typedef struct {
   IDT_ASC_BSW_Interface_bsw_phiRitzel_mi32 value;
} Rte_DE_IDT_ASC_BSW_Interface_bsw_phiRitzel_mi32;

typedef struct {
   IDT_ASC_BSW_Interface_bsw_phvRitzel_mi16 value;
} Rte_DE_IDT_ASC_BSW_Interface_bsw_phvRitzel_mi16;

typedef struct {
   IDT_ASC_BSW_Interface_bsw_stDiagnose_mu32 value;
} Rte_DE_IDT_ASC_BSW_Interface_bsw_stDiagnose_mu32;

typedef struct {
   IDT_ASC_BSW_Interface_bsw_stSAC_mu32 value;
} Rte_DE_IDT_ASC_BSW_Interface_bsw_stSAC_mu32;

typedef struct {
   IDT_ASC_BSW_Interface_bsw_stTac_mu32 value;
} Rte_DE_IDT_ASC_BSW_Interface_bsw_stTac_mu32;

typedef struct {
   IDT_ASC_BSW_Interface_bsw_tZahnstange_mi16 value;
} Rte_DE_IDT_ASC_BSW_Interface_bsw_tZahnstange_mi16;

typedef struct {
   IDT_ASC_BSW_Interface_bsw_tempEcu_mi16 value;
} Rte_DE_IDT_ASC_BSW_Interface_bsw_tempEcu_mi16;

typedef struct {
   IDT_ASC_BSW_Interface_bsw_trqIst_mi16 value;
} Rte_DE_IDT_ASC_BSW_Interface_bsw_trqIst_mi16;

typedef struct {
   IDT_ASC_BSW_Interface_bsw_trqSensorKomp_mi16 value;
} Rte_DE_IDT_ASC_BSW_Interface_bsw_trqSensorKomp_mi16;

typedef struct {
   IDT_ASC_BSW_Interface_bsw_trqSensor_mi16 value;
} Rte_DE_IDT_ASC_BSW_Interface_bsw_trqSensor_mi16;

typedef struct {
   IDT_ASC_BSW_Interface_bsw_trqSoll_mi16 value;
} Rte_DE_IDT_ASC_BSW_Interface_bsw_trqSoll_mi16;

typedef struct {
   IDT_ASC_BSW_Interface_bsw_uBat_mu16 value;
} Rte_DE_IDT_ASC_BSW_Interface_bsw_uBat_mu16;

typedef struct {
   IDT_ASC_BSW_Interface_can_beschlLaengs_mi16 value;
} Rte_DE_IDT_ASC_BSW_Interface_can_beschlLaengs_mi16;

typedef struct {
   IDT_ASC_BSW_Interface_can_beschlQuer_mi16 value;
} Rte_DE_IDT_ASC_BSW_Interface_can_beschlQuer_mi16;

typedef struct {
   IDT_ASC_BSW_Interface_can_facTrqWheel_mu8 value;
} Rte_DE_IDT_ASC_BSW_Interface_can_facTrqWheel_mu8;

typedef struct {
   IDT_ASC_BSW_Interface_can_gierrate_mi16 value;
} Rte_DE_IDT_ASC_BSW_Interface_can_gierrate_mi16;

typedef struct {
   IDT_ASC_BSW_Interface_can_gradUeb_mi8 value;
} Rte_DE_IDT_ASC_BSW_Interface_can_gradUeb_mi8;

typedef struct {
   IDT_ASC_BSW_Interface_can_imp_HL_mu16 value;
} Rte_DE_IDT_ASC_BSW_Interface_can_imp_HL_mu16;

typedef struct {
   IDT_ASC_BSW_Interface_can_imp_HR_mu16 value;
} Rte_DE_IDT_ASC_BSW_Interface_can_imp_HR_mu16;

typedef struct {
   IDT_ASC_BSW_Interface_can_levelPedal_mu8 value;
} Rte_DE_IDT_ASC_BSW_Interface_can_levelPedal_mu8;

typedef struct {
   IDT_ASC_BSW_Interface_can_pBrems_mi16 value;
} Rte_DE_IDT_ASC_BSW_Interface_can_pBrems_mi16;

typedef struct {
   IDT_ASC_BSW_Interface_can_rpmMotor_mu16 value;
} Rte_DE_IDT_ASC_BSW_Interface_can_rpmMotor_mu16;

typedef struct {
   IDT_ASC_BSW_Interface_can_stESP14_mu8 value;
} Rte_DE_IDT_ASC_BSW_Interface_can_stESP14_mu8;

typedef struct {
   IDT_ASC_BSW_Interface_can_stFahrbereitschaft_mu8 value;
} Rte_DE_IDT_ASC_BSW_Interface_can_stFahrbereitschaft_mu8;

typedef struct {
   IDT_ASC_BSW_Interface_can_stLaufleistung_mu32 value;
} Rte_DE_IDT_ASC_BSW_Interface_can_stLaufleistung_mu32;

typedef struct {
   IDT_ASC_BSW_Interface_can_stMO14_mu8 value;
} Rte_DE_IDT_ASC_BSW_Interface_can_stMO14_mu8;

typedef struct {
   IDT_ASC_BSW_Interface_can_stSignale01_mu32 value;
} Rte_DE_IDT_ASC_BSW_Interface_can_stSignale01_mu32;

typedef struct {
   IDT_ASC_BSW_Interface_can_stSignale02_mu32 value;
} Rte_DE_IDT_ASC_BSW_Interface_can_stSignale02_mu32;

typedef struct {
   IDT_ASC_BSW_Interface_can_stTrqWheel_mu8 value;
} Rte_DE_IDT_ASC_BSW_Interface_can_stTrqWheel_mu8;

typedef struct {
   IDT_ASC_BSW_Interface_can_strDevMsgRx1_mu32 value;
} Rte_DE_IDT_ASC_BSW_Interface_can_strDevMsgRx1_mu32;

typedef struct {
   IDT_ASC_BSW_Interface_can_strDevMsgRx2_mu32 value;
} Rte_DE_IDT_ASC_BSW_Interface_can_strDevMsgRx2_mu32;

typedef struct {
   IDT_ASC_BSW_Interface_can_tragMo_mi16 value;
} Rte_DE_IDT_ASC_BSW_Interface_can_tragMo_mi16;

typedef struct {
   IDT_ASC_BSW_Interface_can_trqAllrad_mu8 value;
} Rte_DE_IDT_ASC_BSW_Interface_can_trqAllrad_mu8;

typedef struct {
   IDT_ASC_BSW_Interface_can_trqMoIst_mi16 value;
} Rte_DE_IDT_ASC_BSW_Interface_can_trqMoIst_mi16;

typedef struct {
   IDT_ASC_BSW_Interface_can_trqMoSchub_mi16 value;
} Rte_DE_IDT_ASC_BSW_Interface_can_trqMoSchub_mi16;

typedef struct {
   IDT_ASC_BSW_Interface_can_trqMoSollRoh_mi16 value;
} Rte_DE_IDT_ASC_BSW_Interface_can_trqMoSollRoh_mi16;

typedef struct {
   IDT_ASC_BSW_Interface_can_trqWheelActSec_mi16 value;
} Rte_DE_IDT_ASC_BSW_Interface_can_trqWheelActSec_mi16;

typedef struct {
   IDT_ASC_BSW_Interface_can_trqWheelAct_mi16 value;
} Rte_DE_IDT_ASC_BSW_Interface_can_trqWheelAct_mi16;

typedef struct {
   IDT_ASC_BSW_Interface_can_vRad_HL_mi16 value;
} Rte_DE_IDT_ASC_BSW_Interface_can_vRad_HL_mi16;

typedef struct {
   IDT_ASC_BSW_Interface_can_vRad_HR_mi16 value;
} Rte_DE_IDT_ASC_BSW_Interface_can_vRad_HR_mi16;

typedef struct {
   IDT_ASC_BSW_Interface_can_vRad_VL_mi16 value;
} Rte_DE_IDT_ASC_BSW_Interface_can_vRad_VL_mi16;

typedef struct {
   IDT_ASC_BSW_Interface_can_vRad_VR_mi16 value;
} Rte_DE_IDT_ASC_BSW_Interface_can_vRad_VR_mi16;

typedef struct {
   IDT_ASC_BSW_Interface_can_vSignal_mu16 value;
} Rte_DE_IDT_ASC_BSW_Interface_can_vSignal_mu16;

typedef struct {
   IDT_ASC_BSW_Interface_can_vaqIst_mu8 value;
} Rte_DE_IDT_ASC_BSW_Interface_can_vaqIst_mu8;

typedef struct {
   IDT_ASC_BSW_Interface_cha_facAuto_mu16 value;
} Rte_DE_IDT_ASC_BSW_Interface_cha_facAuto_mu16;

typedef struct {
   IDT_ASC_BSW_Interface_cha_facDyn_mu16 value;
} Rte_DE_IDT_ASC_BSW_Interface_cha_facDyn_mu16;

typedef struct {
   IDT_ASC_BSW_Interface_cha_facEvent_mu16 value;
} Rte_DE_IDT_ASC_BSW_Interface_cha_facEvent_mu16;

typedef struct {
   IDT_ASC_BSW_Interface_cha_facKom_mu16 value;
} Rte_DE_IDT_ASC_BSW_Interface_cha_facKom_mu16;

typedef struct {
   IDT_ASC_BSW_Interface_dia_mskAnpassung01_mu32 value;
} Rte_DE_IDT_ASC_BSW_Interface_dia_mskAnpassung01_mu32;

typedef struct {
   IDT_ASC_BSW_Interface_dia_mskCodierung01_mu32 value;
} Rte_DE_IDT_ASC_BSW_Interface_dia_mskCodierung01_mu32;

typedef struct {
   IDT_ASC_BSW_Interface_fga_mskStVFzg_mu8 value;
} Rte_DE_IDT_ASC_BSW_Interface_fga_mskStVFzg_mu8;

typedef struct {
   IDT_ASC_BSW_Interface_fga_vFzg_mi16 value;
} Rte_DE_IDT_ASC_BSW_Interface_fga_vFzg_mi16;

typedef struct {
   IDT_ASC_BSW_Interface_hca_stHCA_mu8 value;
} Rte_DE_IDT_ASC_BSW_Interface_hca_stHCA_mu8;

typedef struct {
   IDT_ASC_BSW_Interface_qap_stPrioToTnDsaTsc_mu8 value;
} Rte_DE_IDT_ASC_BSW_Interface_qap_stPrioToTnDsaTsc_mu8;

typedef struct {
   IDT_ASC_Interface_asc_StartStopp_Info_mu8 value;
} Rte_DE_IDT_ASC_Interface_asc_StartStopp_Info_mu8;

typedef struct {
   IDT_ASC_Interface_asc_can_strDevMsgTx1_mu32 value;
} Rte_DE_IDT_ASC_Interface_asc_can_strDevMsgTx1_mu32;

typedef struct {
   IDT_ASC_Interface_asc_can_strDevMsgTx2_mu32 value;
} Rte_DE_IDT_ASC_Interface_asc_can_strDevMsgTx2_mu32;

typedef struct {
   IDT_ASC_Interface_asc_epsWarn_mu8 value;
} Rte_DE_IDT_ASC_Interface_asc_epsWarn_mu8;

typedef struct {
   IDT_ASC_Interface_asc_fSoll_mi16 value;
} Rte_DE_IDT_ASC_Interface_asc_fSoll_mi16;

typedef struct {
   IDT_ASC_Interface_asc_facReduzlku_mu16 value;
} Rte_DE_IDT_ASC_Interface_asc_facReduzlku_mu16;

typedef struct {
   IDT_ASC_Interface_asc_facReduztrq_mu16 value;
} Rte_DE_IDT_ASC_Interface_asc_facReduztrq_mu16;

typedef struct {
   IDT_ASC_Interface_asc_ger_phiK_mi16 value;
} Rte_DE_IDT_ASC_Interface_asc_ger_phiK_mi16;

typedef struct {
   IDT_ASC_Interface_asc_ger_phiL_mi16 value;
} Rte_DE_IDT_ASC_Interface_asc_ger_phiL_mi16;

typedef struct {
   IDT_ASC_Interface_asc_ger_stLernK_mu8 value;
} Rte_DE_IDT_ASC_Interface_asc_ger_stLernK_mu8;

typedef struct {
   IDT_ASC_Interface_asc_ger_stLernL_mu8 value;
} Rte_DE_IDT_ASC_Interface_asc_ger_stLernL_mu8;

typedef struct {
   IDT_ASC_Interface_asc_mst_startBed_mu8 value;
} Rte_DE_IDT_ASC_Interface_asc_mst_startBed_mu8;

typedef struct {
   IDT_ASC_Interface_asc_stASC_mu32 value;
} Rte_DE_IDT_ASC_Interface_asc_stASC_mu32;

typedef struct {
   IDT_ASC_Interface_asc_stDsaTsc2Qfk_mu16 value;
} Rte_DE_IDT_ASC_Interface_asc_stDsaTsc2Qfk_mu16;

typedef struct {
   IDT_ASC_Interface_asc_trqOffset_mi16 value;
} Rte_DE_IDT_ASC_Interface_asc_trqOffset_mi16;

typedef struct {
   IDT_ASC_Interface_asc_tsc_fSoll_mi16 value;
} Rte_DE_IDT_ASC_Interface_asc_tsc_fSoll_mi16;

typedef struct {
   IDT_ASC_Interface_asc_tsc_facLern_mu16 value;
} Rte_DE_IDT_ASC_Interface_asc_tsc_facLern_mu16;

typedef struct {
   IDT_ASC_Interface_asc_tsc_stLerrn_mu8 value;
} Rte_DE_IDT_ASC_Interface_asc_tsc_stLerrn_mu8;

typedef struct {
   IDT_BSW_Interface_bsw_stFrgBusFehler_mu8 value;
} Rte_DE_IDT_BSW_Interface_bsw_stFrgBusFehler_mu8;

typedef struct {
   IDT_SAC_BSW_Interface_asc_fSoll_mi16 value;
} Rte_DE_IDT_SAC_BSW_Interface_asc_fSoll_mi16;

typedef struct {
   IDT_SAC_BSW_Interface_asc_ger_phiL_mi16 value;
} Rte_DE_IDT_SAC_BSW_Interface_asc_ger_phiL_mi16;

typedef struct {
   IDT_SAC_BSW_Interface_asc_stASC_mu32 value;
} Rte_DE_IDT_SAC_BSW_Interface_asc_stASC_mu32;

typedef struct {
   IDT_SAC_BSW_Interface_asc_stDsaTsc2Qfk_mu16 value;
} Rte_DE_IDT_SAC_BSW_Interface_asc_stDsaTsc2Qfk_mu16;

typedef struct {
   IDT_SAC_BSW_Interface_bsw_fSollLimMtl_mi16 value;
} Rte_DE_IDT_SAC_BSW_Interface_bsw_fSollLimMtl_mi16;

typedef struct {
   IDT_SAC_BSW_Interface_bsw_levelAssist_mu8 value;
} Rte_DE_IDT_SAC_BSW_Interface_bsw_levelAssist_mu8;

typedef struct {
   IDT_SAC_BSW_Interface_bsw_mskStatusbits01_mu32 value;
} Rte_DE_IDT_SAC_BSW_Interface_bsw_mskStatusbits01_mu32;

typedef struct {
   IDT_SAC_BSW_Interface_bsw_mskStatusbits02_mu32 value;
} Rte_DE_IDT_SAC_BSW_Interface_bsw_mskStatusbits02_mu32;

typedef struct {
   IDT_SAC_BSW_Interface_bsw_phvRitzel_mi16 value;
} Rte_DE_IDT_SAC_BSW_Interface_bsw_phvRitzel_mi16;

typedef struct {
   IDT_SAC_BSW_Interface_bsw_stFehlerULstg_mu8 value;
} Rte_DE_IDT_SAC_BSW_Interface_bsw_stFehlerULstg_mu8;

typedef struct {
   IDT_SAC_BSW_Interface_bsw_stKl15_mu8 value;
} Rte_DE_IDT_SAC_BSW_Interface_bsw_stKl15_mu8;

typedef struct {
   IDT_SAC_BSW_Interface_bsw_stVzstLimSafetyFader_mu8 value;
} Rte_DE_IDT_SAC_BSW_Interface_bsw_stVzstLimSafetyFader_mu8;

typedef struct {
   IDT_SAC_BSW_Interface_bsw_stVzstLimSafety_mu8 value;
} Rte_DE_IDT_SAC_BSW_Interface_bsw_stVzstLimSafety_mu8;

typedef struct {
   IDT_SAC_BSW_Interface_bsw_trqSensorLku_mi16 value;
} Rte_DE_IDT_SAC_BSW_Interface_bsw_trqSensorLku_mi16;

typedef struct {
   IDT_SAC_BSW_Interface_bsw_trqSensor_mi16 value;
} Rte_DE_IDT_SAC_BSW_Interface_bsw_trqSensor_mi16;

typedef struct {
   IDT_SAC_BSW_Interface_bsw_uBatt_mu16 value;
} Rte_DE_IDT_SAC_BSW_Interface_bsw_uBatt_mu16;

typedef struct {
   IDT_SAC_BSW_Interface_bsw_vZstLimMax_mi16 value;
} Rte_DE_IDT_SAC_BSW_Interface_bsw_vZstLimMax_mi16;

typedef struct {
   IDT_SAC_BSW_Interface_bsw_vZstLimMin_mi16 value;
} Rte_DE_IDT_SAC_BSW_Interface_bsw_vZstLimMin_mi16;

typedef struct {
   IDT_SAC_BSW_Interface_bsw_vZst_mi16 value;
} Rte_DE_IDT_SAC_BSW_Interface_bsw_vZst_mi16;

typedef struct {
   IDT_SAC_BSW_Interface_bsw_xZstEASoll_mi16 value;
} Rte_DE_IDT_SAC_BSW_Interface_bsw_xZstEASoll_mi16;

typedef struct {
   IDT_SAC_BSW_Interface_bsw_xZstGerKorr_mi32 value;
} Rte_DE_IDT_SAC_BSW_Interface_bsw_xZstGerKorr_mi32;

typedef struct {
   IDT_SAC_BSW_Interface_bsw_xZst_mi32 value;
} Rte_DE_IDT_SAC_BSW_Interface_bsw_xZst_mi32;

typedef struct {
   IDT_SAC_BSW_Interface_can_beschlQuer_mi16 value;
} Rte_DE_IDT_SAC_BSW_Interface_can_beschlQuer_mi16;

typedef struct {
   IDT_SAC_BSW_Interface_can_cntFas01_mu8 value;
} Rte_DE_IDT_SAC_BSW_Interface_can_cntFas01_mu8;

typedef struct {
   IDT_SAC_BSW_Interface_can_cntFas02_mu8 value;
} Rte_DE_IDT_SAC_BSW_Interface_can_cntFas02_mu8;

typedef struct {
   IDT_SAC_BSW_Interface_can_cntFas03_mu8 value;
} Rte_DE_IDT_SAC_BSW_Interface_can_cntFas03_mu8;

typedef struct {
   IDT_SAC_BSW_Interface_can_cntFas04_mu8 value;
} Rte_DE_IDT_SAC_BSW_Interface_can_cntFas04_mu8;

typedef struct {
   IDT_SAC_BSW_Interface_can_cntFas05_mu8 value;
} Rte_DE_IDT_SAC_BSW_Interface_can_cntFas05_mu8;

typedef struct {
   IDT_SAC_BSW_Interface_can_cntVMM_mu8 value;
} Rte_DE_IDT_SAC_BSW_Interface_can_cntVMM_mu8;

typedef struct {
   IDT_SAC_BSW_Interface_can_facSignal1Fas01_mu16 value;
} Rte_DE_IDT_SAC_BSW_Interface_can_facSignal1Fas01_mu16;

typedef struct {
   IDT_SAC_BSW_Interface_can_facSignal1Fas02_mu16 value;
} Rte_DE_IDT_SAC_BSW_Interface_can_facSignal1Fas02_mu16;

typedef struct {
   IDT_SAC_BSW_Interface_can_facSignal1Fas03_mu16 value;
} Rte_DE_IDT_SAC_BSW_Interface_can_facSignal1Fas03_mu16;

typedef struct {
   IDT_SAC_BSW_Interface_can_facSignal1Fas04_mu16 value;
} Rte_DE_IDT_SAC_BSW_Interface_can_facSignal1Fas04_mu16;

typedef struct {
   IDT_SAC_BSW_Interface_can_facSignal1Fas05_mu16 value;
} Rte_DE_IDT_SAC_BSW_Interface_can_facSignal1Fas05_mu16;

typedef struct {
   IDT_SAC_BSW_Interface_can_facSignal1VMM_mu16 value;
} Rte_DE_IDT_SAC_BSW_Interface_can_facSignal1VMM_mu16;

typedef struct {
   IDT_SAC_BSW_Interface_can_facSignal2Fas01_mu16 value;
} Rte_DE_IDT_SAC_BSW_Interface_can_facSignal2Fas01_mu16;

typedef struct {
   IDT_SAC_BSW_Interface_can_facSignal2Fas02_mu16 value;
} Rte_DE_IDT_SAC_BSW_Interface_can_facSignal2Fas02_mu16;

typedef struct {
   IDT_SAC_BSW_Interface_can_facSignal2Fas03_mu16 value;
} Rte_DE_IDT_SAC_BSW_Interface_can_facSignal2Fas03_mu16;

typedef struct {
   IDT_SAC_BSW_Interface_can_facSignal2Fas04_mu16 value;
} Rte_DE_IDT_SAC_BSW_Interface_can_facSignal2Fas04_mu16;

typedef struct {
   IDT_SAC_BSW_Interface_can_facSignal2Fas05_mu16 value;
} Rte_DE_IDT_SAC_BSW_Interface_can_facSignal2Fas05_mu16;

typedef struct {
   IDT_SAC_BSW_Interface_can_facSignal2VMM_mu16 value;
} Rte_DE_IDT_SAC_BSW_Interface_can_facSignal2VMM_mu16;

typedef struct {
   IDT_SAC_BSW_Interface_can_facSpuerbFas01_mu16 value;
} Rte_DE_IDT_SAC_BSW_Interface_can_facSpuerbFas01_mu16;

typedef struct {
   IDT_SAC_BSW_Interface_can_facSpuerbFas02_mu16 value;
} Rte_DE_IDT_SAC_BSW_Interface_can_facSpuerbFas02_mu16;

typedef struct {
   IDT_SAC_BSW_Interface_can_facSpuerbFas03_mu16 value;
} Rte_DE_IDT_SAC_BSW_Interface_can_facSpuerbFas03_mu16;

typedef struct {
   IDT_SAC_BSW_Interface_can_facSpuerbFas04_mu16 value;
} Rte_DE_IDT_SAC_BSW_Interface_can_facSpuerbFas04_mu16;

typedef struct {
   IDT_SAC_BSW_Interface_can_facSpuerbFas05_mu16 value;
} Rte_DE_IDT_SAC_BSW_Interface_can_facSpuerbFas05_mu16;

typedef struct {
   IDT_SAC_BSW_Interface_can_facSpuerbVMM_mu16 value;
} Rte_DE_IDT_SAC_BSW_Interface_can_facSpuerbVMM_mu16;

typedef struct {
   IDT_SAC_BSW_Interface_can_gierrate_mi16 value;
} Rte_DE_IDT_SAC_BSW_Interface_can_gierrate_mi16;

typedef struct {
   IDT_SAC_BSW_Interface_can_krSollFas01_mi16 value;
} Rte_DE_IDT_SAC_BSW_Interface_can_krSollFas01_mi16;

typedef struct {
   IDT_SAC_BSW_Interface_can_krSollFas02_mi16 value;
} Rte_DE_IDT_SAC_BSW_Interface_can_krSollFas02_mi16;

typedef struct {
   IDT_SAC_BSW_Interface_can_krSollFas03_mi16 value;
} Rte_DE_IDT_SAC_BSW_Interface_can_krSollFas03_mi16;

typedef struct {
   IDT_SAC_BSW_Interface_can_krSollFas04_mi16 value;
} Rte_DE_IDT_SAC_BSW_Interface_can_krSollFas04_mi16;

typedef struct {
   IDT_SAC_BSW_Interface_can_krSollFas05_mi16 value;
} Rte_DE_IDT_SAC_BSW_Interface_can_krSollFas05_mi16;

typedef struct {
   IDT_SAC_BSW_Interface_can_phiEscKinX1_mu16 value;
} Rte_DE_IDT_SAC_BSW_Interface_can_phiEscKinX1_mu16;

typedef struct {
   IDT_SAC_BSW_Interface_can_phiEscKinX2_mu16 value;
} Rte_DE_IDT_SAC_BSW_Interface_can_phiEscKinX2_mu16;

typedef struct {
   IDT_SAC_BSW_Interface_can_phiEscKinX3_mu16 value;
} Rte_DE_IDT_SAC_BSW_Interface_can_phiEscKinX3_mu16;

typedef struct {
   IDT_SAC_BSW_Interface_can_phiEscKinX4_mu16 value;
} Rte_DE_IDT_SAC_BSW_Interface_can_phiEscKinX4_mu16;

typedef struct {
   IDT_SAC_BSW_Interface_can_phiEscKinX5_mu16 value;
} Rte_DE_IDT_SAC_BSW_Interface_can_phiEscKinX5_mu16;

typedef struct {
   IDT_SAC_BSW_Interface_can_phiEscKinY1_mu16 value;
} Rte_DE_IDT_SAC_BSW_Interface_can_phiEscKinY1_mu16;

typedef struct {
   IDT_SAC_BSW_Interface_can_phiEscKinY2_mu16 value;
} Rte_DE_IDT_SAC_BSW_Interface_can_phiEscKinY2_mu16;

typedef struct {
   IDT_SAC_BSW_Interface_can_phiEscKinY3_mu16 value;
} Rte_DE_IDT_SAC_BSW_Interface_can_phiEscKinY3_mu16;

typedef struct {
   IDT_SAC_BSW_Interface_can_phiEscKinY4_mu16 value;
} Rte_DE_IDT_SAC_BSW_Interface_can_phiEscKinY4_mu16;

typedef struct {
   IDT_SAC_BSW_Interface_can_phiEscKinY5_mu16 value;
} Rte_DE_IDT_SAC_BSW_Interface_can_phiEscKinY5_mu16;

typedef struct {
   IDT_SAC_BSW_Interface_can_sESCRadstand_mu16 value;
} Rte_DE_IDT_SAC_BSW_Interface_can_sESCRadstand_mu16;

typedef struct {
   IDT_SAC_BSW_Interface_can_stAnfFas01_mu8 value;
} Rte_DE_IDT_SAC_BSW_Interface_can_stAnfFas01_mu8;

typedef struct {
   IDT_SAC_BSW_Interface_can_stAnfFas02_mu8 value;
} Rte_DE_IDT_SAC_BSW_Interface_can_stAnfFas02_mu8;

typedef struct {
   IDT_SAC_BSW_Interface_can_stAnfFas03_mu8 value;
} Rte_DE_IDT_SAC_BSW_Interface_can_stAnfFas03_mu8;

typedef struct {
   IDT_SAC_BSW_Interface_can_stAnfFas04_mu8 value;
} Rte_DE_IDT_SAC_BSW_Interface_can_stAnfFas04_mu8;

typedef struct {
   IDT_SAC_BSW_Interface_can_stAnfFas05_mu8 value;
} Rte_DE_IDT_SAC_BSW_Interface_can_stAnfFas05_mu8;

typedef struct {
   IDT_SAC_BSW_Interface_can_stArt1Fas01_mu8 value;
} Rte_DE_IDT_SAC_BSW_Interface_can_stArt1Fas01_mu8;

typedef struct {
   IDT_SAC_BSW_Interface_can_stArt1Fas02_mu8 value;
} Rte_DE_IDT_SAC_BSW_Interface_can_stArt1Fas02_mu8;

typedef struct {
   IDT_SAC_BSW_Interface_can_stArt1Fas03_mu8 value;
} Rte_DE_IDT_SAC_BSW_Interface_can_stArt1Fas03_mu8;

typedef struct {
   IDT_SAC_BSW_Interface_can_stArt1Fas04_mu8 value;
} Rte_DE_IDT_SAC_BSW_Interface_can_stArt1Fas04_mu8;

typedef struct {
   IDT_SAC_BSW_Interface_can_stArt1Fas05_mu8 value;
} Rte_DE_IDT_SAC_BSW_Interface_can_stArt1Fas05_mu8;

typedef struct {
   IDT_SAC_BSW_Interface_can_stArt1VMM_mu8 value;
} Rte_DE_IDT_SAC_BSW_Interface_can_stArt1VMM_mu8;

typedef struct {
   IDT_SAC_BSW_Interface_can_stArt2Fas01_mu8 value;
} Rte_DE_IDT_SAC_BSW_Interface_can_stArt2Fas01_mu8;

typedef struct {
   IDT_SAC_BSW_Interface_can_stArt2Fas02_mu8 value;
} Rte_DE_IDT_SAC_BSW_Interface_can_stArt2Fas02_mu8;

typedef struct {
   IDT_SAC_BSW_Interface_can_stArt2Fas03_mu8 value;
} Rte_DE_IDT_SAC_BSW_Interface_can_stArt2Fas03_mu8;

typedef struct {
   IDT_SAC_BSW_Interface_can_stArt2Fas04_mu8 value;
} Rte_DE_IDT_SAC_BSW_Interface_can_stArt2Fas04_mu8;

typedef struct {
   IDT_SAC_BSW_Interface_can_stArt2Fas05_mu8 value;
} Rte_DE_IDT_SAC_BSW_Interface_can_stArt2Fas05_mu8;

typedef struct {
   IDT_SAC_BSW_Interface_can_stArt2VMM_mu8 value;
} Rte_DE_IDT_SAC_BSW_Interface_can_stArt2VMM_mu8;

typedef struct {
   IDT_SAC_BSW_Interface_can_stEingLvVMM_mu8 value;
} Rte_DE_IDT_SAC_BSW_Interface_can_stEingLvVMM_mu8;

typedef struct {
   IDT_SAC_BSW_Interface_can_stEingVMM_mu8 value;
} Rte_DE_IDT_SAC_BSW_Interface_can_stEingVMM_mu8;

typedef struct {
   IDT_SAC_BSW_Interface_can_stLimCtlFReq_mu8 value;
} Rte_DE_IDT_SAC_BSW_Interface_can_stLimCtlFReq_mu8;

typedef struct {
   IDT_SAC_BSW_Interface_can_stSetupStgRackPosnFr_mu8 value;
} Rte_DE_IDT_SAC_BSW_Interface_can_stSetupStgRackPosnFr_mu8;

typedef struct {
   IDT_SAC_BSW_Interface_can_stSignale01_mu32 value;
} Rte_DE_IDT_SAC_BSW_Interface_can_stSignale01_mu32;

typedef struct {
   IDT_SAC_BSW_Interface_can_stSignale02_mu32 value;
} Rte_DE_IDT_SAC_BSW_Interface_can_stSignale02_mu32;

typedef struct {
   IDT_SAC_BSW_Interface_can_stStgVibPatReq_mu8 value;
} Rte_DE_IDT_SAC_BSW_Interface_can_stStgVibPatReq_mu8;

typedef struct {
   IDT_SAC_BSW_Interface_can_stTaHfHOD_mu8 value;
} Rte_DE_IDT_SAC_BSW_Interface_can_stTaHfHOD_mu8;

typedef struct {
   IDT_SAC_BSW_Interface_can_stTaHfKBI_mu8 value;
} Rte_DE_IDT_SAC_BSW_Interface_can_stTaHfKBI_mu8;

typedef struct {
   IDT_SAC_BSW_Interface_can_stTaHfODD_mu8 value;
} Rte_DE_IDT_SAC_BSW_Interface_can_stTaHfODD_mu8;

typedef struct {
   IDT_SAC_BSW_Interface_can_stTilIntpPosnCtlFr_mu8 value;
} Rte_DE_IDT_SAC_BSW_Interface_can_stTilIntpPosnCtlFr_mu8;

typedef struct {
   IDT_SAC_BSW_Interface_can_stVSignalQualifier_mu8 value;
} Rte_DE_IDT_SAC_BSW_Interface_can_stVSignalQualifier_mu8;

typedef struct {
   IDT_SAC_BSW_Interface_can_strDevMsgRx1_mu32 value;
} Rte_DE_IDT_SAC_BSW_Interface_can_strDevMsgRx1_mu32;

typedef struct {
   IDT_SAC_BSW_Interface_can_strDevMsgRx2_mu32 value;
} Rte_DE_IDT_SAC_BSW_Interface_can_strDevMsgRx2_mu32;

typedef struct {
   IDT_SAC_BSW_Interface_can_xZstSollVMM_mi16 value;
} Rte_DE_IDT_SAC_BSW_Interface_can_xZstSollVMM_mi16;

typedef struct {
   IDT_SAC_BSW_Interface_dia_mskAnpassung01_mu32 value;
} Rte_DE_IDT_SAC_BSW_Interface_dia_mskAnpassung01_mu32;

typedef struct {
   IDT_SAC_BSW_Interface_dia_mskCodierung01_mu32 value;
} Rte_DE_IDT_SAC_BSW_Interface_dia_mskCodierung01_mu32;

typedef struct {
   IDT_SAC_BSW_Interface_dia_stDiagnose_mu32 value;
} Rte_DE_IDT_SAC_BSW_Interface_dia_stDiagnose_mu32;

typedef struct {
   IDT_SAC_BSW_Interface_eaf_fSoll_mi16 value;
} Rte_DE_IDT_SAC_BSW_Interface_eaf_fSoll_mi16;

typedef struct {
   IDT_SAC_BSW_Interface_eps_nivAssistRampe_mu16 value;
} Rte_DE_IDT_SAC_BSW_Interface_eps_nivAssistRampe_mu16;

typedef struct {
   IDT_SAC_BSW_Interface_fga_mskStVFzg_mu8 value;
} Rte_DE_IDT_SAC_BSW_Interface_fga_mskStVFzg_mu8;

typedef struct {
   IDT_SAC_BSW_Interface_fga_vFzgRohW_mu16 value;
} Rte_DE_IDT_SAC_BSW_Interface_fga_vFzgRohW_mu16;

typedef struct {
   IDT_SAC_BSW_Interface_fga_vFzg_mu16 value;
} Rte_DE_IDT_SAC_BSW_Interface_fga_vFzg_mu16;

typedef struct {
   IDT_SAC_BSW_Interface_fga_vRadHl_mu16 value;
} Rte_DE_IDT_SAC_BSW_Interface_fga_vRadHl_mu16;

typedef struct {
   IDT_SAC_BSW_Interface_fga_vRadHr_mu16 value;
} Rte_DE_IDT_SAC_BSW_Interface_fga_vRadHr_mu16;

typedef struct {
   IDT_SAC_BSW_Interface_fga_vRadVl_mu16 value;
} Rte_DE_IDT_SAC_BSW_Interface_fga_vRadVl_mu16;

typedef struct {
   IDT_SAC_BSW_Interface_fga_vRadVr_mu16 value;
} Rte_DE_IDT_SAC_BSW_Interface_fga_vRadVr_mu16;

typedef struct {
   IDT_SAC_BSW_Interface_lku_fSoll_mi16 value;
} Rte_DE_IDT_SAC_BSW_Interface_lku_fSoll_mi16;

typedef struct {
   IDT_SAC_BSW_Interface_tac_stTAC_mu32 value;
} Rte_DE_IDT_SAC_BSW_Interface_tac_stTAC_mu32;

typedef struct {
   IDT_SAC_BSW_Interface_unt_diag_aktiv_mu8 value;
} Rte_DE_IDT_SAC_BSW_Interface_unt_diag_aktiv_mu8;

typedef struct {
   IDT_SAC_Interface_sac_can_strDevMsgTx1_mu32 value;
} Rte_DE_IDT_SAC_Interface_sac_can_strDevMsgTx1_mu32;

typedef struct {
   IDT_SAC_Interface_sac_can_strDevMsgTx2_mu32 value;
} Rte_DE_IDT_SAC_Interface_sac_can_strDevMsgTx2_mu32;

typedef struct {
   IDT_SAC_Interface_sac_qap_stFas01_mu8 value;
} Rte_DE_IDT_SAC_Interface_sac_qap_stFas01_mu8;

typedef struct {
   IDT_SAC_Interface_sac_qap_stFas02_mu8 value;
} Rte_DE_IDT_SAC_Interface_sac_qap_stFas02_mu8;

typedef struct {
   IDT_SAC_Interface_sac_qap_stFas03_mu8 value;
} Rte_DE_IDT_SAC_Interface_sac_qap_stFas03_mu8;

typedef struct {
   IDT_SAC_Interface_sac_qap_stFas04_mu8 value;
} Rte_DE_IDT_SAC_Interface_sac_qap_stFas04_mu8;

typedef struct {
   IDT_SAC_Interface_sac_qap_stFas05_mu8 value;
} Rte_DE_IDT_SAC_Interface_sac_qap_stFas05_mu8;

typedef struct {
   IDT_SAC_Interface_sac_qap_stPrioToTnDsaTsc_mu16 value;
} Rte_DE_IDT_SAC_Interface_sac_qap_stPrioToTnDsaTsc_mu16;

typedef struct {
   IDT_SAC_Interface_sac_qap_stQFK_mu8 value;
} Rte_DE_IDT_SAC_Interface_sac_qap_stQFK_mu8;

typedef struct {
   IDT_SAC_Interface_sac_qap_stSelQfk_mu8 value;
} Rte_DE_IDT_SAC_Interface_sac_qap_stSelQfk_mu8;

typedef struct {
   IDT_SAC_Interface_sac_qap_stVMM_mu8 value;
} Rte_DE_IDT_SAC_Interface_sac_qap_stVMM_mu8;

typedef struct {
   IDT_SAC_Interface_sac_qap_stVibr_mu8 value;
} Rte_DE_IDT_SAC_Interface_sac_qap_stVibr_mu8;

typedef struct {
   IDT_SAC_Interface_sac_qhm_fSollNUel_mi16 value;
} Rte_DE_IDT_SAC_Interface_sac_qhm_fSollNUel_mi16;

typedef struct {
   IDT_SAC_Interface_sac_qhm_fSoll_mi16 value;
} Rte_DE_IDT_SAC_Interface_sac_qhm_fSoll_mi16;

typedef struct {
   IDT_SAC_Interface_sac_qhm_mskStatus_mu8 value;
} Rte_DE_IDT_SAC_Interface_sac_qhm_mskStatus_mu8;

typedef struct {
   IDT_SAC_Interface_sac_qhm_nivIstKraft_mi16 value;
} Rte_DE_IDT_SAC_Interface_sac_qhm_nivIstKraft_mi16;

typedef struct {
   IDT_SAC_Interface_sac_qpr_fSollVib_mi16 value;
} Rte_DE_IDT_SAC_Interface_sac_qpr_fSollVib_mi16;

typedef struct {
   IDT_SAC_Interface_sac_qua_krIst_mi16 value;
} Rte_DE_IDT_SAC_Interface_sac_qua_krIst_mi16;

typedef struct {
   IDT_SAC_Interface_sac_qua_stGierSoll_mu8 value;
} Rte_DE_IDT_SAC_Interface_sac_qua_stGierSoll_mu8;

typedef struct {
   IDT_SAC_Interface_sac_qua_trqGierSoll_mi16 value;
} Rte_DE_IDT_SAC_Interface_sac_qua_trqGierSoll_mi16;

typedef struct {
   IDT_SAC_Interface_sac_qua_vFzgLvHigh_mu16 value;
} Rte_DE_IDT_SAC_Interface_sac_qua_vFzgLvHigh_mu16;

typedef struct {
   IDT_SAC_Interface_sac_stSAC_mu32 value;
} Rte_DE_IDT_SAC_Interface_sac_stSAC_mu32;

typedef struct {
   Nv_MechanicalLoadTracker_Struct_Impl value;
} Rte_DE_Nv_MechanicalLoadTracker_Struct_Impl;

typedef struct {
   Nv_MileageTracker_Struct_Impl value;
} Rte_DE_Nv_MileageTracker_Struct_Impl;

typedef struct {
   Nv_RackPosCalib_Struct_Impl value;
} Rte_DE_Nv_RackPosCalib_Struct_Impl;

typedef struct {
   Nv_RackPosCorr_Struct_Impl value;
} Rte_DE_Nv_RackPosCorr_Struct_Impl;

typedef struct {
   Nv_RackPosSync_Struct_Impl value;
} Rte_DE_Nv_RackPosSync_Struct_Impl;

typedef struct {
   Nv_SteeringRangeTracker_Struct_Impl value;
} Rte_DE_Nv_SteeringRangeTracker_Struct_Impl;

typedef struct {
   Nv_TemperatureTracker_Struct_Impl value;
} Rte_DE_Nv_TemperatureTracker_Struct_Impl;

typedef struct {
   Nv_WormWheelDamageTracker_Struct_Impl value;
} Rte_DE_Nv_WormWheelDamageTracker_Struct_Impl;

typedef struct {
   Rte_DE_Nv_RackPosCorr_Struct_Impl           sbuf0;
   Rte_DE_Nv_MechanicalLoadTracker_Struct_Impl sbuf2;
   Rte_DE_Nv_MileageTracker_Struct_Impl        sbuf4;
   Rte_DE_Nv_SteeringRangeTracker_Struct_Impl  sbuf6;
   Rte_DE_Nv_TemperatureTracker_Struct_Impl    sbuf8;
} Rte_TDB_Task100ms;

typedef struct {
   Rte_DE_Nv_RackPosSync_Struct_Impl  sbuf0;
   Rte_DE_Nv_RackPosCalib_Struct_Impl sbuf2;
} Rte_TDB_Task10ms;

typedef struct {
   Rte_DE_Nv_MechanicalLoadTracker_Struct_Impl  sbuf0;
   Rte_DE_Nv_WormWheelDamageTracker_Struct_Impl sbuf1;
} Rte_TDB_Task1ms;

typedef struct {
   Rte_DE_Nv_WormWheelDamageTracker_Struct_Impl sbuf0;
} Rte_TDB_Task1ms_PartThree;

typedef struct {
   Rte_DE_IDT_ASC_Interface_asc_StartStopp_Info_mu8        sbuf0;
   Rte_DE_IDT_ASC_Interface_asc_can_strDevMsgTx1_mu32      sbuf1;
   Rte_DE_IDT_ASC_Interface_asc_ger_stLernL_mu8            sbuf10;
   Rte_DE_IDT_ASC_Interface_asc_mst_startBed_mu8           sbuf11;
   Rte_DE_IDT_ASC_Interface_asc_stASC_mu32                 sbuf12;
   Rte_DE_IDT_ASC_Interface_asc_stDsaTsc2Qfk_mu16          sbuf13;
   Rte_DE_IDT_ASC_Interface_asc_trqOffset_mi16             sbuf14;
   Rte_DE_IDT_ASC_Interface_asc_tsc_fSoll_mi16             sbuf15;
   Rte_DE_IDT_ASC_Interface_asc_tsc_facLern_mu16           sbuf16;
   Rte_DE_IDT_ASC_Interface_asc_tsc_stLerrn_mu8            sbuf17;
   Rte_DE_IDT_ASC_BSW_Interface_bsw_mskStatusbits02_mu32   sbuf18;
   Rte_DE_IDT_ASC_BSW_Interface_bsw_stDiagnose_mu32        sbuf19;
   Rte_DE_IDT_ASC_Interface_asc_can_strDevMsgTx2_mu32      sbuf2;
   Rte_DE_IDT_ASC_BSW_Interface_bsw_tZahnstange_mi16       sbuf20;
   Rte_DE_IDT_ASC_BSW_Interface_bsw_tempEcu_mi16           sbuf21;
   Rte_DE_IDT_ASC_BSW_Interface_can_beschlLaengs_mi16      sbuf22;
   Rte_DE_IDT_ASC_BSW_Interface_can_beschlQuer_mi16        sbuf23;
   Rte_DE_IDT_ASC_BSW_Interface_can_gierrate_mi16          sbuf24;
   Rte_DE_IDT_ASC_BSW_Interface_can_gradUeb_mi8            sbuf25;
   Rte_DE_IDT_ASC_BSW_Interface_can_imp_HL_mu16            sbuf26;
   Rte_DE_IDT_ASC_BSW_Interface_can_imp_HR_mu16            sbuf27;
   Rte_DE_IDT_ASC_BSW_Interface_can_levelPedal_mu8         sbuf28;
   Rte_DE_IDT_ASC_BSW_Interface_can_pBrems_mi16            sbuf29;
   Rte_DE_IDT_ASC_Interface_asc_epsWarn_mu8                sbuf3;
   Rte_DE_IDT_ASC_BSW_Interface_can_rpmMotor_mu16          sbuf30;
   Rte_DE_IDT_ASC_BSW_Interface_can_stESP14_mu8            sbuf31;
   Rte_DE_IDT_ASC_BSW_Interface_can_stFahrbereitschaft_mu8 sbuf32;
   Rte_DE_IDT_ASC_BSW_Interface_can_stLaufleistung_mu32    sbuf33;
   Rte_DE_IDT_ASC_BSW_Interface_can_stMO14_mu8             sbuf34;
   Rte_DE_IDT_ASC_BSW_Interface_can_stSignale01_mu32       sbuf35;
   Rte_DE_IDT_ASC_BSW_Interface_can_stSignale02_mu32       sbuf36;
   Rte_DE_IDT_ASC_BSW_Interface_can_strDevMsgRx1_mu32      sbuf37;
   Rte_DE_IDT_ASC_BSW_Interface_can_strDevMsgRx2_mu32      sbuf38;
   Rte_DE_IDT_ASC_BSW_Interface_can_tragMo_mi16            sbuf39;
   Rte_DE_IDT_ASC_Interface_asc_fSoll_mi16                 sbuf4;
   Rte_DE_IDT_ASC_BSW_Interface_can_trqAllrad_mu8          sbuf40;
   Rte_DE_IDT_ASC_BSW_Interface_can_trqMoIst_mi16          sbuf41;
   Rte_DE_IDT_ASC_BSW_Interface_can_trqMoSchub_mi16        sbuf42;
   Rte_DE_IDT_ASC_BSW_Interface_can_trqMoSollRoh_mi16      sbuf43;
   Rte_DE_IDT_ASC_BSW_Interface_can_vRad_HL_mi16           sbuf44;
   Rte_DE_IDT_ASC_BSW_Interface_can_vRad_HR_mi16           sbuf45;
   Rte_DE_IDT_ASC_BSW_Interface_can_vRad_VL_mi16           sbuf46;
   Rte_DE_IDT_ASC_BSW_Interface_can_vRad_VR_mi16           sbuf47;
   Rte_DE_IDT_ASC_BSW_Interface_can_vSignal_mu16           sbuf48;
   Rte_DE_IDT_ASC_BSW_Interface_can_vaqIst_mu8             sbuf49;
   Rte_DE_IDT_ASC_Interface_asc_facReduzlku_mu16           sbuf5;
   Rte_DE_IDT_ASC_BSW_Interface_cha_facAuto_mu16           sbuf50;
   Rte_DE_IDT_ASC_BSW_Interface_cha_facDyn_mu16            sbuf51;
   Rte_DE_IDT_ASC_BSW_Interface_cha_facEvent_mu16          sbuf52;
   Rte_DE_IDT_ASC_BSW_Interface_cha_facKom_mu16            sbuf53;
   Rte_DE_IDT_ASC_BSW_Interface_dia_mskAnpassung01_mu32    sbuf54;
   Rte_DE_IDT_ASC_BSW_Interface_dia_mskCodierung01_mu32    sbuf55;
   Rte_DE_IDT_ASC_BSW_Interface_fga_mskStVFzg_mu8          sbuf56;
   Rte_DE_IDT_ASC_BSW_Interface_fga_vFzg_mi16              sbuf57;
   Rte_DE_IDT_ASC_BSW_Interface_hca_stHCA_mu8              sbuf58;
   Rte_DE_IDT_ASC_BSW_Interface_qap_stPrioToTnDsaTsc_mu8   sbuf59;
   Rte_DE_IDT_ASC_Interface_asc_facReduztrq_mu16           sbuf6;
   Rte_DE_IDT_ASC_BSW_Interface_bsw_iBat_mi16              sbuf60;
   Rte_DE_IDT_ASC_BSW_Interface_bsw_levelAssist_mu8        sbuf61;
   Rte_DE_IDT_ASC_BSW_Interface_bsw_lku_fSoll_mi16         sbuf62;
   Rte_DE_IDT_ASC_BSW_Interface_bsw_mskStatusbits01_mu32   sbuf63;
   Rte_DE_IDT_ASC_BSW_Interface_bsw_phiRitzelMotor_mi16    sbuf64;
   Rte_DE_IDT_ASC_BSW_Interface_bsw_phiRitzel_mi32         sbuf65;
   Rte_DE_IDT_ASC_BSW_Interface_bsw_phvRitzel_mi16         sbuf66;
   Rte_DE_IDT_ASC_BSW_Interface_bsw_stSAC_mu32             sbuf67;
   Rte_DE_IDT_ASC_BSW_Interface_bsw_stTac_mu32             sbuf68;
   Rte_DE_IDT_ASC_BSW_Interface_bsw_trqIst_mi16            sbuf69;
   Rte_DE_IDT_ASC_Interface_asc_ger_phiK_mi16              sbuf7;
   Rte_DE_IDT_ASC_BSW_Interface_bsw_trqSensorKomp_mi16     sbuf70;
   Rte_DE_IDT_ASC_BSW_Interface_bsw_trqSensor_mi16         sbuf71;
   Rte_DE_IDT_ASC_BSW_Interface_bsw_trqSoll_mi16           sbuf72;
   Rte_DE_IDT_ASC_BSW_Interface_bsw_uBat_mu16              sbuf73;
   Rte_DE_IDT_ASC_BSW_Interface_can_facTrqWheel_mu8        sbuf74;
   Rte_DE_IDT_ASC_BSW_Interface_can_stTrqWheel_mu8         sbuf75;
   Rte_DE_IDT_ASC_BSW_Interface_can_trqWheelActSec_mi16    sbuf76;
   Rte_DE_IDT_ASC_BSW_Interface_can_trqWheelAct_mi16       sbuf77;
   Rte_DE_IDT_ASC_Interface_asc_ger_phiL_mi16              sbuf8;
   Rte_DE_IDT_ASC_Interface_asc_ger_stLernK_mu8            sbuf9;
} Rte_TDB_TaskOem1_1ms;

typedef struct {
   Rte_DE_IDT_SAC_Interface_sac_can_strDevMsgTx1_mu32        sbuf0;
   Rte_DE_IDT_SAC_Interface_sac_can_strDevMsgTx2_mu32        sbuf1;
   Rte_DE_IDT_SAC_Interface_sac_qhm_fSollNUel_mi16           sbuf10;
   Rte_DE_IDT_SAC_BSW_Interface_can_stEingLvVMM_mu8          sbuf100;
   Rte_DE_IDT_SAC_BSW_Interface_can_stEingVMM_mu8            sbuf101;
   Rte_DE_IDT_SAC_BSW_Interface_can_stSignale01_mu32         sbuf102;
   Rte_DE_IDT_SAC_BSW_Interface_can_stSignale02_mu32         sbuf103;
   Rte_DE_IDT_SAC_BSW_Interface_can_stVSignalQualifier_mu8   sbuf104;
   Rte_DE_IDT_SAC_BSW_Interface_can_strDevMsgRx1_mu32        sbuf105;
   Rte_DE_IDT_SAC_BSW_Interface_can_strDevMsgRx2_mu32        sbuf106;
   Rte_DE_IDT_SAC_BSW_Interface_can_xZstSollVMM_mi16         sbuf107;
   Rte_DE_IDT_SAC_BSW_Interface_dia_mskAnpassung01_mu32      sbuf108;
   Rte_DE_IDT_SAC_BSW_Interface_dia_mskCodierung01_mu32      sbuf109;
   Rte_DE_IDT_SAC_Interface_sac_qhm_fSoll_mi16               sbuf11;
   Rte_DE_IDT_SAC_BSW_Interface_dia_stDiagnose_mu32          sbuf110;
   Rte_DE_IDT_SAC_BSW_Interface_eaf_fSoll_mi16               sbuf111;
   Rte_DE_IDT_SAC_BSW_Interface_eps_nivAssistRampe_mu16      sbuf112;
   Rte_DE_IDT_SAC_BSW_Interface_fga_mskStVFzg_mu8            sbuf113;
   Rte_DE_IDT_SAC_BSW_Interface_fga_vFzgRohW_mu16            sbuf114;
   Rte_DE_IDT_SAC_BSW_Interface_fga_vFzg_mu16                sbuf115;
   Rte_DE_IDT_SAC_BSW_Interface_fga_vRadHl_mu16              sbuf116;
   Rte_DE_IDT_SAC_BSW_Interface_fga_vRadHr_mu16              sbuf117;
   Rte_DE_IDT_SAC_BSW_Interface_fga_vRadVl_mu16              sbuf118;
   Rte_DE_IDT_SAC_BSW_Interface_fga_vRadVr_mu16              sbuf119;
   Rte_DE_IDT_SAC_Interface_sac_qhm_mskStatus_mu8            sbuf12;
   Rte_DE_IDT_SAC_BSW_Interface_lku_fSoll_mi16               sbuf120;
   Rte_DE_IDT_SAC_BSW_Interface_tac_stTAC_mu32               sbuf121;
   Rte_DE_IDT_SAC_BSW_Interface_unt_diag_aktiv_mu8           sbuf122;
   Rte_DE_IDT_SAC_BSW_Interface_bsw_stVzstLimSafetyFader_mu8 sbuf123;
   Rte_DE_IDT_SAC_BSW_Interface_bsw_stVzstLimSafety_mu8      sbuf124;
   Rte_DE_IDT_SAC_BSW_Interface_bsw_vZstLimMax_mi16          sbuf125;
   Rte_DE_IDT_SAC_BSW_Interface_bsw_vZstLimMin_mi16          sbuf126;
   Rte_DE_IDT_SAC_BSW_Interface_can_stLimCtlFReq_mu8         sbuf127;
   Rte_DE_IDT_SAC_BSW_Interface_can_stSetupStgRackPosnFr_mu8 sbuf128;
   Rte_DE_IDT_SAC_BSW_Interface_can_stStgVibPatReq_mu8       sbuf129;
   Rte_DE_IDT_SAC_Interface_sac_qhm_nivIstKraft_mi16         sbuf13;
   Rte_DE_IDT_SAC_BSW_Interface_can_stTilIntpPosnCtlFr_mu8   sbuf130;
   Rte_DE_IDT_SAC_BSW_Interface_can_stTaHfHOD_mu8            sbuf131;
   Rte_DE_IDT_SAC_BSW_Interface_can_stTaHfKBI_mu8            sbuf132;
   Rte_DE_IDT_SAC_BSW_Interface_can_stTaHfODD_mu8            sbuf133;
   Rte_DE_IDT_SAC_Interface_sac_qpr_fSollVib_mi16            sbuf14;
   Rte_DE_IDT_SAC_Interface_sac_qua_krIst_mi16               sbuf15;
   Rte_DE_IDT_SAC_Interface_sac_qua_stGierSoll_mu8           sbuf16;
   Rte_DE_IDT_SAC_Interface_sac_qua_trqGierSoll_mi16         sbuf17;
   Rte_DE_IDT_SAC_Interface_sac_qua_vFzgLvHigh_mu16          sbuf18;
   Rte_DE_IDT_SAC_Interface_sac_stSAC_mu32                   sbuf19;
   Rte_DE_IDT_SAC_Interface_sac_qap_stFas01_mu8              sbuf2;
   Rte_DE_IDT_SAC_Interface_sac_qap_stSelQfk_mu8             sbuf20;
   Rte_DE_IDT_SAC_Interface_sac_qap_stVibr_mu8               sbuf21;
   Rte_DE_IDT_SAC_BSW_Interface_asc_fSoll_mi16               sbuf22;
   Rte_DE_IDT_SAC_BSW_Interface_asc_ger_phiL_mi16            sbuf23;
   Rte_DE_IDT_SAC_BSW_Interface_asc_stASC_mu32               sbuf24;
   Rte_DE_IDT_SAC_BSW_Interface_asc_stDsaTsc2Qfk_mu16        sbuf25;
   Rte_DE_IDT_SAC_BSW_Interface_bsw_fSollLimMtl_mi16         sbuf26;
   Rte_DE_IDT_SAC_BSW_Interface_bsw_levelAssist_mu8          sbuf27;
   Rte_DE_IDT_SAC_BSW_Interface_bsw_mskStatusbits01_mu32     sbuf28;
   Rte_DE_IDT_SAC_BSW_Interface_bsw_mskStatusbits02_mu32     sbuf29;
   Rte_DE_IDT_SAC_Interface_sac_qap_stFas02_mu8              sbuf3;
   Rte_DE_IDT_SAC_BSW_Interface_bsw_phvRitzel_mi16           sbuf30;
   Rte_DE_IDT_SAC_BSW_Interface_bsw_stFehlerULstg_mu8        sbuf31;
   Rte_DE_IDT_BSW_Interface_bsw_stFrgBusFehler_mu8           sbuf32;
   Rte_DE_IDT_SAC_BSW_Interface_bsw_stKl15_mu8               sbuf33;
   Rte_DE_IDT_SAC_BSW_Interface_bsw_trqSensorLku_mi16        sbuf34;
   Rte_DE_IDT_SAC_BSW_Interface_bsw_trqSensor_mi16           sbuf35;
   Rte_DE_IDT_SAC_BSW_Interface_bsw_uBatt_mu16               sbuf36;
   Rte_DE_IDT_SAC_BSW_Interface_bsw_vZst_mi16                sbuf37;
   Rte_DE_IDT_SAC_BSW_Interface_bsw_xZstEASoll_mi16          sbuf38;
   Rte_DE_IDT_SAC_BSW_Interface_bsw_xZstGerKorr_mi32         sbuf39;
   Rte_DE_IDT_SAC_Interface_sac_qap_stFas03_mu8              sbuf4;
   Rte_DE_IDT_SAC_BSW_Interface_bsw_xZst_mi32                sbuf40;
   Rte_DE_IDT_SAC_BSW_Interface_can_beschlQuer_mi16          sbuf41;
   Rte_DE_IDT_SAC_BSW_Interface_can_cntFas01_mu8             sbuf42;
   Rte_DE_IDT_SAC_BSW_Interface_can_cntFas02_mu8             sbuf43;
   Rte_DE_IDT_SAC_BSW_Interface_can_cntFas03_mu8             sbuf44;
   Rte_DE_IDT_SAC_BSW_Interface_can_cntFas04_mu8             sbuf45;
   Rte_DE_IDT_SAC_BSW_Interface_can_cntFas05_mu8             sbuf46;
   Rte_DE_IDT_SAC_BSW_Interface_can_cntVMM_mu8               sbuf47;
   Rte_DE_IDT_SAC_BSW_Interface_can_facSignal1Fas01_mu16     sbuf48;
   Rte_DE_IDT_SAC_BSW_Interface_can_facSignal1Fas02_mu16     sbuf49;
   Rte_DE_IDT_SAC_Interface_sac_qap_stFas04_mu8              sbuf5;
   Rte_DE_IDT_SAC_BSW_Interface_can_facSignal1Fas03_mu16     sbuf50;
   Rte_DE_IDT_SAC_BSW_Interface_can_facSignal1Fas04_mu16     sbuf51;
   Rte_DE_IDT_SAC_BSW_Interface_can_facSignal1Fas05_mu16     sbuf52;
   Rte_DE_IDT_SAC_BSW_Interface_can_facSignal1VMM_mu16       sbuf53;
   Rte_DE_IDT_SAC_BSW_Interface_can_facSignal2Fas01_mu16     sbuf54;
   Rte_DE_IDT_SAC_BSW_Interface_can_facSignal2Fas02_mu16     sbuf55;
   Rte_DE_IDT_SAC_BSW_Interface_can_facSignal2Fas03_mu16     sbuf56;
   Rte_DE_IDT_SAC_BSW_Interface_can_facSignal2Fas04_mu16     sbuf57;
   Rte_DE_IDT_SAC_BSW_Interface_can_facSignal2Fas05_mu16     sbuf58;
   Rte_DE_IDT_SAC_BSW_Interface_can_facSignal2VMM_mu16       sbuf59;
   Rte_DE_IDT_SAC_Interface_sac_qap_stFas05_mu8              sbuf6;
   Rte_DE_IDT_SAC_BSW_Interface_can_facSpuerbFas01_mu16      sbuf60;
   Rte_DE_IDT_SAC_BSW_Interface_can_facSpuerbFas02_mu16      sbuf61;
   Rte_DE_IDT_SAC_BSW_Interface_can_facSpuerbFas03_mu16      sbuf62;
   Rte_DE_IDT_SAC_BSW_Interface_can_facSpuerbFas04_mu16      sbuf63;
   Rte_DE_IDT_SAC_BSW_Interface_can_facSpuerbFas05_mu16      sbuf64;
   Rte_DE_IDT_SAC_BSW_Interface_can_facSpuerbVMM_mu16        sbuf65;
   Rte_DE_IDT_SAC_BSW_Interface_can_gierrate_mi16            sbuf66;
   Rte_DE_IDT_SAC_BSW_Interface_can_krSollFas01_mi16         sbuf67;
   Rte_DE_IDT_SAC_BSW_Interface_can_krSollFas02_mi16         sbuf68;
   Rte_DE_IDT_SAC_BSW_Interface_can_krSollFas03_mi16         sbuf69;
   Rte_DE_IDT_SAC_Interface_sac_qap_stPrioToTnDsaTsc_mu16    sbuf7;
   Rte_DE_IDT_SAC_BSW_Interface_can_krSollFas04_mi16         sbuf70;
   Rte_DE_IDT_SAC_BSW_Interface_can_krSollFas05_mi16         sbuf71;
   Rte_DE_IDT_SAC_BSW_Interface_can_phiEscKinX1_mu16         sbuf72;
   Rte_DE_IDT_SAC_BSW_Interface_can_phiEscKinX2_mu16         sbuf73;
   Rte_DE_IDT_SAC_BSW_Interface_can_phiEscKinX3_mu16         sbuf74;
   Rte_DE_IDT_SAC_BSW_Interface_can_phiEscKinX4_mu16         sbuf75;
   Rte_DE_IDT_SAC_BSW_Interface_can_phiEscKinX5_mu16         sbuf76;
   Rte_DE_IDT_SAC_BSW_Interface_can_phiEscKinY1_mu16         sbuf77;
   Rte_DE_IDT_SAC_BSW_Interface_can_phiEscKinY2_mu16         sbuf78;
   Rte_DE_IDT_SAC_BSW_Interface_can_phiEscKinY3_mu16         sbuf79;
   Rte_DE_IDT_SAC_Interface_sac_qap_stQFK_mu8                sbuf8;
   Rte_DE_IDT_SAC_BSW_Interface_can_phiEscKinY4_mu16         sbuf80;
   Rte_DE_IDT_SAC_BSW_Interface_can_phiEscKinY5_mu16         sbuf81;
   Rte_DE_IDT_SAC_BSW_Interface_can_sESCRadstand_mu16        sbuf82;
   Rte_DE_IDT_SAC_BSW_Interface_can_stAnfFas01_mu8           sbuf83;
   Rte_DE_IDT_SAC_BSW_Interface_can_stAnfFas02_mu8           sbuf84;
   Rte_DE_IDT_SAC_BSW_Interface_can_stAnfFas03_mu8           sbuf85;
   Rte_DE_IDT_SAC_BSW_Interface_can_stAnfFas04_mu8           sbuf86;
   Rte_DE_IDT_SAC_BSW_Interface_can_stAnfFas05_mu8           sbuf87;
   Rte_DE_IDT_SAC_BSW_Interface_can_stArt1Fas01_mu8          sbuf88;
   Rte_DE_IDT_SAC_BSW_Interface_can_stArt1Fas02_mu8          sbuf89;
   Rte_DE_IDT_SAC_Interface_sac_qap_stVMM_mu8                sbuf9;
   Rte_DE_IDT_SAC_BSW_Interface_can_stArt1Fas03_mu8          sbuf90;
   Rte_DE_IDT_SAC_BSW_Interface_can_stArt1Fas04_mu8          sbuf91;
   Rte_DE_IDT_SAC_BSW_Interface_can_stArt1Fas05_mu8          sbuf92;
   Rte_DE_IDT_SAC_BSW_Interface_can_stArt1VMM_mu8            sbuf93;
   Rte_DE_IDT_SAC_BSW_Interface_can_stArt2Fas01_mu8          sbuf94;
   Rte_DE_IDT_SAC_BSW_Interface_can_stArt2Fas02_mu8          sbuf95;
   Rte_DE_IDT_SAC_BSW_Interface_can_stArt2Fas03_mu8          sbuf96;
   Rte_DE_IDT_SAC_BSW_Interface_can_stArt2Fas04_mu8          sbuf97;
   Rte_DE_IDT_SAC_BSW_Interface_can_stArt2Fas05_mu8          sbuf98;
   Rte_DE_IDT_SAC_BSW_Interface_can_stArt2VMM_mu8            sbuf99;
} Rte_TDB_TaskOem2_1ms;


#endif /* !RTE_DATA_HANDLE_TYPE_H */
