/** @file     Rte_SAC_SWC_Type.h
  *
  * @brief    Application types header file
  *
  * @note     AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
  *
  * @note     Generated by ETAS RTA-RTE
  * @note     Version 7.3.0 
  */

#ifndef RTE_SAC_SWC_TYPE_H
#define RTE_SAC_SWC_TYPE_H

#include "Rte_Type.h"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

/* BEGIN: SWC specific types */
#ifndef RTE_CORE
#ifndef RTE_MODETYPE_MODES
#define RTE_MODETYPE_MODES

typedef uint8 Rte_ModeType_Modes;

#endif /* !RTE_MODETYPE_MODES */
#endif /* RTE_CORE */

/* END: SWC specific types */

/* BEGIN: SWC specific definitions */
#ifndef RTE_CORE
#ifndef RTE_MODE_Modes_Init
#define RTE_MODE_Modes_Init                      0U
#endif /* !RTE_MODE_Modes_Init */
#ifndef RTE_MODE_Modes_Running
#define RTE_MODE_Modes_Running                   1U
#endif /* !RTE_MODE_Modes_Running */
#ifndef RTE_MODE_Modes_Terminate
#define RTE_MODE_Modes_Terminate                 2U
#endif /* !RTE_MODE_Modes_Terminate */
#ifndef RTE_TRANSITION_Modes
#define RTE_TRANSITION_Modes                     3U
#endif /* !RTE_TRANSITION_Modes */
#endif /* RTE_CORE */

#if !defined(RTE_CORE)

/* Box: /TargetLink/TLDataTypes/Bool begin */
/* Box: "FALSE" begin */
#ifndef FALSE
#define FALSE (0U)
#endif /* !FALSE */
/* Box: "FALSE" end */
/* Box: "TRUE" begin */
#ifndef TRUE
#define TRUE (1U)
#endif /* !TRUE */
/* Box: "TRUE" end */
/* Box: /TargetLink/TLDataTypes/Bool end */
#endif /* !defined(RTE_CORE) */
/* END: SWC specific definitions */

#ifdef __cplusplus
} /* extern C */
#endif /* __cplusplus */

#endif /* !RTE_SAC_SWC_TYPE_H */
