<?xml version="1.0" encoding="UTF-8"?>
<xs:schema targetNamespace="www.rbin.com/mds-1" xmlns="www.rbin.com/mds-1" xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xs:element name="CONF">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="HEXMOD"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="HEXMOD">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="ERRMOD" minOccurs="0"/>
                <xs:element ref="CLEANUP"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="IBLK">
        <xs:complexType>
            <xs:attribute name="START" type="exhexBinary" use="required"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="CLEANUP">
        <xs:complexType>        
            <xs:sequence>
                <xs:choice>
                    <xs:element ref="IBLK" maxOccurs="unbounded"/>
					<xs:element ref="CHECK"/>
                </xs:choice>
            </xs:sequence>
            <xs:attribute name="NAME" type="xs:string" />
            <xs:attribute name="TYPE" type="filetype" />
            <xs:attribute name="DIVISION" type="xs:string"/>
            <xs:attribute name="MDGTYPE" type="xs:string"/>
        </xs:complexType>
    </xs:element>
	<xs:element name="CHECK">
		<xs:annotation>
			<xs:documentation>CHECK is used to check the hex file if it is cleaned or not.</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
     		    <xs:element ref="IBLK" minOccurs="1" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
    <xs:element name="REFFILEIN">
        <xs:annotation>
            <xs:documentation>REFFILEIN Tag is used to read the reference files specified in the attribute NAME. OVERWRITE attribute is specified with true or false depending on whether they have to be overwritten or not. IGNORELINECKS attribute has to be set to true or false depending on whether ignoring is required or not. The TYPE attribute can be either IHEX or S19 files. This file must contain the Tprot, CTprot section</xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:attribute name="TYPE" type="filetype" use="required"/>
            <xs:attribute name="IGNORELINECKS" type="xs:boolean" default="false"/>
            <xs:attribute name="NAME" type="xs:string" use="required"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="FILEIN">
        <xs:annotation>
            <xs:documentation>FILEIN Tag is used to read the files specified in the attribute NAME. FROM and LEN have to be filled when range of data has to read. OVERWRITE attribute is specified with true or false depending on whether they have to be overwritten or not. IGNORELINECKS attribute has to be set to true or false depending on whether ignoring is required or not. The TYPE attribute can be either IHEX or S19 files.</xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:attribute name="TYPE" type="filetype" use="required"/>
            <xs:attribute name="IGNORELINECKS" type="xs:boolean" default="false"/>
            <xs:attribute name="NAME" type="xs:string" use="required"/>
        </xs:complexType>
    </xs:element>
    <xs:simpleType name="filetype">
        <xs:restriction base="xs:string">
            <xs:enumeration value="S19"/>
            <xs:enumeration value="IHEX"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="exhexBinary">
        <xs:restriction base="xs:string">
            <xs:maxLength value="10"/>
            <xs:minLength value="3"/>
            <xs:pattern value="[0]x[a-fA-F0-9]*"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:element name="ERRMOD">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="LOG"/>
                <xs:element ref="MSGLOG" minOccurs="0"/>
                <xs:element ref="MSGCONSOLE" minOccurs="0"/>
                <xs:element ref="PROGABORT" minOccurs="0"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="LOG">
        <xs:complexType>
            <xs:attribute name="FILE" type="xs:string" use="required"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="MSGCONSOLE">
        <xs:complexType>
            <xs:attribute name="LVL" type="exLvl" use="required"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="MSGLOG">
        <xs:complexType>
            <xs:attribute name="LVL" type="exLvl" use="required"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="PROGABORT">
        <xs:complexType>
            <xs:attribute name="LVL" type="exLvl2" use="required"/>
        </xs:complexType>
    </xs:element>
    <xs:simpleType name="exLvl">
        <xs:restriction base="xs:unsignedByte">
            <xs:minInclusive value="1"/>
            <xs:maxInclusive value="4"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="exLvl2">
        <xs:restriction base="xs:unsignedByte">
            <xs:minInclusive value="2"/>
            <xs:maxInclusive value="3"/>
        </xs:restriction>
    </xs:simpleType>
    
</xs:schema>
