<?xml version="1.0" encoding="utf-8"?>
<xs:schema targetNamespace="www.rbin.com/mds-1"
           xmlns="www.rbin.com/mds-1"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified">

    <xs:element name="HEXMOD">
        <xs:complexType>
            <xs:sequence>
                <xs:element
                    name="HASH"
                    minOccurs="0"
                    maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element
                                ref="INPUT"
                                minOccurs="1"
                                maxOccurs="unbounded"></xs:element>            
                        </xs:sequence>            
                        <xs:attribute
                            name="TYPE"
                            type="xs:string"
                            use="optional">
                        </xs:attribute>
                        <!-- Introduced for GSTC -->
                        <xs:attribute
                            name="DIVISION"
                            type="xs:string"
                            use="optional" />   
                        <!-- To identify Trust Center type -->
                        <xs:attribute name="TC_TYPE" type="trustCenterType" use="optional">                            
                        </xs:attribute>  
                        <xs:attribute name="HSM_FILE" type="xs:string" use="optional">                            
                        </xs:attribute> 
                    </xs:complexType>
                </xs:element>
                <xs:element ref="MDG1TPROT" minOccurs="0"></xs:element>
            </xs:sequence>
        </xs:complexType></xs:element>

 <xs:element name="RANGES">
        <xs:complexType>
            <xs:sequence>
                        <xs:element ref="RANGE" minOccurs="1" maxOccurs="unbounded"/> 
            </xs:sequence>
             <xs:attribute
                name="OUTPUT"
                type="xs:string" 
                use="optional">
             </xs:attribute>
        </xs:complexType></xs:element>
        
         <xs:element name="RANGE">
            <xs:complexType>
                <xs:attribute
                name="FROM"
                type="xs:string" use="required">
                 </xs:attribute>
                 <xs:attribute
                name="TO"
                type="xs:string" use="required">
                 </xs:attribute>
            </xs:complexType>
        </xs:element>
        
        
    <xs:element name="TPROT"> 
        <xs:complexType>
            <xs:sequence>
            </xs:sequence>
        </xs:complexType></xs:element>
        
      <xs:element name="INFOBLOCK">
        <xs:complexType>
            <xs:attribute
                name="INFOBLOCKADDR"
                type="xs:string" use="required">
            </xs:attribute>
        </xs:complexType></xs:element>


    <xs:element name="MDG1TPROT">
        <xs:complexType>
            <xs:sequence>
                <xs:element
                    ref="SIGNATURE"
                    maxOccurs="unbounded"
                    minOccurs="1">
                </xs:element>

                <xs:element ref="CERTIFICATE" maxOccurs="unbounded" minOccurs="0"></xs:element>
            </xs:sequence>
            <xs:attribute name="AUTOSIGNFILE" type="xs:string" use="optional"/>

        </xs:complexType></xs:element>
        
        

    <xs:element name="SIGNATURE">
        <xs:complexType>
            <xs:choice maxOccurs="unbounded">
                <xs:element
                    ref="INPUT_HEX"
                    minOccurs="0"
                    maxOccurs="unbounded">
                </xs:element>
                <xs:element
                    ref="INPUT_HASH"
                    minOccurs="0"
                    maxOccurs="unbounded">
                </xs:element>
                <xs:element
                    ref="GENERATE_CERTIFICATE_KEYS"
                    minOccurs="0"
                    maxOccurs="unbounded">
                </xs:element>
                <xs:element ref="INPUT_SIGN" 
                    minOccurs="0" 
                    maxOccurs="unbounded">
                </xs:element>
            </xs:choice>
            <xs:attribute
                name="MODE"
                type="xs:string"
                use="optional"
                default="ONLINE">
            </xs:attribute>
            <xs:attribute
                name="DUMMY"
                type="xs:string"
                use="optional"
                default="false">
            </xs:attribute>
            <xs:attribute
                name="TYPE"
                type="xs:string" use="optional">
            </xs:attribute>
            <xs:attribute
                name="LASTRUN"
                type="xs:string" use="optional">
            </xs:attribute>
            <xs:attribute
                name="PINPATH"
                type="xs:string" use="optional">
            </xs:attribute>
            <!-- Introduced for GSTC -->
            <xs:attribute
                name="DIVISION"
                type="xs:string"
                use="optional" />
             <!-- To identify Trust Center type -->
            <xs:attribute name="TC_TYPE" type="trustCenterType" use="optional">                            
            </xs:attribute>              
            <xs:attribute name="SIGNATURE_ALGO" type="xs:string" use="optional">                            
            </xs:attribute>
            <xs:attribute name="HSM_FILE" type="xs:string" use="optional">                            
            </xs:attribute>   
            <xs:attribute name="HSM_CONFIG" type="xs:boolean" default="false">
            </xs:attribute>              
        </xs:complexType></xs:element>        
        

    <xs:element name="INPUT_HEX">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="OUTPUT"></xs:element>
            </xs:sequence>

            <xs:attribute
                name="SREC_INFOBLK_XML"
                type="xs:string"
                use="optional">
            </xs:attribute>

            <xs:attribute
                name="INFOBLKADDR"
                type="eAddr"
                use="optional">
            </xs:attribute>

            <xs:attribute
                name="IGNORELINECKS"
                type="xs:boolean"
                default="false">
            </xs:attribute>
            <xs:attribute
                name="MODE"
                type="xs:string"
                use="optional">
            </xs:attribute>
            <xs:attribute
                name="TYPE"
                type="xs:string"
                use="optional">
            </xs:attribute>
            <xs:attribute
                name="INPUTFILE"
                type="xs:string">
            </xs:attribute>
            <xs:attribute
                name="KEYPATH"
                type="xs:string"
                use="optional">
            </xs:attribute>
            <xs:attribute
                name="OID"
                type="xs:string"
                use="optional">
            </xs:attribute>
            <xs:attribute
                name="OID_PUB"
                type="xs:string"
                use="optional">
            </xs:attribute>
             <xs:attribute
                name="AUTHBITS"
                type="xs:string"
                use="optional">
            </xs:attribute>
        </xs:complexType></xs:element>

    <xs:element name="INPUT">
           <xs:complexType>
                     <xs:sequence>
                         <xs:element ref="INFOBLOCK" minOccurs="0" maxOccurs="unbounded"></xs:element>
                         <xs:element ref="RANGES" minOccurs="0" maxOccurs="unbounded"></xs:element> 
                      </xs:sequence>
            <xs:attribute
                name="INPUT"
                type="xs:string"
                use="required">
            </xs:attribute>
            <xs:attribute
                name="OUTPUT"
                type="xs:string"
                use="required">
            </xs:attribute>
            <xs:attribute
                name="INFOBLKADDR"
                type="eAddr"
                use="optional">
            </xs:attribute>

            <xs:attribute
                name="LYT"
                default="0x20"
                type="exFillBinary">
            </xs:attribute>
            
            <xs:attribute
                name="IGNORELINECKS"
                type="xs:boolean"
                default="false">
            </xs:attribute>
            
            <xs:attribute
                name="MODE"
                type="xs:string"
                use="optional">
            </xs:attribute>
            
             <xs:attribute
                name="TYPE"
                type="xs:string"
                use="optional">
            </xs:attribute>
            
             <xs:attribute
                name="CERTINFO_OUTPUT"
                type="xs:string"
                use="optional">
            </xs:attribute>
            
            <xs:attribute
                name="ID"
                type="xs:string"
                use="optional">
            </xs:attribute>
            
            <xs:attribute
                name="OID_PUB"
                type="xs:string"
                use="optional">
            </xs:attribute>
        </xs:complexType></xs:element>
        
        <xs:element name="GENERATE_CERTIFICATE_KEYS">
           <xs:complexType>
                     <xs:sequence>
                         <xs:element ref="OUTPUT" minOccurs="0" maxOccurs="unbounded"></xs:element>
                      </xs:sequence>
             <!-- This attribute is made optional as GENERATE_CERTIFICATE_KEYS element is used for HSM configuration area as well -->
            <xs:attribute
                name="INFOBLKADDR"
                type="eAddr"
                use="optional">
            </xs:attribute>
            <xs:attribute
                name="INPUTFILE"
                type="xs:string"
                use="required">
            </xs:attribute>
            <xs:attribute
                name="MODE"
                type="xs:string"
                use="required">
            </xs:attribute>            
            
            <xs:attribute
                name="IGNORELINECKS"
                type="xs:boolean"
                default="false">
            </xs:attribute>
            
             <xs:attribute
                name="TYPE"
                type="xs:string"
                use="optional">
            </xs:attribute>
            
             <xs:attribute
                name="JDPCERTADD"
                type="xs:string"
                use="optional">
            </xs:attribute>
            
            <xs:attribute
                name="INFCERTADD"
                type="xs:string"
                use="optional">
            </xs:attribute>
        </xs:complexType></xs:element>

    <xs:simpleType name="eAddr">
        <xs:restriction base="xs:string">
            <xs:minLength value="0"></xs:minLength>
            <xs:maxLength value="10"></xs:maxLength>
            <xs:pattern value="[0]x[a-fA-F0-9]*"></xs:pattern>
            <xs:pattern value=""></xs:pattern>
        </xs:restriction>
    </xs:simpleType>

    <xs:element name="CONF">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="HEXMOD"></xs:element>
            </xs:sequence>
        </xs:complexType></xs:element>

    <xs:simpleType name="exFillBinary">
        <xs:restriction base="xs:string">
            <xs:minLength value="4"></xs:minLength>
            <xs:maxLength value="4"></xs:maxLength>
            <xs:pattern value="[0]x[a-fA-F0-9]*"></xs:pattern>
        </xs:restriction>
    </xs:simpleType>

    <xs:element name="CERTIFICATE">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="INPUT" maxOccurs="unbounded"></xs:element>
            </xs:sequence>

        </xs:complexType></xs:element>

    <xs:complexType name="NewType"></xs:complexType>



    <xs:element name="OUTPUT">
         <xs:complexType>
             <xs:sequence></xs:sequence>
             <xs:attribute
                 name="FILENAME"
                 type="xs:string"
                 use="optional">
             </xs:attribute>
             <xs:attribute
                 name="TYPE"
                 type="xs:string"
                 use="optional">
             </xs:attribute>
              <xs:attribute
                name="INFOBLKADDR"
                type="eAddr"
                use="optional">
            </xs:attribute>
             <xs:attribute
                 name="LYT"
                 type="exFillBinary"
                 use="optional">
             </xs:attribute>
         </xs:complexType></xs:element>


    <xs:element name="INPUT_HASH">
        <xs:complexType>
            <xs:sequence>

            </xs:sequence>
            <xs:attribute
                name="INPUT"
                type="xs:string"
                use="required">
               
            </xs:attribute>
            <xs:attribute
                name="OUTPUT"
                type="xs:string">
            </xs:attribute>
            <xs:attribute
                name="KEYPATH"
                type="xs:string"
                use="optional">
            </xs:attribute>
            <xs:attribute
                name="OID"
                type="xs:string"
                use="optional">
            </xs:attribute>
            <xs:attribute
                name="OID_PUB"
                type="xs:string"
                use="optional">
            </xs:attribute>
            <xs:attribute
                name="AUTHBITS"
                type="xs:string"
                use="optional">
            </xs:attribute>
        </xs:complexType></xs:element>

    <xs:element name="INPUT_SIGN">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="OUTPUT"></xs:element>
            </xs:sequence>
            <xs:attribute
                name="INPUTFILE"
                type="xs:string">
            </xs:attribute>
                        <xs:attribute
                name="INFOBLKADDR"
                type="eAddr"
                use="optional">
            </xs:attribute>
            <xs:attribute
                name="INPUT_TXT"
                type="xs:string">
            </xs:attribute>
            <xs:attribute
                name="IGNORELINECKS"
                type="xs:boolean">
            </xs:attribute>
            <xs:attribute
                name="TYPE"
                type="xs:string">
            </xs:attribute>
            <xs:attribute
                name="MODE"
                type="xs:string">
            </xs:attribute>
            <xs:attribute
                name="ID"
                type="xs:string">
            </xs:attribute>

        </xs:complexType></xs:element>
        
        <xs:simpleType name="trustCenterType">
            <xs:restriction base="xs:string">
                <xs:enumeration value="BOSCH_TRUST_CENTER"></xs:enumeration>
                <xs:enumeration value="bosch_trust_center"></xs:enumeration>
                <xs:enumeration value="VW_TRUST_CENTER"></xs:enumeration>
                <xs:enumeration value="vw_trust_center"></xs:enumeration>                
            </xs:restriction>
        </xs:simpleType>
        
</xs:schema>