/*-----------------------------------------------------------------------*/
/* File Identifier on server    $Id: asc_swc_lut.h 254 2024-09-27 09:19:52Z VWQCRBZ $ */
/* File location on server $HeadURL: https://subversion.wob.vw.vwg/SWIfaceMxB26/Branches/MQB41BW_V0091_Bosch_100Fit_Auslieferung_LSMQBWASIL-190/20_ENG/Units/ASC/Product/INC/asc_swc_lut.h $ */
/*-----------------------------------------------------------------------*/

/* Spezifikation "AutosarEPSInterface Baseline 2.1" */

		
/**************************************************************************************************\
 *** 
 *** Simulink model       : ASC
 *** TargetLink subsystem : ASC/TL_Ignore_ASC
 *** Codefile             : asc_swc_lut.h
 ***
 *** Generated by TargetLink, the dSPACE production quality code generator
 *** Generation date: 2024-09-27 11:13:41
 ***
 *** CODE GENERATOR OPTIONS:
 *** Code generation mode                     : Classic AUTOSAR
 *** AUTOSAR version                          : 4.4.0
 *** Compiler                                 : <unknown>
 *** Target                                   : Generic
 *** ANSI-C compatible code                   : yes
 *** Code Optimization                        : enabled
 *** Constant style                           : decimal
 *** Clean code option                        : enabled
 *** Logging mode                             : Do not log anything
 *** Code Coverage                            : disabled
 *** Generate empty conditional branches      : enabled
 *** Loop unroll threshold                    : 5
 *** Utilize bitwise shift operations         : Never
 *** Handle unscaled SF expr. with TL type    : enabled
 *** Assignment of conditions                 : AllBooleanOutputs 
 *** Scope reduction only to function level   : disabled
 *** Exploit ranges if not erasable           : disabled
 *** Exploit Compute Through Overflow         : optimized
 *** Linker sections                          : enabled
 *** Enable Assembler                         : disabled
 *** Variable name length                     : unlimited
 *** Use global bitfields                     : enabled
 *** Stateflow: use of bitfields              : enabled
 *** State activity encoding limit            : 5
 *** Omit zero inits in restart function      : disabled
 *** Share functions between TL subsystems    : disabled
 *** Generate 64bit functions                 : enabled
 *** Inlining Threshold                       : 6
 *** Line break limit                         : 100
 *** Target optimized boolean data type       : enabled
 *** Keep saturation elements                 : disabled
 *** Extended variable sharing                : disabled
 *** Extended lifetime optimization           : enabled
 *** Style definition file                    : C:\Program Files\dSPACE TargetLink 5.0\matlab\tl\con
 ***                                            fig\codegen\cconfig.xml
 *** Root style sheet                         : C:\Program Files\dSPACE TargetLink 5.0\Matlab\Tl\XML
 ***                                            \CodeGen\Stylesheets\TL_CSourceCodeSS.xsl
 ***
 *** TargetLink version      : 5.0 from 02-Oct-2019
 *** Code generator version  : Build Id 5.0.0.24 from 2019-10-07 12:46:33
\**************************************************************************************************/

#ifndef ASC_SWC_LUT_H
#define ASC_SWC_LUT_H
/* line(s) below inserted by custom_post_codegen_hook */
#define DVERASC_SWC_LUT_H "$Rev:: 254   $"
/* line(s) above inserted by custom_post_codegen_hook */

/*------------------------------------------------------------------------------------------------*\
  DEFINES (OPT)
\*------------------------------------------------------------------------------------------------*/
/*------------------------------------------------------------------------------------------------*\
  INCLUDES
\*------------------------------------------------------------------------------------------------*/

#include "Rte_Type.h"

#ifdef __cplusplus
extern "C" {
#endif

/*------------------------------------------------------------------------------------------------*\
  ENUMS
\*------------------------------------------------------------------------------------------------*/
/*------------------------------------------------------------------------------------------------*\
  DEFINES
\*------------------------------------------------------------------------------------------------*/
/*------------------------------------------------------------------------------------------------*\
  TYPEDEFS
\*------------------------------------------------------------------------------------------------*/
/*------------------------------------------------------------------------------------------------*\
  VARIABLES
\*------------------------------------------------------------------------------------------------*/
/*------------------------------------------------------------------------------------------------*\
  PARAMETERIZED MACROS
\*------------------------------------------------------------------------------------------------*/
/*------------------------------------------------------------------------------------------------*\
  FUNCTION PROTOTYPES
\*------------------------------------------------------------------------------------------------*/

/**************************************************************************************************\
   GlobalLookup1D_asc: Derived TL_CG default function class.
\**************************************************************************************************/
extern sint16 Tab1DnMS0I2T2081_asc(uint8 Nx, const uint16 * x_table, const sint16 * z_table, uint16
    x);
extern uint16 Tab1DnMS0I2T521_asc(uint8 Nx, const uint16 * x_table, const uint16 * z_table, uint16
    x);
extern uint16 Tab1DnMS0I2T524_asc(uint8 Nx, const sint16 * x_table, const uint16 * z_table, sint16
    x);

#ifdef __cplusplus
}
#endif

#endif /* ASC_SWC_LUT_H */
/*------------------------------------------------------------------------------------------------*\
  END OF FILE
\*------------------------------------------------------------------------------------------------*/
