/*-----------------------------------------------------------------------*/
/* File Identifier on server    $Id: ZPC_ram.h 254 2024-09-27 09:19:52Z VWQCRBZ $ */
/* File location on server $HeadURL: https://subversion.wob.vw.vwg/SWIfaceMxB26/Branches/MQB41BW_V0091_Bosch_100Fit_Auslieferung_LSMQBWASIL-190/20_ENG/Units/ZPC/Product/INC/ZPC_ram.h $ */
/*-----------------------------------------------------------------------*/

/* Spezifikation "AutosarEPSInterface Baseline 2.1" */

		
/**************************************************************************************************\
 *** 
 *** Code generation unit : 
 *** Codefile             : ZPC_ram.h
 ***
 *** Generated by TargetLink, the dSPACE production quality code generator
 *** Generation date: 2024-09-27 11:12:30
 ***
 *** CODE GENERATOR OPTIONS:
 *** Code generation mode                     : Classic AUTOSAR
 *** AUTOSAR version                          : 4.4.0
 *** Compiler                                 : <unknown>
 *** Target                                   : Generic
 *** ANSI-C compatible code                   : yes
 *** Code Optimization                        : enabled
 *** Constant style                           : decimal
 *** Clean code option                        : enabled
 *** Logging mode                             : Do not log anything
 *** Code Coverage                            : disabled
 *** Generate empty conditional branches      : enabled
 *** Loop unroll threshold                    : 5
 *** Utilize bitwise shift operations         : Never
 *** Handle unscaled SF expr. with TL type    : enabled
 *** Assignment of conditions                 : AllBooleanOutputs 
 *** Scope reduction only to function level   : disabled
 *** Exploit ranges if not erasable           : disabled
 *** Exploit Compute Through Overflow         : optimized
 *** Linker sections                          : enabled
 *** Enable Assembler                         : disabled
 *** Variable name length                     : unlimited
 *** Use global bitfields                     : enabled
 *** Stateflow: use of bitfields              : enabled
 *** State activity encoding limit            : 5
 *** Omit zero inits in restart function      : disabled
 *** Share functions between TL subsystems    : disabled
 *** Generate 64bit functions                 : enabled
 *** Inlining Threshold                       : 6
 *** Line break limit                         : 100
 *** Target optimized boolean data type       : enabled
 *** Keep saturation elements                 : disabled
 *** Extended variable sharing                : disabled
 *** Extended lifetime optimization           : enabled
 *** Style definition file                    : C:\Program Files\dSPACE TargetLink 5.0\matlab\tl\con
 ***                                            fig\codegen\cconfig.xml
 *** Root style sheet                         : C:\Program Files\dSPACE TargetLink 5.0\Matlab\Tl\XML
 ***                                            \CodeGen\Stylesheets\TL_CSourceCodeSS.xsl
 ***
 *** TargetLink version      : 5.0 from 02-Oct-2019
 *** Code generator version  : Build Id 5.0.0.24 from 2019-10-07 12:46:33
\**************************************************************************************************/

#ifndef ZPC_RAM_H
#define ZPC_RAM_H
/* line(s) below inserted by custom_post_codegen_hook */
#define DVERZPC_RAM_H "$Rev:: 254   $"
/* line(s) above inserted by custom_post_codegen_hook */

/*------------------------------------------------------------------------------------------------*\
  DEFINES (OPT)
\*------------------------------------------------------------------------------------------------*/
/*------------------------------------------------------------------------------------------------*\
  INCLUDES
\*------------------------------------------------------------------------------------------------*/

#include "Rte_Type.h"
#include "tl_defines_ZPC.h"

#ifdef __cplusplus
extern "C" {
#endif

/*------------------------------------------------------------------------------------------------*\
  ENUMS
\*------------------------------------------------------------------------------------------------*/
/*------------------------------------------------------------------------------------------------*\
  DEFINES
\*------------------------------------------------------------------------------------------------*/
/*------------------------------------------------------------------------------------------------*\
  TYPEDEFS
\*------------------------------------------------------------------------------------------------*/

struct tag_RAM_Struct {
   sint32 ASC_BELA_X_AI32[105]; /* Description: Description not set */
   sint32 ASC_BELA_Y_AI32[105]; /* Description: Description not set */
   sint32 ASC_BELB_X_AI32[101]; /* Description: Description not set */
   sint32 ASC_BELB_Y_AI32[101]; /* Description: Description not set */
   sint32 ASC_BELC_X_AI32[84]; /* Description: Description not set */
   sint32 ASC_BELC_Y_AI32[84]; /* Description: Description not set */
   const uint32 BSW_ST_SIGNALE02_FAS01_CU32; /* Description: can_stSignale02_mu32: QFK FAS01 PLA Kom
   munikation gueltig (0) ungueltig (1) */
   const uint32 BSW_ST_SIGNALE02_FAS02_CU32; /* Description: can_stSignale02_mu32: QFK FAS02 AWV Kom
   munikation gueltig (0) ungueltig (1) */
   const uint32 BSW_ST_SIGNALE02_FAS03_CU32; /* Description: can_stSignale02_mu32: QFK FAS03 HCA Kom
   munikation gueltig (0) ungueltig (1) */
   const uint32 BSW_ST_SIGNALE02_FAS04_CU32; /* Description: can_stSignale02_mu32: QFK FAS04 DSR Kom
   munikation gueltig (0) ungueltig (1) */
   const uint32 BSW_ST_SIGNALE02_FAS05_CU32; /* Description: can_stSignale02_mu32: QFK FAS05 XXX Kom
   munikation gueltig (0) ungueltig (1) */
   const uint32 BSW_ST_SIGNALE02_VMM_CU32; /* Description: can_stSignale02_mu32: QFK VMM Kommunikati
   on gueltig (0) ungueltig (1) */
   const uint32 BSW_ST_STBITS01_EPS_INITIALISIERT_CU32; /* Description: bsw_mskStatusbits01_mu32: In
   formation EPS Initialisiert (1) oder nicht initialisiert (0) */
   const uint32 BSW_ST_STBITS02_ESP_FUNKTIONALITAET_CU32; /* Description: bsw_mskStatusbits02_mu32: 
   ESP Funktionalitaet iO (0) niO (1) */
   const uint32 DIA_MSK_ANPASSUNG01_FAS01_CU32; /* Description: dia_mskAnpassung01_mu32: QFK FAS01 P
   LA Codierung nicht aktiv (0) aktiv (1) */
   const uint32 DIA_MSK_ANPASSUNG01_FAS02_CU32; /* Description: dia_mskAnpassung01_mu32: QFK FAS02 A
   WV Codierung nicht aktiv (0) aktiv (1) */
   const uint32 DIA_MSK_ANPASSUNG01_FAS03_CU32; /* Description: dia_mskAnpassung01_mu32: QFK FAS03 H
   CA Codierung nicht aktiv (0) aktiv (1) */
   const uint32 DIA_MSK_ANPASSUNG01_FAS04_CU32; /* Description: dia_mskAnpassung01_mu32: QFK FAS04 D
   SR Codierung nicht aktiv (0) aktiv (1) */
   const uint32 DIA_MSK_ANPASSUNG01_VMM_CU32; /* Description: dia_mskAnpassung01_mu32: QFK VMM Codie
   rung nicht aktiv (0) aktiv (1) */
   const uint32 DIA_MSK_CODIERUNG01_QFK_CU32; /* Description: dia_mskCodierung01_mu32: QFK codiert n
   icht aktiv (0) aktiv (1) */
   const uint8 QAP_ST_CAN2TN_EINGRIFF_CU8; /* Description: can_stAnfFasXX_mu8: Regeleingriff aktiv
   */
   const uint8 QAP_ST_CAN2TN_EINGRIFF_HANDSOFF_CU8; /* Description: can_stAnfFasXX_mu8: Regeleingrif
   f HandsOff aktiv */
   const uint8 QAP_ST_CAN2TN_INIT_CU8; /* Description: can_stAnfFasXX_mu8: Initphase/ Fehler ohne Fe
   hlereintrag (z.B. keine/ zu geringe LU) ggf. Trennen */
   const uint8 QAP_ST_CAN2TN_READY_CU8; /* Description: can_stAnfFasXX_mu8: Ready- QFK aktiv, spezif
   ische Fkt. nicht im Eingriff */
   const uint8 QAP_ST_EING_LV_VMM_KEINEING_CU8; /* Description: can_stEingLvVMM_mu8: kein Eingriff
   */
   const uint8 QAP_ST_EING_LV_VMM_PLA_EMRG_CU8; /* Description: can_stEingLvVMM_mu8: nicht ueberlenk
   barer Emergency-Eingriff */
   const uint8 QAP_ST_EING_LV_VMM_UEL_EMRG_CU8; /* Description: can_stEingLvVMM_mu8: ueberlenkbarer 
   Emergency-Eingriff */
   const uint8 QAP_ST_MAIN2CAN_ABBRUCH_CU8; /* Description: qap_stQFK_mu8: Abbruch */
   const uint8 QAP_ST_MAIN2CAN_EINGRIFF_CU8; /* Description: qap_stQFK_mu8: Regeleingriff aktiv */
   const uint8 QAP_ST_MAIN2CAN_EINGRIFF_ED_CU8; /* Description: qap_stQFK_mu8: Regeleingriff aktiv; 
   eingeschraenkte Dynamik */
   const uint8 QAP_ST_MAIN2CAN_EINGRIFF_HANDSOFF_CU8; /* Description: qap_stQFK_mu8: Regeleingriff a
   ktiv; HandsOff Betrieb */
   const uint8 QAP_ST_MAIN2CAN_FEHLER_ME_CU8; /* Description: qap_stQFK_mu8: allgemeiner Fehler mit 
   Eintrag der zentral QFK-Schnittstelle blockiert */
   const uint8 QAP_ST_MAIN2CAN_FEHLER_OE_CU8; /* Description: qap_stQFK_mu8: Fehler ohne Eintrag der
    zentral QFK-Schnittstelle blockiert (z.B. im QFK der diese Funktion verhindert */
   const uint8 QAP_ST_MAIN2CAN_INIT_CU8; /* Description: qap_stQFK_mu8: Initphase/ Aufstarten */
   const uint8 QAP_ST_MAIN2CAN_READY_CU8; /* Description: qap_stQFK_mu8: Ready- QFK-Eingriff moeglic
   h aber kein Eingriff aktiv */
   const uint8 QAP_ST_MAIN2PRIO_EINGRIFF_CU8; /* Description: qap_stMainToPrio_mu8: Regeleingriff ak
   tiv */
   const uint8 QAP_ST_MAIN2PRIO_FEHLER_ME_CU8; /* Description: qap_stMainToPrio_mu8: allgemeiner Feh
   ler mit Eintrag der zentral QFK-Schnittstelle blockiert */
   const uint8 QAP_ST_MAIN2PRIO_FEHLER_OE_CU8; /* Description: qap_stMainToPrio_mu8: Fehler ohne Ein
   trag der zentral QFK-Schnittstelle blockiert (z.B. im QFK der diese Funktion verhindert) */
   const uint8 QAP_ST_MAIN2PRIO_INIT_CU8; /* Description: qap_stMainToPrio_mu8: Initphase */
   const uint8 QAP_ST_MAIN2PRIO_READY_CU8; /* Description: qap_stMainToPrio_mu8: Ready- QFK-Eingriff
    zentral moeglich oder wird durchgefuehrt */
   const uint8 QAP_ST_MAIN2TN_ABBRUCH_CU8; /* Description: qap_stMainToTn_mu8: Abbruch- Kein Eingrif
   f moeglich */
   const uint8 QAP_ST_MAIN2TN_FEHLER_ME_CU8; /* Description: qap_stMainToTn_mu8: allgemeiner Fehler 
   mit Eintrag der zentral QFK-Schnittstelle blockiert */
   const uint8 QAP_ST_MAIN2TN_FEHLER_OE_CU8; /* Description: qap_stMainToTn_mu8: Fehler ohne Eintrag
    der zentral QFK-Schnittstelle blockiert (z.B. im QFK der diese Funktion verhindert) */
   const uint8 QAP_ST_MAIN2TN_INIT_CU8; /* Description: qap_stMainToTn_mu8: Initphase */
   const uint8 QAP_ST_MAIN2TN_READY_CU8; /* Description: qap_stMainToTn_mu8: Ready- QFK-Eingriff zen
   tral moeglich oder wird durchgefuehrt */
   const uint8 QAP_ST_MAIN2TN_READY_ED_CU8; /* Description: qap_stMainToTn_mu8: Ready- QFK-Eingriff 
   zentral moeglich oder wird durchgefuehrt */
   const uint8 QAP_ST_MAININT_ABBRUCH_CU8; /* Description: qap_stQfkMainInt_mu8: Abbruch Regeleingri
   ff durch QFK (z.B. Fahrereingriff, Ueberschreitung von Regelgrenzen, ...) */
   const uint8 QAP_ST_MAININT_DEAKTIV_CU8; /* Description: qap_stQfkMainInt_mu8: Funktion Deaktiv (a
   lle Teilnehmer deaktiv, daher keine Schnittstelle nach aussen verfuegbar) */
   const uint8 QAP_ST_MAININT_EINGRIFF_CU8; /* Description: qap_stQfkMainInt_mu8: Regeleingriff akti
   v */
   const uint8 QAP_ST_MAININT_EINGRIFF_HANDSOFF_CU8; /* Description: qap_stQfkMainInt_mu8: Regeleing
   riff HandsOff-Funktion aktiv */
   const uint8 QAP_ST_MAININT_EINGRIFF_ED_CU8; /* Description: qap_stQfkMainInt_mu8: Regeleingriff a
   ktiv; eingeschraenkte Dynamik */
   const uint8 QAP_ST_MAININT_FEHLER_ME_CU8; /* Description: qap_stQfkMainInt_mu8: allgemeiner Fehle
   r mit Eintrag der zentral QFK-Schnittstelle blockiert */
   const uint8 QAP_ST_MAININT_FEHLER_OE_CU8; /* Description: qap_stQfkMainInt_mu8: Fehler ohne Eintr
   ag der zentral QFK-Schnittstelle blockiert (z.B. im QFK der diese Funktion verhindert) */
   const uint8 QAP_ST_MAININT_INIT_CU8; /* Description: qap_stQfkMainInt_mu8: Initphase/ Aufstarten
   */
   const uint8 QAP_ST_MAININT_READY_CU8; /* Description: qap_stQfkMainInt_mu8: Ready- QFK-Eingriff m
   oeglich aber kein Eingriff aktiv */
   const uint8 QAP_ST_PRIO2MAIN_EINGRIFF_CU8; /* Description: qap_stPrioToMain_mu8: Funktion im Eing
   riff */
   const uint8 QAP_ST_PRIO2MAIN_EINGRIFF_HANDSOFF_CU8; /* Description: qap_stPrioToMain_mu8: Funktio
   n im Eingriff HandOff-Betrieb */
   const uint8 QAP_ST_PRIO2MAIN_READY_CU8; /* Description: qap_stPrioToMain_mu8: Priorisierung Berei
   t */
   const uint8 QAP_ST_PRIO2TN_ACTIVE_CU8; /* Description: qap_stPrioToTnX_mu8: Funktion darf exklusi
   ven Momenteneingriff durchfuehren (identisch KOR) */
   const uint8 QAP_ST_PRIO2TN_IDLE_CU8; /* Description: qap_stPrioToTnX_mu8: PRIO aktiv; aktuell koe
   nnen Momenteneingriffe durch die Funktion angefordert werden (identisch KOR) */
   const uint8 QAP_ST_PRIO2TN_INIT_CU8; /* Description: qap_stPrioToTnX_mu8: Initphase/ Fkt. deaktiv
    (identisch KOR) */
   const uint8 QAP_ST_PRIO2TN_REJECT_CU8; /* Description: qap_stPrioToTnX_mu8: Momenteneingriff fuer
    Funktion abgewiesen/ gesperrt (identisch KOR) */
   const uint8 QAP_ST_PRIOMAIN_EINGRIFF_COMFORT_CU8; /* Description: qap_stPrioMain_mu8: Komfortfunk
   tion im Eingriff */
   const uint8 QAP_ST_PRIOMAIN_EINGRIFF_EMERGENCY_CU8; /* Description: qap_stPrioMain_mu8: Notfallfu
   nktion im Eingriff */
   const uint8 QAP_ST_PRIOMAIN_INIT_CU8; /* Description: qap_stPrioMain_mu8: Priorisierung INIT */
   const uint8 QAP_ST_PRIOMAIN_READY_CU8; /* Description: qap_stPrioMain_mu8: Priorisierung Bereit
   */
   const uint8 QAP_ST_PRIO_TNCOMFORT_INIT_CU8; /* Description: qap_stSMTnComfort_mu8: Inittialisieru
   ng/ keine Anforderung Komfortteilnehmer */
   const uint8 QAP_ST_PRIO_TNCOMFORT_TN10_CU8; /* Description: qap_stSMTnComfort_mu8: Komfortfunktio
   n Teilnehmer 10 gewaehlt */
   const uint8 QAP_ST_PRIO_TNCOMFORT_TN11_CU8; /* Description: qap_stSMTnComfort_mu8: Komfortfunktio
   n Teilnehmer 11 gewaehlt */
   const uint8 QAP_ST_PRIO_TNCOMFORT_TN1_CU8; /* Description: qap_stSMTnComfort_mu8: Komfortfunktion
    Teilnehmer 1 gewaehlt */
   const uint8 QAP_ST_PRIO_TNCOMFORT_TN3_CU8; /* Description: qap_stSMTnComfort_mu8: Komfortfunktion
    Teilnehmer 3 gewaehlt */
   const uint8 QAP_ST_PRIO_TNCOMFORT_TN6_CU8; /* Description: qap_stSMTnComfort_mu8: Komfortfunktion
    Teilnehmer 6 gewaehlt */
   const uint8 QAP_ST_PRIO_TNCOMFORT_TN8_CU8; /* Description: qap_stSMTnComfort_mu8: Komfortfunktion
    Teilnehmer 8 gewaehlt */
   const uint8 QAP_ST_PRIO_TNCOMFORT_TN9_CU8; /* Description: qap_stSMTnComfort_mu8: Komfortfunktion
    Teilnehmer 9 gewaehlt */
   const uint8 QAP_ST_PRIO_TNEMERGCY_INIT_CU8; /* Description: qap_stSMTnEmergency_mu8: Inittialisie
   rung/ keine Anforderung Komfortteilnehmer */
   const uint8 QAP_ST_PRIO_TNEMERGCY_TN11_CU8; /* Description: qap_stSMTnEmergency_mu8: Notfallfunkt
   ion Teilnehmer 11 gewaehlt */
   const uint8 QAP_ST_PRIO_TNEMERGCY_TN2_CU8; /* Description: qap_stSMTnEmergency_mu8: Notfallfunkti
   on Teilnehmer 2 gewaehlt */
   const uint8 QAP_ST_PRIO_TNEMERGCY_TN4_CU8; /* Description: qap_stSMTnEmergency_mu8: Notfallfunkti
   on Teilnehmer 4 gewaehlt */
   const uint8 QAP_ST_PRIO_TNEMERGCY_TN5_CU8; /* Description: qap_stSMTnEmergency_mu8: Notfallfunkti
   on Teilnehmer 5 gewaehlt */
   const uint8 QAP_ST_PRIO_TNEMERGCY_TN7_CU8; /* Description: qap_stSMTnEmergency_mu8: Notfallfunkti
   on Teilnehmer 7 gewaehlt */
   const uint8 QAP_ST_QPR2QAP_EINGRIFF_CU8; /* Description: qpr_stRegler_mu8: Regler/ Lenkung im Reg
   eleingriff */
   const uint8 QAP_ST_QPR2QAP_EINGRIFF_ED_CU8; /* Description: qpr_stRegler_mu8: Regler/ Lenkung im 
   Regeleingriff eingeschraenkte Dynamik */
   const uint8 QAP_ST_QPR2QAP_EINGRIFF_HANDSOFF_CU8; /* Description: qpr_stRegler_mu8: Regler/ Lenku
   ng im Regeleingriff Hands Off Betrieb */
   const uint8 QAP_ST_QPR2QAP_FEHLER_ME_CU8; /* Description: qpr_stRegler_mu8: Regler/ Lenkung fehle
   rhaft mit Eintrag */
   const uint8 QAP_ST_QPR2QAP_INIT_CU8; /* Description: qpr_stRegler_mu8: Regler/ Lenkung wird initi
   alisiert/ Regeleingriff temp. nicht zur Verfuegung */
   const uint8 QAP_ST_QPR2QAP_READY_CU8; /* Description: qpr_stRegler_mu8: Regler/ Lenkung bereit fu
   er Eingriff */
   const uint8 QAP_ST_SMTNX_ABBRUCH_CU8; /* Description: qap_stQfkSmTnX_mu8: Abbruch Regeleingriff d
   urch QFK (z.B. Fahrereingriff, Ueberschreitung */
   const uint8 QAP_ST_SMTNX_DEAKTIV_CU8; /* Description: qap_stQfkSmTnX_mu8: Funktion Deaktiv */
   const uint8 QAP_ST_SMTNX_EINGRIFF_CU8; /* Description: qap_stQfkSmTnX_mu8: Regeleingriff aktiv */
   const uint8 QAP_ST_SMTNX_EINGRIFF_ED_CU8; /* Description: qap_stQfkSmTnX_mu8: Regeleingriff aktiv
    eingeschraenkte Dynamik */
   const uint8 QAP_ST_SMTNX_EINGRIFF_HANDSOFF_CU8; /* Description: qap_stQfkSmTnX_mu8: Regeleingriff
    aktiv HandsOff Betrieb */
   const uint8 QAP_ST_SMTNX_FEHLER_ME_CU8; /* Description: qap_stQfkSmTnX_mu8: Fehler mit Eintrag im
    QFK der diese Funktion verhindert */
   const uint8 QAP_ST_SMTNX_FEHLER_OE_CU8; /* Description: qap_stQfkSmTnX_mu8: Fehler ohne Eintrag i
   m QFK der diese Funktion verhindert */
   const uint8 QAP_ST_SMTNX_GESPERRT_CU8; /* Description: qap_stQfkSmTnX_mu8: Kein Eingriff moeglich
    wegen hoeherpriorer Fkt. */
   const uint8 QAP_ST_SMTNX_INIT_CU8; /* Description: qap_stQfkSmTnX_mu8: Initphase/ Aufstarten */
   const uint8 QAP_ST_SMTNX_READY_ANFR_CU8; /* Description: qap_stQfkSmTnX_mu8: Eingriffsanfrage Rea
   dy- QFK aktiv, spezifische Fkt. nicht im Eingriff */
   const uint8 QAP_ST_SMTNX_READY_CU8; /* Description: qap_stQfkSmTnX_mu8: Ready- QFK aktiv, spezifi
   sche Fkt. nicht im Eingriff */
   const uint8 QAP_ST_TN2CAN_ABBRUCH_CU8; /* Description: qap_stFasXX_mu8: Abbruch Regeleingriff dur
   ch QFK (z.B. Fahrereingriff, Ueberschreitung von Regelgrenzen, ...) */
   const uint8 QAP_ST_TN2CAN_DEAKTIV_CU8; /* Description: qap_stFasXX_mu8: Teilfunktion deaktiv */
   const uint8 QAP_ST_TN2CAN_EINGRIFF_CU8; /* Description: qap_stFasXX_mu8: Regeleingriff aktiv */
   const uint8 QAP_ST_TN2CAN_EINGRIFF_ED_CU8; /* Description: qap_stFasXX_mu8: Regeleingriff aktiv e
   ingeschraenkte Dynamik */
   const uint8 QAP_ST_TN2CAN_EINGRIFF_HANDSOFF_CU8; /* Description: qap_stFasXX_mu8: Regeleingriff a
   ktiv Hands Off Betrieb */
   const uint8 QAP_ST_TN2CAN_FEHLER_ME_CU8; /* Description: qap_stFasXX_mu8: Fehler mit Eintrag im Q
   FK der diese Funktion verhindert */
   const uint8 QAP_ST_TN2CAN_FEHLER_OE_CU8; /* Description: qap_stFasXX_mu8: Fehler ohne Eintrag im 
   QFK der diese Funktion verhindert */
   const uint8 QAP_ST_TN2CAN_GESPERRT_CU8; /* Description: qap_stFasXX_mu8: Kein Eingriff moeglich w
   egen hoeherpriorer Fkt. */
   const uint8 QAP_ST_TN2CAN_INIT_CU8; /* Description: qap_stFasXX_mu8: Initphase/ Aufstarten (so la
   nge aktive wie QFK nicht bereit) */
   const uint8 QAP_ST_TN2CAN_READY_CU8; /* Description: qap_stFasXX_mu8: Ready- QFK aktiv, spezifisc
   he Fkt. nicht im Eingriff (Bereit fuer Eingriffe) */
   const uint8 QAP_ST_TN2MAIN_EINGRIFF_CU8; /* Description: qfk_stTnXToMAIN_u8: Momenteneingriff in 
   der Funktion ist aktiv (identisch KOR)  */
   const uint8 QAP_ST_TN2MAIN_EINGRIFF_HANDSOFF_CU8; /* Description: qfk_stTnXToMAIN_u8: Momentenein
   griff in der Funktion ist mit HandsOff Funktionalität aktiv (identisch KOR)  */
   const uint8 QAP_ST_TN2MAIN_IDLE_CU8; /* Description: qfk_stTnXToMAIN_u8: aktiv aber kein Eingriff
    (identisch KOR) */
   const uint8 QAP_ST_TN2MAIN_INIT_CU8; /* Description: qfk_stTnXToMAIN_u8: Initphase/ Fkt. deaktiv 
   (identisch KOR) */
   const uint8 QAP_ST_TN2MAIN_REQ_CU8; /* Description: qfk_stTnXToMAIN_u8: Freigabe fuer Eingriff wi
   rd von Funktion angefordert (identisch KOR) */
   const uint8 QAP_ST_TN2PRIO_ACTIVE_CU8; /* Description: qfk_stTnXToPrio_mu8: Momenteneingriff in d
   er Funktion ist aktiv (identisch KOR)  */
   const uint8 QAP_ST_TN2PRIO_IDLE_CU8; /* Description: qfk_stTnXToPrio_mu8: aktiv aber kein Eingrif
   f (identisch KOR) */
   const uint8 QAP_ST_TN2PRIO_INIT_CU8; /* Description: qfk_stTnXToPrio_mu8: Initphase/ Fkt. deaktiv
    (identisch KOR) */
   const uint8 QAP_ST_TN2PRIO_REQ_CU8; /* Description: qfk_stTnXToPrio_mu8: Freigabe fuer Eingriff w
   ird von Funktion angefordert (identisch KOR) */
   const uint16 QAP_TMR_ABBRUCH_ENTPR_CU16; /* Description: Entprellzeit Automatischer Bereitschafts
   wechsel nach Abbruch [s] */
   const uint16 QAP_TMR_RESET_CU16; /* Description: Startwert fuer Timer [s] */
   const uint16 QAP_TMR_SAMPLE_TIME_CU16; /* Description: Zykluszeit QAP [s] */
   const uint16 QHM_F_KSK_BEGRENZ_NUEL_CU16; /* Description: QHM-Limits - Maximalkraft des nicht ueb
   erlenkbaren Eingriffs [N] */
   const uint16 QHM_FAC_SAMPLE_TIME_CU16; /* Description: Zykluszeit QHM [s] */
   const uint16 QPR_FAC_SAMPLE_TIME_CU16; /* Description: Zykluszeit QPR [s] */
   const uint8 QPR_ST_ABBRUCH_CU8; /* Description: qua_stReglerRequest_mu8: Abbruch */
   const uint8 QPR_ST_BEREIT_CU8; /* Description: qua_stReglerRequest_mu8: Bereit */
   const uint8 QPR_ST_EINGRIFF_CU8; /* Description: qua_stReglerRequest_mu8: Eingriff */
   const uint8 QPR_ST_EINGRIFF_NUEL_CU8; /* Description: qua_stReglerRequest_mu8: Eingriff_NUel */
   const uint16 QUA_FAC_GRAD2RAD_CU16; /* Description: Umrechnungsfaktor Grad in Radiant */
   const uint16 QUA_FAC_RAD2GRAD_KMH2MPS_CU16; /* Description: Umrechnungsfaktor Radiant in Grad und
    km/h in m/s */
   const uint8 QUA_ST_AKTIVFASIDX_VMM_CU8; /* Description: qua_stAktivFasIdxMod_u8: Eingriff VMM */
   const uint8 QUA_ST_QUA2QPR_REQ_EINGRIFF_CU8; /* Description: qua_stReglerRequest_mu8: Eingriff */
   const uint8 QUA_ST_QUA2QPR_REQ_EIN_NUEL_CU8; /* Description: qua_stReglerRequest_mu8: Eingriff ni
   cht ueberlenkbar */
   const uint8 QUA_ST_QUA2QPR_REQ_READY_CU8; /* Description: qua_stReglerRequest_mu8: Bereit */
   const uint8 QUA_ST_VMM_PLA_COM_CU8; /* Description: can_stEingLvVMM_mu8: Eingriff VMM PLA-Komfort
   system */
   const uint8 QUA_ST_VMM_PLA_EMRG_CU8; /* Description: can_stEingLvVMM_mu8: Eingriff VMM PLA-Notfal
   lsystem */
   const uint16 QUA_VFZG_MAX_CU16; /* Description: QUA-SignalQualifier - Ersatzwert, bei gesetzten B
   its in fga_mskStVFzg_mu8 */
   const uint16 QUA_VFZG_SIG_QUALITY_LV0_CU16; /* Description: QUA-SignalQualifier - Ungenauigkeit d
   es Geschwindigkeitsignals bei can_stVSignalQualifier_mu8: 0 */
   const uint16 QUA_VFZG_SIG_QUALITY_LV1_CU16; /* Description: QUA-SignalQualifier - Ungenauigkeit d
   es Geschwindigkeitsignals bei can_stVSignalQualifier_mu8: 1 */
   const uint16 QUA_VFZG_SIG_QUALITY_LV2_CU16; /* Description: QUA-SignalQualifier - Ungenauigkeit d
   es Geschwindigkeitsignals bei can_stVSignalQualifier_mu8: 2 */
   const uint16 QUA_VFZG_SIG_QUALITY_LV3_CU16; /* Description: QUA-SignalQualifier - Ungenauigkeit d
   es Geschwindigkeitsignals bei can_stVSignalQualifier_mu8: 3 */
   const uint16 QUA_VFZG_SIG_QUALITY_LV4_CU16; /* Description: QUA-SignalQualifier - Ungenauigkeit d
   es Geschwindigkeitsignals bei can_stVSignalQualifier_mu8: 4 */
   const uint16 QUA_VFZG_SIG_QUALITY_LV5_CU16; /* Description: QUA-SignalQualifier - Ungenauigkeit d
   es Geschwindigkeitsignals bei can_stVSignalQualifier_mu8: 5 */
}; /* Description: struct type created for variable: RAM_Struct */

/*------------------------------------------------------------------------------------------------*\
  VARIABLES
\*------------------------------------------------------------------------------------------------*/

#ifndef USE_CST_PARAM_STRUCT_H
/**************************************************************************************************\
   MERGEABLE_CAL: mergeable calibratable parameters (ROM) | Width: N.A.
\**************************************************************************************************/
extern MERGEABLE_CAL struct tag_RAM_Struct RAM_Struct;
#endif /*USE_CST_PARAM_STRUCT_H*/

/*------------------------------------------------------------------------------------------------*\
  PARAMETERIZED MACROS
\*------------------------------------------------------------------------------------------------*/
/*------------------------------------------------------------------------------------------------*\
  FUNCTION PROTOTYPES
\*------------------------------------------------------------------------------------------------*/
#ifdef __cplusplus
}
#endif

#endif /* ZPC_RAM_H */
/*------------------------------------------------------------------------------------------------*\
  END OF FILE
\*------------------------------------------------------------------------------------------------*/
