/*-----------------------------------------------------------------------*/
/* File Identifier on server    $Id: ZPC_veh.h 254 2024-09-27 09:19:52Z VWQCRBZ $ */
/* File location on server $HeadURL: https://subversion.wob.vw.vwg/SWIfaceMxB26/Branches/MQB41BW_V0091_Bosch_100Fit_Auslieferung_LSMQBWASIL-190/20_ENG/Units/ZPC/Product/INC/ZPC_veh.h $ */
/*-----------------------------------------------------------------------*/

/* Spezifikation "AutosarEPSInterface Baseline 2.1" */

		
/**************************************************************************************************\
 *** 
 *** Code generation unit : 
 *** Codefile             : ZPC_veh.h
 ***
 *** Generated by TargetLink, the dSPACE production quality code generator
 *** Generation date: 2024-09-27 11:12:30
 ***
 *** CODE GENERATOR OPTIONS:
 *** Code generation mode                     : Classic AUTOSAR
 *** AUTOSAR version                          : 4.4.0
 *** Compiler                                 : <unknown>
 *** Target                                   : Generic
 *** ANSI-C compatible code                   : yes
 *** Code Optimization                        : enabled
 *** Constant style                           : decimal
 *** Clean code option                        : enabled
 *** Logging mode                             : Do not log anything
 *** Code Coverage                            : disabled
 *** Generate empty conditional branches      : enabled
 *** Loop unroll threshold                    : 5
 *** Utilize bitwise shift operations         : Never
 *** Handle unscaled SF expr. with TL type    : enabled
 *** Assignment of conditions                 : AllBooleanOutputs 
 *** Scope reduction only to function level   : disabled
 *** Exploit ranges if not erasable           : disabled
 *** Exploit Compute Through Overflow         : optimized
 *** Linker sections                          : enabled
 *** Enable Assembler                         : disabled
 *** Variable name length                     : unlimited
 *** Use global bitfields                     : enabled
 *** Stateflow: use of bitfields              : enabled
 *** State activity encoding limit            : 5
 *** Omit zero inits in restart function      : disabled
 *** Share functions between TL subsystems    : disabled
 *** Generate 64bit functions                 : enabled
 *** Inlining Threshold                       : 6
 *** Line break limit                         : 100
 *** Target optimized boolean data type       : enabled
 *** Keep saturation elements                 : disabled
 *** Extended variable sharing                : disabled
 *** Extended lifetime optimization           : enabled
 *** Style definition file                    : C:\Program Files\dSPACE TargetLink 5.0\matlab\tl\con
 ***                                            fig\codegen\cconfig.xml
 *** Root style sheet                         : C:\Program Files\dSPACE TargetLink 5.0\Matlab\Tl\XML
 ***                                            \CodeGen\Stylesheets\TL_CSourceCodeSS.xsl
 ***
 *** TargetLink version      : 5.0 from 02-Oct-2019
 *** Code generator version  : Build Id 5.0.0.24 from 2019-10-07 12:46:33
\**************************************************************************************************/

#ifndef ZPC_VEH_H
#define ZPC_VEH_H
/* line(s) below inserted by custom_post_codegen_hook */
#define DVERZPC_VEH_H "$Rev:: 254   $"
/* line(s) above inserted by custom_post_codegen_hook */

/*------------------------------------------------------------------------------------------------*\
  DEFINES (OPT)
\*------------------------------------------------------------------------------------------------*/
/*------------------------------------------------------------------------------------------------*\
  INCLUDES
\*------------------------------------------------------------------------------------------------*/

#include "Rte_Type.h"
#include "tl_defines_ZPC.h"

#ifdef __cplusplus
extern "C" {
#endif

/*------------------------------------------------------------------------------------------------*\
  ENUMS
\*------------------------------------------------------------------------------------------------*/
/*------------------------------------------------------------------------------------------------*\
  DEFINES
\*------------------------------------------------------------------------------------------------*/
/*------------------------------------------------------------------------------------------------*\
  TYPEDEFS
\*------------------------------------------------------------------------------------------------*/

struct tag_VEH_Struct {
   const volatile uint16 CST_SPARE_DATA[4]; /* Description: Custom Spare Data (4x16Bit) */
   const volatile uint16 ARS_V_PHV_AKTIV_AU16; /* Description: Geschwindigkeitsabhängiger Rücklauf a
   ktiv */
   const volatile uint16 ARS_PHV_V1_AU16; /* Description: Geschwindigkeitsbereich Sollrücklauf 1 */
   const volatile uint16 ARS_PHV_V2_AU16; /* Description: Geschwindigkeitsbereich Sollrücklauf 2 */
   const volatile uint16 ARS_PHV_V3_AU16; /* Description: Geschwindigkeitsbereich Sollrücklauf 3 */
   const volatile uint16 ARS_PHV_V4_AU16; /* Description: Geschwindigkeitsbereich Sollrücklauf 3 */
   const volatile uint16 ARS_PHV_RITZEL_V2_AUTO_KLU16[14]; /* Description: Kennlinie Active Return S
   ollrücklaufgeschwindigkeit Auto V2 */
   const volatile uint16 ARS_PHV_RITZEL_V2_DYN_KLU16[14]; /* Description: Kennlinie Active Return So
   llrücklaufgeschwindigkeit Dynamik V2 */
   const volatile uint16 ARS_PHV_RITZEL_V2_KOM_KLU16[14]; /* Description: Kennlinie Active Return So
   llrücklaufgeschwindigkeit Komfort V2 */
   const volatile uint16 ARS_PHV_RITZEL_V2_AUTO_XI16[14]; /* Description: Kennlinie Active Return So
   llrücklaufgeschwindigkeit Auto X-Stützstellen V2 */
   const volatile uint16 ARS_PHV_RITZEL_V2_KOM_XI16[14]; /* Description: Kennlinie Active Return Sol
   lrücklaufgeschwindigkeit Auto X-Stützstellen V2 */
   const volatile uint16 ARS_PHV_RITZEL_V2_DYN_XI16[14]; /* Description: Kennlinie Active Return Sol
   lrücklaufgeschwindigkeit Auto X-Stützstellen V2 */
   const volatile uint16 ARS_FAC_KL_PHV_V2_AUTO_AI16; /* Description: Faktor auf Kennlinie Active Re
   turn Sollrücklaufgeschwindigkeit V2 Auto */
   const volatile uint16 ARS_FAC_KL_PHV_V2_DYN_AI16; /* Description: Faktor auf Kennlinie Active Ret
   urn Sollrücklaufgeschwindigkeit V2 Dyn */
   const volatile uint16 ARS_FAC_KL_PHV_V2_KOM_AI16; /* Description: Faktor auf Kennlinie Active Ret
   urn Sollrücklaufgeschwindigkeit V2 Kom */
   const volatile uint16 ARS_FAC_KL_PHV_V3_AUTO_AI16; /* Description: Faktor auf Kennlinie Active Re
   turn Sollrücklaufgeschwindigkeit V3 Auto */
   const volatile uint16 ARS_FAC_KL_PHV_V3_DYN_AI16; /* Description: Faktor auf Kennlinie Active Ret
   urn Sollrücklaufgeschwindigkeit V3 Dyn */
   const volatile uint16 ARS_FAC_KL_PHV_V3_KOM_AI16; /* Description: Faktor auf Kennlinie Active Ret
   urn Sollrücklaufgeschwindigkeit V3 Kom */
   const volatile uint16 ARS_PHV_RITZEL_V3_AUTO_KLU16[14]; /* Description: Kennlinie Active Return S
   ollrücklaufgeschwindigkeit Auto V3 */
   const volatile uint16 ARS_PHV_RITZEL_V3_DYN_KLU16[14]; /* Description: Kennlinie Active Return So
   llrücklaufgeschwindigkeit Dynamik V3 */
   const volatile uint16 ARS_PHV_RITZEL_V3_KOM_KLU16[14]; /* Description: Kennlinie Active Return So
   llrücklaufgeschwindigkeit Komfort V3 */
   const volatile uint16 ARS_PHV_RITZEL_V3_AUTO_XI16[14]; /* Description: Kennlinie Active Return So
   llrücklaufgeschwindigkeit Auto X-Stützstellen V3 */
   const volatile uint16 ARS_PHV_RITZEL_V3_KOM_XI16[14]; /* Description: Kennlinie Active Return Sol
   lrücklaufgeschwindigkeit Auto X-Stützstellen V3 */
   const volatile uint16 ARS_PHV_RITZEL_V3_DYN_XI16[14]; /* Description: Kennlinie Active Return Sol
   lrücklaufgeschwindigkeit Auto X-Stützstellen V3 */
   const volatile sint16 ARS_FAC_FILT_STOP_A2_AI16; /* Description: Filterkonstante A2 */
   const volatile sint16 ARS_FAC_FILT_STOP_A3_AU16; /* Description: Filterkonstante A3 */
   const volatile sint16 ARS_FAC_FILT_STOP_B11_AI16; /* Description: Filterkonstante B2 */
   const volatile sint16 ARS_FAC_FILT_STOP_B2_AI16; /* Description: Filterkonstante B2 */
   const volatile sint16 ARS_FAC_FILT_STOP_B3_AU16; /* Description: Filterkonstante B3 */
   const volatile uint8 ARS_SWS_SEL_FILT_PT1_TRQ_AU08; /* Description: Schalter für Filterauswahl 1 
   = Tiefpass, 0 = Bandsperre */
   const volatile uint8 ARS_SWS_SEL_FILT_PT1_TRQ_D_AU08; /* Description: Schalter für Filterauswahl 
   1 = Tiefpass, 0 = Bandsperre */
   const volatile uint8 ARS_SWS_FILT_TRQ_AU08; /* Description: Schalter für Handmomentenfilter */
   const volatile uint8 ARS_SWS_FILT_TRQ_D_AU08; /* Description: Schalter für Handmomentenfilter Däm
   pfung */
   const volatile uint16 ARS_FAC_VFZG_FILTER_TRQ_KLU16[4]; /* Description: Filterzeitkonstanten für 
   Handmomentenfilter */
   const volatile uint16 ARS_FAC_VFZG_FILTER_TRQ_D_KLU16[4]; /* Description: Filterzeitkonstanten fü
   r Handmomentenfilter Dämpfung */
   const volatile uint16 ARS_FAC_VFZG_FILTER_TRQ_XU16[4]; /* Description: Handmomentenfilter Stützst
   ellen Geschwindigkeit */
   const volatile uint16 ARS_FAC_TRQSENSOR_AUTO_KLU16[10]; /* Description: Kennlinie Active Return A
   uto Handmoment */
   const volatile uint16 ARS_FAC_TRQSENSOR_AUTO_XI16[10]; /* Description: Kennlinie Active Return Au
   to Handmoment X-Stützstellen */
   const volatile uint16 ARS_FAC_TRQSENSOR_DYN_KLU16[10]; /* Description: Kennlinie Active Return Dy
   namik Handmoment */
   const volatile uint16 ARS_FAC_TRQSENSOR_DYN_XI16[10]; /* Description: Kennlinie Active Return Dyn
   amik Handmoment X-Stützstellen */
   const volatile uint16 ARS_FAC_TRQSENSOR_KOM_KLU16[10]; /* Description: Kennlinie Active Return Ko
   mfort Handmoment */
   const volatile uint16 ARS_FAC_TRQSENSOR_KOM_XI16[10]; /* Description: Kennlinie Active Return Kom
   fort Handmoment X-Stützstellen */
   const volatile uint16 ARS_FAC_KL_TRQ_AUTO_AI16; /* Description: Faktor auf Handmoment Auto */
   const volatile uint16 ARS_FAC_KL_TRQ_DYN_AI16; /* Description: Faktor auf Handmoment Dynamik */
   const volatile uint16 ARS_FAC_KL_TRQ_KOM_AI16; /* Description: Faktor auf Handmoment Komfort */
   const volatile uint16 ARS_FAC_TRQSENSOR_D_AUTO_KLU16[10]; /* Description: Kennlinie Active Return
    Handmoment Auto Dämpfung */
   const volatile uint16 ARS_FAC_TRQSENSOR_D_AUTO_XI16[10]; /* Description: Kennlinie Active Return 
   Handmoment Auto Dämpfung x-Stützstellen */
   const volatile uint16 ARS_FAC_TRQSENSOR_D_DYN_KLU16[10]; /* Description: Kennlinie Active Return 
   Handmoment Dynamik Dämpfung x-Stützstellen */
   const volatile uint16 ARS_FAC_TRQSENSOR_D_DYN_XI16[10]; /* Description: Kennlinie Active Return H
   andmoment Dynamik Dämpfung x-Stützstellen */
   const volatile uint16 ARS_FAC_TRQSENSOR_D_KOM_KLU16[10]; /* Description: Kennlinie Active Return 
   Handmoment Komfort Dämpfung  */
   const volatile uint16 ARS_FAC_TRQSENSOR_D_KOM_XI16[10]; /* Description: Kennlinie Active Return H
   andmoment Komfort Dämpfung x-Stützstellen */
   const volatile uint16 ARS_FAC_KL_TRQ_D_AUTO_AI16; /* Description: Faktor Kennlinie Active Return 
   Handmoment Auto Dämpfung */
   const volatile uint16 ARS_FAC_KL_TRQ_D_DYN_AI16; /* Description: Faktor Kennlinie Active Return H
   andmoment Dynamik Dämpfung */
   const volatile uint16 ARS_FAC_KL_TRQ_D_KOM_AI16; /* Description: Faktor Kennlinie Active Return H
   andmoment Komfort Dämpfung */
   const volatile uint16 ARS_FAC_VFZG_AUTO_KLU16[10]; /* Description: Kennlinie Active Return Fahrze
   uggeschwindigkeit Auto */
   const volatile uint16 ARS_FAC_VFZG_DYN_KLU16[10]; /* Description: Kennlinie Active Return Fahrzeu
   ggeschwindigkeit Dynamik */
   const volatile uint16 ARS_FAC_VFZG_KOM_KLU16[10]; /* Description: Kennlinie Active Return Fahrzeu
   ggeschwindigkeit Komfort */
   const volatile uint16 ARS_FAC_VFZG_AUTO_XI16[10]; /* Description: Kennlinie Active Return Fahrzeu
   ggeschwindigkeit Auto X-Stützstellen */
   const volatile uint16 ARS_FAC_VFZG_KOM_XI16[10]; /* Description: Kennlinie Active Return Fahrzeug
   geschwindigkeit Komfort X-Stützstellen */
   const volatile uint16 ARS_FAC_VFZG_DYN_XI16[10]; /* Description: Kennlinie Active Return Fahrzeug
   geschwindigkeit Dynamik X-Stützstellen */
   const volatile uint16 ARS_FAC_KL_VFZG_AUTO_AI16; /* Description: Faktor auf Kennlinie Active Retu
   rn Fahrzeuggeschwindigkeit Auto */
   const volatile uint16 ARS_FAC_KL_VFZG_DYN_AI16; /* Description: Faktor auf Kennlinie Active Retur
   n Fahrzeuggeschwindigkeit Dynamik */
   const volatile uint16 ARS_FAC_KL_VFZG_KOM_AI16; /* Description: Faktor auf Kennlinie Active Retur
   n Fahrzeuggeschwindigkeit Komfort */
   const volatile uint16 ARS_FAC_VFZG_D_AUTO_KLU16[10]; /* Description: Kennlinie Active Return Fahr
   zeuggeschwindigkeit Auto Dämpfung */
   const volatile uint16 ARS_FAC_VFZG_D_DYN_KLU16[10]; /* Description: Kennlinie Active Return Fahrz
   euggeschwindigkeit Dynamik Dämpfung */
   const volatile uint16 ARS_FAC_VFZG_D_KOM_KLU16[10]; /* Description: Kennlinie Active Return Fahrz
   euggeschwindigkeit Komfort Dämpfung */
   const volatile uint16 ARS_FAC_VFZG_D_AUTO_XI16[10]; /* Description: Kennlinie Active Return Fahrz
   euggeschwindigkeit Auto X-Stützstellen */
   const volatile uint16 ARS_FAC_VFZG_D_DYN_XI16[10]; /* Description: Kennlinie Active Return Fahrze
   uggeschwindigkeit Dynamik X-Stützstellen */
   const volatile uint16 ARS_FAC_VFZG_D_KOM_XI16[10]; /* Description: Kennlinie Active Return Fahrze
   uggeschwindigkeit Komfort X-Stützstellen */
   const volatile uint16 ARS_FAC_KL_VFZG_D_AUTO_AI16; /* Description: Faktor auf Kennlinie Active Re
   turn Fahrzeuggeschwindigkeit Auto Dämpfung */
   const volatile uint16 ARS_FAC_KL_VFZG_D_DYN_AI16; /* Description: Faktor auf Kennlinie Active Ret
   urn Fahrzeuggeschwindigkeit Dynamik Dämpfung */
   const volatile uint16 ARS_FAC_KL_VFZG_D_KOM_AI16; /* Description: Faktor auf Kennlinie Active Ret
   urn Fahrzeuggeschwindigkeit Komfort Dämpfung */
   const volatile uint16 ARS_PHV_RITZEL_AUTO_KLU16[14]; /* Description: Kennlinie Active Return Soll
   rücklaufgeschwindigkeit Auto */
   const volatile uint16 ARS_PHV_RITZEL_DYN_KLU16[14]; /* Description: Kennlinie Active Return Sollr
   ücklaufgeschwindigkeit Dynamik */
   const volatile uint16 ARS_PHV_RITZEL_KOM_KLU16[14]; /* Description: Kennlinie Active Return Sollr
   ücklaufgeschwindigkeit Komfort */
   const volatile uint16 ARS_PHV_RITZEL_AUTO_XI16[14]; /* Description: Kennlinie Active Return Sollr
   ücklaufgeschwindigkeit Auto X-Stützstellen */
   const volatile uint16 ARS_PHV_RITZEL_DYN_XI16[14]; /* Description: Kennlinie Active Return Sollrü
   cklaufgeschwindigkeit Dynamik X-Stützstellen */
   const volatile uint16 ARS_PHV_RITZEL_KOM_XI16[14]; /* Description: Kennlinie Active Return Sollrü
   cklaufgeschwindigkeit Komfort X-Stützstellen */
   const volatile uint16 ARS_FAC_KL_PHV_AUTO_AI16; /* Description: Faktor auf Kennlinie Active Retur
   n Sollrücklaufgeschwindigkeit Auto */
   const volatile uint16 ARS_FAC_KL_PHV_DYN_AI16; /* Description: Faktor auf Kennlinie Active Return
    Sollrücklaufgeschwindigkeit Dynamik */
   const volatile uint16 ARS_FAC_KL_PHV_KOM_AI16; /* Description: Faktor auf Kennlinie Active Return
    Sollrücklaufgeschwindigkeit Komfort */
   const volatile uint16 ARS_FAC_ARS_AI16; /* Description: Faktor Verstärkung Active Return */
   const volatile uint8 TSC_SWS_AKTIV_AU08; /* Description: TSC aktivieren (geodert mit Codierung, m
   uss 0 sein, um die Aktivierung der Funktion per Codierung zu ermöglichen) */
   const volatile uint8 TSC_STLERN_AU08; /* Description: Lerner aktivieren (1=Aktiv, 0=Festwert) */
   const volatile uint16 TSC_GRAD_POS_AU16; /* Description: Maximaler positiver Ausgangsgradient TSC
    Kompensationskraft (wenn Gradientbegrenzung anstatt Filter benutzt, TSC_SEL_FILTER=0) */
   const volatile uint16 TSC_GRAD_NEG_AU16; /* Description: Maximaler negativer Ausgangsgradient TSC
    Kompensationskraft (wenn Gradientbegrenzung anstatt Filter benutzt, TSC_SEL_FILTER=0) */
   const volatile uint8 TSC_SWS_XPP_AU08; /* Description: Auswahl Berechnung Laengsbeschleunigung (1
   =Raddrehzahl, 0=ESC) */
   const volatile uint8 TSC_SEL_FANTRIEB_GEW_MO_XPP_AU08; /* Description: Quelle FANTRIEB (3=Gew, 2=
   Mo, 1=XPP) */
   const volatile uint16 TSC_FILT_OUT_AU16; /* Description: Zeitkonstante Ausgangsfilter Kompensatio
   nskraft (wenn Filter anstat Gradientbegrenzung benutzt, TSC_SEL_FILTER=1) */
   const volatile uint16 TSC_FILT_IFZG_AU16; /* Description: Filterzeitkonstante Fahrzeugübersetzung
    (mög. Leiche) */
   const volatile uint16 TSC_FILT_FLKU_AU16; /* Description: Filterzeitkonstante Unterstützungskraft
    */
   const volatile uint16 TSC_FILT_FANTRIEB_AU16; /* Description: Filterzeitkonstante Antriebskraft (
   in Berechnung_Ausgang) */
   const volatile uint16 TSC_FILT_IMOTORA_AU16; /* Description: Zeitkonstante Filter A Motorübersetz
   ung (zur Berechnung Änderungsrate Motorübersetzung) */
   const volatile uint16 TSC_FILT_IMOTORB_AU16; /* Description: Zeitkonstante Filter B Motorübersetz
   ung (zur Berechnung Änderungsrate Motorübersetzung) */
   const volatile uint8 TSC_SEL_FILTER_AU08; /* Description: Auswahl Ausgangsfilter (1=PT1, 0=Gradie
   ntebegrenzung) */
   const volatile uint8 TSC_ACTIV_LERN_AU08; /* Description: TSC aktivieren (falscher Variablenname,
    hat nichts mit dem Lerner zu tun) */
   const volatile sint16 TSC_GRAD_FEST_AI16; /* Description: Fester Lernwert (bei deaktivierung des 
   Lerners) */
   const volatile uint16 TSC_FAC_FANTRIEB_KLU16[5]; /* Description: Kennlinie Korrekturfaktor der Ko
   mpensationskraft nach Antriebskraft */
   const volatile uint16 TSC_FAC_FANTRIEB_XI16[5]; /* Description: Kennlinie Korrekturfaktor der Kom
   pensationskraft nach Antriebskraft X-Werte */
   const volatile sint16 TSC_F_KORVFZG_KLU16[5]; /* Description: Kennlinie Offset Kompensationskraft
    nach vFzg */
   const volatile uint16 TSC_F_KORVFZG_XI16[5]; /* Description: Kennlinie Offset Kompensationskraft 
   nach vFzg X-Stützstellen */
   const volatile uint16 TSC_FAC_KORPHI_KLU16[5]; /* Description: Kennlinie Korrekturfaktor der Komp
   ensationskraft nach Lenkwinkel */
   const volatile uint16 TSC_FAC_KORPHI_XI16[5]; /* Description: Kennlinie Korrekturfaktor der Kompe
   nsationskraft nach Lenkwinkel X-Stützstellen */
   const volatile uint16 TSC_FAC_KORVFZG_KLU16[5]; /* Description: Kennlinie Korrekturfaktor der Kom
   pensationskraft nach vFzg */
   const volatile uint16 TSC_FAC_KORVFZG_XI16[5]; /* Description: Kennlinie Korrekturfaktor der Komp
   ensationskraft nach vFzg X-Stützstellen */
   const volatile uint16 TSC_FAC_MMOTOR_AU16; /* Description: Faktor Antriebsmoment (zum Korrigieren
    von skalierten Werten im CAN) */
   const volatile uint16 TSC_MAX_ANTRIEB_AU16; /* Description: Obere Begrenzung der maximale Antrieb
   skraft (unabhängig von ihrer Quelle) */
   const volatile uint16 TSC_FZG_MASSE_AU16; /* Description: Fahrzeugmasse */
   const volatile uint16 TSC_FANTRIEB_AB_KOM_AU16; /* Description: Schwelle Antriebsmoment EIN (mög.
    Leiche) */
   const volatile sint16 TSC_XPP_AB_KLU16[4]; /* Description: Kennlinie Kompensationsbedingung minim
   ale Längsbeschleunigungs (Fahrgeschwindigkeit abhängig) */
   const volatile uint16 TSC_XPP_AB_XU16[4]; /* Description: Kennlinie Kompensationsbedingung minima
   le Längsbeschleunigungs (Fahrgeschwindigkeit abhängig) X-Werte */
   const volatile uint8 TSC_PED_AB_KOM_AU8; /* Description: Kompensationsbedingung minimaler Gaspeda
   lwert */
   const volatile uint16 TSC_PBREMS_AB_KOM_AU16; /* Description: Kompensationsbedingung maximaler Br
   emsdruck */
   const volatile uint8 TSC_ESC_COD_AU08; /* Description: Codierung ESC manuell setzen */
   const volatile uint32 GER_FAC_LERN_L_AU32; /* Description: Geradeauslaufkorrektur Lernfaktor Lang
   zeit */
   const volatile uint32 GER_FAC_LERN_K_AU32; /* Description: Geradeauslaufkorrektur Lernfaktor Kurz
   zeit */
   const volatile uint8 GER_SWS_AKTIV_AU08; /* Description: Geradelauf aktivieren */
   const volatile uint8 BEL_SWS_AKTIV_AU08; /* Description: Belastungserfassung aktivieren */
   const volatile uint16 QPR_CNT_TEST_DURATION_AU16; /* Description: QPR-ReglerTest - Testdauer [tic
   ks] */
   const volatile uint8 QPR_ST_TEST_TRIGGER_VZST_AU8; /* Description: QPR-ReglerTest - Trigger fuer 
   Testfunktion [-] */
   const volatile sint16 QPR_VZST_TEST_SOLL_AI16; /* Description: QPR-ReglerTest - Sollzahnstangenge
   schwindigkeit der Testfunktion [mm/s] */
   const volatile uint16 QUA_FAC_TEST_FRQ_AU16; /* Description: QUA-Test - Aktualisierungsrate der T
   estanregung [1/tick] */
   const volatile uint16 QUA_FAC_TEST_HAPTIK_AU16; /* Description: QUA-Test - Haptikfaktor waehrend 
   der Testanregung [%] */
   const volatile uint16 QUA_FAC_TEST_SIG1A_AU16; /* Description: QUA-Test - Anregung eines Signals,
    welches aequivalent zu can_facSignal1FasXX_mu16 ist  */
   const volatile uint16 QUA_FAC_TEST_SIG2_AU16; /* Description: QUA-Test - Anregung eines Signals, 
   welches aequivalent zu can_facSignal2FasXX_mu16 ist */
   const volatile uint8 QUA_ST_FRQPOSSOLL_TEST_AU8; /* Description: QUA-SigRouting - Auswahl der Bot
   schafts-Zykluszeit fuer Testfunktion */
   const volatile uint8 QUA_ST_TEST_AKTIV_FAS_IDX_AU8; /* Description: QUA-Test - Ueberschreib die F
   AS-Auswahl durch QAP (255 == Vorgabe erfolgt durch QAP) */
   const volatile uint8 QUA_ST_TEST_ART1_AU8; /* Description: QUA-Test - Anregung eines Signals, wel
   ches aequivalent zu can_stArt1FasXX_mu8 ist */
   const volatile uint8 QUA_ST_TEST_ART2_AU8; /* Description: QUA-Test - Anregung eines Signals, wel
   ches aequivalent zu can_stArt2FasXX_mu8 ist */
   const volatile uint16 QUA_VZST_TEST_GRDB_AU16; /* Description: QUA-Test - Zahnstangengeschwindigk
   eit der Testanregung bei Aenderungen der Sollposition [mm/s] */
   const volatile sint16 QUA_XZST_TEST_SOLL_AI16; /* Description: QUA-Test - Zahnstangensollposition
    fuer Testanregung[mm] */
}; /* Description: struct type created for variable: VEH_Struct */

/*------------------------------------------------------------------------------------------------*\
  VARIABLES
\*------------------------------------------------------------------------------------------------*/

#ifndef USE_CST_PARAM_STRUCT_H
/**************************************************************************************************\
   MERGEABLE_CAL: mergeable calibratable parameters (ROM) | Width: N.A.
\**************************************************************************************************/
extern MERGEABLE_CAL struct tag_VEH_Struct VEH_Struct;
#endif /*USE_CST_PARAM_STRUCT_H*/

/*------------------------------------------------------------------------------------------------*\
  PARAMETERIZED MACROS
\*------------------------------------------------------------------------------------------------*/
/*------------------------------------------------------------------------------------------------*\
  FUNCTION PROTOTYPES
\*------------------------------------------------------------------------------------------------*/
#ifdef __cplusplus
}
#endif

#endif /* ZPC_VEH_H */
/*------------------------------------------------------------------------------------------------*\
  END OF FILE
\*------------------------------------------------------------------------------------------------*/
