#
#
#
#
#
#
#
#
#                            RBEI
#                     All rights reserved
#                     Team HEXMODX
#               HEXMODX
#               needed for HEXMODX
#  Author:            RBEI/ETB4
#  Purpose:     Contains a list of tools including versions
###############################################################################
###############################################################################
###############################################################################
java_jre=1.8.0_275_64
