/** @file     Rte_ASC_SWC.h
  *
  * @brief    Application header file
  *
  * @note     AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
  *
  * @note     Generated by ETAS RTA-RTE
  * @note     Version 7.3.0 
  */

#ifndef RTE_ASC_SWC_H
#define RTE_ASC_SWC_H

#ifndef RTE_CORE
#ifdef RTE_APPLICATION_HEADER_FILE
#error Multiple application header files included.
#endif /* RTE_APPLICATION_HEADER_FILE */
#define RTE_APPLICATION_HEADER_FILE
#endif /* RTE_CORE */

/*******************************************************
 ***
 *** Includes
 ***
 *******************************************************/

#include "Rte.h"
#include "Rte_Intl.h"
#include "Rte_ASC_SWC_Type.h"

#include "Rte_DataHandleType.h"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#if defined(RTE_RUNNABLEAPI_ASC_Controller)
   /* Do nothing for this and all elif clauses below (rte_sws_2751) */
#elif defined(RTE_RUNNABLEAPI_ASC_Init)
#else
   /* None of above defined so define value including all APIs (rte_sws_2751) */
   #define RTE_PRV_ALL_API
#endif

/*******************************************************
 ***
 *** Constants
 ***
 *******************************************************/


/*******************************************************
 ***
 *** Public Types
 ***
 *******************************************************/

/* BEGIN: SWC types (core visible) */
struct Rte_CDS_ASC_SWC {
   /* Data handles */
   P2VAR(Rte_DE_IDT_ASC_Interface_asc_StartStopp_Info_mu8       , AUTOMATIC, RTE_DATA) ASC_Controller_Provided_ASC_asc_StartStopp_Info_mu8;
   P2VAR(Rte_DE_IDT_ASC_Interface_asc_can_strDevMsgTx1_mu32     , AUTOMATIC, RTE_DATA) ASC_Controller_Provided_ASC_asc_can_strDevMsgTx1_mu32;
   P2VAR(Rte_DE_IDT_ASC_Interface_asc_can_strDevMsgTx2_mu32     , AUTOMATIC, RTE_DATA) ASC_Controller_Provided_ASC_asc_can_strDevMsgTx2_mu32;
   P2VAR(Rte_DE_IDT_ASC_Interface_asc_epsWarn_mu8               , AUTOMATIC, RTE_DATA) ASC_Controller_Provided_ASC_asc_epsWarn_mu8;
   P2VAR(Rte_DE_IDT_ASC_Interface_asc_fSoll_mi16                , AUTOMATIC, RTE_DATA) ASC_Controller_Provided_ASC_asc_fSoll_mi16;
   P2VAR(Rte_DE_IDT_ASC_Interface_asc_facReduzlku_mu16          , AUTOMATIC, RTE_DATA) ASC_Controller_Provided_ASC_asc_facReduzlku_mu16;
   P2VAR(Rte_DE_IDT_ASC_Interface_asc_facReduztrq_mu16          , AUTOMATIC, RTE_DATA) ASC_Controller_Provided_ASC_asc_facReduztrq_mu16;
   P2VAR(Rte_DE_IDT_ASC_Interface_asc_ger_phiK_mi16             , AUTOMATIC, RTE_DATA) ASC_Controller_Provided_ASC_asc_ger_phiK_mi16;
   P2VAR(Rte_DE_IDT_ASC_Interface_asc_ger_phiL_mi16             , AUTOMATIC, RTE_DATA) ASC_Controller_Provided_ASC_asc_ger_phiL_mi16;
   P2VAR(Rte_DE_IDT_ASC_Interface_asc_ger_stLernK_mu8           , AUTOMATIC, RTE_DATA) ASC_Controller_Provided_ASC_asc_ger_stLernK_mu8;
   P2VAR(Rte_DE_IDT_ASC_Interface_asc_ger_stLernL_mu8           , AUTOMATIC, RTE_DATA) ASC_Controller_Provided_ASC_asc_ger_stLernL_mu8;
   P2VAR(Rte_DE_IDT_ASC_Interface_asc_mst_startBed_mu8          , AUTOMATIC, RTE_DATA) ASC_Controller_Provided_ASC_asc_mst_startBed_mu8;
   P2VAR(Rte_DE_IDT_ASC_Interface_asc_stASC_mu32                , AUTOMATIC, RTE_DATA) ASC_Controller_Provided_ASC_asc_stASC_mu32;
   P2VAR(Rte_DE_IDT_ASC_Interface_asc_stDsaTsc2Qfk_mu16         , AUTOMATIC, RTE_DATA) ASC_Controller_Provided_ASC_asc_stDsaTsc2Qfk_mu16;
   P2VAR(Rte_DE_IDT_ASC_Interface_asc_trqOffset_mi16            , AUTOMATIC, RTE_DATA) ASC_Controller_Provided_ASC_asc_trqOffset_mi16;
   P2VAR(Rte_DE_IDT_ASC_Interface_asc_tsc_fSoll_mi16            , AUTOMATIC, RTE_DATA) ASC_Controller_Provided_ASC_asc_tsc_fSoll_mi16;
   P2VAR(Rte_DE_IDT_ASC_Interface_asc_tsc_facLern_mu16          , AUTOMATIC, RTE_DATA) ASC_Controller_Provided_ASC_asc_tsc_facLern_mu16;
   P2VAR(Rte_DE_IDT_ASC_Interface_asc_tsc_stLerrn_mu8           , AUTOMATIC, RTE_DATA) ASC_Controller_Provided_ASC_asc_tsc_stLerrn_mu8;
   P2VAR(Rte_DE_IDT_ASC_BSW_Interface_bsw_iBat_mi16             , AUTOMATIC, RTE_DATA) ASC_Controller_Required_BSW_bsw_iBat_mi16;
   P2VAR(Rte_DE_IDT_ASC_BSW_Interface_bsw_levelAssist_mu8       , AUTOMATIC, RTE_DATA) ASC_Controller_Required_BSW_bsw_levelAssist_mu8;
   P2VAR(Rte_DE_IDT_ASC_BSW_Interface_bsw_lku_fSoll_mi16        , AUTOMATIC, RTE_DATA) ASC_Controller_Required_BSW_bsw_lku_fSoll_mi16;
   P2VAR(Rte_DE_IDT_ASC_BSW_Interface_bsw_mskStatusbits01_mu32  , AUTOMATIC, RTE_DATA) ASC_Controller_Required_BSW_bsw_mskStatusbits01_mu32;
   P2VAR(Rte_DE_IDT_ASC_BSW_Interface_bsw_mskStatusbits02_mu32  , AUTOMATIC, RTE_DATA) ASC_Controller_Required_BSW_bsw_mskStatusbits02_mu32;
   P2VAR(Rte_DE_IDT_ASC_BSW_Interface_bsw_phiRitzelMotor_mi16   , AUTOMATIC, RTE_DATA) ASC_Controller_Required_BSW_bsw_phiRitzelMotor_mi16;
   P2VAR(Rte_DE_IDT_ASC_BSW_Interface_bsw_phiRitzel_mi32        , AUTOMATIC, RTE_DATA) ASC_Controller_Required_BSW_bsw_phiRitzel_mi32;
   P2VAR(Rte_DE_IDT_ASC_BSW_Interface_bsw_phvRitzel_mi16        , AUTOMATIC, RTE_DATA) ASC_Controller_Required_BSW_bsw_phvRitzel_mi16;
   P2VAR(Rte_DE_IDT_ASC_BSW_Interface_bsw_stDiagnose_mu32       , AUTOMATIC, RTE_DATA) ASC_Controller_Required_BSW_bsw_stDiagnose_mu32;
   P2VAR(Rte_DE_IDT_ASC_BSW_Interface_bsw_stSAC_mu32            , AUTOMATIC, RTE_DATA) ASC_Controller_Required_BSW_bsw_stSAC_mu32;
   P2VAR(Rte_DE_IDT_ASC_BSW_Interface_bsw_stTac_mu32            , AUTOMATIC, RTE_DATA) ASC_Controller_Required_BSW_bsw_stTac_mu32;
   P2VAR(Rte_DE_IDT_ASC_BSW_Interface_bsw_tZahnstange_mi16      , AUTOMATIC, RTE_DATA) ASC_Controller_Required_BSW_bsw_tZahnstange_mi16;
   P2VAR(Rte_DE_IDT_ASC_BSW_Interface_bsw_tempEcu_mi16          , AUTOMATIC, RTE_DATA) ASC_Controller_Required_BSW_bsw_tempEcu_mi16;
   P2VAR(Rte_DE_IDT_ASC_BSW_Interface_bsw_trqIst_mi16           , AUTOMATIC, RTE_DATA) ASC_Controller_Required_BSW_bsw_trqIst_mi16;
   P2VAR(Rte_DE_IDT_ASC_BSW_Interface_bsw_trqSensorKomp_mi16    , AUTOMATIC, RTE_DATA) ASC_Controller_Required_BSW_bsw_trqSensorKomp_mi16;
   P2VAR(Rte_DE_IDT_ASC_BSW_Interface_bsw_trqSensor_mi16        , AUTOMATIC, RTE_DATA) ASC_Controller_Required_BSW_bsw_trqSensor_mi16;
   P2VAR(Rte_DE_IDT_ASC_BSW_Interface_bsw_trqSoll_mi16          , AUTOMATIC, RTE_DATA) ASC_Controller_Required_BSW_bsw_trqSoll_mi16;
   P2VAR(Rte_DE_IDT_ASC_BSW_Interface_bsw_uBat_mu16             , AUTOMATIC, RTE_DATA) ASC_Controller_Required_BSW_bsw_uBat_mu16;
   P2VAR(Rte_DE_IDT_ASC_BSW_Interface_can_beschlLaengs_mi16     , AUTOMATIC, RTE_DATA) ASC_Controller_Required_BSW_can_beschlLaengs_mi16;
   P2VAR(Rte_DE_IDT_ASC_BSW_Interface_can_beschlQuer_mi16       , AUTOMATIC, RTE_DATA) ASC_Controller_Required_BSW_can_beschlQuer_mi16;
   P2VAR(Rte_DE_IDT_ASC_BSW_Interface_can_facTrqWheel_mu8       , AUTOMATIC, RTE_DATA) ASC_Controller_Required_BSW_can_facTrqWheel_mu8;
   P2VAR(Rte_DE_IDT_ASC_BSW_Interface_can_gierrate_mi16         , AUTOMATIC, RTE_DATA) ASC_Controller_Required_BSW_can_gierrate_mi16;
   P2VAR(Rte_DE_IDT_ASC_BSW_Interface_can_gradUeb_mi8           , AUTOMATIC, RTE_DATA) ASC_Controller_Required_BSW_can_gradUeb_mi8;
   P2VAR(Rte_DE_IDT_ASC_BSW_Interface_can_imp_HL_mu16           , AUTOMATIC, RTE_DATA) ASC_Controller_Required_BSW_can_imp_HL_mu16;
   P2VAR(Rte_DE_IDT_ASC_BSW_Interface_can_imp_HR_mu16           , AUTOMATIC, RTE_DATA) ASC_Controller_Required_BSW_can_imp_HR_mu16;
   P2VAR(Rte_DE_IDT_ASC_BSW_Interface_can_levelPedal_mu8        , AUTOMATIC, RTE_DATA) ASC_Controller_Required_BSW_can_levelPedal_mu8;
   P2VAR(Rte_DE_IDT_ASC_BSW_Interface_can_pBrems_mi16           , AUTOMATIC, RTE_DATA) ASC_Controller_Required_BSW_can_pBrems_mi16;
   P2VAR(Rte_DE_IDT_ASC_BSW_Interface_can_rpmMotor_mu16         , AUTOMATIC, RTE_DATA) ASC_Controller_Required_BSW_can_rpmMotor_mu16;
   P2VAR(Rte_DE_IDT_ASC_BSW_Interface_can_stESP14_mu8           , AUTOMATIC, RTE_DATA) ASC_Controller_Required_BSW_can_stESP14_mu8;
   P2VAR(Rte_DE_IDT_ASC_BSW_Interface_can_stFahrbereitschaft_mu8, AUTOMATIC, RTE_DATA) ASC_Controller_Required_BSW_can_stFahrbereitschaft_mu8;
   P2VAR(Rte_DE_IDT_ASC_BSW_Interface_can_stLaufleistung_mu32   , AUTOMATIC, RTE_DATA) ASC_Controller_Required_BSW_can_stLaufleistung_mu32;
   P2VAR(Rte_DE_IDT_ASC_BSW_Interface_can_stMO14_mu8            , AUTOMATIC, RTE_DATA) ASC_Controller_Required_BSW_can_stMO14_mu8;
   P2VAR(Rte_DE_IDT_ASC_BSW_Interface_can_stSignale01_mu32      , AUTOMATIC, RTE_DATA) ASC_Controller_Required_BSW_can_stSignale01_mu32;
   P2VAR(Rte_DE_IDT_ASC_BSW_Interface_can_stSignale02_mu32      , AUTOMATIC, RTE_DATA) ASC_Controller_Required_BSW_can_stSignale02_mu32;
   P2VAR(Rte_DE_IDT_ASC_BSW_Interface_can_stTrqWheel_mu8        , AUTOMATIC, RTE_DATA) ASC_Controller_Required_BSW_can_stTrqWheel_mu8;
   P2VAR(Rte_DE_IDT_ASC_BSW_Interface_can_strDevMsgRx1_mu32     , AUTOMATIC, RTE_DATA) ASC_Controller_Required_BSW_can_strDevMsgRx1_mu32;
   P2VAR(Rte_DE_IDT_ASC_BSW_Interface_can_strDevMsgRx2_mu32     , AUTOMATIC, RTE_DATA) ASC_Controller_Required_BSW_can_strDevMsgRx2_mu32;
   P2VAR(Rte_DE_IDT_ASC_BSW_Interface_can_tragMo_mi16           , AUTOMATIC, RTE_DATA) ASC_Controller_Required_BSW_can_tragMo_mi16;
   P2VAR(Rte_DE_IDT_ASC_BSW_Interface_can_trqAllrad_mu8         , AUTOMATIC, RTE_DATA) ASC_Controller_Required_BSW_can_trqAllrad_mu8;
   P2VAR(Rte_DE_IDT_ASC_BSW_Interface_can_trqMoIst_mi16         , AUTOMATIC, RTE_DATA) ASC_Controller_Required_BSW_can_trqMoIst_mi16;
   P2VAR(Rte_DE_IDT_ASC_BSW_Interface_can_trqMoSchub_mi16       , AUTOMATIC, RTE_DATA) ASC_Controller_Required_BSW_can_trqMoSchub_mi16;
   P2VAR(Rte_DE_IDT_ASC_BSW_Interface_can_trqMoSollRoh_mi16     , AUTOMATIC, RTE_DATA) ASC_Controller_Required_BSW_can_trqMoSollRoh_mi16;
   P2VAR(Rte_DE_IDT_ASC_BSW_Interface_can_trqWheelActSec_mi16   , AUTOMATIC, RTE_DATA) ASC_Controller_Required_BSW_can_trqWheelActSec_mi16;
   P2VAR(Rte_DE_IDT_ASC_BSW_Interface_can_trqWheelAct_mi16      , AUTOMATIC, RTE_DATA) ASC_Controller_Required_BSW_can_trqWheelAct_mi16;
   P2VAR(Rte_DE_IDT_ASC_BSW_Interface_can_vRad_HL_mi16          , AUTOMATIC, RTE_DATA) ASC_Controller_Required_BSW_can_vRad_HL_mi16;
   P2VAR(Rte_DE_IDT_ASC_BSW_Interface_can_vRad_HR_mi16          , AUTOMATIC, RTE_DATA) ASC_Controller_Required_BSW_can_vRad_HR_mi16;
   P2VAR(Rte_DE_IDT_ASC_BSW_Interface_can_vRad_VL_mi16          , AUTOMATIC, RTE_DATA) ASC_Controller_Required_BSW_can_vRad_VL_mi16;
   P2VAR(Rte_DE_IDT_ASC_BSW_Interface_can_vRad_VR_mi16          , AUTOMATIC, RTE_DATA) ASC_Controller_Required_BSW_can_vRad_VR_mi16;
   P2VAR(Rte_DE_IDT_ASC_BSW_Interface_can_vSignal_mu16          , AUTOMATIC, RTE_DATA) ASC_Controller_Required_BSW_can_vSignal_mu16;
   P2VAR(Rte_DE_IDT_ASC_BSW_Interface_can_vaqIst_mu8            , AUTOMATIC, RTE_DATA) ASC_Controller_Required_BSW_can_vaqIst_mu8;
   P2VAR(Rte_DE_IDT_ASC_BSW_Interface_cha_facAuto_mu16          , AUTOMATIC, RTE_DATA) ASC_Controller_Required_BSW_cha_facAuto_mu16;
   P2VAR(Rte_DE_IDT_ASC_BSW_Interface_cha_facDyn_mu16           , AUTOMATIC, RTE_DATA) ASC_Controller_Required_BSW_cha_facDyn_mu16;
   P2VAR(Rte_DE_IDT_ASC_BSW_Interface_cha_facEvent_mu16         , AUTOMATIC, RTE_DATA) ASC_Controller_Required_BSW_cha_facEvent_mu16;
   P2VAR(Rte_DE_IDT_ASC_BSW_Interface_cha_facKom_mu16           , AUTOMATIC, RTE_DATA) ASC_Controller_Required_BSW_cha_facKom_mu16;
   P2VAR(Rte_DE_IDT_ASC_BSW_Interface_dia_mskAnpassung01_mu32   , AUTOMATIC, RTE_DATA) ASC_Controller_Required_BSW_dia_mskAnpassung01_mu32;
   P2VAR(Rte_DE_IDT_ASC_BSW_Interface_dia_mskCodierung01_mu32   , AUTOMATIC, RTE_DATA) ASC_Controller_Required_BSW_dia_mskCodierung01_mu32;
   P2VAR(Rte_DE_IDT_ASC_BSW_Interface_fga_mskStVFzg_mu8         , AUTOMATIC, RTE_DATA) ASC_Controller_Required_BSW_fga_mskStVFzg_mu8;
   P2VAR(Rte_DE_IDT_ASC_BSW_Interface_fga_vFzg_mi16             , AUTOMATIC, RTE_DATA) ASC_Controller_Required_BSW_fga_vFzg_mi16;
   P2VAR(Rte_DE_IDT_ASC_BSW_Interface_hca_stHCA_mu8             , AUTOMATIC, RTE_DATA) ASC_Controller_Required_BSW_hca_stHCA_mu8;
   P2VAR(Rte_DE_IDT_ASC_BSW_Interface_qap_stPrioToTnDsaTsc_mu8  , AUTOMATIC, RTE_DATA) ASC_Controller_Required_BSW_qap_stPrioToTnDsaTsc_mu8;
};
typedef struct Rte_CDS_ASC_SWC Rte_CDS_ASC_SWC;
/* END: SWC types (core visible) */

/*******************************************************
 ***
 *** Private Types
 ***
 *******************************************************/

/* BEGIN: SWC types (private) */
/* END: SWC types (private) */

/*******************************************************
 ***
 *** Instance Declarations
 ***
 *******************************************************/

#define RTE_START_SEC_CONST_UNSPECIFIED
#include "Rte_MemMap.h"
extern CONST(struct Rte_CDS_ASC_SWC, RTE_CONST) Rte_Inst_ASC_SWC;
#define RTE_STOP_SEC_CONST_UNSPECIFIED
#include "Rte_MemMap.h"


#ifndef RTE_CORE
typedef CONSTP2CONST(struct Rte_CDS_ASC_SWC, AUTOMATIC, RTE_CONST) Rte_Instance;
#endif /* RTE_CORE */

/*******************************************************
 ***
 *** API Mapping macros
 ***
 *******************************************************/

/* API Mapping Macros */
#ifndef RTE_CORE
#define RTE_START_SEC_VAR_IMPLICITSR_TASKOEM1_1MS
#include "Rte_MemMap.h"
extern VAR(Rte_TDB_TaskOem1_1ms, RTE_DATA) Rte_ImplicitBufs_TaskOem1_1ms;
#define RTE_STOP_SEC_VAR_IMPLICITSR_TASKOEM1_1MS
#include "Rte_MemMap.h"
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_ASC_Controller)
/* Inline read optimization; Rte_IRead_ASC_Controller_Required_BSW_bsw_iBat_mi16 to implicit access macro */
#define Rte_IRead_ASC_Controller_Required_BSW_bsw_iBat_mi16()  ( (CONST(IDT_ASC_BSW_Interface_bsw_iBat_mi16, RTE_DATA)) Rte_ImplicitBufs_TaskOem1_1ms.sbuf60.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_ASC_Controller)
/* Inline read optimization; Rte_IRead_ASC_Controller_Required_BSW_bsw_levelAssist_mu8 to implicit access macro */
#define Rte_IRead_ASC_Controller_Required_BSW_bsw_levelAssist_mu8()  ( (CONST(IDT_ASC_BSW_Interface_bsw_levelAssist_mu8, RTE_DATA)) Rte_ImplicitBufs_TaskOem1_1ms.sbuf61.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_ASC_Controller)
/* Inline read optimization; Rte_IRead_ASC_Controller_Required_BSW_bsw_lku_fSoll_mi16 to implicit access macro */
#define Rte_IRead_ASC_Controller_Required_BSW_bsw_lku_fSoll_mi16()  ( (CONST(IDT_ASC_BSW_Interface_bsw_lku_fSoll_mi16, RTE_DATA)) Rte_ImplicitBufs_TaskOem1_1ms.sbuf62.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_ASC_Controller)
/* Inline read optimization; Rte_IRead_ASC_Controller_Required_BSW_bsw_mskStatusbits01_mu32 to implicit access macro */
#define Rte_IRead_ASC_Controller_Required_BSW_bsw_mskStatusbits01_mu32()  ( (CONST(IDT_ASC_BSW_Interface_bsw_mskStatusbits01_mu32, RTE_DATA)) Rte_ImplicitBufs_TaskOem1_1ms.sbuf63.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_ASC_Controller)
/* Inline read optimization; Rte_IRead_ASC_Controller_Required_BSW_bsw_mskStatusbits02_mu32 to implicit access macro */
#define Rte_IRead_ASC_Controller_Required_BSW_bsw_mskStatusbits02_mu32()  ( (CONST(IDT_ASC_BSW_Interface_bsw_mskStatusbits02_mu32, RTE_DATA)) Rte_ImplicitBufs_TaskOem1_1ms.sbuf18.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_ASC_Controller)
/* Inline read optimization; Rte_IRead_ASC_Controller_Required_BSW_bsw_phiRitzelMotor_mi16 to implicit access macro */
#define Rte_IRead_ASC_Controller_Required_BSW_bsw_phiRitzelMotor_mi16()  ( (CONST(IDT_ASC_BSW_Interface_bsw_phiRitzelMotor_mi16, RTE_DATA)) Rte_ImplicitBufs_TaskOem1_1ms.sbuf64.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_ASC_Controller)
/* Inline read optimization; Rte_IRead_ASC_Controller_Required_BSW_bsw_phiRitzel_mi32 to implicit access macro */
#define Rte_IRead_ASC_Controller_Required_BSW_bsw_phiRitzel_mi32()  ( (CONST(IDT_ASC_BSW_Interface_bsw_phiRitzel_mi32, RTE_DATA)) Rte_ImplicitBufs_TaskOem1_1ms.sbuf65.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_ASC_Controller)
/* Inline read optimization; Rte_IRead_ASC_Controller_Required_BSW_bsw_phvRitzel_mi16 to implicit access macro */
#define Rte_IRead_ASC_Controller_Required_BSW_bsw_phvRitzel_mi16()  ( (CONST(IDT_ASC_BSW_Interface_bsw_phvRitzel_mi16, RTE_DATA)) Rte_ImplicitBufs_TaskOem1_1ms.sbuf66.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_ASC_Controller)
/* Inline read optimization; Rte_IRead_ASC_Controller_Required_BSW_bsw_stDiagnose_mu32 to implicit access macro */
#define Rte_IRead_ASC_Controller_Required_BSW_bsw_stDiagnose_mu32()  ( (CONST(IDT_ASC_BSW_Interface_bsw_stDiagnose_mu32, RTE_DATA)) Rte_ImplicitBufs_TaskOem1_1ms.sbuf19.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_ASC_Controller)
/* Inline read optimization; Rte_IRead_ASC_Controller_Required_BSW_bsw_stSAC_mu32 to implicit access macro */
#define Rte_IRead_ASC_Controller_Required_BSW_bsw_stSAC_mu32()  ( (CONST(IDT_ASC_BSW_Interface_bsw_stSAC_mu32, RTE_DATA)) Rte_ImplicitBufs_TaskOem1_1ms.sbuf67.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_ASC_Controller)
/* Inline read optimization; Rte_IRead_ASC_Controller_Required_BSW_bsw_stTac_mu32 to implicit access macro */
#define Rte_IRead_ASC_Controller_Required_BSW_bsw_stTac_mu32()  ( (CONST(IDT_ASC_BSW_Interface_bsw_stTac_mu32, RTE_DATA)) Rte_ImplicitBufs_TaskOem1_1ms.sbuf68.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_ASC_Controller)
/* Inline read optimization; Rte_IRead_ASC_Controller_Required_BSW_bsw_tZahnstange_mi16 to implicit access macro */
#define Rte_IRead_ASC_Controller_Required_BSW_bsw_tZahnstange_mi16()  ( (CONST(IDT_ASC_BSW_Interface_bsw_tZahnstange_mi16, RTE_DATA)) Rte_ImplicitBufs_TaskOem1_1ms.sbuf20.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_ASC_Controller)
/* Inline read optimization; Rte_IRead_ASC_Controller_Required_BSW_bsw_tempEcu_mi16 to implicit access macro */
#define Rte_IRead_ASC_Controller_Required_BSW_bsw_tempEcu_mi16()  ( (CONST(IDT_ASC_BSW_Interface_bsw_tempEcu_mi16, RTE_DATA)) Rte_ImplicitBufs_TaskOem1_1ms.sbuf21.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_ASC_Controller)
/* Inline read optimization; Rte_IRead_ASC_Controller_Required_BSW_bsw_trqIst_mi16 to implicit access macro */
#define Rte_IRead_ASC_Controller_Required_BSW_bsw_trqIst_mi16()  ( (CONST(IDT_ASC_BSW_Interface_bsw_trqIst_mi16, RTE_DATA)) Rte_ImplicitBufs_TaskOem1_1ms.sbuf69.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_ASC_Controller)
/* Inline read optimization; Rte_IRead_ASC_Controller_Required_BSW_bsw_trqSensorKomp_mi16 to implicit access macro */
#define Rte_IRead_ASC_Controller_Required_BSW_bsw_trqSensorKomp_mi16()  ( (CONST(IDT_ASC_BSW_Interface_bsw_trqSensorKomp_mi16, RTE_DATA)) Rte_ImplicitBufs_TaskOem1_1ms.sbuf70.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_ASC_Controller)
/* Inline read optimization; Rte_IRead_ASC_Controller_Required_BSW_bsw_trqSensor_mi16 to implicit access macro */
#define Rte_IRead_ASC_Controller_Required_BSW_bsw_trqSensor_mi16()  ( (CONST(IDT_ASC_BSW_Interface_bsw_trqSensor_mi16, RTE_DATA)) Rte_ImplicitBufs_TaskOem1_1ms.sbuf71.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_ASC_Controller)
/* Inline read optimization; Rte_IRead_ASC_Controller_Required_BSW_bsw_trqSoll_mi16 to implicit access macro */
#define Rte_IRead_ASC_Controller_Required_BSW_bsw_trqSoll_mi16()  ( (CONST(IDT_ASC_BSW_Interface_bsw_trqSoll_mi16, RTE_DATA)) Rte_ImplicitBufs_TaskOem1_1ms.sbuf72.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_ASC_Controller)
/* Inline read optimization; Rte_IRead_ASC_Controller_Required_BSW_bsw_uBat_mu16 to implicit access macro */
#define Rte_IRead_ASC_Controller_Required_BSW_bsw_uBat_mu16()  ( (CONST(IDT_ASC_BSW_Interface_bsw_uBat_mu16, RTE_DATA)) Rte_ImplicitBufs_TaskOem1_1ms.sbuf73.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_ASC_Controller)
/* Inline read optimization; Rte_IRead_ASC_Controller_Required_BSW_can_beschlLaengs_mi16 to implicit access macro */
#define Rte_IRead_ASC_Controller_Required_BSW_can_beschlLaengs_mi16()  ( (CONST(IDT_ASC_BSW_Interface_can_beschlLaengs_mi16, RTE_DATA)) Rte_ImplicitBufs_TaskOem1_1ms.sbuf22.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_ASC_Controller)
/* Inline read optimization; Rte_IRead_ASC_Controller_Required_BSW_can_beschlQuer_mi16 to implicit access macro */
#define Rte_IRead_ASC_Controller_Required_BSW_can_beschlQuer_mi16()  ( (CONST(IDT_ASC_BSW_Interface_can_beschlQuer_mi16, RTE_DATA)) Rte_ImplicitBufs_TaskOem1_1ms.sbuf23.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_ASC_Controller)
/* Inline read optimization; Rte_IRead_ASC_Controller_Required_BSW_can_facTrqWheel_mu8 to implicit access macro */
#define Rte_IRead_ASC_Controller_Required_BSW_can_facTrqWheel_mu8()  ( (CONST(IDT_ASC_BSW_Interface_can_facTrqWheel_mu8, RTE_DATA)) Rte_ImplicitBufs_TaskOem1_1ms.sbuf74.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_ASC_Controller)
/* Inline read optimization; Rte_IRead_ASC_Controller_Required_BSW_can_gierrate_mi16 to implicit access macro */
#define Rte_IRead_ASC_Controller_Required_BSW_can_gierrate_mi16()  ( (CONST(IDT_ASC_BSW_Interface_can_gierrate_mi16, RTE_DATA)) Rte_ImplicitBufs_TaskOem1_1ms.sbuf24.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_ASC_Controller)
/* Inline read optimization; Rte_IRead_ASC_Controller_Required_BSW_can_gradUeb_mi8 to implicit access macro */
#define Rte_IRead_ASC_Controller_Required_BSW_can_gradUeb_mi8()  ( (CONST(IDT_ASC_BSW_Interface_can_gradUeb_mi8, RTE_DATA)) Rte_ImplicitBufs_TaskOem1_1ms.sbuf25.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_ASC_Controller)
/* Inline read optimization; Rte_IRead_ASC_Controller_Required_BSW_can_imp_HL_mu16 to implicit access macro */
#define Rte_IRead_ASC_Controller_Required_BSW_can_imp_HL_mu16()  ( (CONST(IDT_ASC_BSW_Interface_can_imp_HL_mu16, RTE_DATA)) Rte_ImplicitBufs_TaskOem1_1ms.sbuf26.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_ASC_Controller)
/* Inline read optimization; Rte_IRead_ASC_Controller_Required_BSW_can_imp_HR_mu16 to implicit access macro */
#define Rte_IRead_ASC_Controller_Required_BSW_can_imp_HR_mu16()  ( (CONST(IDT_ASC_BSW_Interface_can_imp_HR_mu16, RTE_DATA)) Rte_ImplicitBufs_TaskOem1_1ms.sbuf27.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_ASC_Controller)
/* Inline read optimization; Rte_IRead_ASC_Controller_Required_BSW_can_levelPedal_mu8 to implicit access macro */
#define Rte_IRead_ASC_Controller_Required_BSW_can_levelPedal_mu8()  ( (CONST(IDT_ASC_BSW_Interface_can_levelPedal_mu8, RTE_DATA)) Rte_ImplicitBufs_TaskOem1_1ms.sbuf28.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_ASC_Controller)
/* Inline read optimization; Rte_IRead_ASC_Controller_Required_BSW_can_pBrems_mi16 to implicit access macro */
#define Rte_IRead_ASC_Controller_Required_BSW_can_pBrems_mi16()  ( (CONST(IDT_ASC_BSW_Interface_can_pBrems_mi16, RTE_DATA)) Rte_ImplicitBufs_TaskOem1_1ms.sbuf29.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_ASC_Controller)
/* Inline read optimization; Rte_IRead_ASC_Controller_Required_BSW_can_rpmMotor_mu16 to implicit access macro */
#define Rte_IRead_ASC_Controller_Required_BSW_can_rpmMotor_mu16()  ( (CONST(IDT_ASC_BSW_Interface_can_rpmMotor_mu16, RTE_DATA)) Rte_ImplicitBufs_TaskOem1_1ms.sbuf30.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_ASC_Controller)
/* Inline read optimization; Rte_IRead_ASC_Controller_Required_BSW_can_stESP14_mu8 to implicit access macro */
#define Rte_IRead_ASC_Controller_Required_BSW_can_stESP14_mu8()  ( (CONST(IDT_ASC_BSW_Interface_can_stESP14_mu8, RTE_DATA)) Rte_ImplicitBufs_TaskOem1_1ms.sbuf31.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_ASC_Controller)
/* Inline read optimization; Rte_IRead_ASC_Controller_Required_BSW_can_stFahrbereitschaft_mu8 to implicit access macro */
#define Rte_IRead_ASC_Controller_Required_BSW_can_stFahrbereitschaft_mu8()  ( (CONST(IDT_ASC_BSW_Interface_can_stFahrbereitschaft_mu8, RTE_DATA)) Rte_ImplicitBufs_TaskOem1_1ms.sbuf32.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_ASC_Controller)
/* Inline read optimization; Rte_IRead_ASC_Controller_Required_BSW_can_stLaufleistung_mu32 to implicit access macro */
#define Rte_IRead_ASC_Controller_Required_BSW_can_stLaufleistung_mu32()  ( (CONST(IDT_ASC_BSW_Interface_can_stLaufleistung_mu32, RTE_DATA)) Rte_ImplicitBufs_TaskOem1_1ms.sbuf33.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_ASC_Controller)
/* Inline read optimization; Rte_IRead_ASC_Controller_Required_BSW_can_stMO14_mu8 to implicit access macro */
#define Rte_IRead_ASC_Controller_Required_BSW_can_stMO14_mu8()  ( (CONST(IDT_ASC_BSW_Interface_can_stMO14_mu8, RTE_DATA)) Rte_ImplicitBufs_TaskOem1_1ms.sbuf34.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_ASC_Controller)
/* Inline read optimization; Rte_IRead_ASC_Controller_Required_BSW_can_stSignale01_mu32 to implicit access macro */
#define Rte_IRead_ASC_Controller_Required_BSW_can_stSignale01_mu32()  ( (CONST(IDT_ASC_BSW_Interface_can_stSignale01_mu32, RTE_DATA)) Rte_ImplicitBufs_TaskOem1_1ms.sbuf35.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_ASC_Controller)
/* Inline read optimization; Rte_IRead_ASC_Controller_Required_BSW_can_stSignale02_mu32 to implicit access macro */
#define Rte_IRead_ASC_Controller_Required_BSW_can_stSignale02_mu32()  ( (CONST(IDT_ASC_BSW_Interface_can_stSignale02_mu32, RTE_DATA)) Rte_ImplicitBufs_TaskOem1_1ms.sbuf36.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_ASC_Controller)
/* Inline read optimization; Rte_IRead_ASC_Controller_Required_BSW_can_stTrqWheel_mu8 to implicit access macro */
#define Rte_IRead_ASC_Controller_Required_BSW_can_stTrqWheel_mu8()  ( (CONST(IDT_ASC_BSW_Interface_can_stTrqWheel_mu8, RTE_DATA)) Rte_ImplicitBufs_TaskOem1_1ms.sbuf75.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_ASC_Controller)
/* Inline read optimization; Rte_IRead_ASC_Controller_Required_BSW_can_strDevMsgRx1_mu32 to implicit access macro */
#define Rte_IRead_ASC_Controller_Required_BSW_can_strDevMsgRx1_mu32()  ( (CONST(IDT_ASC_BSW_Interface_can_strDevMsgRx1_mu32, RTE_DATA)) Rte_ImplicitBufs_TaskOem1_1ms.sbuf37.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_ASC_Controller)
/* Inline read optimization; Rte_IRead_ASC_Controller_Required_BSW_can_strDevMsgRx2_mu32 to implicit access macro */
#define Rte_IRead_ASC_Controller_Required_BSW_can_strDevMsgRx2_mu32()  ( (CONST(IDT_ASC_BSW_Interface_can_strDevMsgRx2_mu32, RTE_DATA)) Rte_ImplicitBufs_TaskOem1_1ms.sbuf38.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_ASC_Controller)
/* Inline read optimization; Rte_IRead_ASC_Controller_Required_BSW_can_tragMo_mi16 to implicit access macro */
#define Rte_IRead_ASC_Controller_Required_BSW_can_tragMo_mi16()  ( (CONST(IDT_ASC_BSW_Interface_can_tragMo_mi16, RTE_DATA)) Rte_ImplicitBufs_TaskOem1_1ms.sbuf39.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_ASC_Controller)
/* Inline read optimization; Rte_IRead_ASC_Controller_Required_BSW_can_trqAllrad_mu8 to implicit access macro */
#define Rte_IRead_ASC_Controller_Required_BSW_can_trqAllrad_mu8()  ( (CONST(IDT_ASC_BSW_Interface_can_trqAllrad_mu8, RTE_DATA)) Rte_ImplicitBufs_TaskOem1_1ms.sbuf40.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_ASC_Controller)
/* Inline read optimization; Rte_IRead_ASC_Controller_Required_BSW_can_trqMoIst_mi16 to implicit access macro */
#define Rte_IRead_ASC_Controller_Required_BSW_can_trqMoIst_mi16()  ( (CONST(IDT_ASC_BSW_Interface_can_trqMoIst_mi16, RTE_DATA)) Rte_ImplicitBufs_TaskOem1_1ms.sbuf41.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_ASC_Controller)
/* Inline read optimization; Rte_IRead_ASC_Controller_Required_BSW_can_trqMoSchub_mi16 to implicit access macro */
#define Rte_IRead_ASC_Controller_Required_BSW_can_trqMoSchub_mi16()  ( (CONST(IDT_ASC_BSW_Interface_can_trqMoSchub_mi16, RTE_DATA)) Rte_ImplicitBufs_TaskOem1_1ms.sbuf42.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_ASC_Controller)
/* Inline read optimization; Rte_IRead_ASC_Controller_Required_BSW_can_trqMoSollRoh_mi16 to implicit access macro */
#define Rte_IRead_ASC_Controller_Required_BSW_can_trqMoSollRoh_mi16()  ( (CONST(IDT_ASC_BSW_Interface_can_trqMoSollRoh_mi16, RTE_DATA)) Rte_ImplicitBufs_TaskOem1_1ms.sbuf43.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_ASC_Controller)
/* Inline read optimization; Rte_IRead_ASC_Controller_Required_BSW_can_trqWheelActSec_mi16 to implicit access macro */
#define Rte_IRead_ASC_Controller_Required_BSW_can_trqWheelActSec_mi16()  ( (CONST(IDT_ASC_BSW_Interface_can_trqWheelActSec_mi16, RTE_DATA)) Rte_ImplicitBufs_TaskOem1_1ms.sbuf76.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_ASC_Controller)
/* Inline read optimization; Rte_IRead_ASC_Controller_Required_BSW_can_trqWheelAct_mi16 to implicit access macro */
#define Rte_IRead_ASC_Controller_Required_BSW_can_trqWheelAct_mi16()  ( (CONST(IDT_ASC_BSW_Interface_can_trqWheelAct_mi16, RTE_DATA)) Rte_ImplicitBufs_TaskOem1_1ms.sbuf77.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_ASC_Controller)
/* Inline read optimization; Rte_IRead_ASC_Controller_Required_BSW_can_vRad_HL_mi16 to implicit access macro */
#define Rte_IRead_ASC_Controller_Required_BSW_can_vRad_HL_mi16()  ( (CONST(IDT_ASC_BSW_Interface_can_vRad_HL_mi16, RTE_DATA)) Rte_ImplicitBufs_TaskOem1_1ms.sbuf44.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_ASC_Controller)
/* Inline read optimization; Rte_IRead_ASC_Controller_Required_BSW_can_vRad_HR_mi16 to implicit access macro */
#define Rte_IRead_ASC_Controller_Required_BSW_can_vRad_HR_mi16()  ( (CONST(IDT_ASC_BSW_Interface_can_vRad_HR_mi16, RTE_DATA)) Rte_ImplicitBufs_TaskOem1_1ms.sbuf45.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_ASC_Controller)
/* Inline read optimization; Rte_IRead_ASC_Controller_Required_BSW_can_vRad_VL_mi16 to implicit access macro */
#define Rte_IRead_ASC_Controller_Required_BSW_can_vRad_VL_mi16()  ( (CONST(IDT_ASC_BSW_Interface_can_vRad_VL_mi16, RTE_DATA)) Rte_ImplicitBufs_TaskOem1_1ms.sbuf46.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_ASC_Controller)
/* Inline read optimization; Rte_IRead_ASC_Controller_Required_BSW_can_vRad_VR_mi16 to implicit access macro */
#define Rte_IRead_ASC_Controller_Required_BSW_can_vRad_VR_mi16()  ( (CONST(IDT_ASC_BSW_Interface_can_vRad_VR_mi16, RTE_DATA)) Rte_ImplicitBufs_TaskOem1_1ms.sbuf47.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_ASC_Controller)
/* Inline read optimization; Rte_IRead_ASC_Controller_Required_BSW_can_vSignal_mu16 to implicit access macro */
#define Rte_IRead_ASC_Controller_Required_BSW_can_vSignal_mu16()  ( (CONST(IDT_ASC_BSW_Interface_can_vSignal_mu16, RTE_DATA)) Rte_ImplicitBufs_TaskOem1_1ms.sbuf48.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_ASC_Controller)
/* Inline read optimization; Rte_IRead_ASC_Controller_Required_BSW_can_vaqIst_mu8 to implicit access macro */
#define Rte_IRead_ASC_Controller_Required_BSW_can_vaqIst_mu8()  ( (CONST(IDT_ASC_BSW_Interface_can_vaqIst_mu8, RTE_DATA)) Rte_ImplicitBufs_TaskOem1_1ms.sbuf49.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_ASC_Controller)
/* Inline read optimization; Rte_IRead_ASC_Controller_Required_BSW_cha_facAuto_mu16 to implicit access macro */
#define Rte_IRead_ASC_Controller_Required_BSW_cha_facAuto_mu16()  ( (CONST(IDT_ASC_BSW_Interface_cha_facAuto_mu16, RTE_DATA)) Rte_ImplicitBufs_TaskOem1_1ms.sbuf50.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_ASC_Controller)
/* Inline read optimization; Rte_IRead_ASC_Controller_Required_BSW_cha_facDyn_mu16 to implicit access macro */
#define Rte_IRead_ASC_Controller_Required_BSW_cha_facDyn_mu16()  ( (CONST(IDT_ASC_BSW_Interface_cha_facDyn_mu16, RTE_DATA)) Rte_ImplicitBufs_TaskOem1_1ms.sbuf51.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_ASC_Controller)
/* Inline read optimization; Rte_IRead_ASC_Controller_Required_BSW_cha_facEvent_mu16 to implicit access macro */
#define Rte_IRead_ASC_Controller_Required_BSW_cha_facEvent_mu16()  ( (CONST(IDT_ASC_BSW_Interface_cha_facEvent_mu16, RTE_DATA)) Rte_ImplicitBufs_TaskOem1_1ms.sbuf52.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_ASC_Controller)
/* Inline read optimization; Rte_IRead_ASC_Controller_Required_BSW_cha_facKom_mu16 to implicit access macro */
#define Rte_IRead_ASC_Controller_Required_BSW_cha_facKom_mu16()  ( (CONST(IDT_ASC_BSW_Interface_cha_facKom_mu16, RTE_DATA)) Rte_ImplicitBufs_TaskOem1_1ms.sbuf53.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_ASC_Controller)
/* Inline read optimization; Rte_IRead_ASC_Controller_Required_BSW_dia_mskAnpassung01_mu32 to implicit access macro */
#define Rte_IRead_ASC_Controller_Required_BSW_dia_mskAnpassung01_mu32()  ( (CONST(IDT_ASC_BSW_Interface_dia_mskAnpassung01_mu32, RTE_DATA)) Rte_ImplicitBufs_TaskOem1_1ms.sbuf54.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_ASC_Controller)
/* Inline read optimization; Rte_IRead_ASC_Controller_Required_BSW_dia_mskCodierung01_mu32 to implicit access macro */
#define Rte_IRead_ASC_Controller_Required_BSW_dia_mskCodierung01_mu32()  ( (CONST(IDT_ASC_BSW_Interface_dia_mskCodierung01_mu32, RTE_DATA)) Rte_ImplicitBufs_TaskOem1_1ms.sbuf55.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_ASC_Controller)
/* Inline read optimization; Rte_IRead_ASC_Controller_Required_BSW_fga_mskStVFzg_mu8 to implicit access macro */
#define Rte_IRead_ASC_Controller_Required_BSW_fga_mskStVFzg_mu8()  ( (CONST(IDT_ASC_BSW_Interface_fga_mskStVFzg_mu8, RTE_DATA)) Rte_ImplicitBufs_TaskOem1_1ms.sbuf56.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_ASC_Controller)
/* Inline read optimization; Rte_IRead_ASC_Controller_Required_BSW_fga_vFzg_mi16 to implicit access macro */
#define Rte_IRead_ASC_Controller_Required_BSW_fga_vFzg_mi16()  ( (CONST(IDT_ASC_BSW_Interface_fga_vFzg_mi16, RTE_DATA)) Rte_ImplicitBufs_TaskOem1_1ms.sbuf57.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_ASC_Controller)
/* Inline read optimization; Rte_IRead_ASC_Controller_Required_BSW_hca_stHCA_mu8 to implicit access macro */
#define Rte_IRead_ASC_Controller_Required_BSW_hca_stHCA_mu8()  ( (CONST(IDT_ASC_BSW_Interface_hca_stHCA_mu8, RTE_DATA)) Rte_ImplicitBufs_TaskOem1_1ms.sbuf58.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_ASC_Controller)
/* Inline read optimization; Rte_IRead_ASC_Controller_Required_BSW_qap_stPrioToTnDsaTsc_mu8 to implicit access macro */
#define Rte_IRead_ASC_Controller_Required_BSW_qap_stPrioToTnDsaTsc_mu8()  ( (CONST(IDT_ASC_BSW_Interface_qap_stPrioToTnDsaTsc_mu8, RTE_DATA)) Rte_ImplicitBufs_TaskOem1_1ms.sbuf59.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_ASC_Controller)
/* Inline write optimization; Rte_IWriteRef_ASC_Controller_Provided_ASC_asc_StartStopp_Info_mu8 to implicit access macro */
#define Rte_IWriteRef_ASC_Controller_Provided_ASC_asc_StartStopp_Info_mu8()  ( (P2VAR(IDT_ASC_Interface_asc_StartStopp_Info_mu8, AUTOMATIC, RTE_DATA)) &Rte_ImplicitBufs_TaskOem1_1ms.sbuf0.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_ASC_Controller)
/* Inline write optimization; Rte_IWriteRef_ASC_Controller_Provided_ASC_asc_can_strDevMsgTx1_mu32 to implicit access macro */
#define Rte_IWriteRef_ASC_Controller_Provided_ASC_asc_can_strDevMsgTx1_mu32()  ( (P2VAR(IDT_ASC_Interface_asc_can_strDevMsgTx1_mu32, AUTOMATIC, RTE_DATA)) &Rte_ImplicitBufs_TaskOem1_1ms.sbuf1.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_ASC_Controller)
/* Inline write optimization; Rte_IWriteRef_ASC_Controller_Provided_ASC_asc_can_strDevMsgTx2_mu32 to implicit access macro */
#define Rte_IWriteRef_ASC_Controller_Provided_ASC_asc_can_strDevMsgTx2_mu32()  ( (P2VAR(IDT_ASC_Interface_asc_can_strDevMsgTx2_mu32, AUTOMATIC, RTE_DATA)) &Rte_ImplicitBufs_TaskOem1_1ms.sbuf2.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_ASC_Controller)
/* Inline write optimization; Rte_IWriteRef_ASC_Controller_Provided_ASC_asc_epsWarn_mu8 to implicit access macro */
#define Rte_IWriteRef_ASC_Controller_Provided_ASC_asc_epsWarn_mu8()  ( (P2VAR(IDT_ASC_Interface_asc_epsWarn_mu8, AUTOMATIC, RTE_DATA)) &Rte_ImplicitBufs_TaskOem1_1ms.sbuf3.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_ASC_Controller)
/* Inline write optimization; Rte_IWriteRef_ASC_Controller_Provided_ASC_asc_fSoll_mi16 to implicit access macro */
#define Rte_IWriteRef_ASC_Controller_Provided_ASC_asc_fSoll_mi16()  ( (P2VAR(IDT_ASC_Interface_asc_fSoll_mi16, AUTOMATIC, RTE_DATA)) &Rte_ImplicitBufs_TaskOem1_1ms.sbuf4.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_ASC_Controller)
/* Inline write optimization; Rte_IWriteRef_ASC_Controller_Provided_ASC_asc_facReduzlku_mu16 to implicit access macro */
#define Rte_IWriteRef_ASC_Controller_Provided_ASC_asc_facReduzlku_mu16()  ( (P2VAR(IDT_ASC_Interface_asc_facReduzlku_mu16, AUTOMATIC, RTE_DATA)) &Rte_ImplicitBufs_TaskOem1_1ms.sbuf5.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_ASC_Controller)
/* Inline write optimization; Rte_IWriteRef_ASC_Controller_Provided_ASC_asc_facReduztrq_mu16 to implicit access macro */
#define Rte_IWriteRef_ASC_Controller_Provided_ASC_asc_facReduztrq_mu16()  ( (P2VAR(IDT_ASC_Interface_asc_facReduztrq_mu16, AUTOMATIC, RTE_DATA)) &Rte_ImplicitBufs_TaskOem1_1ms.sbuf6.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_ASC_Controller)
/* Inline write optimization; Rte_IWriteRef_ASC_Controller_Provided_ASC_asc_ger_phiK_mi16 to implicit access macro */
#define Rte_IWriteRef_ASC_Controller_Provided_ASC_asc_ger_phiK_mi16()  ( (P2VAR(IDT_ASC_Interface_asc_ger_phiK_mi16, AUTOMATIC, RTE_DATA)) &Rte_ImplicitBufs_TaskOem1_1ms.sbuf7.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_ASC_Controller)
/* Inline write optimization; Rte_IWriteRef_ASC_Controller_Provided_ASC_asc_ger_phiL_mi16 to implicit access macro */
#define Rte_IWriteRef_ASC_Controller_Provided_ASC_asc_ger_phiL_mi16()  ( (P2VAR(IDT_ASC_Interface_asc_ger_phiL_mi16, AUTOMATIC, RTE_DATA)) &Rte_ImplicitBufs_TaskOem1_1ms.sbuf8.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_ASC_Controller)
/* Inline write optimization; Rte_IWriteRef_ASC_Controller_Provided_ASC_asc_ger_stLernK_mu8 to implicit access macro */
#define Rte_IWriteRef_ASC_Controller_Provided_ASC_asc_ger_stLernK_mu8()  ( (P2VAR(IDT_ASC_Interface_asc_ger_stLernK_mu8, AUTOMATIC, RTE_DATA)) &Rte_ImplicitBufs_TaskOem1_1ms.sbuf9.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_ASC_Controller)
/* Inline write optimization; Rte_IWriteRef_ASC_Controller_Provided_ASC_asc_ger_stLernL_mu8 to implicit access macro */
#define Rte_IWriteRef_ASC_Controller_Provided_ASC_asc_ger_stLernL_mu8()  ( (P2VAR(IDT_ASC_Interface_asc_ger_stLernL_mu8, AUTOMATIC, RTE_DATA)) &Rte_ImplicitBufs_TaskOem1_1ms.sbuf10.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_ASC_Controller)
/* Inline write optimization; Rte_IWriteRef_ASC_Controller_Provided_ASC_asc_mst_startBed_mu8 to implicit access macro */
#define Rte_IWriteRef_ASC_Controller_Provided_ASC_asc_mst_startBed_mu8()  ( (P2VAR(IDT_ASC_Interface_asc_mst_startBed_mu8, AUTOMATIC, RTE_DATA)) &Rte_ImplicitBufs_TaskOem1_1ms.sbuf11.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_ASC_Controller)
/* Inline write optimization; Rte_IWriteRef_ASC_Controller_Provided_ASC_asc_stASC_mu32 to implicit access macro */
#define Rte_IWriteRef_ASC_Controller_Provided_ASC_asc_stASC_mu32()  ( (P2VAR(IDT_ASC_Interface_asc_stASC_mu32, AUTOMATIC, RTE_DATA)) &Rte_ImplicitBufs_TaskOem1_1ms.sbuf12.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_ASC_Controller)
/* Inline write optimization; Rte_IWriteRef_ASC_Controller_Provided_ASC_asc_stDsaTsc2Qfk_mu16 to implicit access macro */
#define Rte_IWriteRef_ASC_Controller_Provided_ASC_asc_stDsaTsc2Qfk_mu16()  ( (P2VAR(IDT_ASC_Interface_asc_stDsaTsc2Qfk_mu16, AUTOMATIC, RTE_DATA)) &Rte_ImplicitBufs_TaskOem1_1ms.sbuf13.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_ASC_Controller)
/* Inline write optimization; Rte_IWriteRef_ASC_Controller_Provided_ASC_asc_trqOffset_mi16 to implicit access macro */
#define Rte_IWriteRef_ASC_Controller_Provided_ASC_asc_trqOffset_mi16()  ( (P2VAR(IDT_ASC_Interface_asc_trqOffset_mi16, AUTOMATIC, RTE_DATA)) &Rte_ImplicitBufs_TaskOem1_1ms.sbuf14.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_ASC_Controller)
/* Inline write optimization; Rte_IWriteRef_ASC_Controller_Provided_ASC_asc_tsc_fSoll_mi16 to implicit access macro */
#define Rte_IWriteRef_ASC_Controller_Provided_ASC_asc_tsc_fSoll_mi16()  ( (P2VAR(IDT_ASC_Interface_asc_tsc_fSoll_mi16, AUTOMATIC, RTE_DATA)) &Rte_ImplicitBufs_TaskOem1_1ms.sbuf15.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_ASC_Controller)
/* Inline write optimization; Rte_IWriteRef_ASC_Controller_Provided_ASC_asc_tsc_facLern_mu16 to implicit access macro */
#define Rte_IWriteRef_ASC_Controller_Provided_ASC_asc_tsc_facLern_mu16()  ( (P2VAR(IDT_ASC_Interface_asc_tsc_facLern_mu16, AUTOMATIC, RTE_DATA)) &Rte_ImplicitBufs_TaskOem1_1ms.sbuf16.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_ASC_Controller)
/* Inline write optimization; Rte_IWriteRef_ASC_Controller_Provided_ASC_asc_tsc_stLerrn_mu8 to implicit access macro */
#define Rte_IWriteRef_ASC_Controller_Provided_ASC_asc_tsc_stLerrn_mu8()  ( (P2VAR(IDT_ASC_Interface_asc_tsc_stLerrn_mu8, AUTOMATIC, RTE_DATA)) &Rte_ImplicitBufs_TaskOem1_1ms.sbuf17.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_ASC_Controller)
/* Inline write optimization; Rte_IWrite_ASC_Controller_Provided_ASC_asc_StartStopp_Info_mu8 to implicit access macro */
#define Rte_IWrite_ASC_Controller_Provided_ASC_asc_StartStopp_Info_mu8( data )  ( Rte_ImplicitBufs_TaskOem1_1ms.sbuf0.value = (data) )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_ASC_Controller)
/* Inline write optimization; Rte_IWrite_ASC_Controller_Provided_ASC_asc_can_strDevMsgTx1_mu32 to implicit access macro */
#define Rte_IWrite_ASC_Controller_Provided_ASC_asc_can_strDevMsgTx1_mu32( data )  ( Rte_ImplicitBufs_TaskOem1_1ms.sbuf1.value = (data) )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_ASC_Controller)
/* Inline write optimization; Rte_IWrite_ASC_Controller_Provided_ASC_asc_can_strDevMsgTx2_mu32 to implicit access macro */
#define Rte_IWrite_ASC_Controller_Provided_ASC_asc_can_strDevMsgTx2_mu32( data )  ( Rte_ImplicitBufs_TaskOem1_1ms.sbuf2.value = (data) )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_ASC_Controller)
/* Inline write optimization; Rte_IWrite_ASC_Controller_Provided_ASC_asc_epsWarn_mu8 to implicit access macro */
#define Rte_IWrite_ASC_Controller_Provided_ASC_asc_epsWarn_mu8( data )  ( Rte_ImplicitBufs_TaskOem1_1ms.sbuf3.value = (data) )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_ASC_Controller)
/* Inline write optimization; Rte_IWrite_ASC_Controller_Provided_ASC_asc_fSoll_mi16 to implicit access macro */
#define Rte_IWrite_ASC_Controller_Provided_ASC_asc_fSoll_mi16( data )  ( Rte_ImplicitBufs_TaskOem1_1ms.sbuf4.value = (data) )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_ASC_Controller)
/* Inline write optimization; Rte_IWrite_ASC_Controller_Provided_ASC_asc_facReduzlku_mu16 to implicit access macro */
#define Rte_IWrite_ASC_Controller_Provided_ASC_asc_facReduzlku_mu16( data )  ( Rte_ImplicitBufs_TaskOem1_1ms.sbuf5.value = (data) )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_ASC_Controller)
/* Inline write optimization; Rte_IWrite_ASC_Controller_Provided_ASC_asc_facReduztrq_mu16 to implicit access macro */
#define Rte_IWrite_ASC_Controller_Provided_ASC_asc_facReduztrq_mu16( data )  ( Rte_ImplicitBufs_TaskOem1_1ms.sbuf6.value = (data) )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_ASC_Controller)
/* Inline write optimization; Rte_IWrite_ASC_Controller_Provided_ASC_asc_ger_phiK_mi16 to implicit access macro */
#define Rte_IWrite_ASC_Controller_Provided_ASC_asc_ger_phiK_mi16( data )  ( Rte_ImplicitBufs_TaskOem1_1ms.sbuf7.value = (data) )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_ASC_Controller)
/* Inline write optimization; Rte_IWrite_ASC_Controller_Provided_ASC_asc_ger_phiL_mi16 to implicit access macro */
#define Rte_IWrite_ASC_Controller_Provided_ASC_asc_ger_phiL_mi16( data )  ( Rte_ImplicitBufs_TaskOem1_1ms.sbuf8.value = (data) )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_ASC_Controller)
/* Inline write optimization; Rte_IWrite_ASC_Controller_Provided_ASC_asc_ger_stLernK_mu8 to implicit access macro */
#define Rte_IWrite_ASC_Controller_Provided_ASC_asc_ger_stLernK_mu8( data )  ( Rte_ImplicitBufs_TaskOem1_1ms.sbuf9.value = (data) )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_ASC_Controller)
/* Inline write optimization; Rte_IWrite_ASC_Controller_Provided_ASC_asc_ger_stLernL_mu8 to implicit access macro */
#define Rte_IWrite_ASC_Controller_Provided_ASC_asc_ger_stLernL_mu8( data )  ( Rte_ImplicitBufs_TaskOem1_1ms.sbuf10.value = (data) )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_ASC_Controller)
/* Inline write optimization; Rte_IWrite_ASC_Controller_Provided_ASC_asc_mst_startBed_mu8 to implicit access macro */
#define Rte_IWrite_ASC_Controller_Provided_ASC_asc_mst_startBed_mu8( data )  ( Rte_ImplicitBufs_TaskOem1_1ms.sbuf11.value = (data) )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_ASC_Controller)
/* Inline write optimization; Rte_IWrite_ASC_Controller_Provided_ASC_asc_stASC_mu32 to implicit access macro */
#define Rte_IWrite_ASC_Controller_Provided_ASC_asc_stASC_mu32( data )  ( Rte_ImplicitBufs_TaskOem1_1ms.sbuf12.value = (data) )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_ASC_Controller)
/* Inline write optimization; Rte_IWrite_ASC_Controller_Provided_ASC_asc_stDsaTsc2Qfk_mu16 to implicit access macro */
#define Rte_IWrite_ASC_Controller_Provided_ASC_asc_stDsaTsc2Qfk_mu16( data )  ( Rte_ImplicitBufs_TaskOem1_1ms.sbuf13.value = (data) )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_ASC_Controller)
/* Inline write optimization; Rte_IWrite_ASC_Controller_Provided_ASC_asc_trqOffset_mi16 to implicit access macro */
#define Rte_IWrite_ASC_Controller_Provided_ASC_asc_trqOffset_mi16( data )  ( Rte_ImplicitBufs_TaskOem1_1ms.sbuf14.value = (data) )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_ASC_Controller)
/* Inline write optimization; Rte_IWrite_ASC_Controller_Provided_ASC_asc_tsc_fSoll_mi16 to implicit access macro */
#define Rte_IWrite_ASC_Controller_Provided_ASC_asc_tsc_fSoll_mi16( data )  ( Rte_ImplicitBufs_TaskOem1_1ms.sbuf15.value = (data) )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_ASC_Controller)
/* Inline write optimization; Rte_IWrite_ASC_Controller_Provided_ASC_asc_tsc_facLern_mu16 to implicit access macro */
#define Rte_IWrite_ASC_Controller_Provided_ASC_asc_tsc_facLern_mu16( data )  ( Rte_ImplicitBufs_TaskOem1_1ms.sbuf16.value = (data) )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_ASC_Controller)
/* Inline write optimization; Rte_IWrite_ASC_Controller_Provided_ASC_asc_tsc_stLerrn_mu8 to implicit access macro */
#define Rte_IWrite_ASC_Controller_Provided_ASC_asc_tsc_stLerrn_mu8( data )  ( Rte_ImplicitBufs_TaskOem1_1ms.sbuf17.value = (data) )
#endif

#endif /* RTE_CORE */

/*******************************************************
 ***
 *** RE Prototypes
 ***
 *******************************************************/

#define ASC_SWC_START_SEC_CODE
#include "Std_Types.h"
FUNC(void, ASC_SWC_CODE) ASC_Controller_runnable(void);
FUNC(void, ASC_SWC_CODE) ASC_Init_runnable(void);
#define ASC_SWC_STOP_SEC_CODE
#include "Std_Types.h"

/* Initial values for data element prototypes */

#ifdef __cplusplus
} /* extern C */
#endif /* __cplusplus */

#endif /* !RTE_ASC_SWC_H */
