/** @file     Rte_Cfg.h
  *
  * @brief    RTE Configuration file
  *
  * @note     Generated by ETAS RTA-RTE
  * @note     Version 7.3.0 
  */

#ifndef RTE_CFG_H
#define RTE_CFG_H

#include <Std_Types.h>

/* BEGIN: VFB tracing definitions */
#ifndef RTE_VFB_TRACE
#define RTE_VFB_TRACE                            (0)
#endif /* !RTE_VFB_TRACE */
/* END: VFB tracing definitions */

/* BEGIN: Condition Value Macros */
#define Rte_SysCon_AZG_VPP_ProductionEndStopLearning                                                     (TRUE)
#define Rte_VPCon_AZG_RP_EndStopServices_ProductionEndStopLearning_active                                (TRUE)
#define Rte_VPCon_AZG_azApplAzg_RP_EndStopServices_GetEndStop_ProductionEndStopLearning_active           (TRUE)
#define Rte_VPCon_AZG_azApplAzg_RP_EndStopServices_LearnEndStop_ProductionEndStopLearning_active         (TRUE)
#define Rte_VPCon_AZG_azApplAzg_RP_EndStopServices_ResetAdapDataEndStop_ProductionEndStopLearning_active (TRUE)
/* END: Condition Value Macros */

#endif /* !RTE_CFG_H */
