/** @file     Rte_Const.h
  *
  * @brief    RTA-RTE related configuration constants
  *
  * @note     AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
  *
  * @note     Generated by ETAS RTA-RTE
  * @note     Version 7.3.0 
  */

#ifndef RTE_CONST_H
#define RTE_CONST_H

#define OSENV_RTAOS40                                                                          (1)
#define RTE_CALPRM_NONE                                                                        (1)
#define RTE_IMODEINIT                                                                          (1)
#define RTE_INITIALIZING                                                                       (1)
#define RTE_MAINFUNCTION_PERIOD_MS                                                             (10)
#define RTE_MAINFUNCTION_PERIOD_NS                                                             (10000000)
#define RTE_MAINFUNCTION_PERIOD_US                                                             (10000)
#define RTE_MAX_USED_CORE_ID                                                                   (1)
#define RTE_MAX_USED_OSAPP_ID                                                                  (5)
#define RTE_MEASUREMENT_ENABLED                                                                (1)
#define RTE_NULL_SCHEDULE                                                                      (1)
#define RTE_NUM_TASKS                                                                          (27)
#define RTE_NUM_TIMEOUT_ALARMS                                                                 (0)
#define RTE_ONSTART                                                                            (1)
#define RTE_OSAPI_AUTOSAR_R40                                                                  (1)
#define RTE_OSCFG_AUTOSAR_R40                                                                  (1)
#define RTE_REQUIRES_COM                                                                       (1)
#define RTE_REQUIRES_IOC                                                                       (1)
#define RTE_REQUIRES_NVM                                                                       (1)
#define RTE_RIPS_SUPPORT                                                                       (0)
#define RTE_TASKS_ARRAYSIZE                                                                    (27)
#define RTE_VENDOR_MODE                                                                        (1)
#define RTE_WOWP_EVENTS                                                                        (0)
#define SCHM_GETVERSIONINFO                                                                    (0)
#define _System_EcuConfiguration_EPS_Main_ECU_EcuFlatView_ASC_SWC                              SWCI145
#define _System_EcuConfiguration_EPS_Main_ECU_EcuFlatView_ASMPlausi_var_SingleUc               SWCI66
#define _System_EcuConfiguration_EPS_Main_ECU_EcuFlatView_ASM_var_SingleUc_Osci                SWCI65
#define _System_EcuConfiguration_EPS_Main_ECU_EcuFlatView_AZG                                  SWCI109
#define _System_EcuConfiguration_EPS_Main_ECU_EcuFlatView_AZGCaller                            SWCI126
#define _System_EcuConfiguration_EPS_Main_ECU_EcuFlatView_AZGProjectCommands                   SWCI180
#define _System_EcuConfiguration_EPS_Main_ECU_EcuFlatView_AZGSFDSecurity                       SWCI185
#define _System_EcuConfiguration_EPS_Main_ECU_EcuFlatView_AZGSecurityAccess                    SWCI28
#define _System_EcuConfiguration_EPS_Main_ECU_EcuFlatView_ActiveReturn                         SWCI0
#define _System_EcuConfiguration_EPS_Main_ECU_EcuFlatView_ActiveReturnCheck                    SWCI1
#define _System_EcuConfiguration_EPS_Main_ECU_EcuFlatView_AheadDetection                       SWCI39
#define _System_EcuConfiguration_EPS_Main_ECU_EcuFlatView_AheadDetectionSupp                   SWCI40
#define _System_EcuConfiguration_EPS_Main_ECU_EcuFlatView_ApplicationStateMachineSupp          SWCI63
#define _System_EcuConfiguration_EPS_Main_ECU_EcuFlatView_ArModeManAbstraction                 SWCI2
#define _System_EcuConfiguration_EPS_Main_ECU_EcuFlatView_AscHndlCheck                         SWCI148
#define _System_EcuConfiguration_EPS_Main_ECU_EcuFlatView_AscMonitor                           SWCI141
#define _System_EcuConfiguration_EPS_Main_ECU_EcuFlatView_AssCtrl_var_SingleUc                 SWCI67
#define _System_EcuConfiguration_EPS_Main_ECU_EcuFlatView_AssSysMon                            SWCI164
#define _System_EcuConfiguration_EPS_Main_ECU_EcuFlatView_AssistanceV3                         SWCI115
#define _System_EcuConfiguration_EPS_Main_ECU_EcuFlatView_AzgUdsAdapter                        SWCI110
#define _System_EcuConfiguration_EPS_Main_ECU_EcuFlatView_BallNutGearLoadTracker               SWCI98
#define _System_EcuConfiguration_EPS_Main_ECU_EcuFlatView_BatteryVoltageMonitor                SWCI153
#define _System_EcuConfiguration_EPS_Main_ECU_EcuFlatView_BatteryWarningVibration              SWCI174
#define _System_EcuConfiguration_EPS_Main_ECU_EcuFlatView_BatteryWarningVibrationCheck         SWCI175
#define _System_EcuConfiguration_EPS_Main_ECU_EcuFlatView_BbaAscIn                             SWCI139
#define _System_EcuConfiguration_EPS_Main_ECU_EcuFlatView_BbaAscOut                            SWCI140
#define _System_EcuConfiguration_EPS_Main_ECU_EcuFlatView_BbaSacIn                             SWCI144
#define _System_EcuConfiguration_EPS_Main_ECU_EcuFlatView_BbaSacOut                            SWCI143
#define _System_EcuConfiguration_EPS_Main_ECU_EcuFlatView_BoostCurveInterpolation              SWCI116
#define _System_EcuConfiguration_EPS_Main_ECU_EcuFlatView_BootFlashHandler                     SWCI95
#define _System_EcuConfiguration_EPS_Main_ECU_EcuFlatView_BswM                                 SWCI68
#define _System_EcuConfiguration_EPS_Main_ECU_EcuFlatView_CalibDataHandler                     SWCI101
#define _System_EcuConfiguration_EPS_Main_ECU_EcuFlatView_CanSMCdd                             SWCI205
#define _System_EcuConfiguration_EPS_Main_ECU_EcuFlatView_CanTerm                              SWCI9
#define _System_EcuConfiguration_EPS_Main_ECU_EcuFlatView_CharHdlMain                          SWCI154
#define _System_EcuConfiguration_EPS_Main_ECU_EcuFlatView_ChatterSensor                        SWCI3
#define _System_EcuConfiguration_EPS_Main_ECU_EcuFlatView_ChatterSensorSupp                    SWCI4
#define _System_EcuConfiguration_EPS_Main_ECU_EcuFlatView_ComM                                 SWCI69
#define _System_EcuConfiguration_EPS_Main_ECU_EcuFlatView_ComVarHdlr                           SWCI208
#define _System_EcuConfiguration_EPS_Main_ECU_EcuFlatView_CryptoServices                       SWCI75
#define _System_EcuConfiguration_EPS_Main_ECU_EcuFlatView_Csm                                  SWCI129
#define _System_EcuConfiguration_EPS_Main_ECU_EcuFlatView_CurrentRecalibPermission             SWCI15
#define _System_EcuConfiguration_EPS_Main_ECU_EcuFlatView_CurrentRecalibPermissionSupp         SWCI16
#define _System_EcuConfiguration_EPS_Main_ECU_EcuFlatView_CustomerData                         SWCI102
#define _System_EcuConfiguration_EPS_Main_ECU_EcuFlatView_CustomerDataSupp                     SWCI181
#define _System_EcuConfiguration_EPS_Main_ECU_EcuFlatView_CustomerStateRepresentation          SWCI61
#define _System_EcuConfiguration_EPS_Main_ECU_EcuFlatView_Dcm                                  SWCI70
#define _System_EcuConfiguration_EPS_Main_ECU_EcuFlatView_DcmClient                            SWCI96
#define _System_EcuConfiguration_EPS_Main_ECU_EcuFlatView_DcmClientApp                         SWCI177
#define _System_EcuConfiguration_EPS_Main_ECU_EcuFlatView_Dem                                  SWCI71
#define _System_EcuConfiguration_EPS_Main_ECU_EcuFlatView_DemAbstraction                       SWCI6
#define _System_EcuConfiguration_EPS_Main_ECU_EcuFlatView_DemComplexDeviceDriver               SWCI125
#define _System_EcuConfiguration_EPS_Main_ECU_EcuFlatView_Det                                  SWCI72
#define _System_EcuConfiguration_EPS_Main_ECU_EcuFlatView_DevMessages                          SWCI169
#define _System_EcuConfiguration_EPS_Main_ECU_EcuFlatView_DiagA                                SWCI209
#define _System_EcuConfiguration_EPS_Main_ECU_EcuFlatView_DiagNvDataAccess                     SWCI76
#define _System_EcuConfiguration_EPS_Main_ECU_EcuFlatView_DiagSrvDID_ReadWriteDBI              SWCI155
#define _System_EcuConfiguration_EPS_Main_ECU_EcuFlatView_DiagSrvRID_StateMachine              SWCI156
#define _System_EcuConfiguration_EPS_Main_ECU_EcuFlatView_DiagSrvSID_EcuResetHandler           SWCI179
#define _System_EcuConfiguration_EPS_Main_ECU_EcuFlatView_DiagSrv_Control                      SWCI157
#define _System_EcuConfiguration_EPS_Main_ECU_EcuFlatView_DiagSrv_PreconditionsManager         SWCI183
#define _System_EcuConfiguration_EPS_Main_ECU_EcuFlatView_DiagnosticAbstraction                SWCI191
#define _System_EcuConfiguration_EPS_Main_ECU_EcuFlatView_DiagnosticConnector                  SWCI7
#define _System_EcuConfiguration_EPS_Main_ECU_EcuFlatView_DitherControl                        SWCI167
#define _System_EcuConfiguration_EPS_Main_ECU_EcuFlatView_DitherControlCheck                   SWCI166
#define _System_EcuConfiguration_EPS_Main_ECU_EcuFlatView_DitherControlSupp                    SWCI170
#define _System_EcuConfiguration_EPS_Main_ECU_EcuFlatView_DriverTorqueV2                       SWCI10
#define _System_EcuConfiguration_EPS_Main_ECU_EcuFlatView_DrivingDirection                     SWCI188
#define _System_EcuConfiguration_EPS_Main_ECU_EcuFlatView_EcuM                                 SWCI73
#define _System_EcuConfiguration_EPS_Main_ECU_EcuFlatView_EndStop                              SWCI32
#define _System_EcuConfiguration_EPS_Main_ECU_EcuFlatView_EndStopHsdSupp                       SWCI114
#define _System_EcuConfiguration_EPS_Main_ECU_EcuFlatView_EndStopSupp                          SWCI33
#define _System_EcuConfiguration_EPS_Main_ECU_EcuFlatView_EngineRun                            SWCI5
#define _System_EcuConfiguration_EPS_Main_ECU_EcuFlatView_EpsInput                             SWCI133
#define _System_EcuConfiguration_EPS_Main_ECU_EcuFlatView_EpsOutput                            SWCI134
#define _System_EcuConfiguration_EPS_Main_ECU_EcuFlatView_ErrorInjection                       SWCI35
#define _System_EcuConfiguration_EPS_Main_ECU_EcuFlatView_FactorMinimizer                      SWCI46
#define _System_EcuConfiguration_EPS_Main_ECU_EcuFlatView_FactoryResetHandlerAdapters          SWCI187
#define _System_EcuConfiguration_EPS_Main_ECU_EcuFlatView_FactoryResetHandlerCore              SWCI182
#define _System_EcuConfiguration_EPS_Main_ECU_EcuFlatView_FaderConnMotTrqSum                   SWCI123
#define _System_EcuConfiguration_EPS_Main_ECU_EcuFlatView_FaultInjection                       SWCI11
#define _System_EcuConfiguration_EPS_Main_ECU_EcuFlatView_FaultInjectionSupp                   SWCI12
#define _System_EcuConfiguration_EPS_Main_ECU_EcuFlatView_FlashHandler                         SWCI131
#define _System_EcuConfiguration_EPS_Main_ECU_EcuFlatView_FltManCheck                          SWCI77
#define _System_EcuConfiguration_EPS_Main_ECU_EcuFlatView_FltManDebug                          SWCI78
#define _System_EcuConfiguration_EPS_Main_ECU_EcuFlatView_FltManInputAdapter                   SWCI79
#define _System_EcuConfiguration_EPS_Main_ECU_EcuFlatView_FltManRmtCfmAbstraction              SWCI132
#define _System_EcuConfiguration_EPS_Main_ECU_EcuFlatView_FltManStateMachine                   SWCI80
#define _System_EcuConfiguration_EPS_Main_ECU_EcuFlatView_FltManStateMachinePlausi             SWCI97
#define _System_EcuConfiguration_EPS_Main_ECU_EcuFlatView_FreshnessValueManager                SWCI128
#define _System_EcuConfiguration_EPS_Main_ECU_EcuFlatView_FunctionCoordinatorCheck             SWCI14
#define _System_EcuConfiguration_EPS_Main_ECU_EcuFlatView_HighSpeedDamping                     SWCI189
#define _System_EcuConfiguration_EPS_Main_ECU_EcuFlatView_HighSpeedDampingCheck                SWCI190
#define _System_EcuConfiguration_EPS_Main_ECU_EcuFlatView_HwLib                                SWCI18
#define _System_EcuConfiguration_EPS_Main_ECU_EcuFlatView_HwLibWrapper                         SWCI17
#define _System_EcuConfiguration_EPS_Main_ECU_EcuFlatView_IVD_Wrapper                          SWCI163
#define _System_EcuConfiguration_EPS_Main_ECU_EcuFlatView_Ignition                             SWCI59
#define _System_EcuConfiguration_EPS_Main_ECU_EcuFlatView_InertiaModification                  SWCI117
#define _System_EcuConfiguration_EPS_Main_ECU_EcuFlatView_IpcAbstraction                       SWCI127
#define _System_EcuConfiguration_EPS_Main_ECU_EcuFlatView_IpcAbstraction_CPR                   flatInstance_Composition_IpcAbstraction_zEmyTry02_IPC_Prim2Sec
#define _System_EcuConfiguration_EPS_Main_ECU_EcuFlatView_IvdSfdA                              SWCI160
#define _System_EcuConfiguration_EPS_Main_ECU_EcuFlatView_Locks                                SWCI94
#define _System_EcuConfiguration_EPS_Main_ECU_EcuFlatView_LowVoltageAssistReduction            SWCI82
#define _System_EcuConfiguration_EPS_Main_ECU_EcuFlatView_LowVoltageAssistReductionCheck       SWCI176
#define _System_EcuConfiguration_EPS_Main_ECU_EcuFlatView_LowVoltageAssistReductionSupp        SWCI83
#define _System_EcuConfiguration_EPS_Main_ECU_EcuFlatView_MCDataIntegrity                      SWCI37
#define _System_EcuConfiguration_EPS_Main_ECU_EcuFlatView_MainConnMotTrqSum                    SWCI23
#define _System_EcuConfiguration_EPS_Main_ECU_EcuFlatView_MechanicalLoadTracker                SWCI86
#define _System_EcuConfiguration_EPS_Main_ECU_EcuFlatView_MechanicalStuckPrevention            SWCI151
#define _System_EcuConfiguration_EPS_Main_ECU_EcuFlatView_MechanicalStuckPreventionCheck       SWCI152
#define _System_EcuConfiguration_EPS_Main_ECU_EcuFlatView_MileageTracker                       SWCI90
#define _System_EcuConfiguration_EPS_Main_ECU_EcuFlatView_MotorTorqueLimiter                   SWCI24
#define _System_EcuConfiguration_EPS_Main_ECU_EcuFlatView_NetworkLifeCycleCoordinator          SWCI137
#define _System_EcuConfiguration_EPS_Main_ECU_EcuFlatView_NetworkLifeCycleCoordinatorSupp      SWCI138
#define _System_EcuConfiguration_EPS_Main_ECU_EcuFlatView_NvA                                  SWCI161
#define _System_EcuConfiguration_EPS_Main_ECU_EcuFlatView_NvBlkSWC_AZGSFDSecurity              SWCI186
#define _System_EcuConfiguration_EPS_Main_ECU_EcuFlatView_NvBlkSWC_AsilAdapter                 SWCI212
#define _System_EcuConfiguration_EPS_Main_ECU_EcuFlatView_NvBlkSWC_BallNutDamageTracker        SWCI99
#define _System_EcuConfiguration_EPS_Main_ECU_EcuFlatView_NvBlkSWC_BootSecAccRetryCntr         SWCI184
#define _System_EcuConfiguration_EPS_Main_ECU_EcuFlatView_NvBlkSWC_DFLayout                    SWCI120
#define _System_EcuConfiguration_EPS_Main_ECU_EcuFlatView_NvBlkSWC_DiagConn                    SWCI8
#define _System_EcuConfiguration_EPS_Main_ECU_EcuFlatView_NvBlkSWC_HwlOutStgTestResult         SWCI214
#define _System_EcuConfiguration_EPS_Main_ECU_EcuFlatView_NvBlkSWC_MechanicalLoadTracker       SWCI87
#define _System_EcuConfiguration_EPS_Main_ECU_EcuFlatView_NvBlkSWC_MileageTracker              SWCI91
#define _System_EcuConfiguration_EPS_Main_ECU_EcuFlatView_NvBlkSWC_OBD_01_DrivingCycle         SWCI178
#define _System_EcuConfiguration_EPS_Main_ECU_EcuFlatView_NvBlkSWC_PCBTemperatureTracker       SWCI93
#define _System_EcuConfiguration_EPS_Main_ECU_EcuFlatView_NvBlkSWC_ProductionFlags             SWCI108
#define _System_EcuConfiguration_EPS_Main_ECU_EcuFlatView_NvBlkSWC_RackPositionCorrection      SWCI44
#define _System_EcuConfiguration_EPS_Main_ECU_EcuFlatView_NvBlkSWC_RackPositionSynchronization SWCI135
#define _System_EcuConfiguration_EPS_Main_ECU_EcuFlatView_NvBlkSWC_ResetInfo                   SWCI64
#define _System_EcuConfiguration_EPS_Main_ECU_EcuFlatView_NvBlkSWC_SimpleVar                   SWCI103
#define _System_EcuConfiguration_EPS_Main_ECU_EcuFlatView_NvBlkSWC_SteeringRangeTracker        SWCI89
#define _System_EcuConfiguration_EPS_Main_ECU_EcuFlatView_NvBlkSWC_SwEndStop                   SWCI34
#define _System_EcuConfiguration_EPS_Main_ECU_EcuFlatView_NvBlkSWC_TaskControl                 SWCI26
#define _System_EcuConfiguration_EPS_Main_ECU_EcuFlatView_NvBlkSWC_VariantHandling             SWCI104
#define _System_EcuConfiguration_EPS_Main_ECU_EcuFlatView_NvBlkSWC_WormWheelDamageTracker      SWCI20
#define _System_EcuConfiguration_EPS_Main_ECU_EcuFlatView_NvM                                  SWCI74
#define _System_EcuConfiguration_EPS_Main_ECU_EcuFlatView_OsMonitoring                         SWCI38
#define _System_EcuConfiguration_EPS_Main_ECU_EcuFlatView_PAMotTrqSum                          SWCI121
#define _System_EcuConfiguration_EPS_Main_ECU_EcuFlatView_PatternGenerator                     SWCI13
#define _System_EcuConfiguration_EPS_Main_ECU_EcuFlatView_ProductionServices_L_Adapter         SWCI112
#define _System_EcuConfiguration_EPS_Main_ECU_EcuFlatView_ProductionUDS                        SWCI29
#define _System_EcuConfiguration_EPS_Main_ECU_EcuFlatView_RTAOS                                SWCI124
#define _System_EcuConfiguration_EPS_Main_ECU_EcuFlatView_RackPositionCorrection               SWCI41
#define _System_EcuConfiguration_EPS_Main_ECU_EcuFlatView_RackPositionCorrectionSupp           SWCI42
#define _System_EcuConfiguration_EPS_Main_ECU_EcuFlatView_RackPositionMain                     SWCI43
#define _System_EcuConfiguration_EPS_Main_ECU_EcuFlatView_RackPositionMainSupp_100FIT          SWCI168
#define _System_EcuConfiguration_EPS_Main_ECU_EcuFlatView_RackPositionSynchronization          SWCI136
#define _System_EcuConfiguration_EPS_Main_ECU_EcuFlatView_RotorSpeed                           SWCI31
#define _System_EcuConfiguration_EPS_Main_ECU_EcuFlatView_SAC_SWC                              SWCI146
#define _System_EcuConfiguration_EPS_Main_ECU_EcuFlatView_SCruiseFader                         SWCI200
#define _System_EcuConfiguration_EPS_Main_ECU_EcuFlatView_SCruiseFaderChk                      SWCI202
#define _System_EcuConfiguration_EPS_Main_ECU_EcuFlatView_SCruiseFaderDrvrIntvIndcn            SWCI201
#define _System_EcuConfiguration_EPS_Main_ECU_EcuFlatView_SCruiseInpLimr                       SWCI198
#define _System_EcuConfiguration_EPS_Main_ECU_EcuFlatView_SCruiseLimrCouplr                    SWCI196
#define _System_EcuConfiguration_EPS_Main_ECU_EcuFlatView_SCruiseMaxRackSpd                    SWCI193
#define _System_EcuConfiguration_EPS_Main_ECU_EcuFlatView_SCruiseMaxRackSpdChk                 SWCI192
#define _System_EcuConfiguration_EPS_Main_ECU_EcuFlatView_SCruiseRackSpdLimr                   SWCI195
#define _System_EcuConfiguration_EPS_Main_ECU_EcuFlatView_SCruiseRackSpdLimrChk                SWCI194
#define _System_EcuConfiguration_EPS_Main_ECU_EcuFlatView_SCruiseSigPrcrCdng                   SWCI199
#define _System_EcuConfiguration_EPS_Main_ECU_EcuFlatView_SCruiseState                         SWCI197
#define _System_EcuConfiguration_EPS_Main_ECU_EcuFlatView_SFD_Wrapper                          SWCI159
#define _System_EcuConfiguration_EPS_Main_ECU_EcuFlatView_SacHandling                          SWCI165
#define _System_EcuConfiguration_EPS_Main_ECU_EcuFlatView_SacMonitor                           SWCI142
#define _System_EcuConfiguration_EPS_Main_ECU_EcuFlatView_SafCtrl                              SWCI21
#define _System_EcuConfiguration_EPS_Main_ECU_EcuFlatView_SafCtrlCheck                         SWCI22
#define _System_EcuConfiguration_EPS_Main_ECU_EcuFlatView_SafetyRampController                 SWCI81
#define _System_EcuConfiguration_EPS_Main_ECU_EcuFlatView_SecOC                                SWCI130
#define _System_EcuConfiguration_EPS_Main_ECU_EcuFlatView_ServoSlipDetection                   SWCI150
#define _System_EcuConfiguration_EPS_Main_ECU_EcuFlatView_SfdA                                 SWCI158
#define _System_EcuConfiguration_EPS_Main_ECU_EcuFlatView_ShA                                  SWCI162
#define _System_EcuConfiguration_EPS_Main_ECU_EcuFlatView_ShutCo_DualUc                        SWCI62
#define _System_EcuConfiguration_EPS_Main_ECU_EcuFlatView_ShutdownPermission                   SWCI60
#define _System_EcuConfiguration_EPS_Main_ECU_EcuFlatView_SignalConditioning                   SWCI149
#define _System_EcuConfiguration_EPS_Main_ECU_EcuFlatView_SimpleVarMeasurement                 SWCI105
#define _System_EcuConfiguration_EPS_Main_ECU_EcuFlatView_SmtActrRackPosCtrl                   SWCI203
#define _System_EcuConfiguration_EPS_Main_ECU_EcuFlatView_SmtActrRackPosCtrlCheck              SWCI204
#define _System_EcuConfiguration_EPS_Main_ECU_EcuFlatView_SmtActrTorqueVibrationCheck          SWCI207
#define _System_EcuConfiguration_EPS_Main_ECU_EcuFlatView_SmtActrTorqueVibrationMain           SWCI206
#define _System_EcuConfiguration_EPS_Main_ECU_EcuFlatView_SteeringControlV2                    SWCI118
#define _System_EcuConfiguration_EPS_Main_ECU_EcuFlatView_SteeringGearCorrection               SWCI172
#define _System_EcuConfiguration_EPS_Main_ECU_EcuFlatView_SteeringRangeTracker                 SWCI88
#define _System_EcuConfiguration_EPS_Main_ECU_EcuFlatView_Stubs                                SWCI45
#define _System_EcuConfiguration_EPS_Main_ECU_EcuFlatView_SubConnMotTrqSumAfterMtl             SWCI47
#define _System_EcuConfiguration_EPS_Main_ECU_EcuFlatView_SubConnMotTrqSumAfterSCI             SWCI113
#define _System_EcuConfiguration_EPS_Main_ECU_EcuFlatView_SubConnMotTrqSumBeforeMtl            SWCI48
#define _System_EcuConfiguration_EPS_Main_ECU_EcuFlatView_SubConnSteerTrqSum                   SWCI49
#define _System_EcuConfiguration_EPS_Main_ECU_EcuFlatView_SwCompatibilityCheck                 SWCI119
#define _System_EcuConfiguration_EPS_Main_ECU_EcuFlatView_SystemData                           SWCI106
#define _System_EcuConfiguration_EPS_Main_ECU_EcuFlatView_SystemTimer                          SWCI25
#define _System_EcuConfiguration_EPS_Main_ECU_EcuFlatView_T1                                   SWCI36
#define _System_EcuConfiguration_EPS_Main_ECU_EcuFlatView_TaskControl                          SWCI27
#define _System_EcuConfiguration_EPS_Main_ECU_EcuFlatView_TemperatureTracker                   SWCI92
#define _System_EcuConfiguration_EPS_Main_ECU_EcuFlatView_TorqueCorrector                      SWCI171
#define _System_EcuConfiguration_EPS_Main_ECU_EcuFlatView_TorqueReductionCoordinator           SWCI30
#define _System_EcuConfiguration_EPS_Main_ECU_EcuFlatView_TorqueSensorFallback                 SWCI50
#define _System_EcuConfiguration_EPS_Main_ECU_EcuFlatView_TorqueSensorFallbackCheck            SWCI51
#define _System_EcuConfiguration_EPS_Main_ECU_EcuFlatView_TorqueSignalConditioningCheck        SWCI84
#define _System_EcuConfiguration_EPS_Main_ECU_EcuFlatView_TorqueSignalConditioningGradient     SWCI55
#define _System_EcuConfiguration_EPS_Main_ECU_EcuFlatView_TorqueSignalConditioningMain         SWCI53
#define _System_EcuConfiguration_EPS_Main_ECU_EcuFlatView_TorqueSignalConditioningMinimum      SWCI52
#define _System_EcuConfiguration_EPS_Main_ECU_EcuFlatView_TorqueSignalConditioningPlausi       SWCI100
#define _System_EcuConfiguration_EPS_Main_ECU_EcuFlatView_TorqueSignalConditioningSupp         SWCI54
#define _System_EcuConfiguration_EPS_Main_ECU_EcuFlatView_TqSigCdngMin                         flatInstance_TqSigCdngMin
#define _System_EcuConfiguration_EPS_Main_ECU_EcuFlatView_VehicleIdentification                SWCI173
#define _System_EcuConfiguration_EPS_Main_ECU_EcuFlatView_VehicleSpeedCheck                    SWCI56
#define _System_EcuConfiguration_EPS_Main_ECU_EcuFlatView_VehicleSpeedSafe                     SWCI57
#define _System_EcuConfiguration_EPS_Main_ECU_EcuFlatView_VehicleSpeedWrapper4Old              SWCI58
#define _System_EcuConfiguration_EPS_Main_ECU_EcuFlatView_WarningLightCalculation              SWCI147
#define _System_EcuConfiguration_EPS_Main_ECU_EcuFlatView_WipingController                     SWCI111
#define _System_EcuConfiguration_EPS_Main_ECU_EcuFlatView_WormWheelDamageTracker               SWCI19
#define _System_EcuConfiguration_EPS_Main_ECU_EcuFlatView_XcpCallouts                          SWCI107
#define _System_EcuConfiguration_EPS_Main_ECU_EcuFlatView_rbo_CanTrcvCdd                       SWCI210
#define _System_EcuConfiguration_EPS_Main_ECU_EcuFlatView_rbo_Mpu                              SWCI85
#define _System_EcuConfiguration_EPS_Main_ECU_EcuFlatView_rbo_NmCdd                            SWCI122
/* Box: Rte: OS Environment begin */
/* The following OSENV_ macros are supported by this OS DLL: */
/* OSENV_UNSUPPORTED */
/* OSENV_RTAOS40 */
#if defined(OSENV_RTAOS40)
#if defined(OSENV_UNSUPPORTED)
#error "Please define exactly one of [ OSENV_RTAOS40, OSENV_UNSUPPORTED ] for OS_AUTOSAR40 OS API."
#endif /* defined(OSENV_UNSUPPORTED) */
#elif defined(OSENV_UNSUPPORTED)
#else
#error "Please define exactly one of [ OSENV_RTAOS40, OSENV_UNSUPPORTED ] for OS_AUTOSAR40 OS API."
#endif
/* Box: User declared atomic BSW types: begin */
/*   boolean */
/*   float */
/*   sint16 */
/*   sint32 */
/*   sint8 */
/*   uint16 */
/*   uint32 */
/*   uint8 */
/* Box: User declared atomic BSW types: end */
/* Box: Rte: OS Environment end */

#endif /* !RTE_CONST_H */
