<?xml version="1.0" encoding="UTF-8"?>
<xs:schema targetNamespace="www.rbin.com/mds-1" xmlns="www.rbin.com/mds-1" xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xs:element name="CONF">
        <xs:annotation>
            <xs:documentation>CONF Tag is the root of all tags.</xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="HEXMOD"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="HEXMOD">
        <xs:annotation>
            <xs:documentation>Hexmod Tag is the basic tag for all the modules.This tag always comes after CONF tag. It represents the following content is for Hexmod tool to process</xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:sequence>
                <xs:element name="ENCRYPT" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="BLOCK" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:attribute name="START" type="eAddrMin" use="required"/>
                                    <xs:attribute name="LEN" type="eAddrMax" use="required"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="ALGO" type="xs:string" use="required"/>
                        <xs:attribute
                            name="KEY"
                            use="optional">
                            <xs:simpleType>
                                <xs:restriction base="xs:string">
                                    <xs:length value="34"></xs:length>
                                    <xs:pattern value="[0]x[a-fA-F0-9]*"></xs:pattern>
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:attribute>
                        <xs:attribute
                            name="VECTOR"
                            use="optional">
                            <xs:simpleType>
                                <xs:restriction base="xs:string">
                                    <xs:length value="34"></xs:length>
                                    <xs:pattern value="[0]x[a-fA-F0-9]*"></xs:pattern>
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:attribute>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:simpleType name="action">
        <xs:restriction base="xs:string">
            <xs:enumeration value="COPY"/>
            <xs:enumeration value="DEL"/>
            <xs:enumeration value="MOVE"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="filetype">
        <xs:restriction base="xs:string">
            <xs:enumeration value="S19"/>
            <xs:enumeration value="IHEX"/>
        </xs:restriction>
    </xs:simpleType>
    <!-- Removed from Version 3.1.1.0 as not used />
    <xs:simpleType name="layout">
        <xs:restriction base="xs:string">
            <xs:maxLength value="4"/>
            <xs:minLength value="3"/>
            <xs:pattern value="[0]x[1-2][a-fA-F0-9]"/>
        </xs:restriction>
    </xs:simpleType-->
    <xs:simpleType name="exhexBinary">
        <xs:restriction base="xs:string">
            <xs:maxLength value="10"/>
            <xs:minLength value="3"/>
            <xs:pattern value="[0]x[a-fA-F0-9]*"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="exLvl">
        <xs:restriction base="xs:unsignedByte">
            <xs:minInclusive value="1"/>
            <xs:maxInclusive value="4"/>
        </xs:restriction>
    </xs:simpleType>
    <!-- Removed from Version 3.1.1.0 as not used />
    <xs:simpleType name="mode">
        <xs:restriction base="xs:string">
            <xs:enumeration value="BigEndian"/>
            <xs:enumeration value="LittleEndian"/>
        </xs:restriction>
    </xs:simpleType-->
    <xs:simpleType name="exLvl2">
        <xs:restriction base="xs:unsignedByte">
            <xs:minInclusive value="2"/>
            <xs:maxInclusive value="3"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="eAddrMax">
        <xs:restriction base="xs:string">
            <xs:maxLength value="10"/>
            <xs:minLength value="3"/>
            <xs:pattern value="[0]x[a-fA-F0-9]*|MAXADDRESS"/>
        </xs:restriction>
    </xs:simpleType>
     <xs:simpleType name="eAddrMin">
        <xs:restriction base="xs:string">
            <xs:maxLength value="10"/>
            <xs:minLength value="3"/>
            <xs:pattern value="[0]x[a-fA-F0-9]*|MINADDRESS"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="exFillBinary">
        <xs:annotation>
            <xs:documentation> to have values from 0x0 to 0xFF</xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:string">
            <xs:maxLength value="4"/>
            <xs:minLength value="4"/>
            <xs:pattern value="[0]x[a-fA-F0-9]*"/>
        </xs:restriction>
    </xs:simpleType>

</xs:schema>
