/*-----------------------------------------------------------------------*/
/* File Identifier on server    $Id: asc_swc.h 254 2024-09-27 09:19:52Z VWQCRBZ $ */
/* File location on server $HeadURL: https://subversion.wob.vw.vwg/SWIfaceMxB26/Branches/MQB41BW_V0091_Bosch_100Fit_Auslieferung_LSMQBWASIL-190/20_ENG/Units/ASC/Product/INC/asc_swc.h $ */
/*-----------------------------------------------------------------------*/

/* Spezifikation "AutosarEPSInterface Baseline 2.1" */

		
/**************************************************************************************************\
 *** 
 *** Simulink model       : ASC
 *** TargetLink subsystem : ASC/TL_Ignore_ASC
 *** Codefile             : asc_swc.h
 ***
 *** Generated by TargetLink, the dSPACE production quality code generator
 *** Generation date: 2024-09-27 11:13:41
 ***
 *** CODE GENERATOR OPTIONS:
 *** Code generation mode                     : Classic AUTOSAR
 *** AUTOSAR version                          : 4.4.0
 *** Compiler                                 : <unknown>
 *** Target                                   : Generic
 *** ANSI-C compatible code                   : yes
 *** Code Optimization                        : enabled
 *** Constant style                           : decimal
 *** Clean code option                        : enabled
 *** Logging mode                             : Do not log anything
 *** Code Coverage                            : disabled
 *** Generate empty conditional branches      : enabled
 *** Loop unroll threshold                    : 5
 *** Utilize bitwise shift operations         : Never
 *** Handle unscaled SF expr. with TL type    : enabled
 *** Assignment of conditions                 : AllBooleanOutputs 
 *** Scope reduction only to function level   : disabled
 *** Exploit ranges if not erasable           : disabled
 *** Exploit Compute Through Overflow         : optimized
 *** Linker sections                          : enabled
 *** Enable Assembler                         : disabled
 *** Variable name length                     : unlimited
 *** Use global bitfields                     : enabled
 *** Stateflow: use of bitfields              : enabled
 *** State activity encoding limit            : 5
 *** Omit zero inits in restart function      : disabled
 *** Share functions between TL subsystems    : disabled
 *** Generate 64bit functions                 : enabled
 *** Inlining Threshold                       : 6
 *** Line break limit                         : 100
 *** Target optimized boolean data type       : enabled
 *** Keep saturation elements                 : disabled
 *** Extended variable sharing                : disabled
 *** Extended lifetime optimization           : enabled
 *** Style definition file                    : C:\Program Files\dSPACE TargetLink 5.0\matlab\tl\con
 ***                                            fig\codegen\cconfig.xml
 *** Root style sheet                         : C:\Program Files\dSPACE TargetLink 5.0\Matlab\Tl\XML
 ***                                            \CodeGen\Stylesheets\TL_CSourceCodeSS.xsl
 ***
 *** TargetLink version      : 5.0 from 02-Oct-2019
 *** Code generator version  : Build Id 5.0.0.24 from 2019-10-07 12:46:33
\**************************************************************************************************/

#ifndef ASC_SWC_H
#define ASC_SWC_H
/* line(s) below inserted by custom_post_codegen_hook */
#define DVERASC_SWC_H "$Rev:: 254   $"
/* line(s) above inserted by custom_post_codegen_hook */

/*------------------------------------------------------------------------------------------------*\
  DEFINES (OPT)
\*------------------------------------------------------------------------------------------------*/
/*------------------------------------------------------------------------------------------------*\
  INCLUDES
\*------------------------------------------------------------------------------------------------*/

#include "Rte_Type.h"
#include "tl_defines_asc.h"

#ifdef __cplusplus
extern "C" {
#endif

/*------------------------------------------------------------------------------------------------*\
  ENUMS
\*------------------------------------------------------------------------------------------------*/
/*------------------------------------------------------------------------------------------------*\
  DEFINES
\*------------------------------------------------------------------------------------------------*/
/*------------------------------------------------------------------------------------------------*\
  TYPEDEFS
\*------------------------------------------------------------------------------------------------*/

struct tag_GIBFS_asc__tp {
   unsigned int StARS10_ROWD : 1;
   unsigned int StARS12_ROWD : 1;
   unsigned int StARS15_ROWD : 1;
   unsigned int StARS16_ROWD : 1;
   unsigned int StARS17_ROWD : 1;
   unsigned int StARS9_ROWD : 1;
   unsigned int StGER8_S_R_Flip_Flop1_Q : 1;
   unsigned int StGER8_S_R_Flip_Flop_Lern_L_Q : 1;
   unsigned int StPHV10_ROWD : 1;
   unsigned int StPHV11_ROWD : 1;
   unsigned int StPHV12_ROWD : 1;
   unsigned int StPHV13_ROWD : 1;
   unsigned int StPHV2_ROWD : 1;
   unsigned int StPHV3_ROWD : 1;
   unsigned int StPHV4_ROWD : 1;
   unsigned int StPHV5_ROWD : 1;
   unsigned int StPHV6_ROWD : 1;
   unsigned int StPHV7_ROWD : 1;
   unsigned int StPHV8_ROWD : 1;
   unsigned int StPHV9_ROWD : 1;
   unsigned int StTRQ2_ROWD : 1;
   unsigned int StTRQ3_ROWD : 1;
   unsigned int StTRQ6_ROWD : 1;
   unsigned int StVFZ2_ROWD : 1;
   unsigned int StVFZ3_ROWD : 1;
   unsigned int StVFZ4_ROWD : 1;
   unsigned int X_StGER8_Unit_Delay15 : 1;
   unsigned int X_StGER9_Unit_Delay3 : 1;
   unsigned int X_StTSC_Lang1_Unit_Delay1 : 1;
};

/*------------------------------------------------------------------------------------------------*\
  VARIABLES
\*------------------------------------------------------------------------------------------------*/

/**************************************************************************************************\
   CONST: global constants (ROM) | Width: 32
\**************************************************************************************************/
extern const sint32 DD_StTSC_Lang3_Null; /* 
   LSB: 2^-26 OFF: 0
   Description: TSC Basiswert */

/**************************************************************************************************\
   CONST: global constants (ROM) | Width: 16
\**************************************************************************************************/
extern const uint16 DD_StTSC_LaenX1_Null3; /* Description: Null */
extern const uint16 DD_StTSC_Laeng1_Null1; /* 
   LSB: 2^-15 OFF: 0
   Description: Null */
extern const uint16 DD_StTSC_Laeng2_TSC_FAKTOR_MS; /* 
   LSB: 2^-15 OFF: 0
   Description: Faktor m/s */
extern const uint16 DD_StTSC_TAus1_Null1; /* 
   LSB: 2^-5 OFF: 0
   Description: Null */
extern const uint16 DD_StTSC_TAus1_Null2; /* 
   LSB: 2^-5 OFF: 0
   Description: Null */
extern const uint16 DD_StTSC_TAus1_Null3; /* Description: Null */
extern const uint16 DD_StTSC_TAus2_Null2; /* 
   LSB: 2^-12 OFF: 0
   Description: Null */
extern const uint16 DD_StTSC_TAus2_Null4; /* 
   LSB: 2^-12 OFF: 0
   Description: Null */
extern const uint16 StTSC_LaenX1_Gewichtskraft_gain; /* LSB: 2^-12 OFF: 0 */
extern const uint16 StTSC_LaenX1_m_s_gain; /* LSB: 2^-14 OFF: 0 */
extern const uint16 StTSC_Lernb3_Eins; /* LSB: 2^-15 OFF: 0 */
extern const uint16 StTSC_Lernb3_Eins2; /* LSB: 2^-15 OFF: 0 */

/**************************************************************************************************\
   CONST: global constants (ROM) | Width: 8
\**************************************************************************************************/
extern const uint8 DD_Sasc8_Start; /* Description: Eins */
extern const uint8 DD_StTSC1_Start1; /* Description: Eins */
extern const uint8 DD_StTSC1_Start2; /* Description: Eins */
extern const uint8 StTSC_Lernb3_Eins1;
extern const uint8 StTSC_Lernb3_Null;

#ifndef USE_CST_PARAM_STRUCT_H
/**************************************************************************************************\
   DISP_XTR: global observable variables (RAM) | Width: 16
\**************************************************************************************************/
extern DISP_XTR sint16 DD_StARS1_ars_fSoll_mi16; /* Description: Unterstützungskraft aus Softwaremod
   ul  */
#endif /*USE_CST_PARAM_STRUCT_H*/

/*------------------------------------------------------------------------------------------------*\
  PARAMETERIZED MACROS
\*------------------------------------------------------------------------------------------------*/
/*------------------------------------------------------------------------------------------------*\
  FUNCTION PROTOTYPES
\*------------------------------------------------------------------------------------------------*/

/**************************************************************************************************\
   GLOBAL_FCN: global function(s) (exported to other modules)
\**************************************************************************************************/
extern void ASC_Controller_runnable(void);
extern void ASC_Init_runnable(void);

#ifdef __cplusplus
}
#endif

#endif /* ASC_SWC_H */
/*------------------------------------------------------------------------------------------------*\
  END OF FILE
\*------------------------------------------------------------------------------------------------*/
