/*-----------------------------------------------------------------------*/
/* File Identifier on server    $Id: sac_swc.h 254 2024-09-27 09:19:52Z VWQCRBZ $ */
/* File location on server $HeadURL: https://subversion.wob.vw.vwg/SWIfaceMxB26/Branches/MQB41BW_V0091_Bosch_100Fit_Auslieferung_LSMQBWASIL-190/20_ENG/Units/SAC/Product/INC/sac_swc.h $ */
/*-----------------------------------------------------------------------*/

/* Spezifikation "AutosarEPSInterface Baseline 2.1" */

		
/**************************************************************************************************\
 *** 
 *** Simulink model       : SAC
 *** TargetLink subsystem : SAC/TL_Ignore_SAC
 *** Codefile             : sac_swc.h
 ***
 *** Generated by TargetLink, the dSPACE production quality code generator
 *** Generation date: 2024-09-27 11:16:11
 ***
 *** CODE GENERATOR OPTIONS:
 *** Code generation mode                     : Classic AUTOSAR
 *** AUTOSAR version                          : 4.4.0
 *** Compiler                                 : <unknown>
 *** Target                                   : Generic
 *** ANSI-C compatible code                   : yes
 *** Code Optimization                        : enabled
 *** Constant style                           : decimal
 *** Clean code option                        : enabled
 *** Logging mode                             : Do not log anything
 *** Code Coverage                            : disabled
 *** Generate empty conditional branches      : enabled
 *** Loop unroll threshold                    : 5
 *** Utilize bitwise shift operations         : Never
 *** Handle unscaled SF expr. with TL type    : enabled
 *** Assignment of conditions                 : AllBooleanOutputs 
 *** Scope reduction only to function level   : disabled
 *** Exploit ranges if not erasable           : disabled
 *** Exploit Compute Through Overflow         : optimized
 *** Linker sections                          : enabled
 *** Enable Assembler                         : disabled
 *** Variable name length                     : unlimited
 *** Use global bitfields                     : enabled
 *** Stateflow: use of bitfields              : enabled
 *** State activity encoding limit            : 5
 *** Omit zero inits in restart function      : disabled
 *** Share functions between TL subsystems    : disabled
 *** Generate 64bit functions                 : enabled
 *** Inlining Threshold                       : 6
 *** Line break limit                         : 100
 *** Target optimized boolean data type       : enabled
 *** Keep saturation elements                 : disabled
 *** Extended variable sharing                : disabled
 *** Extended lifetime optimization           : enabled
 *** Style definition file                    : C:\Program Files\dSPACE TargetLink 5.0\matlab\tl\con
 ***                                            fig\codegen\cconfig.xml
 *** Root style sheet                         : C:\Program Files\dSPACE TargetLink 5.0\Matlab\Tl\XML
 ***                                            \CodeGen\Stylesheets\TL_CSourceCodeSS.xsl
 ***
 *** TargetLink version      : 5.0 from 02-Oct-2019
 *** Code generator version  : Build Id 5.0.0.24 from 2019-10-07 12:46:33
\**************************************************************************************************/

#ifndef SAC_SWC_H
#define SAC_SWC_H
/* line(s) below inserted by custom_post_codegen_hook */
#define DVERSAC_SWC_H "$Rev:: 254   $"
/* line(s) above inserted by custom_post_codegen_hook */

/*------------------------------------------------------------------------------------------------*\
  DEFINES (OPT)
\*------------------------------------------------------------------------------------------------*/
/*------------------------------------------------------------------------------------------------*\
  INCLUDES
\*------------------------------------------------------------------------------------------------*/

#include "Rte_Type.h"
#include "tl_defines_sac.h"

#ifdef __cplusplus
extern "C" {
#endif

/*------------------------------------------------------------------------------------------------*\
  ENUMS
\*------------------------------------------------------------------------------------------------*/
/*------------------------------------------------------------------------------------------------*\
  DEFINES
\*------------------------------------------------------------------------------------------------*/
/*------------------------------------------------------------------------------------------------*\
  TYPEDEFS
\*------------------------------------------------------------------------------------------------*/

struct tag_GIBFS_sac__tp {
   unsigned int StQPR_A11_ROWD : 1;
   unsigned int StQPR_A11_RSWE : 1;
   unsigned int StQPR_B3_ROWD : 1;
   unsigned int StQPR_B3_RSWE : 1;
};

struct tag_SIBFS_QAP_SFL_Priorisierung_SM_Main_tQAP_B_tp {
   unsigned int CtQAP_B2_S02_QFKTN_AKTIV : 1;
   unsigned int CtQAP_B3_S06_QAP_ST_PRIOMAIN_EINGRIFF_COMFORT : 1;
   unsigned int CtQAP_B4_S02_QAP_ST_PRIOMAIN_READY : 1;
   unsigned int CtQAP_B5_S07_QAP_ST_PRIOMAIN_EINGRIFF_EMERGENCY : 1;
   unsigned int CtQAP_B6_S01_QAP_ST_PRIOMAIN_INIT : 1;
}; /* Description: Type of structure containing bitfields for Stateflow chart  */

struct tag_SIBFS_QAP_SFL_Priorisierung_TN_Comfort_tQAP_B_tp {
   unsigned int CtQAP_B7_QAP_SFL_Priorisierung_TN_Comfort_ns : 4;
}; /* Description: Type of structure containing bitfields for Stateflow chart  */

struct tag_SIBFS_QAP_SFL_Priorisierung_TN_Emergency_tQAP_B_tp {
   unsigned int CtQAP_B16_QAP_SFL_Priorisierung_TN_Emergency_ns : 3;
}; /* Description: Type of structure containing bitfields for Stateflow chart  */

struct tag_SIBFS_QAP_SFL_Zustandsautomat_Main_tQAP_A_tp {
   unsigned int CtQAP_A10_S08_QAP_ST_MAIN2CAN_FEHLER_ME : 1;
   unsigned int CtQAP_A11_S07_QAP_ST_MAIN2CAN_FEHLER_OE : 1;
   unsigned int CtQAP_A2_S03_SUB_QFKMAIN_EINGRIFF : 1;
   unsigned int CtQAP_A3_S04_SUB_QFKMAIN_REGELUNG : 1;
   unsigned int CtQAP_A4_S12_QAP_ST_MAIN2CAN_EINGRIFF_ED : 1;
   unsigned int CtQAP_A5_S06_QAP_ST_MAIN2CAN_EINGRIFF : 1;
   unsigned int CtQAP_A6_S13_QAP_ST_MAIN2CAN_EINGRIFF_HANDSOFF : 1;
   unsigned int CtQAP_A7_S05_QAP_ST_MAIN2CAN_ABBRUCH : 1;
   unsigned int CtQAP_A8_S02_QAP_ST_MAIN2CAN_READY : 1;
   unsigned int CtQAP_A9_S01_QAP_ST_MAIN2CAN_INIT : 1;
}; /* Description: Type of structure containing bitfields for Stateflow chart  */

struct tag_SIBFS_QAP_SFL_Zustandsautomat_Tn05_tQAP_G_tp {
   unsigned int CtQAP_G10_S32_QAP_ST_SMTNX_READY_ANFR : 1;
   unsigned int CtQAP_G11_S04_QAP_ST_SMTNX_GESPERRT : 1;
   unsigned int CtQAP_G12_S08_QAP_ST_SMTNX_ABBRUCH : 1;
   unsigned int CtQAP_G13_S09_QAP_ST_SMTNX_FEHLER_ME : 1;
   unsigned int CtQAP_G14_S10_QAP_ST_SMTNX_FEHLER_OE : 1;
   unsigned int CtQAP_G15_S00_QAP_ST_SMTNX_DEAKTIV : 1;
   unsigned int CtQAP_G16_S01_QAP_ST_SMTNX_INIT : 1;
   unsigned int CtQAP_G2_S1_QAP_AKTIV : 1;
   unsigned int CtQAP_G3_S2_QAP_EINGRIFF_STATUS : 1;
   unsigned int CtQAP_G4_S4_QAP_EINGRIFF : 1;
   unsigned int CtQAP_G5_S12_QAP_ST_SMTNX_EINGRIFF_ED : 1;
   unsigned int CtQAP_G6_S13_QAP_ST_SMTNX_EINGRIFF_HANDSOFF : 1;
   unsigned int CtQAP_G7_S06_QAP_ST_SMTNX_EINGRIFF : 1;
   unsigned int CtQAP_G8_S3_QAP_READY2EINGRIFF : 1;
   unsigned int CtQAP_G9_S02_QAP_ST_SMTNX_READY : 1;
}; /* Description: Type of structure containing bitfields for Stateflow chart  */

struct tag_SIBFS_QAP_SFL_Zustandsautomat_TnXX_tQAP_C_tp {
   unsigned int CtQAP_C10_S04_QAP_ST_SMTNX_GESPERRT : 1;
   unsigned int CtQAP_C11_S08_QAP_ST_SMTNX_ABBRUCH : 1;
   unsigned int CtQAP_C12_S09_QAP_ST_SMTNX_FEHLER_ME : 1;
   unsigned int CtQAP_C13_S10_QAP_ST_SMTNX_FEHLER_OE : 1;
   unsigned int CtQAP_C14_S00_QAP_ST_SMTNX_DEAKTIV : 1;
   unsigned int CtQAP_C15_S01_QAP_ST_SMTNX_INIT : 1;
   unsigned int CtQAP_C2_S1_QAP_AKTIV : 1;
   unsigned int CtQAP_C3_S2_QAP_EINGRIFF_STATUS : 1;
   unsigned int CtQAP_C4_S4_QAP_EINGRIFF : 1;
   unsigned int CtQAP_C5_S12_QAP_ST_SMTNX_EINGRIFF_ED : 1;
   unsigned int CtQAP_C6_S06_QAP_ST_SMTNX_EINGRIFF : 1;
   unsigned int CtQAP_C7_S3_QAP_READY2EINGRIFF : 1;
   unsigned int CtQAP_C8_S02_QAP_ST_SMTNX_READY : 1;
   unsigned int CtQAP_C9_S32_QAP_ST_SMTNX_READY_ANFR : 1;
}; /* Description: Type of structure containing bitfields for Stateflow chart  */

struct tag_SIBFS_QAP_SFL_Zustandsautomat_TnXX_tQAP_D_tp {
   unsigned int CtQAP_D10_S04_QAP_ST_SMTNX_GESPERRT : 1;
   unsigned int CtQAP_D11_S08_QAP_ST_SMTNX_ABBRUCH : 1;
   unsigned int CtQAP_D12_S09_QAP_ST_SMTNX_FEHLER_ME : 1;
   unsigned int CtQAP_D13_S10_QAP_ST_SMTNX_FEHLER_OE : 1;
   unsigned int CtQAP_D14_S00_QAP_ST_SMTNX_DEAKTIV : 1;
   unsigned int CtQAP_D15_S01_QAP_ST_SMTNX_INIT : 1;
   unsigned int CtQAP_D2_S1_QAP_AKTIV : 1;
   unsigned int CtQAP_D3_S2_QAP_EINGRIFF_STATUS : 1;
   unsigned int CtQAP_D4_S4_QAP_EINGRIFF : 1;
   unsigned int CtQAP_D5_S12_QAP_ST_SMTNX_EINGRIFF_ED : 1;
   unsigned int CtQAP_D6_S06_QAP_ST_SMTNX_EINGRIFF : 1;
   unsigned int CtQAP_D7_S3_QAP_READY2EINGRIFF : 1;
   unsigned int CtQAP_D8_S02_QAP_ST_SMTNX_READY : 1;
   unsigned int CtQAP_D9_S32_QAP_ST_SMTNX_READY_ANFR : 1;
}; /* Description: Type of structure containing bitfields for Stateflow chart  */

struct tag_SIBFS_QAP_SFL_Zustandsautomat_TnXX_tQAP_E_tp {
   unsigned int CtQAP_E10_S04_QAP_ST_SMTNX_GESPERRT : 1;
   unsigned int CtQAP_E11_S08_QAP_ST_SMTNX_ABBRUCH : 1;
   unsigned int CtQAP_E12_S09_QAP_ST_SMTNX_FEHLER_ME : 1;
   unsigned int CtQAP_E13_S10_QAP_ST_SMTNX_FEHLER_OE : 1;
   unsigned int CtQAP_E14_S00_QAP_ST_SMTNX_DEAKTIV : 1;
   unsigned int CtQAP_E15_S01_QAP_ST_SMTNX_INIT : 1;
   unsigned int CtQAP_E2_S1_QAP_AKTIV : 1;
   unsigned int CtQAP_E3_S2_QAP_EINGRIFF_STATUS : 1;
   unsigned int CtQAP_E4_S4_QAP_EINGRIFF : 1;
   unsigned int CtQAP_E5_S12_QAP_ST_SMTNX_EINGRIFF_ED : 1;
   unsigned int CtQAP_E6_S06_QAP_ST_SMTNX_EINGRIFF : 1;
   unsigned int CtQAP_E7_S3_QAP_READY2EINGRIFF : 1;
   unsigned int CtQAP_E8_S02_QAP_ST_SMTNX_READY : 1;
   unsigned int CtQAP_E9_S32_QAP_ST_SMTNX_READY_ANFR : 1;
}; /* Description: Type of structure containing bitfields for Stateflow chart  */

struct tag_SIBFS_QAP_SFL_Zustandsautomat_TnXX_tQAP_F_tp {
   unsigned int CtQAP_F10_S04_QAP_ST_SMTNX_GESPERRT : 1;
   unsigned int CtQAP_F11_S08_QAP_ST_SMTNX_ABBRUCH : 1;
   unsigned int CtQAP_F12_S09_QAP_ST_SMTNX_FEHLER_ME : 1;
   unsigned int CtQAP_F13_S10_QAP_ST_SMTNX_FEHLER_OE : 1;
   unsigned int CtQAP_F14_S00_QAP_ST_SMTNX_DEAKTIV : 1;
   unsigned int CtQAP_F15_S01_QAP_ST_SMTNX_INIT : 1;
   unsigned int CtQAP_F2_S1_QAP_AKTIV : 1;
   unsigned int CtQAP_F3_S2_QAP_EINGRIFF_STATUS : 1;
   unsigned int CtQAP_F4_S4_QAP_EINGRIFF : 1;
   unsigned int CtQAP_F5_S12_QAP_ST_SMTNX_EINGRIFF_ED : 1;
   unsigned int CtQAP_F6_S06_QAP_ST_SMTNX_EINGRIFF : 1;
   unsigned int CtQAP_F7_S3_QAP_READY2EINGRIFF : 1;
   unsigned int CtQAP_F8_S02_QAP_ST_SMTNX_READY : 1;
   unsigned int CtQAP_F9_S32_QAP_ST_SMTNX_READY_ANFR : 1;
}; /* Description: Type of structure containing bitfields for Stateflow chart  */

struct tag_SIBFS_QAP_SFL_Zustandsautomat_TnXX_tQAP_H_tp {
   unsigned int CtQAP_H10_S04_QAP_ST_SMTNX_GESPERRT : 1;
   unsigned int CtQAP_H11_S08_QAP_ST_SMTNX_ABBRUCH : 1;
   unsigned int CtQAP_H12_S09_QAP_ST_SMTNX_FEHLER_ME : 1;
   unsigned int CtQAP_H13_S10_QAP_ST_SMTNX_FEHLER_OE : 1;
   unsigned int CtQAP_H14_S00_QAP_ST_SMTNX_DEAKTIV : 1;
   unsigned int CtQAP_H15_S01_QAP_ST_SMTNX_INIT : 1;
   unsigned int CtQAP_H2_S1_QAP_AKTIV : 1;
   unsigned int CtQAP_H3_S2_QAP_EINGRIFF_STATUS : 1;
   unsigned int CtQAP_H4_S4_QAP_EINGRIFF : 1;
   unsigned int CtQAP_H5_S12_QAP_ST_SMTNX_EINGRIFF_ED : 1;
   unsigned int CtQAP_H6_S06_QAP_ST_SMTNX_EINGRIFF : 1;
   unsigned int CtQAP_H7_S3_QAP_READY2EINGRIFF : 1;
   unsigned int CtQAP_H8_S02_QAP_ST_SMTNX_READY : 1;
   unsigned int CtQAP_H9_S32_QAP_ST_SMTNX_READY_ANFR : 1;
}; /* Description: Type of structure containing bitfields for Stateflow chart  */

/*------------------------------------------------------------------------------------------------*\
  VARIABLES
\*------------------------------------------------------------------------------------------------*/

#ifndef USE_CST_PARAM_STRUCT_H
/**************************************************************************************************\
   DISP_XTR: global observable variables (RAM) | Width: 32
\**************************************************************************************************/
extern DISP_XTR sint32 DD_StQHM_F11_QHM_SWT_fAZstFilt; /* 
   LSB: 2^-8 OFF: 0 MIN/MAX: -8388608 .. 8388607.99609375
   Description: Korrigertes Handmoment */
#endif /*USE_CST_PARAM_STRUCT_H*/

/*------------------------------------------------------------------------------------------------*\
  PARAMETERIZED MACROS
\*------------------------------------------------------------------------------------------------*/
/*------------------------------------------------------------------------------------------------*\
  FUNCTION PROTOTYPES
\*------------------------------------------------------------------------------------------------*/

/**************************************************************************************************\
   GLOBAL_FCN: global function(s) (exported to other modules)
\**************************************************************************************************/
extern void SAC_Controller_runnable(void);
extern void SAC_Init_runnable(void);

#ifdef __cplusplus
}
#endif

#endif /* SAC_SWC_H */
/*------------------------------------------------------------------------------------------------*\
  END OF FILE
\*------------------------------------------------------------------------------------------------*/
