/*************************************************************************************
 ***
 ***  Simulation frame header file: tl_types.h
 ***
 ***  Definitions of the TargetLink data types.
 ***
 ***  Generated by dSPACE TargetLink, version 5.0p1 from 01-Jun-2020
 ***  Generation date: 05-Aug-2020 20:43:57
\************************************************************************************/

#ifndef TL_TYPES_H
#define TL_TYPES_H

#include "Rte_Type.h" 

#endif
