/*-----------------------------------------------------------------------*/
/* File Identifier on server    $Id: ZPC_sys.h 254 2024-09-27 09:19:52Z VWQCRBZ $ */
/* File location on server $HeadURL: https://subversion.wob.vw.vwg/SWIfaceMxB26/Branches/MQB41BW_V0091_Bosch_100Fit_Auslieferung_LSMQBWASIL-190/20_ENG/Units/ZPC/Product/INC/ZPC_sys.h $ */
/*-----------------------------------------------------------------------*/

/* Spezifikation "AutosarEPSInterface Baseline 2.1" */

		
/**************************************************************************************************\
 *** 
 *** Code generation unit : 
 *** Codefile             : ZPC_sys.h
 ***
 *** Generated by TargetLink, the dSPACE production quality code generator
 *** Generation date: 2024-09-27 11:12:30
 ***
 *** CODE GENERATOR OPTIONS:
 *** Code generation mode                     : Classic AUTOSAR
 *** AUTOSAR version                          : 4.4.0
 *** Compiler                                 : <unknown>
 *** Target                                   : Generic
 *** ANSI-C compatible code                   : yes
 *** Code Optimization                        : enabled
 *** Constant style                           : decimal
 *** Clean code option                        : enabled
 *** Logging mode                             : Do not log anything
 *** Code Coverage                            : disabled
 *** Generate empty conditional branches      : enabled
 *** Loop unroll threshold                    : 5
 *** Utilize bitwise shift operations         : Never
 *** Handle unscaled SF expr. with TL type    : enabled
 *** Assignment of conditions                 : AllBooleanOutputs 
 *** Scope reduction only to function level   : disabled
 *** Exploit ranges if not erasable           : disabled
 *** Exploit Compute Through Overflow         : optimized
 *** Linker sections                          : enabled
 *** Enable Assembler                         : disabled
 *** Variable name length                     : unlimited
 *** Use global bitfields                     : enabled
 *** Stateflow: use of bitfields              : enabled
 *** State activity encoding limit            : 5
 *** Omit zero inits in restart function      : disabled
 *** Share functions between TL subsystems    : disabled
 *** Generate 64bit functions                 : enabled
 *** Inlining Threshold                       : 6
 *** Line break limit                         : 100
 *** Target optimized boolean data type       : enabled
 *** Keep saturation elements                 : disabled
 *** Extended variable sharing                : disabled
 *** Extended lifetime optimization           : enabled
 *** Style definition file                    : C:\Program Files\dSPACE TargetLink 5.0\matlab\tl\con
 ***                                            fig\codegen\cconfig.xml
 *** Root style sheet                         : C:\Program Files\dSPACE TargetLink 5.0\Matlab\Tl\XML
 ***                                            \CodeGen\Stylesheets\TL_CSourceCodeSS.xsl
 ***
 *** TargetLink version      : 5.0 from 02-Oct-2019
 *** Code generator version  : Build Id 5.0.0.24 from 2019-10-07 12:46:33
\**************************************************************************************************/

#ifndef ZPC_SYS_H
#define ZPC_SYS_H
/* line(s) below inserted by custom_post_codegen_hook */
#define DVERZPC_SYS_H "$Rev:: 254   $"
/* line(s) above inserted by custom_post_codegen_hook */

/*------------------------------------------------------------------------------------------------*\
  DEFINES (OPT)
\*------------------------------------------------------------------------------------------------*/
/*------------------------------------------------------------------------------------------------*\
  INCLUDES
\*------------------------------------------------------------------------------------------------*/

#include "Rte_Type.h"
#include "tl_defines_ZPC.h"

#ifdef __cplusplus
extern "C" {
#endif

/*------------------------------------------------------------------------------------------------*\
  ENUMS
\*------------------------------------------------------------------------------------------------*/
/*------------------------------------------------------------------------------------------------*\
  DEFINES
\*------------------------------------------------------------------------------------------------*/
/*------------------------------------------------------------------------------------------------*\
  TYPEDEFS
\*------------------------------------------------------------------------------------------------*/

struct tag_SYS_Struct {
   const volatile uint16 CST_SPARE_DATA[4]; /* Description: Custom Spare Data (4x16Bit) */
   const volatile sint16 ASC_PHIOFFSET_AI16; /* Description: Description not set */
   const volatile sint16 ARS_F_BEGRENZ_MAX_AI16; /* Description: Maximale Kraft */
   const volatile sint16 ARS_F_BEGRENZ_MIN_AI16; /* Description: Minimale Kraft */
   const volatile sint16 ARS_F_OFFSET_AI16; /* Description: Offset auf Ausgang */
   const volatile uint16 ARS_SW_HAND_AU16; /* Description: Schwelle Handmoment */
   const volatile uint16 ARS_PHV_ERSATZ_AI16; /* Description: Ersatzwert Lenkwinkelgeschwindigkeit
   */
   const volatile uint16 ASC_FAC_BEGR_REDUZ_LKU_HIGH_AU16; /* Description: Obere Begrenzung REDUZ LK
   U Verstärkung */
   const volatile uint16 ASC_FAC_BEGR_REDUZ_LKU_LOW_AU16; /* Description: Untere Begrenzung REDUZ LK
   U Verstärkung */
   const volatile uint8 ARS_SWS_FREIGABE_AU8; /* Description: Schalter Ausgang Active Return */
   const volatile sint16 GER_PHI_AUSGBEGR_L_AU16; /* Description: Geradelauf Ausgangsbegrenzung Lang
   zeit */
   const volatile sint16 GER_PHI_AUSGBEGR_L_NEG_AU16; /* Description: Geradelauf Ausgangsbegrenzung 
   Langzeit */
   const volatile sint16 GER_PHI_AUSGBEGR_K_AU16; /* Description: Geradelauf Ausgangsbegrenzung Kurz
   zeit */
   const volatile sint16 GER_PHI_AUSGBEGR_K_NEG_AU16; /* Description: Geradelauf Ausgangsbegrenzung 
   Kurzzeit */
   const volatile sint16 GER_PHI_AUSGBEGR_GER_AU16; /* Description: Geradelauf Ausgangsbegrenzung Ph
   iGerade */
   const volatile sint16 GER_PHI_EINGBEGR_L_AU16; /* Description: Geradelauf Eingangsbegrenzung Lang
   zeit */
   const volatile sint16 GER_PHI_EINGBEGR_L_NEG_AU16; /* Description: Geradelauf Eingangsbegrenzung 
   Langzeit */
   const volatile sint16 GER_PHI_EINGBEGR_K_AU16; /* Description: Geradelauf Eingangsbegrenzung Kurz
   zeit */
   const volatile sint16 GER_PHI_EINGBEGR_K_NEG_AU16; /* Description: Geradelauf Eingangsbegrenzung 
   Kurzzeit */
   const volatile uint8 GER_SWS_RESETL_AU08; /* Description: Geradelauf Rücksetzen Langzeit */
   const volatile uint16 GER_VFZG_AB_AI16; /* Description: Geradelauf Schwelle Fahrzeuggeschwindigke
   it */
   const volatile sint16 GER_PHI_AB_L_AI16; /* Description: Geradelauf Schwelle Lenkwinkel Langzeit
   */
   const volatile sint16 GER_PHV_AB_L_AI16; /* Description: Geradelauf Schwelle Lenkwinkelgeschwindi
   gkeit Langzeit */
   const volatile sint16 GER_PHI_AB_K_AI16; /* Description: Geradelauf Schwelle Lenkwinkel Kurzzeit
   */
   const volatile sint16 GER_PHV_AB_K_AI16; /* Description: Geradelauf Schwelle Lenkwinkelgeschwindi
   gkeit Kurzzeit */
   const volatile sint16 GER_PHV_Reset_K_AU16; /* Description: Geradelauf Eingangsbegrenzung Kurzzei
   t */
   const volatile sint16 GER_PHI_Reset_K_AU16; /* Description: Geradelauf Eingangsbegrenzung Kurzzei
   t */
   const volatile sint16 GER_VFG_Reset_K_AU16; /* Description: Geradelauf Eingangsbegrenzung Kurzzei
   t */
   const volatile sint32 GER_MAX_GRAD_AU16; /* Description: Geradelauf Eingangsbegrenzung Kurzzeit
   */
   const volatile uint16 GER_TRQ_CONST_AU16; /* Description: Kehrwert der DME Konstante */
   const volatile uint16 GER_TH_ST_LERNEN_AU16; /* Description: Zeitkostante des Monoflops für Lernb
   edingung */
   const volatile uint32 TSC_FAC_LERN_AU32; /* Description: Lernfaktor Langzeit (mög. Leiche) */
   const volatile uint16 TSC_FILT_VFZG_XPP_AU16; /* Description: Filterzeitkonstante für Berechnung 
   von Längsbeschleunigung aus Radgeschwindigkeit */
   const volatile uint16 TSC_FILT_RPMPP_AU16; /* Description: Filterzeitkonstante für Berechnung von
    Motordrehbeschleunigung aus Motordrehzahl */
   const volatile uint16 TSC_FILT_FANTRIEB_XPP_AU16; /* Description: Filterzeitkonstante Kraft aus L
   ängsbeschleunigung */
   const volatile uint16 TSC_FILT_ISUMME_AU16; /* Description: Filterzeitkonstante für PT1 der Gewic
   htung von Antriebskraftquellen */
   const volatile uint16 TSC_FILT_TRQ_MOTOR_AU16; /* Description: Filterzeitkonstante Motormoment */
   const volatile uint16 TSC_FILT_ANG_MASSE_AU16; /* Description: Filterzeitkonstante angetriebene M
   asse */
   const volatile sint16 TSC_FSOLL_AUSGBEGR_NEG_AU16; /* Description: Neg. Begrenzung von TSC-Kompen
   sationskraft */
   const volatile sint16 TSC_FSOLL_AUSGBEGR_AU16; /* Description: Pos. Begrenzung von TSC-Kompensati
   onskraft */
   const volatile uint16 TSC_MECH_VERST_AU16; /* Description: Mechanische Verstärkung Lenkgetriebe
   */
   const volatile uint16 TSC_TRAGMASSEMO_AU16; /* Description: Motorträgheit (zur Verwendung bei der
    Berechnung der angetriebenen Masse) */
   const volatile sint16 TSC_FAC_CANTRAG_MO_AU16; /* Description: Faktor Motorträgheitsmoment vom CA
   N */
   const volatile sint16 TSC_FAC_CANSCHUB_MO_AU16; /* Description: Faktor Schubmoment vom CAN */
   const volatile uint16 TSC_ROWI_KOEFF_AU16; /* Description: Faktor Rollwiderstand */
   const volatile uint16 TSC_FAC_ROWI_EINBLEND_KLU16[4]; /* Description: Einblendfaktor Rollwidersta
   nd nach vfzg (soll bei niedriger vfzg null sein) */
   const volatile uint16 TSC_FAC_ROWI_EINBLEND_XU16[4]; /* Description: Einblendfaktor Rollwiderstan
   d nach vfzg (soll bei niedriger vfzg null sein) X-Werte */
   const volatile sint16 TSC_GRAD_BASIS_AI16; /* Description: Startwert Lernfaktor */
   const volatile sint16 TSC_MAX_LERNGRAD_AU16; /* Description: Begrenzung Quotient Zahnstangenkraft
    / Antriebskraft (vor Lerner) */
   const volatile sint16 TSC_MIN_LERNGRAD_AU16; /* Description: Begrenzung Quotient Zahnstangenkraft
    / Antriebskraft (vor Lerner) */
   const volatile sint16 TSC_MIN_LERNWERT_AU16; /* Description: Begrenzung des angewendeten Langlern
   werts in Berechnung_Ausgang */
   const volatile sint16 TSC_MAX_LERNWERT_AU16; /* Description: Begrenzung des angewendeten Langlern
   werts in Berechnung_Ausgang */
   const volatile uint16 TSC_MIN_LERN_ZEITKONST_AU16; /* Description: Zeitkonstante für maximale Ler
   ngeschwindigkeit */
   const volatile uint32 TSC_MAX_LERN_ZEITKONST_AU32; /* Description: Zeitkonstante für minimale Ler
   ngeschwindigkeit (zum Garantieren der numerischen Stabilität; soll fast eins sein) */
   const volatile uint16 TSC_EXP_LERN_ZEITKONST_AU16; /* Description: Exponent zur Berechnung der Ze
   itkonstante des Lerners aus der gewünschten Lerngeschwindigkeit */
   const volatile sint16 TSC_PHI_AB_AI16; /* Description: Schwelle Lenkwinkel (mög. Leiche) */
   const volatile uint16 TSC_FAC_LERNBED_FANTRIEB_KLU16[5]; /* Description: Kennlinie Lerngeschwindi
   gkeit Antriebskraft */
   const volatile uint16 TSC_FAC_LERNBED_FANTRIEB_XU16[5]; /* Description: Kennlinie Lerngeschwindig
   keit Antriebskraft X-Werte */
   const volatile uint16 TSC_FAC_LERNBED_PHI_KLU16[5]; /* Description: Kennlinie Lerngeschwindigkeit
    Lenkwinkel */
   const volatile uint16 TSC_FAC_LERNBED_PHI_XU16[5]; /* Description: Kennlinie Lerngeschwindigkeit 
   Lenkwinkel X-Werte */
   const volatile uint16 TSC_FAC_LERNBED_PHV_KLU16[5]; /* Description: Kennlinie Lerngeschwindigkeit
    Lenkgeschwindigkeit */
   const volatile uint16 TSC_FAC_LERNBED_PHV_XU16[5]; /* Description: Kennlinie Lerngeschwindigkeit 
   Lenkgeschwindigkeit X-Werte */
   const volatile uint16 TSC_WICHT_FAC_LERN_KLU16[5]; /* Description: Wichtung Kennlinie Lernwert Le
   nkwinkel */
   const volatile uint16 TSC_WICHT_FAC_LERN_XU16[5]; /* Description: Wichtung Kennlinie Lernwert Len
   kwinkel */
   const volatile sint16 TSC_XPP_AB_AI16; /* Description: Lernbedingung minimale Längsbeschleunigung
    */
   const volatile sint16 TSC_PHV_AB_AI16; /* Description: Schwelle Lenkwinkelgeschwindigkeit (mög. L
   eiche) */
   const volatile sint16 TSC_VFZG_AB_AI16; /* Description: Lernbedingung minimale Fahrzeuggeschwindi
   gkeit */
   const volatile uint16 TSC_LKU_AB_AU16; /* Description: Lernbedingung maximale Lenkunterstützung
   */
   const volatile uint16 TSC_TRQ_AB_AU16; /* Description: Schwelle Handmoment (mög. Leiche) */
   const volatile uint8 TSC_SWS_RESETL_AU08; /* Description: Rücksetzen Lerner */
   const volatile uint16 TSC_IMAX_AU16; /* Description: Maximaler Ausgangsgradient TSC Kraft (mög. L
   eiche) */
   const volatile uint8 TSC_SWS_SEL_VAR_LERN_AU08; /* Description: Auswahl Variable Lernzeit (mög. L
   eiche) */
   const volatile uint16 TSC_FAC_ISUMME_KLU16[4]; /* Description: Gewichtung Antriebskraftquelle nac
   h Änderungsrate der Getriebeübersetzung (1=nach xpp, 0=nach Mmot) */
   const volatile uint16 TSC_FAC_ISUMME_XU16[4]; /* Description: Gewichtung Antriebskraftquelle nach
    Änderungsrate der Getriebeübersetzung (1=nach xpp, 0=nach Mmot) X-Werte */
   const volatile uint16 TSC_FAC_ISUMME_SRAD_KLU16[4]; /* Description: Gewichtung Antriebskraftquell
   e nach Radschlupf (1=nach xpp, 0=nach Mmot) */
   const volatile uint16 TSC_FAC_ISUMME_SRAD_XU16[4]; /* Description: Gewichtung Antriebskraftquelle
    nach Radschlupf (1=nach xpp, 0=nach Mmot) X-Werte */
   const volatile uint16 TSC_FAC_ISUMME_ANG_MASSE_KLU16[5]; /* Description: Gewichtung Antriebskraft
   quelle nach angetriebener Masse (1=nach xpp, 0=nach Mmot) */
   const volatile uint16 TSC_FAC_ISUMME_ANG_MASSE_XU16[5]; /* Description: Gewichtung Antriebskraftq
   uelle nach angetriebener Masse (1=nach xpp, 0=nach Mmot) X-Werte */
   const volatile uint8 TSC_SEL_FILT_ISUMME_AU8; /* Description: Schalter des Filters der Gewichtung
    von Antriebskraftquellen (1=aktiv) */
   const volatile uint16 TSC_FAC_KOMP_ESP_AU16; /* Description: Kompensationskraft-Faktor bei ESP Ei
   ngriffen */
   const volatile uint16 TSC_FAC_KOMP_ASRESP_AU16; /* Description: Kompensationskraft-Faktor bei ASR
   ESP-Eingriffen */
   const volatile uint16 TSC_BEGRENZ_MAX_FILTERB_AU16; /* Description: Obere Begrenzung Nenner der B
   erechnung der Änderungsrate der Getriebeübersetzung */
   const volatile uint16 TSC_IMAX_MOTOR_AU16; /* Description: Begrenzung Motorübersetzung für Berech
   nung der Antriebskraft */
   const volatile uint16 TSC_AERO_CWA_AU16; /* Description: CW Wert Fahrzeug */
   const volatile uint16 TSC_J_RAD_AU16; /* Description: Trägheitsmoment Rad */
   const volatile uint16 TSC_ULIMIT_TRQ_MOTOR_AU16; /* Description: Untere Begrenzung Zäehler der Be
   rechnung der angetriebenen Masse ( Quotient (Mmot-Mmotbesch)/rpmpp ) */
   const volatile uint16 TSC_ULIMIT_RPMPP_AU16; /* Description: Untere Begrenzung Nenner der Berechn
   ung der angetriebenen Masse ( Quotient (Mmot-Mmotbesch)/rpmpp ) */
   const volatile uint16 TSC_VRAD_OFFSET_HA_AU16; /* Description: Offet auf hintere Radgeschwindigke
   it (zur numerischen Stabilitat des Quotients der Berechnung des Schlupfes) */
   const volatile uint16 TSC_XPP_VA_ANTEIL_KLU16[7]; /* Description: Anteil der Vorderachse bei der 
   Berechnung von xpp */
   const volatile sint16 TSC_XPP_VA_ANTEIL_XU16[7]; /* Description: Anteil der Vorderachse bei der B
   erechnung von xpp X-Werte */
   const volatile uint16 TSC_IMAX_MOTOR_ANG_MASSE_AU16; /* Description: Obere Begrenzung der Motorüb
   ersetzung vor Berechnung ihrer Änderungsrate in Gewichtung_fAntrieb_XPP_Mo (falscher Variablennam
   e, hat nichts mit ang_masse zu tun) */
   const volatile uint16 TSC_TRAGMO_ANG_MASSE_AI16; /* Description: Motorträgheit für Berechnung des
    eigenen Momentbedarfs um sich zu beschleunigen */
   const volatile uint32 QAP_MSK_ANPASSUNG01_FAS05_AU32; /* Description: dia_mskAnpassung01_mu32: QF
   K FAS05 XXX Codierung nicht aktiv (0) aktiv (1) */
   const volatile uint16 QAP_MSK_ERR_DIAG_AU16; /* Description: Fehlerqualifizierungsmaske (auf qap_
   mskErrRoh_u16) für Diagnoseabhaengige Fehler */
   const volatile uint16 QAP_MSK_ERR_ULSTG_AU16; /* Description: Fehlerqualifizierungsmaske (auf qap
   _mskErrRoh_u16) für Unterstützungsleistungsabhaengige Fehler */
   const volatile uint16 QAP_MSK_ERR_FOE_AU16; /* Description: Fehlerqualifizierungsmaske (auf qap_m
   skErrRoh_u16) für Fehler ohne Eintrag */
   const volatile uint16 QAP_MSK_ERR_MOE_AU16; /* Description: Fehlerqualifizierungsmaske (auf qap_m
   skErrRoh_u16) für Fehler mit Eintrag */
   const volatile uint8 QAP_SWS_HANDSOFF_UMSCHALTUNG_AU8; /* Description: Schalter um die Möglichkei
   t zu aktivieren, dass RHP zwischen zwei Performances umschalten kann [0=nicht möglich 1=Umschaltu
   ng über Status 13] */
   const volatile uint16 QAP_TMR_FRG_BUS_FEHLER_AU16; /* Description: Haltezeit für die Diagnose der
    Busfehler */
   const volatile uint16 QAP_TMR_DELAY_STATS_AU16; /* Description: Haltezeit fuer hohe Krafanforderu
   ng */
   const volatile uint8 QHM_FAC_ARSFSOLL_NACHKOMP_AU8; /* Description: QHM-Stoergroessenkompensation
    - Anteil der ASC-Kompensation nach Gegenlenkverrechnung [-] */
   const volatile uint8 QHM_FAC_ARSFSOLL_VORKOMP_AU8; /* Description: QHM-Stoergroessenkompensation 
   - Anteil der ASC-Kompensation [-] */
   const volatile uint8 QHM_FAC_ARS_BLEND_AU8; /* Description: QHM-Stoergroessenkompensation - Fakto
   r zur Normierung des Handmomentes (Ausblenden von ASC) [1/Nm] */
   const volatile uint16 QHM_FAC_AZST2FSOLL_AU16; /* Description: QHM-LimitUeF - Parameter fuer Grad
   ientenbegrenzung der Kraft [N*s/mm] */
   const volatile uint8 QHM_FAC_EAF_FSOLL_AU8; /* Description: QHM-Stoergroessenkompensation - Antei
   l der EAF-Kompensation [-] */
   const volatile uint16 QHM_FAC_FILTER_F_AZST_AU16; /* Description: Filterkonstante für die Filteru
   ng des zahnstangenschleunigungsabhängigen Krafftoffsets */
   const volatile uint16 QHM_FAC_FILTER_PHV2TRQ_AU16; /* Description: QHM-Momentenkompensation - Fil
   terfaktor zur Kompensation des Lenkradtraegheitsmomentes [-] */
   const volatile uint16 QHM_FAC_FILTER_TRQ_DT1_AU16; /* Description: QHM-Momentenkompensation - DT1
   -Filterkoeffizient im Handmomentenpfad [-] */
   const volatile sint16 QHM_FAC_FZAHNSTANGE_AI16; /* Description: Mechanische Uebersetzung Handmome
   nt in Zahnstangenkraft [N/Nm] */
   const volatile uint16 QHM_FAC_GAIN_VZST_LIM_AU16; /* Description: QHM-LimitUeF - Parameter fuer z
   ahnstangengeschwindigkeitsabhaengige Begrenzung der Kraft [Nkm/h] */
   const volatile uint16 QHM_FAC_GAIN_VZST_LIM_HANDSOFF_AU16; /* Description: QHM-LimitUeF - Paramet
   er fuer zahnstangengeschwindigkeitsabhaengige Begrenzung der Kraft [Nkm/h] für den HandsOff Betri
   eb */
   const volatile uint8 QHM_FAC_GEGENL_A_AU8; /* Description: QHM-LimitUeF - Parameter fuer handmome
   ntenabhaengige Begrenzung der Kraft [1/Nm] */
   const volatile uint16 QHM_FAC_GEGENL_B_AU16; /* Description: QHM-LimitUeF - Parameter fuer handmo
   mentenabhaengige Begrenzung der Kraft [N/Nm] */
   const volatile uint16 QHM_FAC_HAPTIK_KLU16[11]; /* Description: QHM-Haptik - normierte Ausblendke
   nnlinie [-] */
   const volatile uint16 QHM_FAC_HAPTIK_XU16[11]; /* Description: QHM-Haptik - normierte Ausblendken
   nlinie [-] */
   const volatile uint8 QHM_FAC_LKUFSOLL_AU8; /* Description: QHM-Stoergroessenkompensation - Anteil
    der LKU-Kompensation [-] */
   const volatile uint8 QHM_FAC_NIV_MAX_AU8; /* Description: QHM-Bratwurst - Obere und Untere Grenze
    fuer ausgegebenes Kraftniveau [%] */
   const volatile uint16 QHM_FAC_NIV_PT1_FILTER_AU16; /* Description: QHM-Bratwurst - Filterkoeffizi
   ent fuer ausgegebenes Kraftniveau [-] */
   const volatile uint16 QHM_FAC_NIV_VERST_AU16; /* Description: QHM-Bratwurst - Verstaerkungsfaktor
    fuer ausgegebenes Kraftniveau [%/N] */
   const volatile sint16 QHM_FAC_PHA2TRQ_AI16; /* Description: QHM-Momentenkompensation - Umrechnung
   sfaktor von Winkelbeschleunigung auf Drehmoment [Nm/deg /ticks_per_s] */
   const volatile sint16 QHM_FAC_TRQ_DT1_AI16; /* Description: QHM-Momentenkompensation - DT1-Versta
   erkungsfaktor im Handmomentenpfad [1/s /ticks_per_s ]. */
   const volatile uint16 QHM_FAC_V2F_VZST_LIM_AU16; /* Description: QHM-LimitUeF - Parameter fuer za
   hnstangengeschwindigkeitsabhaengige Begrenzung der Kraft [Ns/mm] */
   const volatile uint16 QHM_FAC_VZST2FSOLL_AU16; /* Description: QHM-LimitUeF - Parameter fuer Grad
   ientenbegrenzung der Kraft [N/mm/ticks_per_s] */
   const volatile uint16 QHM_FAC_VZST_FILTER_DT1_AU16; /* Description: QHM-LimitUeF - DT1-Filterkoef
   fizient für Zahnstangengeschwindigkeit [-] */
   const volatile sint16 QHM_FAC_VZST_DT1_AI16; /* Description: QHM-LimitUeF - DT1-Verstaerkungsfakt
   or für Zahnstangenbeschleunigung in Kraft [N * mm/(s *s *ticks_per_s) ]. */
   const volatile uint16 QHM_F_GEGENL_OFFS_A_AU16; /* Description: QHM-LimitUeF - Parameter fuer han
   dmomentenabhaengige Begrenzung der Kraft [N] */
   const volatile uint16 QHM_F_GEGENL_OFFS_B_AU16; /* Description: QHM-LimitUeF - Parameter fuer han
   dmomentenabhaengige Begrenzung der Kraft [N] */
   const volatile uint16 QHM_F_GRADIENT_MAX_AU16; /* Description: QHM-LimitUeF - Parameter fuer Grad
   ientenbegrenzung der Kraft [N/s] */
   const volatile uint16 QHM_F_GRADIENT_MAX_HIGH_AU16; /* Description: QHM-LimitUeF - Parameter fuer
    Gradientenbegrenzung der Kraft [N/s] */
   const volatile uint16 QHM_F_GRADIENT_MAX_HO_AU16; /* Description: QHM-LimitUeF - Parameter fuer G
   radientenbegrenzung der Kraft [N/s] im HandsOff Betrieb */
   const volatile uint16 QHM_F_GRADIENT_OFFSET_AU16; /* Description: QHM-LimitUeF - Parameter fuer G
   radientenbegrenzung der Kraft [N] */
   const volatile uint16 QHM_F_GRUNDKRAFT_VZST_LIM_AU16; /* Description: QHM-LimitUeF - Parameter fu
   er zahnstangengeschwindigkeitsabhaengige Begrenzung der Kraft [N] */
   const volatile uint16 QHM_F_GRUNDKRAFT_VZST_LIM_HANDSOFF_AU16; /* Description: QHM-LimitUeF - Par
   ameter fuer zahnstangengeschwindigkeitsabhaengige Begrenzung der Kraft [N] für den HandsOff Betri
   eb */
   const volatile uint16 QHM_F_KSK_BEGRENZ_AU16; /* Description: QHM-Limits - Maximalkraft des ueber
   lenkbaren Eingriffs [N] */
   const volatile uint16 QHM_F_MAXKRAFT_AU16; /* Description: QHM-LimitUeF - Parameter fuer handmome
   ntenabhaengige Begrenzung der Kraft [N] */
   const volatile uint16 QHM_F_MAXKRAFT_VZST_LIM_AU16; /* Description: QHM-LimitUeF - Parameter fuer
    zahnstangengeschwindigkeitsabhaengige Begrenzung der Kraft [N] */
   const volatile uint16 QHM_F_MAXKRAFT_VZST_LIM_HANDSOFF_AU16; /* Description: QHM-LimitUeF - Param
   eter fuer zahnstangengeschwindigkeitsabhaengige Begrenzung der Kraft [N] für den HandsOff Betrieb
    */
   const volatile uint8 QHM_MSK_BIT0_QPR_INFO_AU8; /* Description: QHM-Statusausgabe - Fehlerstatus 
   bei Begrenzung der Reglerkraft bei zu hoher Dynamik [-] */
   const volatile uint8 QHM_SWS_FORCE_KOMP_AU8; /* Description: QHM-Stoergroessenkompensation - Akti
   vierung der Stoergroessenkompensation [-] */
   const volatile uint8 QHM_SWS_FILTER_F_AZST_AU8; /* Description: QHM-UefBegrenzung - Aktivierung d
   es Filters des Zahnstangenbeschleunigungsabhängigen Offsets 0=deaktiv / 1=aktiv [-] */
   const volatile uint8 QHM_SWS_HAPTIK_AU8; /* Description: QHM-Haptik - Aktivierung des Haptikmodul
   s [-] */
   const volatile uint8 QHM_SWS_HAPTIK_DIREKT_AU8; /* Description: QHM-Haptik - Aktivierung der Hapt
   ikfunktion erst bei Maxkraft [-] */
   const volatile uint8 QHM_SWS_TRQ_SENSOR_AU8; /* Description: QHM-Momentenkompensation - Auswahl M
   omenteneingangssignal [-] */
   const volatile uint8 QHM_SWS_UEF_BEGR_AU8; /* Description: QHM-LimitUeF - Aktivierung der Begrenz
   ungsfunktion [-] */
   const volatile sint8 QHM_TMR_MIN_ENTPRELL_AI8; /* Description: QHM-Statusausgabe -  Entprelltimer
    des Fehlerstatus bei begrenzter Reglerkraft [-ticks] */
   const volatile uint8 QHM_TMR_MIN_HALTEN_AU8; /* Description: QHM-Statusausgabe - Fehlerhaltezeit 
   bei begrenzter Reglerkraft [ticks] */
   const volatile uint8 QHM_TRQ_GEGENL_OFFS_AU8; /* Description: QHM-LimitUeF - Parameter fuer handm
   omentenabhaengige Begrenzung der Kraft [Nm] */
   const volatile sint16 QHM_TRQ_HANDMINABS_AI16; /* Description: QHM-Haptik -  Minimales Ueberlenkm
   oment [Nm] */
   const volatile uint16 QHM_VFZG_GRUND_VZST_LIM_AU16; /* Description: QHM-LimitUeF - Parameter fuer
    zahnstangengeschwindigkeitsabhaengige Begrenzung der Kraft [km/h] */
   const volatile uint16 QHM_VFZG_GRUND_VZST_LIM_HANDSOFF_AU16; /* Description: QHM-LimitUeF - Param
   eter fuer zahnstangengeschwindigkeitsabhaengige Begrenzung der Kraft [km/h] für HandsOff Betrieb
   */
   const volatile uint8 QHM_SWS_FSOLL_FSOLLLIMITMTL_BEGR_AU8; /* Description: QHM-SYS_BegrFDurchHm -
    Umschalter (1) lku_fSoll_mi16 oder (0) bsw_fSollLimMtl_mi16 */
   const volatile uint8 QHM_SWS_FSOLL_FSOLLLIMITMTL_HAPTIK_AU8; /* Description: QHM-SYS_SignKoor - U
   mschalter (1) lku_fSoll_mi16 oder (0) bsw_fSollLimMtl_mi16 */
   const volatile uint8 QHM_SWS_FSOLL_FSOLLLIMITMTL_KOMP_AU8; /* Description: QHM-SYS_Stoergroessenk
   ompensation - Umschalter (1) lku_fSoll_mi16 oder (0) bsw_fSollLimMtl_mi16 */
   const volatile uint16 QHM_TMR_CALC_LIMIT_T_HIGH_AU16; /* Description: Haltezeit fuer hohe Krafanf
   orderung */
   const volatile uint16 QHM_TMR_CALC_LIMIT_SPERRZ_AU16; /* Description: Sperrzeit fuer hohe Krafanf
   orderung */
   const volatile uint8 QPR_CNT_ERR_HOLD_AU8; /* Description: QPR-SM - minimale Haltezeit fuer die A
   usgabe eines Fehlerzustandes [ticks] */
   const volatile uint8 QPR_CNT_WARN_HOLD_AU8; /* Description: QPR-SM - minimale Haltezeit fuer die 
   Ausgabe eines Warnungszustandes [ticks] */
   const volatile sint8 QPR_FAC_AVR_INTERP_AI8; /* Description: QPR-SigJitterKomp - Angestrebter Mit
   telwert des Signaljitterkompensationsfaktors qpr_facTimeoutInterp_mi16 */
   const volatile uint16 QPR_FAC_FILTER_V_DT1_AU16; /* Description: QPR-ReglerVZst - Filterkoeffizie
   nt fuer DT1-Glied der Zahnstangengeschwindigkeitssregelung [-] */
   const volatile uint16 QPR_FAC_FILTER_V_I_REDUZ_AU16; /* Description: QPR-ReglerVZst - Reduzierung
   sfaktor des I-Anteil der Zahnstangengeschwindigkeitssregelung [1/tick] */
   const volatile uint16 QPR_FAC_FILTER_X_DT1_AU16; /* Description: QPR-ReglerXZst - Filterkoeffizie
   nt fuer DT1-Glied der Zahnstangenpositionsregelung [-] */
   const volatile uint16 QPR_FAC_FILTER_X_DT1_VOR_AU16; /* Description: QPR-ReglerXZst - Filterkoeff
   izient fuer DT1-Glied der Vorsteuerung [-] */
   const volatile uint16 QPR_FAC_FILTER_X_I_REDUZ_AU16; /* Description: QPR-ReglerXZst - Reduzierung
   sfaktor des I-Anteil der Zahnstangenpositionsregelung [1/tick] */
   const volatile uint16 QPR_FAC_FRQ_10MS_AU16; /* Description: QPR-SigJitterKomp - Faktor zur Umrec
   hnung auf 10 ms [10ms/tick] */
   const volatile uint16 QPR_FAC_HAPTIK_FORCE_KLU16[5]; /* Description: QPR-SpuerbarBer - Faktor fue
   r die maximale Reglerausgangskraft in Abhaenigkeit der Spuerbarkeit [-] */
   const volatile uint16 QPR_FAC_HAPTIK_REGLER_V_KLU16[5]; /* Description: QPR-SpuerbarBer - Faktor 
   fuer Reglerparameter des Zahnstangengeschwidnigkeitsreglers in Abhaenigkeit der Spuerbarkeit [-]
   */
   const volatile uint16 QPR_FAC_HAPTIK_REGLER_X_KLU16[5]; /* Description: QPR-SpuerbarBer - Faktor 
   fuer Reglerparameter des Zahnstangenpositionsreglers in Abhaenigkeit der Spuerbarkeit [-] */
   const volatile sint16 QPR_FAC_HAPTIK_XI16[5]; /* Description: QPR-SpuerbarBer - X-Achse fuer Spue
   rbarkeitsabhaenige Kennlinien [-] */
   const volatile sint16 QPR_FAC_HM2VZST_AI16; /* Description: QPR-ReglerStabi - Faktor zur Reglerst
   abilisierung bei Lenkraddrehschwingen bei Fahrfunktionen (durch Reduzierungsfaktoren beeinflusst)
    [mm/s / Nm] */
   const volatile sint16 QPR_FAC_HM2VZST_NUEL_AI16; /* Description: QPR-ReglerStabi - Faktor zur Reg
   lerstabilisierung bei Lenkraddrehschwingen bei Parkfunktionen (durch Reduzierungsfaktoren beeinfl
   usst) [mm/s / Nm] */
   const volatile sint16 QPR_FAC_HM2VZST_NOFAC_AI16; /* Description: QPR-ReglerStabi - Faktor zur Re
   glerstabilisierung bei Lenkraddrehschwingen für Fahrfunktionen (nicht durch Reduzierungsfaktoren 
   beeinflusst) [mm/s / Nm] */
   const volatile sint16 QPR_FAC_HM2VZST_NOFAC_NUEL_AI16; /* Description: QPR-ReglerStabi - Faktor z
   ur Reglerstabilisierung bei Lenkraddrehschwingen für Parkfunktionen (nicht durch Reduzierungsfakt
   oren beeinflusst) [mm/s / Nm] */
   const volatile uint8 QPR_FAC_INTERP_REDUZ_AU8; /* Description: QPR-SigJitterKomp - Faktor mit wel
   chem Offset ausgeglichen werden (Angleichung an QPR_FAC_AVR_INTERP_AI8) */
   const volatile sint8 QPR_FAC_MAX_INTERP_AI8; /* Description: QPR-SigJitterKomp - maximaler Interp
   olationsfaktor nach Empfang einer neuen Botschaft, bei Erreichen des Wertes wird die Warnung Sign
   al-Jitter-Limit B ausgloest */
   const volatile sint8 QPR_FAC_MAX_INTERP_RX_AI8; /* Description: QPR-SigJitterKomp - maximaler Int
   erpolationsfaktor, bei Erreichen des Wertes wird die Warnung Signal-Jitter-Limit A ausgloest */
   const volatile uint16 QPR_FAC_PHASE_DELAY_AU16; /* Description: QPR-Vibration - Phasenverschiebun
   g zwischen Vibrationskraft und Zahnstangengeschwindigkeitsoffset bei der Vibration */
   const volatile uint16 QPR_FAC_PHI2XZST_AU16; /* Description: QPR-SollKorr - Umrechnung von Winkel
    in Zahnstangenposition (fuer Beruecksichtigung des Geradeauslaufwinkels) [mm/deg] */
   const volatile uint16 QPR_FAC_TRQ_FILTER_DT1_AU16; /* Description: QPR-Momentenkompensation - DT1
   -Filterkoeffizient im Handmomentenpfad [-] */
   const volatile sint16 QPR_FAC_TRQ_DT1_AI16; /* Description: QPR-Momentenkompensation - DT1-Versta
   erkungsfaktor im Handmomentenpfad [1/s /ticks_per_s ]. */
   const volatile uint16 QPR_FAC_VFZG_VIB_KLU16[5]; /* Description: QPR-Vibration - Kennlinie zur Be
   stimmung eines geschwindigkeitsabhaengigen Korrekturfaktors der Lenkradvibration, Y-Achse [N/Nm]
   */
   const volatile uint16 QPR_FAC_VFZG_VIB_XU16[5]; /* Description: QPR-Vibration - Kennlinie zur Bes
   timmung eines geschwindigkeitsabhaengigen Korrekturfaktors der Lenkradvibration, X-Achse [km/h]
   */
   const volatile uint16 QPR_FAC_VZST2F_PI_AU16; /* Description: QPR-ReglerAntiWindUp - Faktur welch
   er den umgekehrten P- und I-Anteiles des Reglers entspricht [N / (mm/s)] */
   const volatile uint16 QPR_FAC_VZST2F_PREIB_AU16; /* Description: QPR-ReglerAntiWindUp - Mittleres
    Verhaeltnis zwischen Zahnstangengeschwdnigkeit und Reibung [N / (mm/s)] */
   const volatile uint16 QPR_FAC_VZST_VIB_AU16; /* Description: QPR-Vibration - Umrechnungsfaktor fu
   er das Virbationsmoment in einen Zahnstangengeschwindigkeitsoffset fuer den Positionsregler [mm/s
   /Nm] */
   const volatile sint16 QPR_FAC_V_D_ANTEIL_AI16; /* Description: QPR-ReglerVZst - Verstaerkungsfakt
   or des D-Anteils der Zahnstangengeschwindigkeitssregelung [N / (mm/s/tick)] */
   const volatile sint16 QPR_FAC_V_INTEGRATOR_AI16; /* Description: QPR-ReglerVZst - Verstaerkungsfa
   ktor des I-Anteils der Zahnstangengeschwindigkeitsregelung [N/tick / (mm/s)] */
   const volatile sint16 QPR_FAC_V_P_ANTEIL_AI16; /* Description: QPR-ReglerVZst - Verstaerkungsfakt
   or des P-Anteils der Zahnstangengeschwdnigkeitsregelung(durch Reduzierungsfaktoren beeinflusst) [
   N / (mm/s)] */
   const volatile sint16 QPR_FAC_V_P_ANTEIL_FIX_AI16; /* Description: QPR-ReglerVZst - Verstaerkungs
   faktor des P-Anteils der Zahnstangengeschwdnigkeitsregelung(nicht durch Reduzierungsfaktoren beei
   nflusst) [N / (mm/s)] */
   const volatile sint16 QPR_FAC_X_D_ANTEIL_AI16; /* Description: QPR-ReglerXZst - Verstaerkungsfakt
   or des D-Anteils der Zahnstangenpositionsregelung [mm/s / (mm/tick)] */
   const volatile sint16 QPR_FAC_X_D_ANTEIL_VOR_AI16; /* Description: QPR-ReglerXZst - Faktor fuer d
   ie Vorsteuerung durch einen D-Anteil [mm/s / (mm/tick)] */
   const volatile sint16 QPR_FAC_X_INTEGRATOR_AI16; /* Description: QPR-ReglerXZst - Verstaerkungsfa
   ktor des I-Anteils der Zahnstangenpositionsregelung [mm/s/tick / (mm)] */
   const volatile sint16 QPR_FAC_X_P_ANTEIL_AI16; /* Description: QPR-ReglerXZst - Verstaerkungsfakt
   or des P-Anteils der Zahnstangenpositionsregelung (durch Reduzierungsfaktoren beeinflusst) [mm/s 
   / (mm)] */
   const volatile sint16 QPR_FAC_X_P_ANTEIL_FIX_AI16; /* Description: QPR-ReglerXZst - Verstaerkungs
   faktor des P-Anteils der Zahnstangenpositionsregelung (nicht durch Reduzierungsfaktoren beeinflus
   st) [mm/s / (mm)] */
   const volatile sint16 QPR_F_P_REIBKOMP_KLI16[6]; /* Description: QPR-ReglerVZst - Y-Achse der Rei
   bungskompensationskennlinie in Abhaengigkeit der Zahnstangengeschwdnigkeit  [N] */
   const volatile sint16 QPR_F_P_REIBKOMP_XI16[6]; /* Description: QPR-ReglerVZst - X-Achse der Reib
   ungskompensationskennlinie [mm/s] */
   const volatile uint16 QPR_F_REGLER_MAX_AU16; /* Description: QPR-ReglerVZst - maximale Ausgangskr
   aft des Positionsreglers [N] */
   const volatile sint16 QPR_F_WIND_UP_RES_AI16; /* Description: QPR-ReglerAntiWindUp - Saturierung 
   ab welcher die Anti-WindUp Funktion aktiv wird [N] */
   const volatile uint32 QPR_MSK_ERR_AKTIV_AU32; /* Description: QPR-SM - Bitmaske fuer qpr_mskRegle
   rErr_mu32 zur Signalisierung eines Fehlers, der zum Abbruch der Regelung fuehrt */
   const volatile uint32 QPR_MSK_ERR_DISABLE_AU32; /* Description: QPR-SM - Bitmaske fuer qpr_mskReg
   lerErr_mu32, welche bei Setzen der markierten Bits die Kraftausgabe der SAC-NUel-Positionsregelun
   g sofort unterbindet */
   const volatile uint32 QPR_MSK_ERR_FEHLER_ME_AU32; /* Description: QPR-SM - Bitmaske fuer qpr_mskR
   eglerErr_mu32, welche bei Setzen der markierten Bits zur Ausgabe des Status QPR_ST_FEHLER_ME_AU8 
   im Signal qpr_stRegler_mu8 */
   const volatile uint8 QPR_MSK_ERR_FGA_AU8; /* Description: QPR-SM - Bitmaske zur Auswertung von fg
   a_mskStVFzg_mu8 bzgl. Fehler */
   const volatile uint32 QPR_MSK_ERR_SIG01_AU32; /* Description: QPR-SM - Bitmaske zur Auswertung vo
   n can_stSignale01_mu32 bzgl. Fehler */
   const volatile uint32 QPR_MSK_ERR_SIG02_AU32; /* Description: QPR-SM - Bitmaske zur Auswertung vo
   n can_stSignale02_mu32 bzgl. Fehler */
   const volatile uint32 QPR_MSK_ERR_STBITS01A_AU32; /* Description: QPR-SM - Bitmaske zur Auswertun
   g von bsw_mskStatusbits_01_mu32 bzgl. Fehler der Zahnstangengeschwindigkeit */
   const volatile uint32 QPR_MSK_ERR_STBITS01B_AU32; /* Description: QPR-SM - Bitmaske zur Auswertun
   g von bsw_mskStatusbits_01_mu32 bzgl. Fehler der Zahnstangenposition */
   const volatile uint32 QPR_MSK_ERR_STBITS01C_AU32; /* Description: QPR-SM - Bitmaske zur Auswertun
   g von bsw_mskStatusbits_01_mu32 bzgl. Fehler der Softwareendanschlagsposition */
   const volatile uint32 QPR_MSK_ERR_STBITS01D_AU32; /* Description: QPR-SM - Bitmaske zur Auswertun
   g von bsw_mskStatusbits_01_mu32 bzgl. Fehler des Sensormoments */
   const volatile uint32 QPR_MSK_ERR_STBITS02A_AU32; /* Description: QPR-SM - Bitmaske zur Auswertun
   g von bsw_mskStatusbits_02_mu32 bzgl. Fehler */
   const volatile uint8 QPR_MSK_ERR_UEF_AU8; /* Description: QPR-SM - Bitmaske zur Auswertung von qh
   m_mskStatus_mu8 bzgl. Begrenzung fuer die UEF */
   const volatile uint32 QPR_MSK_WARN_AKTIV_AU32; /* Description: QPR-SM - Bitmaske fuer qpr_mskRegl
   erErr_mu32 zur Signalisierung einer Warnung */
   const volatile uint32 QPR_MSK_WARN_UEF_AKTIV_AU32; /* Description: QPR-SM - Bitmaske fuer qpr_msk
   ReglerErr_mu32 zur Signalisierung einer Warnung aufgrund einer Begrenzung des Regeleingriffs zum 
   Schutz einer Abschaltung durch die Ueberwachngsfunktion */
   const volatile uint8 QPR_NIV_ERR_UNT_AU8; /* Description: QPR-SM - unterer Grenzwert von bsw_leve
   lAssist fuer Error Unterstuetzungsleistung [%] */
   const volatile uint8 QPR_NIV_WARN_UNT_AU8; /* Description: QPR-SM - unterer Grenzwert von bsw_lev
   elAssist fuer Warnung Unterstuetzungsleistung [%] */
   const volatile uint8 QPR_ST_BEREIT_AU8; /* Description: QPR-SM - Ausgangszustand der QPR-Statemac
   hine - Bereit */
   const volatile uint8 QPR_ST_EINGRIFF_AU8; /* Description: QPR-SM - Ausgangszustand der QPR-Statem
   achine - Eingriff aktiv */
   const volatile uint8 QPR_ST_EINGRIFF_ED_AU8; /* Description: QPR-SM - Ausgangszustand der QPR-Sta
   temachine - Eingiff mit eingeschraengter Dynamik aktiv */
   const volatile uint8 QPR_ST_FEHLER_ME_AU8; /* Description: QPR-SM - Ausgangszustand der QPR-State
   machine - Fehler mit Eintrag */
   const volatile uint8 QPR_ST_GESPERRT_AU8; /* Description: QPR-SM - Ausgangszustand der QPR-Statem
   achine - Gesperrt */
   const volatile uint8 QPR_ST_IST_GLAETTUNG_AU8; /* Description: QPR-Bratwurst - Schalter zum Aktiv
   ieren der Glaettung der Ist-Zahnstangengeschwindigkeit aus der Basissoftware */
   const volatile uint8 QPR_TMR_ERRORBOTSCHAFT_AU8; /* Description: QPR-SM - Qualifizierungszeit fue
   r Botschaftstimeout der Sollposition [ticks] */
   const volatile uint8 QPR_TMR_TRQ_SENSOR_ERR_AU8; /* Description: QPR_SYS_AnfFehler - Qualifizieru
   ngszeit fuer zu grosses und damit ungueltiges Handlenkmoment [ticks] */
   const volatile uint8 QPR_TMR_TRQ_SENSOR_NOERR_AU8; /* Description: QPR_SYS_AnfFehler - Qualifizie
   rungszeit fuer gueltiges Handlenkmoment [ticks] */
   const volatile uint16 QPR_TRQ_HAND_MAX_ERR_NUEL_AU16; /* Description: QPR-SM - Maximales Sensormo
   ment bei einem nicht ueberlenkbarem Eingriff [Nm] */
   const volatile uint16 QPR_TRQ_HAPTIK_KLU16[5]; /* Description: QPR-SpuerbarBer - notwendiges Uebe
   rlenkmoment des Eingriffs in Abhaenigkeit der Spuerbarkeit [Nm] */
   const volatile uint16 QPR_TRQ_VIB_GRDB_AU16; /* Description: QPR-Vibration - Rampe fuer das Umset
   zen von Vibratinosanforderungen [Nm/tick] */
   const volatile uint16 QPR_VFZG_MAX_ERR_NUEL_AU16; /* Description: QPR-SM - Maximale Fahrzeuggesch
   windigkeit bei einem nicht ueberlenkbarem Eingriff [km/h] */
   const volatile uint16 QPR_VZST_P_REGLER_A_KLU16[6]; /* Description: QPR-ReglerXZst - Kennlinie fu
   er Berechnung der Sollruecklaufgeschwindigkeit auf die Sollposition [mm/s] */
   const volatile uint16 QPR_VZST_SOLL_BEGR_AU16; /* Description: QPR-SollKorr - Grandientenbegrenzu
   ng fuer Sollposition [mm/s] */
   const volatile uint16 QPR_VZST_SOLL_MAX_AU16; /* Description: QPR-ReglerXZst - maximale Sollgesch
   windigkeit, welche durch den Zahnstangenpositionsregler angefordert werden kann [mm/s] */
   const volatile uint8 QPR_XZST_EA_MAX_AU8; /* Description: QPR-SollKorr - Maximale Sollposition de
   r Zahnstangenpositionsregelung [mm] */
   const volatile uint8 QPR_XZST_EA_MIN_AU8; /* Description: QPR-SollKorr - untere Grenze fuer die B
   egrenzung der Sollposition der Zahnstangenpositionsregelung durch die Endanschalgsfunktion [mm]
   */
   const volatile sint16 QPR_XZST_EA_OFFSET_AI16; /* Description: QPR-SollKorr - Verschiebung der ma
   ximalen Sollposition gegenueber der SW-Endanschlagsposition (positiv == groesserer Hub) [mm] */
   const volatile uint16 QPR_XZST_ERR_NUEL_XDIFF_AU16; /* Description: QPR-SM - oberer Grenzwert der
    Differenz von Soll- und Ist-Zahnstangenposition fuer Fehler [mm] */
   const volatile uint16 QPR_XZST_P_REGLER_A_XU16[6]; /* Description: QPR_SM - Kennlinie fuer Berech
   nung der Sollruecklaufgeschwindigkeit auf die Sollposition [mm] */
   const volatile uint16 QPR_XZST_WARN_NUEL_XDIFF_AU16; /* Description: QPR-SM - oberer Grenzwert de
   r Differenz von Soll- und Ist-Zahnstangenposition fuer Warnung [mm] */
   const volatile uint16 QUA_FAC_HAPTIK_D_ANT_AU16; /* Description: Wert gegen den die Spürbarkeit v
   erglichen wird, um die D-Anteile umzuschalten */
   const volatile uint16 QUA_FAC_KR_IST_AU16; /* Description: QUA-KrCalc - Korrekturfaktor fuer Krue
   mmungsberechnung */
   const volatile uint16 QUA_FAC_PHI2XZST_AU16; /* Description: QUA-KrCalc - Umrechnungsfaktor von W
   inkel auf Zahnstangenposition [mm/deg] */
   const volatile uint16 QUA_FAC_PHI2XZST_GER_AU16; /* Description: QUA-KrCalc - Umrechnungsfaktor v
   on Winkel auf Zahnstangenposition zur Beruecksichtigung des Geradeauslauflernwertes in der angefo
   rderten Kruemmung [mm/deg] */
   const volatile sint16 QUA_FAC_VERST_GIERMOMENT_AI16; /* Description: QUA-BrGier - Verstaerkungfak
   tor fuer P-Anteil der Gierratenregelung [Nm / (deg/s)] */
   const volatile uint8 QUA_FRQ_VIBRATION_SET_KLU8[8]; /* Description: QUA-Vib - Array mit Vibration
   frequenzen [Hz] */
   const volatile uint8 QUA_MSK_ERR_FGA_AU8; /* Description: QUA-vFzg - Bitmaske zur Auswertung von 
   fga_mskStVFzg_mu8 (bei gesetzten Bits wird die uebergebne Geschwindigkeit als ungueltig erkannt)
   */
   const volatile uint16 QUA_PHI_DEFAULT_LRW_KLU16[7]; /* Description: QUA-KrCalc - Array mit Defaul
   t-Lenkwinkeln [°] */
   const volatile uint16 QUA_PHI_DEFAULT_RLW_KLU16[7]; /* Description: QUA-KrCalc - Array mit Defaul
   t-Radlenkwinkel [°] */
   const volatile uint16 QUA_S_RADSTAND_DEFAULT_AU16; /* Description: QUA-KrCalc - Defaultwert für d
   en Radstand */
   const volatile uint8 QUA_ST_AKTIVFASIDX_NUEL_AU8; /* Description: QUA-SigRouting - FAS dessen Ein
   griff nicht ueberlenkbar ist */
   const volatile uint8 QUA_ST_FRQPOSSOLL_FAS01_AU8; /* Description: QUA-SigRouting - Auswahl der Bo
   tschafts-Zykluszeit fuer FAS01 */
   const volatile uint8 QUA_ST_FRQPOSSOLL_FAS02_AU8; /* Description: QUA-SigRouting - Auswahl der Bo
   tschafts-Zykluszeit fuer FAS02 */
   const volatile uint8 QUA_ST_FRQPOSSOLL_FAS03_AU8; /* Description: QUA-SigRouting - Auswahl der Bo
   tschafts-Zykluszeit fuer FAS03 */
   const volatile uint8 QUA_ST_FRQPOSSOLL_FAS04_AU8; /* Description: QUA-SigRouting - Auswahl der Bo
   tschafts-Zykluszeit fuer FAS04 */
   const volatile uint8 QUA_ST_FRQPOSSOLL_FAS05_AU8; /* Description: QUA-SigRouting - Auswahl der Bo
   tschafts-Zykluszeit fuer FAS05 */
   const volatile uint8 QUA_ST_FRQPOSSOLL_VMM_AU8; /* Description: QUA-SigRouting gc- Auswahl der Bo
   tschafts-Zykluszeit fuer VMM */
   const volatile uint8 QUA_ST_GIER_SOLL_AU8; /* Description: QUA-BrGier - Ausgabewert fuer qua_stGi
   erSoll_mu8 */
   const volatile uint16 QUA_ST_UDY_INIT_TIMER_AU16; /* Description: QUA-vFzg - Aufstartzeit, in der
    die Gradientenbegrenzung der Geschwindigkeitsberechnung nur eingeschraenkt aktiv sind [ticks] */
   const volatile uint8 QUA_SWS_KR_DEFAULT_AU8; /* Description: QUA-KrCalc - Auswahl der Berechnungs
   methode der Ist-Kruemmung (0 = aus Default-Kennlinie, 1 = aus Radstand, Radlenkwinkel und Lenkwin
   kel) */
   const volatile uint16 QUA_TMR_VIBRATION_GESPERRT_AU16; /* Description: QUA-Vib - Wartezeit bis zu
   r naechsten Vibrationsanforderung [ticks] */
   const volatile uint16 QUA_TMR_VIBRATION_LAEUFT_AU16; /* Description: QUA-Vib - Dauer einer Vibrat
   ionsanforderung [ticks] */
   const volatile uint16 QUA_TRQ_GIERMOMENT_MAX_AU16; /* Description: QUA-BrGier - maximales beim ES
   C angefordertes Giermoment [Nm] */
   const volatile uint8 QUA_TRQ_VIBRATION_SET_KLU8[8]; /* Description: QUA-Vib - Array mit den am Le
   nkrad spuerbaren Amplituden der Vibrationsfunktion [Nm] */
   const volatile uint16 QUA_VFZG_GRDB_NEG_AU16; /* Description: QUA-vFzg - Gradientenbegrenzer fuer
    fallende Fahrzeuggeschwindigkeiten [km/h / tick] */
   const volatile uint16 QUA_VFZG_GRDB_POS_AU16; /* Description: QUA-vFzg - Gradientenbegrenzer fuer
    steigende Fahrzeuggeschwindigkeiten [km/h / tick] */
   const volatile uint16 QUA_VFZG_SAFESPEED_TOL_AU16; /* Description: QUA-vFzg - Toleranzangabe zur 
   Berechnugn einer sicheren Geschwindigkeit  */
   const volatile uint8 QUA_CON_QUALIFIER_AU8; /* Description: QUA-vFzg - Toleranzangabe zur Berechn
   ugn einer sicheren Geschwindigkeit  */
   const volatile uint32 SAC_CAN_STR_DEV_MSG_TX1_AU32; /* Description: SAC - Wert fuer das Signal sa
   c_can_strDevMsgTx1_mu32 */
   const volatile uint32 SAC_CAN_STR_DEV_MSG_TX2_AU32; /* Description: SAC - Wert fuer das Signal sa
   c_can_strDevMsgTx2_mu32 */
   const volatile uint32 SAC_ST_SAC_AU32; /* Description: SAC - Wert fuer das Signal sac_stSAC_mu32
   */
}; /* Description: struct type created for variable: SYS_Struct */

/*------------------------------------------------------------------------------------------------*\
  VARIABLES
\*------------------------------------------------------------------------------------------------*/

#ifndef USE_CST_PARAM_STRUCT_H
/**************************************************************************************************\
   MERGEABLE_CAL: mergeable calibratable parameters (ROM) | Width: N.A.
\**************************************************************************************************/
extern MERGEABLE_CAL struct tag_SYS_Struct SYS_Struct;
#endif /*USE_CST_PARAM_STRUCT_H*/

/*------------------------------------------------------------------------------------------------*\
  PARAMETERIZED MACROS
\*------------------------------------------------------------------------------------------------*/
/*------------------------------------------------------------------------------------------------*\
  FUNCTION PROTOTYPES
\*------------------------------------------------------------------------------------------------*/
#ifdef __cplusplus
}
#endif

#endif /* ZPC_SYS_H */
/*------------------------------------------------------------------------------------------------*\
  END OF FILE
\*------------------------------------------------------------------------------------------------*/
