/*-----------------------------------------------------------------------*/
/* File Identifier on server    $Id: ZPC_eep.h 254 2024-09-27 09:19:52Z VWQCRBZ $ */
/* File location on server $HeadURL: https://subversion.wob.vw.vwg/SWIfaceMxB26/Branches/MQB41BW_V0091_Bosch_100Fit_Auslieferung_LSMQBWASIL-190/20_ENG/Units/ZPC/Product/INC/ZPC_eep.h $ */
/*-----------------------------------------------------------------------*/

/* Spezifikation "AutosarEPSInterface Baseline 2.1" */

		
/**************************************************************************************************\
 *** 
 *** Code generation unit : 
 *** Codefile             : ZPC_eep.h
 ***
 *** Generated by TargetLink, the dSPACE production quality code generator
 *** Generation date: 2024-09-27 11:12:30
 ***
 *** CODE GENERATOR OPTIONS:
 *** Code generation mode                     : Classic AUTOSAR
 *** AUTOSAR version                          : 4.4.0
 *** Compiler                                 : <unknown>
 *** Target                                   : Generic
 *** ANSI-C compatible code                   : yes
 *** Code Optimization                        : enabled
 *** Constant style                           : decimal
 *** Clean code option                        : enabled
 *** Logging mode                             : Do not log anything
 *** Code Coverage                            : disabled
 *** Generate empty conditional branches      : enabled
 *** Loop unroll threshold                    : 5
 *** Utilize bitwise shift operations         : Never
 *** Handle unscaled SF expr. with TL type    : enabled
 *** Assignment of conditions                 : AllBooleanOutputs 
 *** Scope reduction only to function level   : disabled
 *** Exploit ranges if not erasable           : disabled
 *** Exploit Compute Through Overflow         : optimized
 *** Linker sections                          : enabled
 *** Enable Assembler                         : disabled
 *** Variable name length                     : unlimited
 *** Use global bitfields                     : enabled
 *** Stateflow: use of bitfields              : enabled
 *** State activity encoding limit            : 5
 *** Omit zero inits in restart function      : disabled
 *** Share functions between TL subsystems    : disabled
 *** Generate 64bit functions                 : enabled
 *** Inlining Threshold                       : 6
 *** Line break limit                         : 100
 *** Target optimized boolean data type       : enabled
 *** Keep saturation elements                 : disabled
 *** Extended variable sharing                : disabled
 *** Extended lifetime optimization           : enabled
 *** Style definition file                    : C:\Program Files\dSPACE TargetLink 5.0\matlab\tl\con
 ***                                            fig\codegen\cconfig.xml
 *** Root style sheet                         : C:\Program Files\dSPACE TargetLink 5.0\Matlab\Tl\XML
 ***                                            \CodeGen\Stylesheets\TL_CSourceCodeSS.xsl
 ***
 *** TargetLink version      : 5.0 from 02-Oct-2019
 *** Code generator version  : Build Id 5.0.0.24 from 2019-10-07 12:46:33
\**************************************************************************************************/

#ifndef ZPC_EEP_H
#define ZPC_EEP_H
/* line(s) below inserted by custom_post_codegen_hook */
#define DVERZPC_EEP_H "$Rev:: 254   $"
/* line(s) above inserted by custom_post_codegen_hook */

/*------------------------------------------------------------------------------------------------*\
  DEFINES (OPT)
\*------------------------------------------------------------------------------------------------*/
/*------------------------------------------------------------------------------------------------*\
  INCLUDES
\*------------------------------------------------------------------------------------------------*/

#include "Rte_Type.h"
#include "tl_defines_ZPC.h"

#ifdef __cplusplus
extern "C" {
#endif

/*------------------------------------------------------------------------------------------------*\
  ENUMS
\*------------------------------------------------------------------------------------------------*/
/*------------------------------------------------------------------------------------------------*\
  DEFINES
\*------------------------------------------------------------------------------------------------*/
/*------------------------------------------------------------------------------------------------*\
  TYPEDEFS
\*------------------------------------------------------------------------------------------------*/

struct tag_EEP_Struct {
   uint32 bsw_stPhiRitzel_mu32; /* Description: Description not set */
   uint32 bsw_stPhiRitzel_1_mu32; /* Description: Description not set */
   uint32 bsw_stPhiRitzel_2_mu32; /* Description: Description not set */
   uint32 bsw_stPhiRitzel_3_mu32; /* Description: Description not set */
   uint32 bsw_stPhiRitzel_4_mu32; /* Description: Description not set */
   uint32 bsw_stPhiRitzel_5_mu32; /* Description: Description not set */
   uint32 bsw_stPhiRitzel_6_mu32; /* Description: Description not set */
   uint32 bsw_stPhiRitzel_7_mu32; /* Description: Description not set */
   uint32 bsw_stPhiRitzel_8_mu32; /* Description: Description not set */
   uint32 bsw_stPhiRitzel_9_mu32; /* Description: Description not set */
   uint32 bsw_stPhiRitzel_10_mu32; /* Description: Description not set */
   uint32 bsw_stPhiRitzel_11_mu32; /* Description: Description not set */
   uint32 bsw_stPhiRitzel_12_mu32; /* Description: Description not set */
   uint32 bsw_stPhiRitzel_13_mu32; /* Description: Description not set */
   uint32 bsw_stPhiRitzel_14_mu32; /* Description: Description not set */
   uint32 bsw_stPhiRitzel_15_mu32; /* Description: Description not set */
   uint32 bsw_stPhiRitzel_16_mu32; /* Description: Description not set */
   uint32 bsw_stPhiRitzel_17_mu32; /* Description: Description not set */
   uint32 bsw_stPhiRitzel_18_mu32; /* Description: Description not set */
   uint32 bsw_stPhiRitzel_19_mu32; /* Description: Description not set */
   uint32 bsw_stPhiRitzel_20_mu32; /* Description: Description not set */
   uint32 bsw_stPhiRitzel_21_mu32; /* Description: Description not set */
   uint32 bsw_stPhiRitzel_22_mu32; /* Description: Description not set */
   uint32 bsw_stPhiRitzel_23_mu32; /* Description: Description not set */
   uint32 bsw_stPhvRitzel_mu32; /* Description: Description not set */
   uint32 bsw_stPhvRitzel_1_mu32; /* Description: Description not set */
   uint32 bsw_stPhvRitzel_2_mu32; /* Description: Description not set */
   uint32 bsw_stPhvRitzel_3_mu32; /* Description: Description not set */
   uint32 bsw_stTemp_mu32; /* Description: Description not set */
   uint32 bsw_stTemp_1_mu32; /* Description: Description not set */
   uint32 bsw_stTemp_2_mu32; /* Description: Description not set */
   uint32 bsw_stTemp_3_mu32; /* Description: Description not set */
   uint32 bsw_stTemp_4_mu32; /* Description: Description not set */
   uint32 bsw_stTemp_5_mu32; /* Description: Description not set */
   uint32 bsw_stTemp_6_mu32; /* Description: Description not set */
   uint32 bsw_stTemp_7_mu32; /* Description: Description not set */
   uint32 bsw_stTemp_8_mu32; /* Description: Description not set */
   uint32 bsw_stTemp_9_mu32; /* Description: Description not set */
   uint32 bsw_stTemp_10_mu32; /* Description: Description not set */
   uint32 bsw_stTemp_11_mu32; /* Description: Description not set */
   uint32 bsw_stTemp_12_mu32; /* Description: Description not set */
   uint32 bsw_stTemp_13_mu32; /* Description: Description not set */
   uint32 bsw_stTemp_14_mu32; /* Description: Description not set */
   uint32 bsw_stTemp_15_mu32; /* Description: Description not set */
   uint32 bsw_stTemp_16_mu32; /* Description: Description not set */
   uint32 bsw_stTemp_17_mu32; /* Description: Description not set */
   uint32 bsw_stFSoll_mu32; /* Description: Description not set */
   uint32 bsw_stFSoll_1_mu32; /* Description: Description not set */
   uint32 bsw_stFSoll_2_mu32; /* Description: Description not set */
   uint32 bsw_stFSoll_3_mu32; /* Description: Description not set */
   uint32 bsw_stFSoll_4_mu32; /* Description: Description not set */
   uint32 bsw_stFSoll_5_mu32; /* Description: Description not set */
   uint32 bsw_stFSoll_6_mu32; /* Description: Description not set */
   uint32 bsw_stFSoll_7_mu32; /* Description: Description not set */
   uint32 bsw_stFSoll_8_mu32; /* Description: Description not set */
   uint32 bsw_stFSoll_9_mu32; /* Description: Description not set */
   uint32 bsw_stFSoll_10_mu32; /* Description: Description not set */
   uint32 bsw_stFSoll_11_mu32; /* Description: Description not set */
   uint32 bsw_stFSoll_12_mu32; /* Description: Description not set */
   uint32 bsw_stFSoll_13_mu32; /* Description: Description not set */
   uint32 bsw_stFSoll_14_mu32; /* Description: Description not set */
   uint32 bsw_stFSoll_15_mu32; /* Description: Description not set */
   uint32 bsw_stFSoll_16_mu32; /* Description: Description not set */
   uint32 bsw_stFSoll_17_mu32; /* Description: Description not set */
   uint32 bsw_stFSoll_18_mu32; /* Description: Description not set */
   uint32 bsw_stFSoll_19_mu32; /* Description: Description not set */
   uint32 bsw_stFSoll_20_mu32; /* Description: Description not set */
   uint32 bsw_stFSoll_21_mu32; /* Description: Description not set */
   uint32 bsw_stFSoll_22_mu32; /* Description: Description not set */
   uint32 bsw_stFSoll_23_mu32; /* Description: Description not set */
   uint32 bsw_stAsc_mu32; /* Description: Description not set */
   sint32 bsw_fTSC_mu32; /* Description: Description not set */
   sint32 bsw_phiL_mi32; /* Description: Description not set */
   sint16 bsw_phiOffset_mi16; /* Description: Description not set */
   uint16 bsw_fTemp_mi16; /* Description: Description not set */
   sint16 bsw_symPhiL_mi16; /* Description: Description not set */
}; /* Description: struct type created for variable: EEP_Struct */

/*------------------------------------------------------------------------------------------------*\
  VARIABLES
\*------------------------------------------------------------------------------------------------*/

#ifndef USE_CST_PARAM_STRUCT_H
/**************************************************************************************************\
   DISP: global observable variables (RAM) | Width: N.A.
\**************************************************************************************************/
extern DISP struct tag_EEP_Struct EEP_Struct;
#endif /*USE_CST_PARAM_STRUCT_H*/

/*------------------------------------------------------------------------------------------------*\
  PARAMETERIZED MACROS
\*------------------------------------------------------------------------------------------------*/
/*------------------------------------------------------------------------------------------------*\
  FUNCTION PROTOTYPES
\*------------------------------------------------------------------------------------------------*/
#ifdef __cplusplus
}
#endif

#endif /* ZPC_EEP_H */
/*------------------------------------------------------------------------------------------------*\
  END OF FILE
\*------------------------------------------------------------------------------------------------*/
