/*-----------------------------------------------------------------------*/
/* File Identifier on server    $Id: ZPC_msm.h 254 2024-09-27 09:19:52Z VWQCRBZ $ */
/* File location on server $HeadURL: https://subversion.wob.vw.vwg/SWIfaceMxB26/Branches/MQB41BW_V0091_Bosch_100Fit_Auslieferung_LSMQBWASIL-190/20_ENG/Units/ZPC/Product/INC/ZPC_msm.h $ */
/*-----------------------------------------------------------------------*/

/* Spezifikation "AutosarEPSInterface Baseline 2.1" */

		
/**************************************************************************************************\
 *** 
 *** Code generation unit : 
 *** Codefile             : ZPC_msm.h
 ***
 *** Generated by TargetLink, the dSPACE production quality code generator
 *** Generation date: 2024-09-27 11:12:30
 ***
 *** CODE GENERATOR OPTIONS:
 *** Code generation mode                     : Classic AUTOSAR
 *** AUTOSAR version                          : 4.4.0
 *** Compiler                                 : <unknown>
 *** Target                                   : Generic
 *** ANSI-C compatible code                   : yes
 *** Code Optimization                        : enabled
 *** Constant style                           : decimal
 *** Clean code option                        : enabled
 *** Logging mode                             : Do not log anything
 *** Code Coverage                            : disabled
 *** Generate empty conditional branches      : enabled
 *** Loop unroll threshold                    : 5
 *** Utilize bitwise shift operations         : Never
 *** Handle unscaled SF expr. with TL type    : enabled
 *** Assignment of conditions                 : AllBooleanOutputs 
 *** Scope reduction only to function level   : disabled
 *** Exploit ranges if not erasable           : disabled
 *** Exploit Compute Through Overflow         : optimized
 *** Linker sections                          : enabled
 *** Enable Assembler                         : disabled
 *** Variable name length                     : unlimited
 *** Use global bitfields                     : enabled
 *** Stateflow: use of bitfields              : enabled
 *** State activity encoding limit            : 5
 *** Omit zero inits in restart function      : disabled
 *** Share functions between TL subsystems    : disabled
 *** Generate 64bit functions                 : enabled
 *** Inlining Threshold                       : 6
 *** Line break limit                         : 100
 *** Target optimized boolean data type       : enabled
 *** Keep saturation elements                 : disabled
 *** Extended variable sharing                : disabled
 *** Extended lifetime optimization           : enabled
 *** Style definition file                    : C:\Program Files\dSPACE TargetLink 5.0\matlab\tl\con
 ***                                            fig\codegen\cconfig.xml
 *** Root style sheet                         : C:\Program Files\dSPACE TargetLink 5.0\Matlab\Tl\XML
 ***                                            \CodeGen\Stylesheets\TL_CSourceCodeSS.xsl
 ***
 *** TargetLink version      : 5.0 from 02-Oct-2019
 *** Code generator version  : Build Id 5.0.0.24 from 2019-10-07 12:46:33
\**************************************************************************************************/

#ifndef ZPC_MSM_H
#define ZPC_MSM_H
/* line(s) below inserted by custom_post_codegen_hook */
#define DVERZPC_MSM_H "$Rev:: 254   $"
/* line(s) above inserted by custom_post_codegen_hook */

/*------------------------------------------------------------------------------------------------*\
  DEFINES (OPT)
\*------------------------------------------------------------------------------------------------*/
/*------------------------------------------------------------------------------------------------*\
  INCLUDES
\*------------------------------------------------------------------------------------------------*/

#include "Rte_Type.h"
#include "tl_defines_ZPC.h"

#ifdef __cplusplus
extern "C" {
#endif

/*------------------------------------------------------------------------------------------------*\
  ENUMS
\*------------------------------------------------------------------------------------------------*/
/*------------------------------------------------------------------------------------------------*\
  DEFINES
\*------------------------------------------------------------------------------------------------*/
/*------------------------------------------------------------------------------------------------*\
  TYPEDEFS
\*------------------------------------------------------------------------------------------------*/

struct tag_MSM_Struct {
   sint16 bsw_trqSensor_mi16; /* Description: Lenkhandmoment */
   sint16 bsw_trqSensorKomp_mi16; /* Description: Lenkhandmoment */
   sint16 bsw_phvRitzel_mi16; /* Description: Lenkwinkelgeschwindigkeit */
   sint32 bsw_phiRitzel_mi32; /* Description: Lenkwinkel */
   uint16 fga_vFzg_mu16; /* Description: Fahrzeuggeschwindigkeit */
   uint8 fga_mskStVFzg_mu8; /* Description: Status Fahrzeuggeschwindigkeit */
   sint16 can_vRad_VL_mi16; /* Description: Radgeschwindigkeit vorne Links */
   sint16 can_vRad_VR_mi16; /* Description: Radgeschwindigkeit vorne Rechts */
   sint16 can_vRad_HL_mi16; /* Description: Radgeschwindigkeit hinten Links */
   sint16 can_vRad_HR_mi16; /* Description: Radgeschwindigkeit hinten Rechts */
   uint16 can_imp_HL_mu16; /* Description: Radimpulse hinten Links */
   uint16 can_imp_HR_mu16; /* Description: Radimpulse hinten Rechts */
   uint8 can_levelPedal_mu8; /* Description: Fahrpedalweg */
   sint16 can_trqMoSollRoh_mi16; /* Description: Fahrerwunschmoment Verbrennungsmotor */
   sint16 can_trqMoIst_mi16; /* Description: Verbrennungsmotor Istmoment  */
   sint16 can_trqMoSchub_mi16; /* Description: Verbrennungsmotor Schubmoment */
   sint16 can_tragMo_mi16; /* Description: Momente Beschleunigen Traegheiten */
   uint16 can_rpmMotor_mu16; /* Description: Motordrehzahl Verbrennungsmotor */
   sint16 can_beschlQuer_mi16; /* Description: Querbeschleunigung */
   sint16 can_beschlLaengs_mi16; /* Description: Laengsbeschleunigung */
   sint16 can_gierrate_mi16; /* Description: Gierrarte */
   sint16 can_pBrems_mi16; /* Description: Bremsdruck */
   uint16 bsw_uBat_mu16; /* Description: Batteriespannung */
   sint16 bsw_lku_fSoll_mi16; /* Description: Unterstützungskraft */
   sint16 bsw_phiRitzelMotor_mi16; /* Description: Motorlage aus Motorlagesensor */
   sint16 bsw_iBat_mi16; /* Description: Batteriestrom */
   sint16 bsw_trqIst_mi16; /* Description: MotoristMoment */
   sint16 bsw_trqSoll_mi16; /* Description: MotorSollmoment */
   uint32 can_stSignale01_mu32; /* Description: Status information der CAN Signale */
   uint32 can_stSignale02_mu32; /* Description: Status information der CAN Signale */
   uint32 bsw_mskStatusbits01_mu32; /* Description: Status information 1 */
   uint32 bsw_mskStatusbits02_mu32; /* Description: Status information 2 */
   uint32 dia_mskCodierung01_mu32; /* Description: Status Codierung 1 */
   uint32 dia_mskAnpassung01_mu32; /* Description: Status Anpassung 2 */
   uint32 bsw_stSAC_mu32; /* Description: Status information SAC */
   uint32 bsw_stTac_mu32; /* Description: Status information TAC */
   uint32 can_strDevMsgRx1_mu32; /* Description: Signal Entwicklungsidentiefier 1 */
   uint32 can_strDevMsgRx2_mu32; /* Description: Signal Entwicklungsidentiefier 2 */
   uint32 can_stLaufleistung_mu32; /* Description: Laufleistung aus Diagnose1 */
   uint8 bsw_levelAssist_mu8; /* Description: Unterstützungsniveau */
   sint16 bsw_tempEcu_mi16; /* Description: ECU Temperatur */
   sint16 bsw_tZahnstange_mi16; /* Description: Zahnstangen Temperatur */
   uint8 sac_qap_stQfk_mu8; /* Description: Status Querführungskoordinator */
   uint16 cha_facKom_mu16; /* Description: Faktor CHA Komfort */
   uint16 cha_facAuto_mu16; /* Description: Faktor CHA Auto */
   uint16 cha_facDyn_mu16; /* Description: Faktor CHA Dynamik */
   uint16 cha_facEvent_mu16; /* Description: Faktor CHA Erlebnismodus */
   sint16 can_trqOffsetHCA_mi16; /* Description: Offset auf Handmoment HCA */
   uint8 can_stHCA_mu8; /* Description: Heading Control Status */
   uint8 dsr_stDSR_mu8; /* Description: DSR Status Lenkung */
   uint8 hca_stHCA_mu8; /* Description: Heading Control Status Lenkung */
   uint8 can_stESP14_mu8; /* Description: Status DSR vom ESP */
   uint32 bsw_stDiagnose_mu32; /* Description: Diagnosestatus Testerfunktionen */
   sint16 can_trqESP14_mi16; /* Description: Momentenanforderung vom ESP 0 */
   uint8 can_vSignal_mu16; /* Description: Geschwindigkeitssignal ESP21 */
   uint8 can_trqAllrad_mu8; /* Description: Momenteninformation Haldex */
   sint8 can_gradUeb_mi8; /* Description: Über Untersteuergradient */
   uint8 can_stFahrbereitschaft_mu8; /* Description: Statusinformation Fahrbereitschaft */
   uint8 qap_stPrioToTnDsaTsc_mu8; /* Description: Freischlaltung DAS/TSC durch QFK */
   uint8 can_vaqIst_mu8; /* Description: Momentenverteilung Quersperre */
   uint8 can_stMO14_mu8; /* Description: Statusinformation Motor 14 */
   sint16 asc_fSoll_mi16; /* Description: Unterstützungskraft aus Softwaremodul  */
   uint16 asc_facReduzlku_mu16; /* Description: Reduktionsfaktor Lenkunterstützung */
   uint16 asc_facReduztrq_mu16; /* Description: Reduktionsfaktor Handmoment für Lenkunterstützung */
   sint16 asc_trqOffset_mi16; /* Description: Handmomentenoffset für Lenkunterstützung */
   uint8 asc_epsWarn_mu8; /* Description: Reduktionsfaktor für Active Return durch SW-Komponente. */
   uint32 asc_stASC_mu32; /* Description: Status ASC */
   uint16 asc_stDsaTsc2Qfk_mu16; /* Description: Statusinfomation DAS/TSC */
   uint32 asc_can_strDevMsgTx1_mu32; /* Description: Ausgabe EID01 */
   uint32 asc_can_strDevMsgTx2_mu32; /* Description: Ausgabe EID02 */
   uint8 asc_StartStopp_Info_mu8; /* Description: Start Stop Info */
   sint16 asc_ger_phiL_mi16; /* Description: Langzeitlernwert aus der GER */
   sint16 asc_ger_phiK_mi16; /* Description: Kurzzeitlernwert aus der GER */
   uint8 asc_ger_stLernL_mu8; /* Description: Lernbedingung Langzeit */
   uint8 asc_ger_stLernK_mu8; /* Description: Lernbedingung Kurzzeit */
   uint16 asc_tsc_facLern_mu16; /* Description: Langzeitlernwert Torque Steer */
   sint16 asc_tsc_fSoll_mi16; /* Description: Langzeitlernwert Torque Steer */
   uint8 asc_tsc_stLerrn_mu8; /* Description: Lernbedingung TSC */
   uint8 asc_mst_startBed_mu8; /* Description: Startbedingung Motorstart */
   uint16 ars_fac_trqSensor_Klu_mi16; /* Description: Eingangsgrösse Kennlinie Handmoment */
   uint16 ars_fac_trqSensor_Klu_D_mi16; /* Description: Eingangsgrösse Kennlinie Handmoment D */
   uint16 ars_abs_Vfzg_Klu_mi16; /* Description: Eingangsgrösse Absolutwert Fahrzeuggeschwindigkeit
   */
   uint16 ars_abs_Vfzg_D_Klu_mi16; /* Description: Eingangsgrösse Absolutwert Fahrzeuggeschwindigkei
   t D */
   uint16 ars_abs_RedDsr_Klu_mi16; /* Description: Eingangsgrösse Absolutwert Fahrzeuggeschwindigkei
   t Red_DSR */
   uint16 ars_abs_PhiRitzel_Klu_mi16; /* Description: Eingangsgrösse Absolutwert Lenkwinkelgeschwind
   igkeit */
   sint16 ars_phvRitzel_filt_mi16; /* Description: Lenkwinkelgeschwindigkeit */
   sint16 ars_trqSensor_filt_mi16; /* Description: Lenkhandmoment */
   uint16 ars_qfSollTrq_mi16; /* Description: Description not set */
   sint16 ars_fSum_mi16; /* Description: Description not set */
   sint16 ars_fLimit_mi16; /* Description: Description not set */
   sint16 asc_phiRitzel_mi16; /* Description: Description not set */
   sint16 ars_phvSollRitzel_mi16; /* Description: Berechnete Sollrücklaufgeschwindigkeit */
   sint16 ars_fSollBer_mi16; /* Description: Regelgüte */
   sint16 ars_phvSollWicht_mi16; /* Description: Produkt ProPhv_VFzg */
   sint16 ars_ProPhv_mi16; /* Description: Produkt PhvSoll_TRQ */
   sint16 ars_fSollBer_D_mi16; /* Description: Prod Regelgüte_D  */
   sint16 ars_RedArs_mi16; /* Description: Reduktion Rücklauf DSR HCA */
   sint16 ger_KurzLern_mi16; /* Description: Kurzzeitlerner */
   sint16 ger_LangLern_mi16; /* Description: Langzeitlerner */
   uint16 ger_count_KurzLern_mi16; /* Description: Kurzzeitzähler */
   uint16 ger_count_LangLern_mi16; /* Description: Langzeitzähler */
   sint16 ger_ang_KurzLern_mi16; /* Description: angeglichener Kurzzeitlernwinkel */
   sint16 ger_phiGerade_mi16; /* Description: Geradeauslaufkorrektur */
   uint8 ger_LernK_mu8; /* Description: Kurzzeitwert */
   uint8 ger_LernK_Reset_mu8; /* Description: Reset Kurzzeitwert */
   uint8 ger_LernL_mu8; /* Description: Langzeitwert */
   uint8 tsc_stXpp_mu8; /* Description: Lernbedingung minimale Längsbeschleunigung (1=erfüllt) */
   uint8 tsc_stLern_mu8; /* Description: Langzeit Lernwert wird berechnet (mög. Leiche) */
   uint8 tsc_facLernPhi_mu8; /* Description: Lerngeschwindigkeit nach Lenkwinkel */
   uint8 tsc_stPhv_mu8; /* Description: Lerngeschwindigkeit nach Lenkgeschwindigkeit */
   uint8 tsc_stTrq_mu8; /* Description: Lernbedingung minimales Handmoment (1=erfüllt) */
   uint8 tsc_facLernFantrieb_mu8; /* Description: Lerngeschwindigkeit Antriebskraft */
   uint8 tsc_stVfzg_mu8; /* Description: Lernbedingung minimale Fahrgeschwindigkeit (1=erfüllt) */
   uint8 tsc_stKompXpp_mu8; /* Description: Kompensationsbedingung Beschleunigung (mög. Leiche) */
   uint8 tsc_stKompFantrieb_mu8; /* Description: Kompensationsbedingung Antriebskraft (mög. Leiche)
   */
   uint8 tsc_stKomp_mu8; /* Description: Bedingung Kompensieren erfüllt (mög. Leiche) */
   uint8 tsc_stSigNioLern_mu8; /* Description: Signale für Lernen ungültig */
   uint8 tsc_stSigNioKomp_mu8; /* Description: Signale für Kompensieren ungültig */
   uint32 tsc_facLern_mu32; /* Description: LernFaktor TSC (mög. Leiche) */
   sint16 tsc_gradLkuFsoll_mi16; /* Description: Quotient Fzahnstange/Fantrieb (momentaner Zielwert 
   des Lerners) */
   sint16 tsc_LangRoh_mi16; /* Description: Gelernter Kompensationsfaktor (Fzs/Fantr) */
   sint16 tsc_KurzRoh_mi16; /* Description: Kurzzeitwert TSC Roh (mög. Leiche) */
   sint16 tsc_fSumme_mi16; /* Description: Kompensationskraft (begrenzt, nicht gefiltert) */
   sint16 tsc_fSummeGrad_mi16; /* Description: Kompensationskraft (begrenzt und gefiltert, vor Schal
   ter der TSC-Codierung) */
   sint16 tsc_xppRad_mi16; /* Description: Längsbeschleuningug berechnet aus Raddrehzahl */
   sint16 tsc_Xpp_mi16; /* Description: Längsbeschleuningug Algorithmus (mög. Leiche) */
   uint16 tsc_fAntrieb_mi16; /* Description: Berechnete Antriebskraft (aus xpp, Mmot, oder beiden, j
   e nach TSC_SEL_FANTRIEB_GEW_MO_XPP) */
   sint16 tsc_fSoll_mi16; /* Description: Kompensationskraft (finale Ausgang der Funktion, begrenzt,
    gefiltert, nach Schalter der TSC-Codierung) */
   uint16 tsc_fAntriebXpp_mi16; /* Description: Antriebskraft aus Längsbeschleunigung */
   sint16 tsc_rpmppMotor_mi16; /* Description: Motordrehbeschleunigung (wird von Motormoment abgezog
   en zur Berechnung der angetriebenen Masse) */
   uint16 tsc_fAntriebMo_mi16; /* Description: Antriebskraft aus Motormoment */
   sint16 tsc_fLernLang_mi16; /* Description: Langzeit Lernkraft (mög. Leiche) */
   sint16 tsc_fLernKurz_mi16; /* Description: Kurzzeit Lernkraft (mög. Leiche) */
   uint8 tsc_FacAntrieb_mu8; /* Description: Korrekturfactor der Kompensationskraft nach Antriebskra
   ft */
   sint16 tsc_fZahn_mi16; /* Description: Berechnete Zahnstangenkraft */
   uint16 tsc_iMotor_mu16; /* Description: Motor- und Getriebeübersetzung */
   uint16 tsc_vRad_mi16; /* Description: Mittlere Fahrzeuggeschwindigkeit Hinterräder */
   uint16 tsc_sAntrieb_mu16; /* Description: Antriebsschlupf (mög. Leiche) */
   uint8 tsc_stLku_mu8; /* Description: Lernbedingung maximale Unterstützungskraft (1=erfüllt) */
   uint8 tsc_stSantrieb_mu8; /* Description: Bedingung Schlupf (mög. Leiche) */
   uint16 tsc_iPGetrUebersetz_mu16; /* Description: Änderungsrate der Getriebeübersetzung (zur Erken
   nung von Gangwechseln) */
   uint16 tsc_iSumme_mu16; /* Description: Gewichtungsfaktor zur Berechnung der Antriebskraft (maxim
   aler Wert der drei Kriterien: Übersetzung, Radschlupf, angetriebene Masse) */
   uint16 tsc_Gew_Schlupfsum_mu16; /* Description: Gewichtung Schlupfsumme Rad + Getriebe (mög. Leic
   he) */
   uint16 tsc_minLernbed_mu16; /* Description: Lerngeschwindigkeit (Minimum aller Kriterien, Eingang
    zur Berechnung der Zeitkonstante des Lerners) */
   uint16 tsc_vRadHa_mu16; /* Description: Radgeschwindigkeit HA */
   uint16 tsc_vSrad_mu16; /* Description: Differenz Radgeschwindigkeit VA-HA, Zähler der Berechnung 
   des Radschlupfes */
   uint16 tsc_vRadVa_mu16; /* Description: Radgeschwindigkeit VA */
   uint16 tsc_sRad_mu16; /* Description: Schlupf Vorderachse */
   uint16 tsc_masseAng_mu16; /* Description: Angetriebene Masse ( (Mmot - rpmpp*tragmo)/rpmpp ) */
   uint8 tsc_fSollFreigabe_mu8; /* Description: Freigabe der TSC Sollkraft */
   sint16 tsc_xppRadVa_mu16; /* Description: Radbeschleunigung VA */
   sint16 tsc_Messw01_mi16; /* Description: Dummy Messwert TSC */
   sint16 tsc_Messw02_mi16; /* Description: Dummy Messwert TSC */
   sint16 tsc_Messw03_mi16; /* Description: Dummy Messwert TSC */
   sint16 tsc_Messw04_mi16; /* Description: Dummy Messwert TSC */
   sint16 tsc_Messw05_mi16; /* Description: Dummy Messwert TSC */
   sint16 tsc_Messw06_mi16; /* Description: Dummy Messwert TSC */
   sint16 asc_fReturn_mi16; /* Description: Temperaturkompensierte FSoll */
   uint16 sac_qap_mskErrRoh_mu16; /* Description: Bitleiste für die Klassifizierung Fehler ME/OE */
   uint8 sac_qap_stErrOeMe_mu8; /* Description: Status ob ein Fehler mit oder ohne Eintrag vorhanden
    ist */
   uint8 sac_qap_stFasIdxPrio_mu8; /* Description: durch QAP ausgewaehltes FAS */
   uint8 sac_qap_stQfkMainInt_mu8; /* Description: Status QFK-SM */
   uint8 sac_qap_stQfkSmTn11_mu8; /* Description: Status VMM-SM */
   uint8 sac_qap_stQfkSmTn1_mu8; /* Description: Status Teilnehmer1-SM */
   uint8 sac_qap_stQfkSmTn2_mu8; /* Description: Status Teilnehmer2-SM */
   uint8 sac_qap_stQfkSmTn3_mu8; /* Description: Status Teilnehmer3-SM */
   uint8 sac_qap_stQfkSmTn4_mu8; /* Description: Status Teilnehmer4-SM */
   uint8 sac_qap_stQfkSmTn5_mu8; /* Description: Status Teilnehmer5-SM */
   uint8 sac_qap_stSMMainToTnActive_mu8; /* Description: Rueckmeldung Prio an aktiven Teilnehmer */
   uint8 sac_qap_stSMMainToTnComfort_mu8; /* Description: Rueckmeldung Prio an Notfallfunktion */
   uint8 sac_qap_stSMMainToTnEmergency_mu8; /* Description: Rueckmeldung Prio an Komfortfunktion */
   uint8 sac_qap_stSMPrioMain_mu8; /* Description: Status Priorisierungs-SM */
   uint8 sac_qap_stSMTnComfort_mu8; /* Description: Status Komfortfunktion-Priorisierungs-SM */
   uint8 sac_qap_stSMTnEmergency_mu8; /* Description: Status Notfallfunktion-Priorisierungs-SM */
   uint16 sac_qhm_facHaptikInput_mu16; /* Description: Ueberblendfaktor Gegenlenken */
   uint16 sac_qhm_facHaptikLku_mu16; /* Description: Ueberblendfaktor Gegenlenken LKU */
   uint16 sac_qhm_facHaptikOutput_mu16; /* Description: Ueberblendfaktor nach Kennlinie Gegenlenken
   */
   sint16 sac_qhm_fAZst_mi16; /* Description: Offset auf den Grundkraftgradienten, der sich aus der 
   Zahnstangenbeschleunigung ergibt */
   sint16 sac_qhm_fFahrer_mi16; /* Description: Mechanische Kraft durch Fahrerhandmoment [N] */
   sint16 sac_qhm_fReglerKorr_mi16; /* Description: Begrenzte und um Stoerkraefte kompensierte QHM-R
   eglerkraft [N] */
   sint16 sac_qhm_fReglerSatKorr_mi16; /* Description: Korrektur der Reglerkraft aufgrund von Saturi
   erungen [N] */
   sint16 sac_qhm_fSollCalc_mi16; /* Description: Sollkraft QHM vor Begrenzung fuer Ueberwachungsfun
   ktion [N] */
   sint16 sac_qhm_fLimitGradMin_mi16; /* Description: Um Offset nach unten korrigierte limitierte So
   llkraft, durch die untere Sollkraft nach unten beschraenkt [N] */
   sint16 sac_qhm_fLimitGradMax_mi16; /* Description: Um Offset nach oben korrigierte limitierte Sol
   lkraft, durch die obere Sollkraft nach oben beschraenkt [N] */
   sint16 sac_qhm_fSollReglerSatKorr_mi16; /* Description: Kraftaenderungen der Reglersollkraft bedi
   ngt durch Begrenzungen (Nutzung durch QPR fuer AntiWindUp-Massnahmen) [N] */
   uint8 sac_qhm_swsTimerLimHigh_mu8; /* Description: Signal welches durch die Timer gebildet wird u
   nd kurzzeitig auf den hohen gradienten umschaltet */
   sint16 sac_qhm_trqSensor_mi16; /* Description: Korrigertes Handmoment */
   uint16 sac_qpr_facForce_mu16; /* Description: Faktor fuer Ausgangskraft der QHM */
   sint16 sac_qpr_facHaptik_mi16; /* Description: Haptikfaktor nach Signaljitterkompensation */
   sint16 sac_qpr_facTimeoutInterp_mi16; /* Description: Interpolationsfaktor der Signaljitterkompen
   sation */
   sint16 sac_qpr_fSollD_mi16; /* Description: Zahnstangengeschwindigkeitsregler D-Anteil [N] */
   sint16 sac_qpr_fSollI_mi16; /* Description: Zahnstangengeschwindigkeitsregler I-Anteil [N] */
   sint16 sac_qpr_fSollPAnteilReib_mi16; /* Description: Zahnstangengeschwindigkeitsregler Reibkompe
   nsations-Anteil [N] */
   sint16 sac_qpr_fSollRegler_mi16; /* Description: Sollkraft des Reglers [N] */
   sint16 sac_qhm_fVZst_mi16; /* Description: Offset auf den Grundkraftgradienten, der sich aus der 
   Zahnstangengeschwindigkeit ergibt */
   uint32 sac_qpr_mskReglerErr1st_mu32; /* Description: QPR-Fehlermaske (eingefrohren bei letzem Wec
   hsel in der Fehlerzustand) */
   uint32 sac_qpr_mskReglerErr_mu32; /* Description: QPR-Fehlermaske (aktueller Wert) */
   uint8 sac_qpr_mskReglerInfo_mu8; /* Description: Statussignale des Reglers QPR */
   uint32 sac_qpr_mskReglerWarn1st_mu32; /* Description: QPR-Fehlermaske (eingefrohren bei letzem We
   chsel in der Warnzustand) */
   uint8 sac_qpr_stRegler_mu8; /* Description: aktueller Reglerstatus des QPR-Positionsreglers */
   uint16 sac_qpr_trqMaxHm_mu16; /* Description: Handmoment, durch welches der Eingriff ueberlenkt w
   erden kann [Nm] */
   sint16 sac_qpr_vZstDiff_mi16; /* Description: Geschwindigkeitsdifferenz aus Soll- und Ist-Zahnsta
   ngengeschwindigkeit [mm/s] */
   sint16 sac_qpr_vZstDSollVor_mi16; /* Description: Zahnstangenpositionsregler D-Anteil fuer Vorste
   uerung [mm/s] */
   sint16 sac_qpr_vZstDSoll_mi16; /* Description: Zahnstangenpositionsregler D-Anteil [mm/s] */
   sint16 sac_qpr_vZstISoll_mi16; /* Description: Zahnstangenpositionsregler I-Anteil [mm/s] */
   sint16 sac_qpr_vZstIstFltr_mi16; /* Description: gefilterte Zahnstangen-Ist-Geschwdniindigkeit [m
   m/s] */
   sint16 sac_qpr_vZstSoll_mi16; /* Description: Zahnstangen-Soll-Geschwindigkeit aus dem Zahnstange
   npositionsregler [mm/s] */
   sint16 sac_qpr_vZstVibOffset_mi16; /* Description: Vibrationsoffset in der Zahnstang-Soll-Geschwi
   ndigkeit [mm/s] */
   sint16 sac_qpr_xZstDiff_mi16; /* Description: Positionsdifferenz aus Soll- und Ist-Zahnstangenpos
   ition [mm] */
   sint16 sac_qpr_xZstSoll_mi16; /* Description: Zahnstangen-Soll-Position nach Signaljitterkompensa
   tion [mm] */
   uint8 sac_qua_cntPosSoll_mu8; /* Description: Botschaftszaehler des aktuell aktven FAS */
   uint16 sac_qua_facHaptik_mu16; /* Description: Spuerbarkeitsfaktor des aktuell aktiven FAS */
   uint8 sac_qua_frqVibration_mu8; /* Description: aus der FAS-Anforderung abgeleitete Vibrationsfre
   quenz [Hz] */
   uint8 sac_qua_mskReglerReqInfo_mu8; /* Description: Zusatzinformationen fuer den aktuellen Regler
   eingriff (z.B. beim Ueberblenden) */
   uint8 sac_qua_stFrqPosSoll_mu8; /* Description: erwartete Botschaftszykluszeit des aktuell aktive
   n FAS(2 = 10 ms, 3 = 20 ms) */
   uint8 sac_qua_stReglerRequest_mu8; /* Description: Anforderungsstatus zur Ansteuerung des Positio
   nsreglers */
   uint8 sac_qua_stVibration_mu8; /* Description: Vibrationsstatus */
   uint8 sac_qua_trqVibration_mu8; /* Description: aus der FAS-Anforderung abgeleitete Vibrationsamp
   itude [Nm] */
   uint16 sac_qua_vFzgLvLow_mu16; /* Description: das Fahrzeug bewegt sich mit Sicherheit schneller 
   oder entsprechend, der hier angegebene Geschwdnigkeit [km/h] */
   sint16 sac_qua_xZstSoll_mi16; /* Description: Zahnstangensollposition, welche aus der Soll-Kruemm
   ung des aktuell aktiven FAS berechnet wurde [mm] */
   sint16 sac_asc_fSoll_mi16; /* Description: input: Unterstuetzungskraft aus Softwaremodul [N] */
   sint16 sac_asc_ger_phiL_mi16; /* Description: input: Langzeitlernwert der ASC GER [deg] */
   uint32 sac_asc_stASC_mu32; /* Description: input: Statusinformation ASC */
   uint16 sac_asc_stDsaTsc2Qfk_mu16; /* Description: input: Statusinformation der GMV (DAS) und TSC
   */
   uint8 sac_bsw_levelAssist_mu8; /* Description: input: moegliches Unterstuetzungsniveau [%] */
   uint32 sac_bsw_mskStatusbits01_mu32; /* Description: input: Status information 1 der EPS (Siehe D
   okument Signale) */
   uint32 sac_bsw_mskStatusbits02_mu32; /* Description: input: Status information2 der EPS (Siehe Do
   kument EPS_Schnittstelle) */
   sint16 sac_bsw_phvRitzel_mi16; /* Description: input: Lenkwinkelgeschwindigkeit aus Motorlagesens
   or [deg/s] */
   uint8 sac_bsw_stFehlerULstg_mu8; /* Description: input: Status Fehlereintrag aufgrund eines Unter
   stützungsleistungsfehlers. */
   uint8 sac_bsw_stFrgBusFehler_mu8; /* Description: input: Status der Freigabe der BUS-Netzwerkdiag
   nose */
   uint8 sac_bsw_stFrgBusFehler_mod_mu8; /* Description: input: Status der Freigabe der BUS-Netzwerk
   diagnose bei steigender Flanke um "QAP_TMR_FRG_BUS_FEHLER_AU16" verzögert  */
   uint8 sac_bsw_stKl15_mu8; /* Description: input: Statussignal für Klemme 15 */
   sint16 sac_bsw_trqSensorLku_mi16; /* Description: input: Aufsummiertes Handmomentsignal welches a
   ls Grundlage der Berechnung der LKU Kraft dient [Nm] */
   sint16 sac_bsw_trqSensor_mi16; /* Description: input: Handmoment [Nm] */
   uint16 sac_bsw_uBatt_mu16; /* Description: input: Batteriespannung */
   sint16 sac_bsw_vZst_mi16; /* Description: input: Zahnstangengeschwindigkeit */
   sint16 sac_bsw_xZstEASoll_mi16; /* Description: input: Position Software-Endanschlag Positiv/Nega
   tiv(Zahnstangenwegabhaengig) [mm] */
   sint32 sac_bsw_xZstGerKorr_mi32; /* Description: input: Zahnstangenweg Offsetkorrigiert um Lernwe
   rt Geradeauslaufkorrektur (asc_ger_phiL_mi16) [mm] */
   sint32 sac_bsw_xZst_mi32; /* Description: input: Zahnstangenweg [mm] */
   sint16 sac_can_beschlQuer_mi16; /* Description: input: Querbeschleunigung [m/s^2] */
   uint8 sac_can_cntFas01_mu8; /* Description: input: Botschaftszaehler FAS01-QFK */
   uint8 sac_can_cntFas02_mu8; /* Description: input: Botschaftszaehler FAS02-QFK */
   uint8 sac_can_cntFas03_mu8; /* Description: input: Botschaftszaehler FAS03-QFK */
   uint8 sac_can_cntFas04_mu8; /* Description: input: Botschaftszaehler FAS04-QFK */
   uint8 sac_can_cntFas05_mu8; /* Description: input: Botschaftszaehler FAS05-QFK */
   uint8 sac_can_cntVMM_mu8; /* Description: input: Botschaftszaehler Zahnstangensollposition VMM */
   uint16 sac_can_facSignal1Fas01_mu16; /* Description: input: Signal fuer Eingriffsart 1 in FAS01-Q
   FK */
   uint16 sac_can_facSignal1Fas02_mu16; /* Description: input: Signal fuer Eingriffsart 1 in FAS02-Q
   FK */
   uint16 sac_can_facSignal1Fas03_mu16; /* Description: input: Signal fuer Eingriffsart 1 in FAS03-Q
   FK */
   uint16 sac_can_facSignal1Fas04_mu16; /* Description: input: Signal fuer Eingriffsart 1 in FAS04-Q
   FK */
   uint16 sac_can_facSignal1Fas05_mu16; /* Description: input: Signal fuer Eingriffsart 1 in FAS05-Q
   FK */
   uint16 sac_can_facSignal1VMM_mu16; /* Description: input: Signal fuer Eingriffsart 1 in VMM_QFK
   */
   uint16 sac_can_facSignal2Fas01_mu16; /* Description: input: Signal fuer Eingriffsart 2 in FAS01-Q
   FK */
   uint16 sac_can_facSignal2Fas02_mu16; /* Description: input: Signal fuer Eingriffsart 2 in FAS02-Q
   FK */
   uint16 sac_can_facSignal2Fas03_mu16; /* Description: input: Signal fuer Eingriffsart 2 in FAS03-Q
   FK */
   uint16 sac_can_facSignal2Fas04_mu16; /* Description: input: Signal fuer Eingriffsart 2 in FAS04-Q
   FK */
   uint16 sac_can_facSignal2Fas05_mu16; /* Description: input: Signal fuer Eingriffsart 2 in FAS05-Q
   FK */
   uint16 sac_can_facSignal2VMM_mu16; /* Description: input: Signal fuer Eingriffsart 2 in VMM_QFK
   */
   uint16 sac_can_facSpuerbFas01_mu16; /* Description: input: Spuerbarkeit FAS01-QFK */
   uint16 sac_can_facSpuerbFas02_mu16; /* Description: input: Spuerbarkeit FAS02-QFK */
   uint16 sac_can_facSpuerbFas03_mu16; /* Description: input: Spuerbarkeit FAS03-QFK */
   uint16 sac_can_facSpuerbFas04_mu16; /* Description: input: Spuerbarkeit FAS04-QFK */
   uint16 sac_can_facSpuerbFas05_mu16; /* Description: input: Spuerbarkeit FAS05-QFK */
   uint16 sac_can_facSpuerbVMM_mu16; /* Description: input: Spuerbarkeit VMM */
   sint16 sac_can_gierrate_mi16; /* Description: input: Gierrarte [deg/s] */
   sint16 sac_can_krSollFas01_mi16; /* Description: input: Soll-Kruemmung FAS01-QFK [1/m] */
   sint16 sac_can_krSollFas02_mi16; /* Description: input: Soll-Kruemmung FAS02-QFK [1/m] */
   sint16 sac_can_krSollFas03_mi16; /* Description: input: Soll-Kruemmung FAS03-QFK [1/m] */
   sint16 sac_can_krSollFas04_mi16; /* Description: input: Soll-Kruemmung FAS04-QFK [1/m] */
   sint16 sac_can_krSollFas05_mi16; /* Description: input: Soll-Kruemmung FAS05-QFK [1/m] */
   uint16 sac_can_phiESCKinX1_mu16; /* Description: input: Virtueller Lenkwinkel mit der Standard-Za
   hnstangenuebersetzung fuer die 1. Stuetzstelle [Deg] */
   uint16 sac_can_phiESCKinX2_mu16; /* Description: input: Virtueller Lenkwinkel mit der Standard-Za
   hnstangenuebersetzung fuer die 2. Stuetzstelle [Deg] */
   uint16 sac_can_phiESCKinX3_mu16; /* Description: input: Virtueller Lenkwinkel mit der Standard-Za
   hnstangenuebersetzung fuer die 3. Stuetzstelle [Deg] */
   uint16 sac_can_phiESCKinX4_mu16; /* Description: input: Virtueller Lenkwinkel mit der Standard-Za
   hnstangenuebersetzung fuer die 4. Stuetzstelle [Deg] */
   uint16 sac_can_phiESCKinX5_mu16; /* Description: input: Virtueller Lenkwinkel mit der Standard-Za
   hnstangenuebersetzung fuer die 5. Stuetzstelle [Deg] */
   uint16 sac_can_phiESCKinY1_mu16; /* Description: input: Mittlerer Radlenkwinkel mit der Standard-
   Zahnstangenuebersetzung fuer die 1. Stuetzstelle [Deg] */
   uint16 sac_can_phiESCKinY2_mu16; /* Description: input: Mittlerer Radlenkwinkel mit der Standard-
   Zahnstangenuebersetzung fuer die 2. Stuetzstelle [Deg] */
   uint16 sac_can_phiESCKinY3_mu16; /* Description: input: Mittlerer Radlenkwinkel mit der Standard-
   Zahnstangenuebersetzung fuer die 3. Stuetzstelle [Deg] */
   uint16 sac_can_phiESCKinY4_mu16; /* Description: input: Mittlerer Radlenkwinkel mit der Standard-
   Zahnstangenuebersetzung fuer die 4. Stuetzstelle [Deg] */
   uint16 sac_can_phiESCKinY5_mu16; /* Description: input: Mittlerer Radlenkwinkel mit der Standard-
   Zahnstangenuebersetzung fuer die 5. Stuetzstelle [Deg] */
   uint16 sac_can_sESCRadstand_mu16; /* Description: input: Fahrzeugradstand [m] */
   uint8 sac_can_stAnfFas01_mu8; /* Description: input: Statusanforderung FAS01-QFK */
   uint8 sac_can_stAnfFas02_mu8; /* Description: input: Statusanforderung FAS02-QFK */
   uint8 sac_can_stAnfFas03_mu8; /* Description: input: Statusanforderung FAS03-QFK */
   uint8 sac_can_stAnfFas04_mu8; /* Description: input: Statusanforderung FAS04-QFK */
   uint8 sac_can_stAnfFas05_mu8; /* Description: input: Statusanforderung FAS05-QFK */
   uint8 sac_can_stArt1Fas01_mu8; /* Description: input: Eingriffstyp1 FAS01-QFK */
   uint8 sac_can_stArt1Fas02_mu8; /* Description: input: Eingriffstyp1 FAS02-QFK */
   uint8 sac_can_stArt1Fas03_mu8; /* Description: input: Eingriffstyp1 FAS03-QFK */
   uint8 sac_can_stArt1Fas04_mu8; /* Description: input: Eingriffstyp1 FAS04-QFK */
   uint8 sac_can_stArt1Fas05_mu8; /* Description: input: Eingriffstyp1 FAS05-QFK */
   uint8 sac_can_stArt1VMM_mu8; /* Description: input: Eingriffstyp1 VMM */
   uint8 sac_can_stArt2Fas01_mu8; /* Description: input: Eingriffstyp2 FAS01-QFK */
   uint8 sac_can_stArt2Fas02_mu8; /* Description: input: Eingriffstyp2 FAS02-QFK */
   uint8 sac_can_stArt2Fas03_mu8; /* Description: input: Eingriffstyp2 FAS03-QFK */
   uint8 sac_can_stArt2Fas04_mu8; /* Description: input: Eingriffstyp2 FAS04-QFK */
   uint8 sac_can_stArt2Fas05_mu8; /* Description: input: Eingriffstyp2 FAS05-QFK */
   uint8 sac_can_stArt2VMM_mu8; /* Description: input: Eingriffstyp2 VMM */
   uint8 sac_can_stEingLvVMM_mu8; /* Description: input: Eingrifflevel VMM */
   uint8 sac_can_stEingVMM_mu8; /* Description: input: Eingriffstatus VMM */
   uint32 sac_can_strDevMsgRx1_mu32; /* Description: input: Eingang variable CANBotschaft 1. Teil */
   uint32 sac_can_strDevMsgRx2_mu32; /* Description: input: Eingang variable CAN-Botschaft 2. Teil
   */
   uint32 sac_can_stSignale01_mu32; /* Description: input: Status information der CAN Signale */
   uint32 sac_can_stSignale02_mu32; /* Description: input: Status information der CAN Signale */
   uint8 sac_can_stVSignalQualifier_mu8; /* Description: input: Qualifierstatus ESP_21 vSignal */
   sint16 sac_can_xZstSollVMM_mi16; /* Description: input: Zahnstangensollposition VMM */
   uint32 sac_dia_mskAnpassung01_mu32; /* Description: input: Bitleiste, die den Status der Anpassun
   g der Lenkung anzeigt */
   uint32 sac_dia_mskCodierung01_mu32; /* Description: input: Bitleiste, die den Status der Codierun
   g der Lenkung anzeigt. */
   uint32 sac_dia_stDiagnose_mu32; /* Description: input: Bitleiste, die den Funktionsstatus aller F
   unktionen anzeigt und in ASC eingelesen wird */
   sint16 sac_eaf_fSoll_mi16; /* Description: input: Sollkraft aus der Funktion EAF [N] */
   uint16 sac_eps_nivAssistRampe_mu16; /* Description: input: Unterstützungsrampe aus der Funktion E
   PS Zustände */
   uint8 sac_fga_mskStVFzg_mu8; /* Description: input: Statusinformationen des Geschwindigkeitssigna
   ls aus der Funktion FGA */
   uint16 sac_fga_vFzgRohW_mu16; /* Description: input: Rohwert der Fahrzeuggeschwindigkeit (Fehlerb
   ehandlung enthalten) [km/h] */
   uint16 sac_fga_vFzg_mu16; /* Description: input: Absolute gradienten begrenzte und Fehler behande
   lte Geschwidnigkeit aus der Funktion FGA [km/h] */
   uint16 sac_fga_vRadHl_mu16; /* Description: input: Fehlerbehandelte Einzelradgeschwindigkeit HL [
   km/h] */
   uint16 sac_fga_vRadHr_mu16; /* Description: input: Fehlerbehandelte Einzelradgeschwindigkeit HR [
   km/h] */
   uint16 sac_fga_vRadVl_mu16; /* Description: input: Fehlerbehandelte Einzelradgeschwindigkeit VL [
   km/h] */
   uint16 sac_fga_vRadVr_mu16; /* Description: input: Fehlerbehandelte Einzelradgeschwindigkeit VR [
   km/h] */
   sint16 sac_lku_fSoll_mi16; /* Description: input: Sollkraft der Lenkunterstuetzung [N] */
   sint16 sac_bsw_fSollLimMtl_mi16; /* Description: input: Sollkraft nach dem Motor-Torque-Limiter [
   N] */
   uint32 sac_tac_stTAC_mu32; /* Description: input: Statusinformation TAC */
   uint8 sac_unt_diag_aktiv_mu8; /* Description: input: Information: Motor laeuft stabil */
   uint32 sac_can_strDevMsgTx1_mu32; /* Description: output: Ausgang variable CAN-Botschaft 1. Teil
   */
   uint32 sac_can_strDevMsgTx2_mu32; /* Description: output: Ausgang variable CAN-Botschaft 2. Teil
   */
   uint8 sac_qap_stFas01_mu8; /* Description: output: Status FAS01-QFK im QFK */
   uint8 sac_qap_stFas02_mu8; /* Description: output: Status FAS02-QFK im QFK */
   uint8 sac_qap_stFas03_mu8; /* Description: output: Status FAS03-QFK im QFK */
   uint8 sac_qap_stFas04_mu8; /* Description: output: Status FAS04-QFK im QFK */
   uint8 sac_qap_stFas05_mu8; /* Description: output: Status FAS05-QFK im QFK */
   uint16 sac_qap_stPrioToTnDsaTsc_mu16; /* Description: output: Status an GMV (DAS) und TSC in der 
   ASC */
   uint8 sac_qap_stQFK_mu8; /* Description: output: Gesamtstatus QFK */
   uint8 sac_qap_stVMM_mu8; /* Description: output: Status VMM im QFK */
   sint16 sac_qhm_fSollNUel_mi16; /* Description: output: Gesamt-Sollkraft (nicht ueberlenkbar) des 
   QFK [N] */
   sint16 sac_qhm_fSoll_mi16; /* Description: output: Unterstuetzungskraft aus SAC Softwaremodul [N]
    */
   uint8 sac_qhm_mskStatus_mu8; /* Description: output: Status ob QFK Eingriff durch Ueberwachung be
   grenzt */
   sint16 sac_qhm_nivIstKraft_mi16; /* Description: output: Vom QFK berechnetes Ist-Kraft-Niveau [%]
    */
   sint16 sac_qpr_fSollVib_mi16; /* Description: output: Sollkraft der Vibration [N] */
   sint16 sac_qua_krIst_mi16; /* Description: output: Vom QFK berechnete Ist-Kruemmung [1/m] */
   uint16 sac_sai_stSai2Qfk_mu16; /* Description: input: Statussignal von SAI zum QFK. */
   uint16 sac_sai_stSai2QfkPrio_mu16; /* Description: input: Statussignal von SAI zum QFK mit Prioit
   ät */
   uint16 sac_stQfk2Sai_mu16; /* Description: output: Statussignal vom QFK zur SAI. */
   uint16 sac_stQfk2SaiPrio_mu16; /* Description: output: Statussignal vom QFK zur SAI mit Prioität.
    */
   uint8 sac_qua_stGierSoll_mu8; /* Description: output: Status ueber den vom QFK beim ESC ein Gierm
   omentenoffset angefordert wird */
   sint16 sac_qua_trqGierSoll_mi16; /* Description: output: Giermomentenoffset der beim ESC angeford
   ert werden kann [Nm] */
   uint16 sac_qua_vFzgLvHigh_mu16; /* Description: output: aktuelle Geschwindigkeit (maximale Geschw
   indigkeit die mit Sicherheit garantiert werden kann) [km/h] */
   uint32 sac_stSAC_mu32; /* Description: output: Diagnose Bitmaske */
}; /* Description: struct type created for variable: MSM_Struct */

/*------------------------------------------------------------------------------------------------*\
  VARIABLES
\*------------------------------------------------------------------------------------------------*/

#ifndef USE_CST_PARAM_STRUCT_H
/**************************************************************************************************\
   DISP: global observable variables (RAM) | Width: N.A.
\**************************************************************************************************/
extern DISP struct tag_MSM_Struct MSM_Struct;
#endif /*USE_CST_PARAM_STRUCT_H*/

/*------------------------------------------------------------------------------------------------*\
  PARAMETERIZED MACROS
\*------------------------------------------------------------------------------------------------*/
/*------------------------------------------------------------------------------------------------*\
  FUNCTION PROTOTYPES
\*------------------------------------------------------------------------------------------------*/
#ifdef __cplusplus
}
#endif

#endif /* ZPC_MSM_H */
/*------------------------------------------------------------------------------------------------*\
  END OF FILE
\*------------------------------------------------------------------------------------------------*/
